### ISSUE TITLE
日志下载功能不可用

### ISSUE THREAD

**Issue by zhouyq** [goodrain/rainbond#10]
点开后空白页面

**Comment by Gemrails** [comment]
要保证页面正常下载需要两个条件：

1. 确保region端日志下载提供的端口服务正常，默认为`6060`，且该端口对外开放
2. 确保console端对日志文件的超链接使用的端口与之对应。
- console端配置文件为：
` /etc/goodrain/console.py`
- 配置项为：
```
# log domain
LOG_DOMAIN = {
    "cloudbang": "xxx.xxxx.xxx:6060"
}
```
