### ISSUE TITLE
helm error 

### ISSUE THREAD

**Issue by bsbrother** [goodrain/rainbond#100]
$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

$ kubectl create serviceaccount --namespace kube-system tiller
$ kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
$ helm init --service-account tiller
$ helm ls
    Error: Get https://11.1.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 11.1.0.1:443: i/o timeout

thank you very much!

**Comment by barnettZQG** [comment]
@bsbrother 
Did you use Rainbond?

**Comment by bsbrother** [comment]
Yes,  I test rainbond and it run very good.  
But how follow this https://zero-to-jupyterhub.readthedocs.io/en/latest/ to install jupyterhub?
Rainbond how to alternative helm package mangae?
thank you very much again!

**Comment by barnettZQG** [comment]
@bsbrother 
I'm sorry,  current version do not support helm.but ,But we will include support for helm in TODO.
We will maybe support the direct application construction of the helm chart source code.

**Comment by bsbrother** [comment]
Very looking forward to.

**Comment by barnettZQG** [comment]
No feedback, this issue will be closed.
How is there still a problem? Please open it again
