### ISSUE TITLE
有状态实例指定 ES_SELECTNODE 时的异常

### ISSUE THREAD

**Issue by mingyuan2015** [goodrain/rainbond#1016]
创建实例时，环境变量配置 ES_SELECTNODE 
 实例类型：有状态
 存储类型：挂载本地存储。

 上述情况下创建的应用无法创建成功

![image](https://user-images.githubusercontent.com/30488400/122083466-7bc39000-ce33-11eb-8a32-6c33ae087611.png)

**Comment by barnettZQG** [comment]
使用 ES_SELECTNODE 指定节点后，本地存储调度将无法正常工作。

在后续将要发布的5.3.1版本中该问题得到了解决。

**Comment by mingyuan2015** [comment]
不指定ES_SELECTNODE，也有一定概率本地存储调度无法工作，不知道是不是其他应用指定了ES_SELECTNODE 导致的
