### ISSUE TITLE
无状态的组件看不到所有的sc

### ISSUE THREAD

**Issue by mingyuan2015** [goodrain/rainbond#1018]
对接了gfs存储，在集群初始化时候对接的。
有状态的组件可以看到gfs
无状态组件的看不到gfs。无状态的共享存储也非存储到gfs里面（通过查看服务器/data目录得到的结论）

无状态组件：
![image](https://user-images.githubusercontent.com/30488400/122759638-c37f6700-d2cc-11eb-896a-8b58e6da7287.png)
有状态组件：
![image](https://user-images.githubusercontent.com/30488400/122759681-cc703880-d2cc-11eb-9e3b-a287c63e3052.png)

**Comment by barnettZQG** [comment]
@mingyuan2015 
自定义存储类型目前主要设计给有状态组件扩展使用。

无状态组件对存储（SC） 的要求需要支持 ReadWriteMany，目前我们暂无实现对SC的识别和分类。

对于gluster-simple 这个SC，你可以直接使用共享存储即可，它使用子目录的模式进行volume隔离。

**Comment by mingyuan2015** [comment]
对接了gluster-simple，无组件存储的共享存储。实际没有存储到gfs里面。

**Comment by barnettZQG** [comment]
@mingyuan2015 如果没有使用，说明您在集群初始化参数中未配置。
```
kubectl get rainbondcluster rainbondcluster -o yaml -n rbd-system
```

通过上述命令查询集群初始化参数，其中 `rainbondVolumeSpecRWX` 定义集群默认的共享存储提供方。

rainbond 集群安装程序将通过此参数创建 RainbondVolume 类型的资源 rainbondvolumerwx

可以通过下述命令查询：

```
kubectl get RainbondVolume rainbondvolumerwx -o yaml -n rbd-system 
```

该资源决定了默认共享存储的提供者。

**Comment by mingyuan2015** [comment]
rainbondVolumeSpecRWX 果然没有数据。但是初始化时有提供参数

metadata:
name: rainbondcluster
spec:
rainbondVolumeSpecRWX:
storageClassName: glusterfs-simple

**Comment by mingyuan2015** [comment]
请教已经初始化了的集群，是否可以修改rainbondVolumeSpecRWX

**Comment by mingyuan2015** [comment]
准备给集群重新初始化一下，请教使用gfs

metadata:
name: rainbondcluster
spec:
rainbondVolumeSpecRWX:
storageClassName: glusterfs-simple

这个设置要要调整的么

**Comment by mingyuan2015** [comment]
请教如果不能修改，初始化集群的参数是否是：

metadata:
name: rainbondcluster
spec:
rainbondVolumeSpecRWX:
storageClassName: glusterfs-simple

**Comment by barnettZQG** [comment]
For example:
```
metadata:
     name: rainbondcluster
spec:
     rainbondVolumeSpecRWX:
         storageClassName: glusterfs-simple
```

**Comment by mingyuan2015** [comment]
@barnettZQG 初始化时候确实这么设置的，核验也是过去的

**Comment by barnettZQG** [comment]
如无其他问题，我先关闭这个Issues。
