### ISSUE TITLE
php应用构建问题

### ISSUE THREAD

**Issue by mingyuan2015** [goodrain/rainbond#1020]
https://www.rainbond.com/docs/component-create/language-support/php/

php应用编译时候，如果应用根目录带vendor文件夹会导致编译失败。上传git时候不带vendor正常编译

**Comment by barnettZQG** [comment]
该问题使用不同的php项目都可以复现吗？

**Comment by mingyuan2015** [comment]
测试了几个php。都可以复现

**Comment by barnettZQG** [comment]
@mingyuan2015 可否提供一个php测试项目代码地址？

**Comment by mingyuan2015** [comment]
明天来放个demo

**Comment by barnettZQG** [comment]
@mingyuan2015 长时间不更新，我将关闭该Issues，还有问题请重新打开。
