### ISSUE TITLE
80端口http服务问题

### ISSUE THREAD

**Issue by mingyuan2015** [goodrain/rainbond#1021]
不知道这个是不是bug。

6个节点，安装时候选择了5个etcd。2个管理。5个计算。

有3个节点http不通。只有3个节点http可以

**Comment by mingyuan2015** [comment]
端口开放没问题

**Comment by barnettZQG** [comment]
有三个节点 http 不通是啥意思？

**Comment by mingyuan2015** [comment]
这几个节点的80不通

**Comment by mingyuan2015** [comment]
只有3个节点的80通。不是应该5个80可以通么

**Comment by barnettZQG** [comment]
不是，你所指的80端口应该是指集群的网关访问入口。网关服务默认部署在管理节点，rainbondcluster 资源中 spec.nodesForGateway 定义了网关服务部署的节点。

可通过如下命令查看网关服务的运行情况：
```
kubectl get pod -l name=rbd-gateway -o wide -n rbd-system
```

**Comment by mingyuan2015** [comment]
果然是这样，抱歉。误解了
