### ISSUE TITLE
是否可以给一个对接集群时候nfs的参数

### ISSUE THREAD

**Issue by mingyuan2015** [goodrain/rainbond#1024]
如题，是否可以提供一个集群初始化时候对接自有nfs的参数，谢谢

**Comment by 1909490139** [comment]
1. 通过k8s官方提供文档 https://github.com/kubernetes-retired/external-storage/tree/master/nfs-client ，创建storageclass；
2. 参考 Rainbond 集群初始化参数说明 https://www.rainbond.com/docs/user-operations/cluster-manage/init-region/，配置 spec. rainbondVolumeSpecRWX. storageClassName 值为第一步创建的 storageclass 名称。
3. 配置完成后继续后续安装流程即可，安装好的 Rainbond 平台共享存储就会由 自有nfs 来提供了。

**Comment by barnettZQG** [comment]
## 对接存储配置方式



* 使用内置NFS-SERVER (默认)

  ```
  rainbondVolumeSpecRWX:
  	csiPlugin: 
  		nfs: {}
  	storageClassParameters:
  		parameters: {}
  ```

  

* 对接阿里云NAS

  ```
  rainbondVolumeSpecRWX:
  	csiPlugin: 
  		aliyunNas: {}
  	storageClassParameters:
  		mountOptions: 
  		- "nolock,tcp,noresvport"
  		- "vers=4"
  		- "minorversion=0"
  		- "rsize=1048576"
  		- "wsize=1048576"
  		- "timeo=600"
  		- "retrans=2"
  		- "hard"
  		parameters: 
  		  volumeAs: subpath
      	archiveOnDelete: "true"
      	server: <NAS_SERVER_ADDR>
  ```

* 对接GFS

  ```
  rainbondVolumeSpecRWX:
  	storageClassName: <GFS_CLASS_NAME>
  	storageClassParameters:
  		mountOptions: 
  		- "vers=4"
  ```

* 其他StorageClass

  ```
  rainbondVolumeSpecRWX:
  	storageClassName: <CLASS_NAME>
  	storageClassParameters:
  		mountOptions: 
  		- "vers=4"
  ```

  需要StorageClass对应创建出来的PV 是基于以下两种情况：

  * PersistentVolumeSource.NFS  
  * PersistentVolumeSource.Glusterfs
