### ISSUE TITLE
php 构建问题

### ISSUE THREAD

**Issue by mingyuan2015** [goodrain/rainbond#1027]
composer.json内容
{
    "require": {
        "php": "5.5.38"
    }
}

Procfile内容
web: vendor/bin/heroku-php-nginx

编译结果：
make code package success
create build code job success
builder:-----> Detection PHP runtime php-5.5.38
builder:-----> Use custom PHP Procfile
builder:-----> Prepare Handle 5.5.38 Success
builder:-----> Prepare Handle Language PHP RuntimeVersion 5.5.38
builder:-----> Bootstrapping...
builder:
builder: NOTICE: download php-min-7.3.3.tar.gz sucessful
builder:
builder:
builder: NOTICE: download composer-1.8.4.tar.gz sucessful
builder:
builder:
builder:
builder: [UnexpectedValueException]
builder: Unknown package has no name defined ([]).
builder:
builder:
build code job exec failed
build code job exec failed
Compiling the source code failure
Build app version from source code failure,build code job exec failure

通过编译结果看出，指定php5.5.38，下载的是7.3.3的php。另外如果composer.json不带任何包会编译错误

**Comment by barnettZQG** [comment]
7.3.3 是作为 composer 的运行环境。正常构建后会下载指定的php版本。

关于错误`Unknown package has no name defined` 建议搜索composer编译相关资料解决。

**Comment by mingyuan2015** [comment]
依然是vendor文件夹存在导致的错误，删除vendor文件夹，重新编译正常

**Comment by barnettZQG** [comment]
我将关闭这个issues。如还有其他问题请重新提交
