### ISSUE TITLE
Rainbond 集群初始化进度一直卡在”获取集群访问配置文件“步骤

### ISSUE THREAD

**Issue by ooocici** [goodrain/rainbond#1032]
【部署环境】
- Rainbond版本(执行`grctl version`获取): 5.3
- 操作系统类型和版本: CentOS7.5
- 离线部署/网络开放：网络开放

问题描述：
接入K8S集群，Rainbond 集群初始化进度一直卡在”获取集群访问配置文件“，多次卸载集群重新安装依旧如此。
通过事件日志发现， rbd-chaos、rbd-api健康检查均提示”context deadline exceeded (Client.Timeout exceeded while awaiting headers)“

![image](https://user-images.githubusercontent.com/15642865/124088938-05a36800-da86-11eb-97ab-c37ca5d6ba21.png)

使用命令查看该接口，返回正常，结果如下：
![image](https://user-images.githubusercontent.com/15642865/124089296-5b781000-da86-11eb-8a89-6e48d8a9c655.png)

使用”kubectl get pod -n rbd-system“命令可以看见所有服务启动成功：
![image](https://user-images.githubusercontent.com/15642865/124089141-31bee900-da86-11eb-8cc8-7b5fd9e46f8d.png)

请问集群初始化卡主的问题，是否是该问题引起的呢？

**Comment by barnettZQG** [comment]
@ooocici 所有服务都正常启动，那应该是 8443 端口访问权限没有放开？ 比如防火墙或白名单等？

**Comment by barnettZQG** [comment]
@ooocici 我先关闭这个问题，有问题请重新打开。
