### ISSUE TITLE
基于主机安装 Kubernetes 集群 的节点配置错误

### ISSUE THREAD

**Issue by mingyuan2015** [goodrain/rainbond#1038]
![image](https://user-images.githubusercontent.com/30488400/124545145-0e67b580-de5b-11eb-9350-a1593bce91b3.png)
如图，点击节点配置，看不到以往的节点了，并且报错

**Comment by GLYASAI** [comment]
备份迁移的时候没有把 rke_clusters 迁移过去:

```bash
mysql> select * from adaptor_rke_clusters\G
Empty set (0.00 sec)
```

**Comment by barnettZQG** [comment]
@mingyuan2015 升级到5.3.1最新更新版本，修复该问题。
