### ISSUE TITLE
应用市场安装应用报错

### ISSUE THREAD

**Issue by mingyuan2015** [goodrain/rainbond#1046]
从应用市场安装监控报警服务，会提示服务端异常，安装其他应用正常

**Comment by barnettZQG** [comment]
@mingyuan2015 麻烦提供一下安装应用时的控制台日志。 /app/logs/goodrain.log

**Comment by mingyuan2015** [comment]
![image](https://user-images.githubusercontent.com/30488400/125369280-84fe3900-e3ae-11eb-8a3a-e3dc8cd64916.png)
