### ISSUE TITLE
迁移数据库后，日志不显示

### ISSUE THREAD

**Issue by cichuliubai** [goodrain/rainbond#1048]
我们数据库本来已经迁移到rds了，现在我将数据库从rds迁移回本地。但是组件日志无法显示，我点击历史日志下载，是能看到日志的
![image](https://user-images.githubusercontent.com/39149203/125226779-49a73000-e304-11eb-93f0-8f28f11d845a.png)
![image](https://user-images.githubusercontent.com/39149203/125226824-5fb4f080-e304-11eb-8696-d89bac358f6a.png)

**Comment by barnettZQG** [comment]
@cichuliubai 重启一下 rbd-api 和 rbd-event 两个组件呢？

**Comment by barnettZQG** [comment]
长时间不回复我将关闭该问题，如问题还存在请重新打开
