### ISSUE TITLE
GIT构建异常

### ISSUE THREAD

**Issue by mingyuan2015** [goodrain/rainbond#1051]
升级5.3.1后git构建间接性抽风，等NNNN久可能会成功，换了多个git源
![image](https://user-images.githubusercontent.com/30488400/125294715-1772ee00-e357-11eb-9a48-dc7be48bc531.png)

**Comment by barnettZQG** [comment]
@mingyuan2015 从提供的日志看没有异常呀

**Comment by barnettZQG** [comment]
无进一步反馈，我将关闭这个Issues.
