### ISSUE TITLE
是否可以更新下php构建时候的hook脚本文档？

### ISSUE THREAD

**Issue by mingyuan2015** [goodrain/rainbond#1065]
目前rainbond构建时支持hook 脚本，代码主目录上创建一个 bin/php-post-compile bin/php-pre-compile 脚本文件，一个是后置执行，一个是前置执行。

能否更新到文档中，给个具体案例，直接创建这个脚本就可以么？没执行到？

**Comment by barnettZQG** [comment]
是的，构建日志中会打印：`Running bin/php-pre-compile hook`。
文档我们稍后更新

**Comment by barnettZQG** [comment]
参考文档：https://www.rainbond.com/docs/component-create/language-support/php/#shell-hook-%e6%94%af%e6%8c%81
