### ISSUE TITLE
离线安装报错

### ISSUE THREAD

**Issue by wengcx123456** [goodrain/rainbond#108]
If you want to report a bug, please provide the following information:

- [x] Rainbond versions
- [ ] Kubernetes versions
- [ ] Docker version
- [ ] Operating system and kernel
- [ ] Provider(Aliyun,VirtualBox,...)
- [x] Install details(Online/Offline,Single node/HA)
- [ ] Steps to reproduce

**Comment by ysicing** [comment]
离线安装可以参考[离线安装文档](https://www.rainbond.com/docs/stable/operation-manual/install/offline/setup.html)
而且离线安装命令参数不对 `./grctl init --install-type offline --domain cmiot.com`
