### ISSUE TITLE
offline install fail (离线安装失败)

### ISSUE THREAD

**Issue by recotone** [goodrain/rainbond#109]
cd /opt/rainbond/install
./setup
or
./grctl init --install-type offline

Start install image(step: 4/7), it will take 8-15 minutes 
This step will pull/load all docker images 
...
Name: dc-compose up -d rbd-hub - Function: cmd.run - Result: Clean Started: - 23:11:03.785401 Duration: 23.004 ms
----------
          ID: push-lb-image
    Function: cmd.run
        Name: docker push goodrain.me/rbd-lb:3.7
      Result: False
     Comment: Command "docker push goodrain.me/rbd-lb:3.7" run
     Started: 23:11:03.808685
    Duration: 50072.87 ms
     Changes:   
              ----------
              pid:
                  18966
              retcode:
                  1
              stderr:
                  Error: Status 502 trying to push repository rbd-lb:

**Comment by ysicing** [comment]
`dps` 看看 rbd-lb和 rbd-hub服务是否正常

**Comment by recotone** [comment]
正常的
