### ISSUE TITLE
A number of issues related to health monitoring

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#110]
If you want to report a bug, please provide the following information:

- [ v3.7.1 ] Rainbond versions
- [ ] Kubernetes versions
- [ ] Docker version
- [centOS7.4 ] Operating system and kernel
- [ Aliyun] Provider(Aliyun,VirtualBox,...)
- [ ] Install details(Online/Offline,Single node/HA)
- [ ] Steps to reproduce

## 1、Rbd-repo monitoring problems when multiple nodes are deployed
- When multiple management nodes are deployed and a management node is down and restarted, rbd-repo does not follow the server to restart. But when the `grctl cluster` is executed, it is shown to be healthy.

![image](https://user-images.githubusercontent.com/33855684/45283013-4285c500-b50f-11e8-9db6-157ffa307a2e.png)

- Please change the condition of rbd-repo health monitoring to prevent the system from mistakenly thinking that rbd-repo is running normally.

## 2、The calico network did not start properly after the compute node was restarted.
- Following the previous problem, the calico network will not restart with the server after a single node is restarted, but health monitoring still considers it OK

![image](https://user-images.githubusercontent.com/33855684/45283601-e7ed6880-b510-11e8-9ff2-f5bac524ea3d.png)

## 3、Health monitoring problems caused by switching storage
- If the user has switched storage in the environment, then a successful mount is likely, but health monitoring identifies a failed mount.
- In the case above, make sure the hidden files are copied when you transfer the /grdata directory contents. Storing the credential files used by health monitoring is located in a hidden file in the Shared store

**Comment by zjhgoodrain** [comment]
It has been fixed
