### ISSUE TITLE
为什么AppService不定义成CR，而是在内存

### ISSUE THREAD

**Issue by gzlj** [goodrain/rainbond#1110]
为什么是在内存维护AppService底下的子资源（pod等）？这样有时候不能快速和k8s的etcd一致。

**Comment by barnettZQG** [comment]
@gzlj  内存维护的AppService数据模型是组件与Kubernetes Resource 的映射关系，属于状态数据。

**Comment by gzlj** [comment]
> @gzlj 内存维护的AppService数据模型是组件与Kubernetes Resource 的映射关系，属于状态数据。

AppService底下的子资源，没有锁，可以存在有多个协程（informer中的handler方法、UpdateAppServiceStatus之类的方法）并发修改切片，有概率出现数据丢失。为什么不通过在informer的缓存中新增自定义索引方法，来达到相同和拷贝数据一样的效果。例如获取APPService下的pod，可以通过索引方法直接获取，也可以同步到CR中的status字段中。

**Comment by barnettZQG** [comment]
@gzlj  关于一致性，这里考究的是最终一致性，AppService 依赖 informer 的通知形成数据最终一致。

**Comment by gzlj** [comment]
> @gzlj 关于一致性，这里考究的是最终一致性，AppService 依赖 informer 的通知形成数据最终一致。

AppService底下管理的Pod等资源的更新，依赖于注册在informer中的handler方法，但如果AppService在并发map中没缓存，会去数据库拿数据组装，有时候数据库卡顿好几秒，会导致handler方法的执行时间过长，导致后续Pod等资源更新明显不及时。这种方式更新Pod资源，受handler方法的执行时间长短的影响。
