### ISSUE TITLE
连接不上应用市场

### ISSUE THREAD

**Issue by cichuliubai** [goodrain/rainbond#1114]
**Describe the bug**
应用市场突然连接不上，显示：
{"msg":"HTTPSConnectionPool(host='store.goodrain.com', port=443): Max retries exceeded with url: /app-server/openapi/apps/c705df4d711c4a73ac03d9636af25ac8?marketDomain=rainbond (Caused by SSLError(SSLError(\"bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)\",),))","code":10401,"msg_show":"服务端异常"}

**截图**
![image](https://user-images.githubusercontent.com/39149203/140595965-8fac0f3e-de61-4d09-ba61-97ad11c09a2f.png)

rainbond版本：5.2.2
因为连接不上应用市场，导致没法升级

**Comment by yangkaa** [comment]
应用市场证书更换导致，目前应该已正常。

**Comment by yangkaa** [comment]
如果还有问题，请重新打开
