### ISSUE TITLE
添加组件失败后一直显示处于创建中，无法删除

### ISSUE THREAD

**Issue by posssss** [goodrain/rainbond#1115]
添加组件失败后一直显示处于创建中，无法删除，删除貌似只能进入组件页面删除，然后一直显示组件 undefined

**Comment by yangkaa** [comment]
![image](https://user-images.githubusercontent.com/30614084/144535713-73571f2c-e7ef-44e5-be97-8efd2b86ea22.png)
可以在批量操作这里删除

**Comment by yangkaa** [comment]
已于5.5.0版本修复。https://github.com/goodrain/rainbond-ui/pull/906/files
