### ISSUE TITLE
网关策略不生效问题

### ISSUE THREAD

**Issue by pescox** [goodrain/rainbond#1122]
【BUG描述】
在网关策略数量上来后，每次部署新的应用并配置网关策略都不能直接生效。
重启rbd-gateway后，就生效了。
重启rbd-gateway会一直生成类似如下的日志：
![a6e561b67894d358b1be7c8079b9868](https://user-images.githubusercontent.com/33922888/147640727-42534199-469f-425e-bc4c-364a2483dc59.png)

【部署环境】
- Rainbond版本: [v5.4.1]
- 操作系统类型和版本: Kubernetes V1.21.5
- 离线部署/网络开放：[网络开放]

~~~ rainbond集群有还有过备份恢复的经历，从allinone数据迁移到了商店部署rainbond，而且出现该问题也是迁移之后。

**Comment by yangkaa** [comment]
麻烦再提供下现在的网关策略大概数量有多少呢

**Comment by pescox** [comment]
目前gateway网关数量33个

**Comment by yangkaa** [comment]
麻烦再提供下k8s集群是如何创建的

**Comment by pescox** [comment]
我补充了一点信息： rainbond集群有还有过备份恢复的经历，从allinone数据迁移到了商店部署rainbond，而且出现该问题也是迁移之后。
k8s集群是通过rancher部署起来的。第一次部署rainbond是rancher那边通过helm安装，后面用商店重新安装后，迁移了数据。

**Comment by yangkaa** [comment]
好的，后续有时间了，我会尽快排查一下

**Comment by dargoner** [comment]
同样版本，同样的问题

**Comment by dargoner** [comment]
一般是先配置，然后过了一晚第二天就生效了，新的还需要再等一天

**Comment by wzy1880** [comment]
Rainbond版本: [v5.5.0]
出现同样的问题,会不会内存不够

**Comment by yangkaa** [comment]
This issue was fixed in version 5.7.0 , I will close this issue
