### ISSUE TITLE
网关集成path-rewrite功能

### ISSUE THREAD

**Issue by pescox** [goodrain/rainbond#1125]
# Rainbond实现路由重写功能

## 需求

目前rainbond网关只实现了简单的location代理，并未提供路由重写相关的功能。

目前配置网关location只能做到如下：

- 第一种：

  ```nginx
  location / {
      proxy_pass http://127.0.0.1; 
  }
  ```

- 第二种：

  ```nginx
  location /path {
      proxy_pass http://127.0.0.1; # 目标服务自带了/path路径
  }
  ```

当前有这样的需求：要在目标服务`http://{upstream}/index.html`的path多加一层虚拟目录去访问：`http://example/abc/index.html`。

这样就可以实现

http://example/abc/index.html => http://{upstream-1}/index.html

http://example/def/index.html => http://{upstream-2}/index.html

## 实现

我们知道，nginx实际是可以帮助实现路由重写的，主要有两种实现形式：

- 第一种，简单路由重写：

  ```nginx
  location /path {
      proxy_pass http://127.0.0.1/; # upstream后面多添加了斜杠
  }
  ```

- 第二种，借助rewrite配置实现路由重写：

  ```nginx
  location / {
      rewrite /abc(/|$)(.*) /$2 last;
      proxy_pass http://127.0.0.1;
  }
  ```

实现nginx的路由重写配置，需要从UI前端提供HTTPRule配置入口，传输到Console将路由重写配置持久化后，再由Console传输到Rainbond端的API，去创建或更新Ingress，将路由重写的配置写入到IngressAnnotation。Gateway根据IngressAnnotation更新nginx的配置，并热加载实现路由重写功能。

![image-20220107152753549](https://towita-images.oss-cn-beijing.aliyuncs.com/illus/image-20220107152753549.png)

### UI

UI端HTTP网关新增配置参数：

创建或更新HTTP网关界面新增path-rewrite开关配置，以及复杂的rewrites配置

![image-20220107152500623](https://towita-images.oss-cn-beijing.aliyuncs.com/illus/image-20220107152500623.png)

调用接口console接口，传输额外参数：

```json
{
    ...
    # 新增
    "path_rewrite": true,
    "rewrites": []
}
# 或
{
    ...
    # 新增
    "path_rewrite": false,
    "rewrites": [
        {
            "regex": "/abc(/|$)(.*)",
            "replacement": "/$2",
            "flag": "last"
        }
    ]
}
```

### rainbond-console

console数据库service_domain新增字段：

```sql
ALTER TABLE `service_domain` ADD COLUMN `path_rewrite` bool DEFAULT false NOT NULL;
ALTER TABLE `service_domain` ADD COLUMN `rewrites` longtext NOT NULL;
```

接收ui新建和更新HTTPRule额外的path-rewrite参数，调用rianbond-api的AddHTTPRule接口，并持久化到console数据库。

### rainbond

region数据库新增gateway_http_rule_rewrite数据表，gateway_http_rule表新增path_rewrite字段。

table: http_rule

| column       | type | desc                 |
| ------------ | ---- | -------------------- |
| path_rewrite | bool | 是否开启简单路由重写 |

table: gateway_http_rule_rewrite

| column       | type    | desc                 |
| ------------ | ------- | -------------------- |
| uuid         | varchar |                      |
| http_rule_id | varchar | http rule uuid       |
| regex        | varchar | nginx rewrite config |
| replacement  | varchar | nginx rewrite config |
| flag         | varchar | nginx rewrite config |

**api**

创建或更新HTTPRule接收rainbond-console额外的path-rewrite配置参数，持久化到region数据库。

**worker**

创建或更新ingress，path-rewrite的配置体现到ingress的annotation中。

**gateway**

检测ingress以及annotation的变化，更新nginx配置并生效。

## 数据库脚本

**console数据库**

```sql
ALTER TABLE `service_domain` ADD COLUMN `path_rewrite` bool DEFAULT false NOT NULL;
ALTER TABLE `service_domain` ADD COLUMN `rewrites` longtext NOT NULL;
```

### 镜像替换

- console测试镜像：`pescox/rainbond-console:pr-path-rewrite-0.1`
- rbd-api测试镜像：`pescox/rbd-api:pr-path-rewrite-0.1`
- rbd-worker测试镜像：`pescox/rbd-worker:pr-path-rewrite-0.1`
- rbd-gateway测试镜像：`pescox/rbd-gateway:pr-path-rewrite-0.1`

### UI测试

以下截图为rainbond-ui代码，模拟创建/更新HTTP策略时新增传输参数 `path_rewrite`，`rewrites`，

![image-20220111114906096](https://towita-images.oss-cn-beijing.aliyuncs.com/illus/image-20220111114906096.png)

按照正确的功能逻辑：

- 会在console数据库表service_domain中path_rewrite和rewrites字段下生成数据；

- 会在region数据库新增表gateway_http_rule_rewrite，并生成数据，会在gateway_http_rule表path_rewrite字段下生成数据。

- 创建的ingress具有path-rewrite的annotation

  ```yaml
  # 1. Simple path-rewrite
  nginx.ingress.kubernetes.io/path-rewrite: 'true'
  
  # 2. complex path-rewrite
  nginx.ingress.kubernetes.io/rewrite-0-flag: last
  nginx.ingress.kubernetes.io/rewrite-0-regex: /nginx(/|$)(.*)
  nginx.ingress.kubernetes.io/rewrite-0-replacement: /$2
  ```

- 访问服务，可以正确的使用路由重写

  ![image-20220107115912520](https://towita-images.oss-cn-beijing.aliyuncs.com/illus/image-20220107115912520.png)

**Comment by RainBondsongyg** [comment]
ui如何调整

**Comment by pescox** [comment]
> ui如何调整
你可以查看这个issue的UI部分，我更新了一下。

**Comment by yangkaa** [comment]
ui：https://github.com/goodrain/rainbond-ui/pull/919

console：https://github.com/goodrain/rainbond-console/pull/1006

region：https://github.com/goodrain/rainbond/pull/1124

Thank you for your contribution. I will close this issues after the front-end code is merged
