### ISSUE TITLE
网关策略不生效问题

### ISSUE THREAD

**Issue by liukai12** [goodrain/rainbond#1128]
**Describe the bug**
应用重新构建后，端口绑定的域名不生效了，需要重新绑定才行。

**To Reproduce**
1. 构建应用
2.点击访问
![微信截图_20220106161944](https://user-images.githubusercontent.com/24822691/148352665-fbe99934-d0f9-4441-96cb-c0b51a7ec5ef.png)
3.删除原来绑定的域名，重新绑定
![微信截图_20220106162827](https://user-images.githubusercontent.com/24822691/148352972-28a98c6e-b288-4ae7-b903-46c955b693c7.png)

4. 再次访问正常
![微信截图_20220106162919](https://user-images.githubusercontent.com/24822691/148353042-cc11bed5-d7f4-4f8c-b521-6ff22cf92159.png)

**The relevant information:**
 - Rainbond Version [5.5.0]
 - Browser [chrome] 
 - Kubernetes version [v1.19.6]

**Comment by yangkaa** [comment]
是一个应用多个网关策略下出现这个问题？还是默认只有一条网关策略的时候也存在该问题

**Comment by liukai12** [comment]
一个应用下的多个网关策略都不生效

**Comment by yangkaa** [comment]
如果只有一个默认网关策略的情况下，构建完毕，也会不生效吗

**Comment by liukai12** [comment]
也会不生效

**Comment by yangkaa** [comment]
好的，后续我会排查一下

**Comment by zzzhangqi** [comment]
根据你提供的方式没有复现，请提供详细的操作步骤

**Comment by yangkaa** [comment]
Fix: https://github.com/goodrain/rainbond/commit/0de2202a98360e347396ff5bacdfbe083989ecc9
