### ISSUE TITLE
资源监控不生效，伸缩查询命令不显示信息

### ISSUE THREAD

**Issue by liukai12** [goodrain/rainbond#1129]
**Describe the bug**
控制台资源监控无数据显示，伸缩功能里的查询命令查看不了信息

**To Reproduce**
![微信截图_20220106163305](https://user-images.githubusercontent.com/24822691/148353531-e3a407cf-7169-4ca0-aae5-bebbfb3fd098.png)
![微信截图_20220106163334](https://user-images.githubusercontent.com/24822691/148353572-a71cea36-dcdf-430b-93f6-4bdbf07bbcea.png)
![微信截图_20220106163404](https://user-images.githubusercontent.com/24822691/148353620-01408357-bc0b-443e-8a65-d46d666b0c5f.png)

**The relevant information:**
 - Rainbond Version [5.5.0]
 - Browser [chrome] 
 - Kubernetes version [v1.19.6]

**Comment by yangkaa** [comment]
grctl命令是否更新到5.5版本？资源监控后续会进行修复

**Comment by liukai12** [comment]
新安装的，就是5.5版本

**Comment by yangkaa** [comment]
grctl version 查看下

**Comment by liukai12** [comment]
![7a5cfbfe5c70305a625492017c5afef](https://user-images.githubusercontent.com/24822691/148360030-c2ee6eee-5e1c-4132-a8e6-2dec48acf06d.png)
![05104ca3fb255a293b5cccbc21fe718](https://user-images.githubusercontent.com/24822691/148360043-d16c8e1b-e411-4173-af4c-f36dc74032f6.png)
![f5f9fa00eedcad5a826f10980c52aa2](https://user-images.githubusercontent.com/24822691/148360059-4ec0d1fa-6c8b-43dd-b6e1-2470f090ce45.png)
刚更新了下，命令查看不了了，kubecttl是可以的

**Comment by yangkaa** [comment]
grctl查看不了的话，排查rbd-api的日志,另外，服务器公网ip建议打码

**Comment by liukai12** [comment]
我是配了负载均衡后，把grctl更新到5.5就不行了
![5682e91084e75232bc8106f680762c5](https://user-images.githubusercontent.com/24822691/148521606-69cdd4df-1585-4a09-bd23-baebb6b6923c.png)
我用grctl config 看了访问的是网关的8443，但访问不了

**Comment by yangkaa** [comment]
看起来是证书的问题，根目录下有个 `.rbd`的隐藏目录，删除这个目录， 重新安装grctl试试

**Comment by yangkaa** [comment]
This issue was fixed in version 5.7.0 , I will close this issue
