### ISSUE TITLE
 MYSQL-Percona-Cluster安装构建失败

### ISSUE THREAD

**Issue by liukai12** [goodrain/rainbond#1131]
**Describe the bug**
 MYSQL-Percona-Cluster安装构建失败
etcd-cluster组件错误信息
![image](https://user-images.githubusercontent.com/24822691/148522146-5561f870-32ef-481a-bc49-cade64da9f84.png)
![image](https://user-images.githubusercontent.com/24822691/148522300-4e6556ef-3a64-4010-88ae-0bfe936b54a0.png)
pxc-db组件错误信息
![image](https://user-images.githubusercontent.com/24822691/148522362-b2132af0-90c4-4142-9029-2b949cb38f64.png)
![image](https://user-images.githubusercontent.com/24822691/148522414-24f53c73-70ce-44a7-8351-84a9e74940bf.png)
![image](https://user-images.githubusercontent.com/24822691/148522453-1c60bd37-0afc-4905-9b65-59fc598201cf.png)
pxc-haproxy组件错误信息
![image](https://user-images.githubusercontent.com/24822691/148522537-c3902f88-8b75-410c-be81-b8fef0ee0b5d.png)
![image](https://user-images.githubusercontent.com/24822691/148522576-3b8e8dae-7b5e-4ad3-b0da-109856790987.png)
![image](https://user-images.githubusercontent.com/24822691/148522627-6e076620-3241-4a9d-a999-5442026d6b82.png)

**The relevant information:**
 - Rainbond Version [5.5.0]
 - Browser [chrome]
 - Kubernetes version [1.19.6]

**Comment by zzzhangqi** [comment]
Etcd failed to start due to this [problem,[1133](https://github.com/goodrain/rainbond/issues/1133)

**Comment by yangkaa** [comment]
Fix: https://github.com/goodrain/rainbond/commit/3f367ed851bfd861333ae2a9f455411df4239ed2
