### ISSUE TITLE
The service_name in the component environment variable is different from the component statefulset

### ISSUE THREAD

**Issue by zzzhangqi** [goodrain/rainbond#1133]
in v5.5.0 before,the service_name in the component environment variable is same from the component statefulset.

For example:
```
service_name=gr8e4818

$ kubectl get sts -n xxx

NAME         READY   AGE
gr8e4818   1/1     108m

```

now:
```
service_name=gr8e4818
$ kubectl get sts -n xxx

NAME                                  READY   AGE
app-d9928a22-gr8e4818   1/1     108m
```

This will cause applications that use service_name to become unavailable

**Comment by lokywang** [comment]
+1

**Comment by yangkaa** [comment]
Duplicate problem: https://github.com/goodrain/rainbond/issues/1131
Fixed: https://github.com/goodrain/rainbond/commit/3f367ed851bfd861333ae2a9f455411df4239ed2
