### ISSUE TITLE
Cluster initialization problem

### ISSUE THREAD

**Issue by isteven-xu** [goodrain/rainbond#1134]
**Describe the bug**
Cluster initialization problem

**Screenshots**
![image](https://user-images.githubusercontent.com/32054226/150072653-af2eb8fa-151e-418d-be87-af598cb077f0.png)
![image](https://user-images.githubusercontent.com/32054226/150072736-0e9ec8f7-2f17-47fb-9af9-249d8cdac465.png)

**The relevant information:**
 - Rainbond Version :  v5.5.0-release-f8f342c-2021-12-14-08-allinone
 - Browser : chrome
 - Kubernetes version : v1.19.6

**Comment by dazuimao1990** [comment]
As you see ,the pods belong to flannel is running into error status.exec cmds below, you can find logs about flannel pods:
```bash
kubectl logs -f kube-flannel-xxxx -n kube-system
```
I guess you are running flannel in a offline env, without default route. have a look please.

**Comment by dazuimao1990** [comment]
If the problem is not resolved, reopen the issue.
