### ISSUE TITLE
点击对外服务按钮返回-数据中心故障，操作失败

### ISSUE THREAD

**Issue by pxbs1982** [goodrain/rainbond#1135]
**Describe the bug**

**To Reproduce**
1. 进入 组件  端口 页面
2. 点击  对外服务
3. 数据中心故障，操作失败  --- 400 Bad Request

**Screenshots**

**The relevant information:**
 - Rainbond Version [e.g. 5.5.0]

**Comment by dazuimao1990** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. 进入 组件  端口 页面
> 2. 点击  对外服务
> 3. 数据中心故障，操作失败  --- 400 Bad Request
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **The relevant information:**
> 
> * Rainbond Version [e.g. 5.5.0]

请贴上400页面的具体报错的截图，以及控制台 （rainbond-allinone）中的 /app/logs/goodrain.log 日志内容，在触发问题的时候，里面会有详细的信息

**Comment by yangkaa** [comment]
集群安装时未成功创建域名解析导致。此种情况下，无法使用http协议，切换协议为tcp后，再打开对外端口访问。如需使用http协议，可以在企业视图下，选择集群，点击编辑，修改HTTP应用默认域名后缀，该域名后缀需要能解析到所在机器的网关IP
![image](https://user-images.githubusercontent.com/30614084/150288617-2b55cb20-0433-4923-b7aa-a1d62932c25a.png)

**Comment by yangkaa** [comment]
If you have any questions, please reopen it
