### ISSUE TITLE
Can not close outer or inner port

### ISSUE THREAD

**Issue by pescox** [goodrain/rainbond#1136]
Rainbond正常运行，突然发现有一个组件无法关闭对外或对内服务，并且返回了报错信息。
<img width="682" alt="cd0fc50240cbf35bd9cd056a25d8baf" src="https://user-images.githubusercontent.com/33922888/150962395-75623548-b709-4eb3-aa24-377aa24fbaee.png">
<img width="741" alt="88386db93fc95d51837cebaac3a918d" src="https://user-images.githubusercontent.com/33922888/150962426-605bf136-d7c6-47f9-8f13-b739ff5ceeac.png">
 错误提示是无法找到端口，但是查询region数据库的tenant_service_port表，数据是存在的。
![image](https://user-images.githubusercontent.com/33922888/150962796-5992a188-d548-4442-9039-2e040a96f1af.png)

平台信息：
 - Rainbond Version : 5.4.1
 - Kubernetes version: 1.21.5

**Comment by yangkaa** [comment]
![image](https://user-images.githubusercontent.com/30614084/150965825-13b94e8a-1a03-477f-bc7d-64aebb41f6da.png)
很明显，这个组件的1883端口在region数据库中不存在。筛选条件有组件ID和端口才行。

这种情况通常是 console 和 region 端数据库数据不一致导致的。该组件是否有做过升级或删除/添加端口等操作。或是否存在集群端异常时，修改过组件端口等操作。

临时处理办法为：手动修改 console 库中表 tenant_services_port 的该端口数据，修改 is_inner_service 和 is_outer_service字段为false，再在UI界面删除该端口，重新添加即可。

**Comment by pescox** [comment]
> ![image](https://user-images.githubusercontent.com/30614084/150965825-13b94e8a-1a03-477f-bc7d-64aebb41f6da.png) 很明显，这个组件的1883端口在region数据库中不存在。筛选条件有组件ID和端口才行。
> 
> 这种情况通常是 console 和 region 端数据库数据不一致导致的。该组件是否有做过升级或删除/添加端口等操作。或是否存在集群端异常时，修改过组件端口等操作。
> 
> 临时处理办法为：手动修改 console 库中表 tenant_services_port 的该端口数据，修改 is_inner_service 和 is_outer_service字段为false，再在UI界面删除该端口，重新添加即可。

感谢，通过你提供的方法解决了问题。

**Comment by yangkaa** [comment]
我将关闭此问题，如果有能完整复现该现象的流程，请重新打开。
