### ISSUE TITLE
报错未知的Cloud错误，错误码为7028

### ISSUE THREAD

**Issue by chaiqinghu** [goodrain/rainbond#1138]
**问题描述**
我在添加集群的时候选择接入kubernetes 集群，报错未知的Cloud错误，错误码为7028，因为重复添加了同一个集群报以上问题
**问题复现**
1. 正常添加接入k8s集群
2. 发现18个组件一直夯在第3个组件
3. 重新添加k8s集群
4. 发现报错

**截图如下**
![image](https://user-images.githubusercontent.com/34148134/152765370-d0d48149-2eb6-4bf0-9ae4-35830ee547b3.png)
**rdb-system 名称空间的pod状态如下** 
![image](https://user-images.githubusercontent.com/34148134/152766175-6a474d2c-2958-4ecb-85ff-3841f8d07da1.png)

**Comment by yangkaa** [comment]
7028表示已经在集群中进行过初始化操作。
目前看pod的状态是Evicted，表示Pod被驱逐，需要检查你的K8s集群的状态。这种情况通常是由于节点资源匮乏或节点不健康导致的

**Comment by yangkaa** [comment]
状态码需要翻译：
7020 rke配置格式不正确
7021 rke配置丢失
7022 初始化集群任务不存在
7023 rke集群已存在
7026 更新集群任务不存在
7027 集群不存在
7028 rbd-system命名空间已存在，无法再次初始化
7029 集群任务不存在
8000 Helm商店不存在
8001 Helm商店名冲突
8003 Helm应用模版不存在
8004 Helm应用模版版本不存在

**Comment by chaiqinghu** [comment]
感谢，问题已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "goodrain/rainbond"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月23日(星期三) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [goodrain/rainbond] 报错未知的Cloud错误，错误码为7028 (Issue #1138)





 
状态码需要翻译：
 7020 rke配置格式不正确
 7021 rke配置丢失
 7022 初始化集群任务不存在
 7023 rke集群已存在
 7026 更新集群任务不存在
 7027 集群不存在
 7028 rbd-system命名空间已存在，无法再次初始化
 7029 集群任务不存在
 8000 Helm商店不存在
 8001 Helm商店名冲突
 8003 Helm应用模版不存在
 8004 Helm应用模版版本不存在
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yangkaa** [comment]
Merged: https://github.com/goodrain/rainbond-ui/pull/927/commits/7680d5fa08b3a6324a1c287d0d9a3d8d1dc53c22
