### ISSUE TITLE
rbd-worker内存泄漏

### ISSUE THREAD

**Issue by pescox** [goodrain/rainbond#1139]
如果在Rainbond中创建了第三方组件，那么rbd-worker的内存占用会不断上升。经go pprof分析发现，程序goroutine数量不断增加，内存消耗也随之不断上升。
![image](https://user-images.githubusercontent.com/33922888/153142173-8cc23d0b-d186-4f9e-9e68-73770338a3ca.png)
继续借助go pprof web工具分析，发现在不断创建goroutine的位置是[这里](https://github.com/goodrain/rainbond/blob/9d2ade2cc3bfac857d1e7ee0c756a082e59b8cf2/worker/master/controller/thirdcomponent/discover/discover.go#L85)
<img width="853" alt="6c35de11d940dad977ff8bc4c5835a3" src="https://user-images.githubusercontent.com/33922888/153142374-f1e8d2a8-f97b-4d5e-b7c0-5abc5af4b0a0.png">
Discover方法被Worker的Start方法中被不断调用，[这里](https://github.com/goodrain/rainbond/blob/9d2ade2cc3/worker/master/controller/thirdcomponent/worker.go#L35)，Discover方法中对endpoint的Watch会创建相关的goroutine，导致goroutine的数量一直上升。

复现问题的步骤：
1. 进入rainbond控制台，进入团队页面；
2. 如果确定当前没有创建过第三方组件，创建第三方组件，组件注册方式为Kubernetes；
3. 添加有效的端口，如果没有问题，那么组件会成功获取到实例；
4. 此时，观察rbd-worker的内存占用情况，会一直上升。

其他：
Kubernetes版本：V1.21.5
Rainbond版本：>V5.4.0

**Comment by yangkaa** [comment]
You did a good job
