### ISSUE TITLE
通过源码构建.Net6应用镜像，pod无法启动。

### ISSUE THREAD

**Issue by xixinlove** [goodrain/rainbond#1141]
**To Reproduce**
当前版本只支持.Net core 3.1版本构建应用。通过手动拉取.net 6 SDK镜像后使用tag改名为microsoft/dotnet:6.0-sdk，可以完成.Net6应用的构建。【.Net 5同理也可实现】
但是构建之后的应用无法启动,提示错误为：**OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"start\": executable file not found in $PATH": unknown**

**Screenshots**
通过kubectl get pod查询pod信息如下：
[yaml.txt](https://github.com/goodrain/rainbond/files/8067331/yaml.txt)

**The relevant information:**
 - Rainbond Version [5.5.0]
 - Kubernetes version [v1.19.6]
 - Docker version [v19.03.5]

**Comment by zzzhangqi** [comment]
看了你的yaml有
```
args:
  - start
  - web
```
这个是不对的，看起来是个bug

你可以参考 https://www.rainbond.com/docs/component-create/language-support/netcore 项目运行部分添加一个 [rainbondfile](https://www.rainbond.com/docs/component-create/language-support/rainbondfile/) 手动添加cmd部分

**Comment by zzzhangqi** [comment]
看了你的yaml有
```
args:
  - start
  - web
```
这个是不对的，看起来是个bug

你可以参考 https://www.rainbond.com/docs/component-create/language-support/netcore 项目运行部分添加一个 [rainbondfile](https://www.rainbond.com/docs/component-create/language-support/rainbondfile/) 手动添加cmd部分

**Comment by xixinlove** [comment]
通过添加rainbondfile完美解决。
总结一下.Net 5、6的完整构建步骤：
1、手动拉取.Net5、6的mcr镜像（sdk以及runtime）
2、docker tag，将镜像标记为类似microsoft/dotnet:6.0-sdk格式
3、构建时手动添加BUILD和RUNTIME参数
4、项目中添加rainbondfile，手动加入启动命令dotnet xxxxx.dll
5、修改代码中监听端口及IP
6、构建
