### ISSUE TITLE
rbd-worker由于helm商店安装应用导致goroutine泄漏

### ISSUE THREAD

**Issue by pescox** [goodrain/rainbond#1143]
在Rainbond中新建了helm商店后，使用helm商店安装应用后，worker内存持续上升，使用go pprof功能分析，正是helmapp包内ControlLoop.Reconcile函数不断NewApp创建goroutine导致。
![image](https://user-images.githubusercontent.com/33922888/154387350-71f9ab12-d1ba-430a-a9aa-4c2d4aa89b28.png)
![image](https://user-images.githubusercontent.com/33922888/154387473-e67779eb-9b70-4811-8642-e42656018594.png)
问题最终定位在[这里](https://github.com/goodrain/rainbond/blob/V5.4/worker/master/controller/helmapp/app.go#L101)，eventBroadcaster.NewRecorder函数结束后，eventBroadcaster没有调用StutDown函数关闭channel，回收相关资源。

其他：
Kubernetes版本：V1.21.5
Rainbond版本：>V5.4.0

**Comment by yangkaa** [comment]
Thank you for your contribution
