### ISSUE TITLE
希望dashboard能支持istio 跨网络多集群的聚合显示

### ISSUE THREAD

**Issue by YouthInThinking** [goodrain/rainbond#1146]
多个istio集群在不同的网络环境的各个集群信息可以在dashboard全部显示并且可以对相应的资源对象执行常规的操作
如果可以显示集群的流量细节就更棒了

比如kiali 很遗憾它目前只支持但集群，多集群场景下需要在每个集群里都部署一套才可以看到相应的集群信息

如果rainbond能支持多集群场景下的可观测性就更棒了

**Comment by zzzhangqi** [comment]
感谢您对Rainbond产品提出建议，您的意思是希望 Rainbond 的页面支持 istio 的跨集群可观测性嘛？目前Rainbond 对于 istio 的引入是作为 Service Mesh 的插件体系，流量治理等都是在 kiali 中。
