### ISSUE TITLE
OAuth账号绑定gitlab时需要重复绑定，过段时间（大概几个小时）需要重新认证

### ISSUE THREAD

**Issue by yeshusheng1234** [goodrain/rainbond#1147]
如图示
这是已认证状态
![1645779836742_9A602665-9C42-4af8-8BEB-16FC6790B743](https://user-images.githubusercontent.com/100832831/156524046-eb821080-54bb-453b-ac65-d596f7bac6f2.png)

几小时后待认证
![1645843978539_E4AE5F55-46E1-44b9-8F0E-0235FBDCBEE1](https://user-images.githubusercontent.com/100832831/156524130-00211d5c-67ee-436b-a84e-a6fa3c32e43d.png)

**Comment by zzzhangqi** [comment]
请提供 Rainbond 版本和 Gitlab版本，给出具体信息方便我们排查

**Comment by yeshusheng1234** [comment]
rainbond版本 v5.5.0
gitlab版本14.5.0

**Comment by yangkaa** [comment]
Fix: [Fix OAuth authentication expiration](https://github.com/goodrain/rainbond-console/commit/131ee2b4f545a7a00561a19ddfa03c64d82b0ab0)
