### ISSUE TITLE
基于主机高可用 GlusterFS作为共享存储 在第九步 迁移控制台的时候 提示数据中心资源不存在

### ISSUE THREAD

**Issue by lokywang** [goodrain/rainbond#1151]
**Describe the bug**

基于主机高可用 GlusterFS作为共享存储 在第九步 迁移控制台的时候 提示数据中心资源不存在

按照bilibili提供的基于主机高可用教程视频,做到第九步-控制台迁移的时候,从开源市场安装 Rainbond-开源,提示数据中心资源不存在,
是因为我用的外部存储mysql吗?在但数据能连接上,并创建了相应的表结构和数据;

**Screenshots**
![image](https://user-images.githubusercontent.com/28672424/159849364-04450658-5be2-42d1-8f3b-628f8a89dde8.png)

控制台-UI日志如下
![image](https://user-images.githubusercontent.com/28672424/159849417-ebf6acd2-0653-41fb-953d-b93311e7068f.png)

![image](https://user-images.githubusercontent.com/28672424/159849746-adc7e059-9ff8-4272-ace0-03b38dee8db4.png)

rainbond版本 5.6

**Comment by zzzhangqi** [comment]
你这个报错页面是迁移后的控制台报的吗，allinone是否正常。
如果allinone正常，那就是数据没有迁移过去，请问使用的是什么数据库

**Comment by lokywang** [comment]
> 你这个报错页面是迁移后的控制台报的吗，allinone是否正常。 如果allinone正常，那就是数据没有迁移过去，请问使用的是什么数据库

报错界面是迁移前的 我看到教程上面是在allinoe 创建组件 rainbond,然后在将allinone的数据导入到新的rainbond中   数据库用的是mysql 5.7.33

**Comment by lokywang** [comment]
报错界面是迁移前的 我看到教程上面是在allinoe 创建组件 rainbond,然后在将allinone的数据导入到新的rainbond中 数据库用的是mysql 5.7.33

**Comment by zzzhangqi** [comment]
1.  allinone 默认使用sqlite，你是换了mysql么
2. 上图的报错是 allinone 报的吗
3. 进入 allinone 内提供下 /app/logs/goodrain.log 日志

看样子是创建了组件没有写到数据库中，导致了报错

**Comment by lokywang** [comment]
我重新装了一遍更换了教程里面的mysql主从,发现好了 感谢指导
