### ISSUE TITLE
rainbond-cert-controller  自动申请证书 没有成功

### ISSUE THREAD

**Issue by lokywang** [goodrain/rainbond#1153]
**Describe the bug**
安装了rainbond-cert-controller组件   组件按照教程上也配置了 但并没有申请到证书 看日志也没看出什么来,日志如下图

rainbond已做高可用,并迁移到集群中了 rainbond-cert-controller组件也是安装在了集群中的

但自己通过 https://github.com/hongyaa-tech/rainbond-cert-controller  本地docker运行 神奇的是 成功了 并申请到了证书,并且发送了钉钉通知;
但在组件却没有申请到,也没有发送通知;

**Screenshots**
![image](https://user-images.githubusercontent.com/28672424/160232475-775649ea-63a7-4672-800f-ee1ab52c0b68.png)

**The relevant information:**
 - Rainbond Version [e.g. 5.6.0]
 - Browser [e.g. chromei] (if it is the front-end bugs, please provide)
 - Kubernetes version [e.g 1.16.3]

**Comment by lxm** [comment]
从日志上来看，是从rainbond openapi获取信息出错了

**Comment by lokywang** [comment]
那openapi地址是哪个呢? 是控制台的域名吗?

**Comment by lokywang** [comment]
help!!!!!

**Comment by yangkaa** [comment]
openapi的地址配置为控制台的访问地址就行。建议粘贴完整日志。

**Comment by lokywang** [comment]
![image](https://user-images.githubusercontent.com/28672424/164197466-d9eea23b-8c84-4754-9ac7-4e4a607da24b.png)
选择哪个地址呢? 上面的截图就是完整的日志

**Comment by zzzhangqi** [comment]
社区包含同样的问题，请您在社区中答复，感谢！
https://t.goodrain.com/d/19-rainbond-cert-controller
