### ISSUE TITLE
5.1的版本清理磁盘

### ISSUE THREAD

**Issue by meijianxin110** [goodrain/rainbond#1154]
## The requirements?
...
5.1的版本磁盘空间满了，是否有办法清楚，使用的gcluster的文件系统
## Way:
...

**Comment by dazuimao1990** [comment]
如果使用了 glusterfs ，那么服务器本地存储的文件估计就是本地镜像文件了，可以通过以下命令尝试清理。

```bash
docker system prune -a
```

注意这个命令清理的范围比较大，参考文档 https://docs.docker.com/engine/reference/commandline/system_prune/ 了解它的全部
