### ISSUE TITLE
添加阿里云第三方组件redis/mysql，健康状态始终通过不了

### ISSUE THREAD

**Issue by hcxjava** [goodrain/rainbond#1155]
![image](https://user-images.githubusercontent.com/102670721/160836951-c989784c-a664-4207-8288-a1ef69ef5fe3.png)
kubectl describe thirdcomponent e3e48c851e8dc9320d15f69bf0f346c2 -n yun

Name:         e3e48c851e8dc9320d15f69bf0f346c2
Namespace:    yun
Labels:       app=app-e01d5fa3
              app_id=e01d5fa380144ae08295b1b06956180d
              creater_id=1648634711489618695
              creator=Rainbond
              service_alias=grf346c2
              service_id=e3e48c851e8dc9320d15f69bf0f346c2
              tenant_id=f98cde5ba9c8480da5e6da4764a1646a
              tenant_name=uovi5d6p
Annotations:  app.oam.dev/last-applied-configuration:
                {"apiVersion":"rainbond.io/v1alpha1","kind":"ThirdComponent","metadata":{"labels":{"app":"app-e01d5fa3","app_id":"e01d5fa380144ae08295b1b0...
API Version:  rainbond.io/v1alpha1
Kind:         ThirdComponent
Metadata:
  Creation Timestamp:  2022-03-30T09:46:09Z
  Generation:          2
  Managed Fields:
    API Version:  rainbond.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:app.oam.dev/last-applied-configuration:
        f:labels:
          .:
          f:app:
          f:app_id:
          f:creater_id:
          f:creator:
          f:service_alias:
          f:service_id:
          f:tenant_id:
          f:tenant_name:
      f:spec:
        .:
        f:endpointSource:
          .:
          f:endpoints:
        f:ports:
        f:probe:
          .:
          f:failureThreshold:
          f:periodSeconds:
          f:successThreshold:
          f:tcpSocket:
          f:timeoutSeconds:
      f:status:
        .:
        f:endpoints:
        f:phase:
    Manager:         rainbond-worker
    Operation:       Update
    Time:            2022-03-30T09:46:53Z
  Resource Version:  170627821
  UID:               5d12b979-7aa5-45f6-af48-39a9cfa840e3
Spec:
  Endpoint Source:
    Endpoints:
      Address:  rm-bp1ke6i6245p2lghk3o.mysql.rds.aliyuncs.com:3306
      Name:     4146bb8b2d6c4bc08942b5730181bede
  Ports:
    Name:        grf346c23306
    Open Inner:  true
    Open Outer:  false
    Port:        3306
  Probe:
    Failure Threshold:  3
    Period Seconds:     3
    Success Threshold:  1
    Tcp Socket:
    Timeout Seconds:  20
Status:
  Endpoints:
    Address:  rm-bp1ke6i6245p2lghk3o.mysql.rds.aliyuncs.com
    Name:     4146bb8b2d6c4bc08942b5730181bede
    Status:   Unhealthy
  Phase:      Running
Events:
  Type     Reason             Age                     From                       Message
  ----     ------             ----                    ----                       -------
  Warning  EndpointUnhealthy  3m50s (x496 over 168m)  thirdcomponent-controller  probe failed: dial tcp 1.1.1.1:80: i/o timeout

**Comment by yangkaa** [comment]
可以尝试使用ip地址作为第三方组件，看是否能正常依赖

**Comment by hcxjava** [comment]
ip？登录阿里云那个对外地址不久ip吗？

**Comment by hcxjava** [comment]
ip?登录阿里云控制台那个公网访问不就是ip吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月30日 22:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [goodrain/rainbond] 添加阿里云第三方组件redis/mysql，健康状态始终通过不了 (Issue #1155) |

可以尝试使用ip地址作为第三方组件，看是否能正常依赖

**Comment by yangkaa** [comment]
![image](https://user-images.githubusercontent.com/30614084/160856222-de80e218-950b-4273-8f80-60805303914f.png)
就是直接使用 IP 作为第三方组件，例如这种形式

**Comment by yangkaa** [comment]
ping 域名

**Comment by hcxjava** [comment]
今天上午还是好的，就下午四五点的样子突然一下都不健康了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月30日 22:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [goodrain/rainbond] 添加阿里云第三方组件redis/mysql，健康状态始终通过不了 (Issue #1155) |

具体原因需要后续排查，ip+端口只是一个临时解决方案

**Comment by hcxjava** [comment]
![image](https://user-images.githubusercontent.com/102670721/160860155-8af7bbd5-0fdb-45b4-99f2-d86265ec6810.png)
如果是我别的组件，在环境里面配置了的话，是需要替换成ip+端口吗

**Comment by yangkaa** [comment]
应该不用，通过第三方组件代理出来无法使用的，可以通过这种方式暂时绕过
