### ISSUE TITLE
Error reporting for access application market 503

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#116]
If you want to report a bug, please provide the following information:

- [ v3.7.1] Rainbond versions
- [ ] Kubernetes versions
- [ ] Docker version
- [centOS7.4 ] Operating system and kernel
- [ ] Provider(Aliyun,VirtualBox,...)
- [ ] Install details(Online/Offline,Single node/HA)
- [ ] Steps to reproduce

When accessing the application market, an error is reported as shown in the figure
![image](https://user-images.githubusercontent.com/33855684/45484549-183e3c80-b787-11e8-8123-65b8df82ffbf.png)

**Comment by sycki** [comment]
The issue is fixed in next version.
