### ISSUE TITLE
FastDFS外网不可用

### ISSUE THREAD

**Issue by superjackwong** [goodrain/rainbond#1163]
**Describe the bug**

**To Reproduce**
1. 我在Web界面的开源应用商店拉取了FastDFS V5.07
2. 组件服务运行正常，当我需要使用EIP进行访问FastDFS Storage却被拒绝了
3. 通过进入FastDFS容器内部，运行“fdfs_monitor /etc/fdfs/storage.conf”查看得到了问题原因，FastDFS Storage ip_addr=127.0.0.1(见截图)
4. 我希望他默认不是本机内部IP，而是安装时设置的EIP，比如ip_addr=192.168.1.1

**Screenshots**
![6fd144856ff3dff9032fe0d917a2100](https://user-images.githubusercontent.com/57210156/162384424-ec486687-c590-419c-a00f-9c5261daaf37.png)

**The relevant information:**
 - Rainbond Version [v5.6.0-dind-962dc99-2022-03-17-11-allinone]
 - Browser [Google Chrome] 
 - Kubernetes version [1.19.6]

**Comment by zzzhangqi** [comment]
问题已收到，我们会在近期更新 `fastdfs` 版本并修复此问题

**Comment by dinghui40** [comment]
您被拒绝的图有吗，我这边使用时看起来时正常的

**Comment by dinghui40** [comment]
@superjackwong 您这边有被拒绝访问的图吗，我这边使用看起来时正常的，您rainbond是使用哪种方式搭建的呢

**Comment by dinghui40** [comment]
@superjackwong 如果您没有其他问题，我认为可以关闭这个问题了
