### ISSUE TITLE
部署组件404

### ISSUE THREAD

**Issue by haohao722** [goodrain/rainbond#1166]
**部署组件404**
部署最新版本的pig4cloud后，pig-register组件出现404，文档中只有以前版本的部署

**Comment by zzzhangqi** [comment]
这并不是 Rainbond 的问题，但我对 Pig 有所了解，麻烦你描述清楚如何部署以及相关日志和截图等详细信息，我可以更好的帮助到你

**Comment by haohao722** [comment]
可以访问到前端，但是验证码无法显示，pig-gateway报这个错





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "goodrain/rainbond"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月12日(星期二) 晚上10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [goodrain/rainbond] 部署组件404 (Issue #1166)





 
这并不是 Rainbond 的问题，但我对 Pig 有所了解，麻烦你描述清楚如何部署以及相关日志和截图等详细信息，我可以更好的帮助到你

**Comment by zzzhangqi** [comment]
日志报错，截图等相关信息麻烦提供，光凭文字我没法判断，感谢

**Comment by zzzhangqi** [comment]
如果您在5天内不再继续提出问题，我将关闭此 issue。
如问题未解决，可以再次打开此 issue

**Comment by zzzhangqi** [comment]
我将关闭此问题，有问题请随时打开

**Comment by haohao722** [comment]
现在应该就是配置文件不知道怎么配置，出的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "goodrain/rainbond"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月12日(星期二) 晚上10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [goodrain/rainbond] 部署组件404 (Issue #1166)





 
这并不是 Rainbond 的问题，但我对 Pig 有所了解，麻烦你描述清楚如何部署以及相关日志和截图等详细信息，我可以更好的帮助到你
