### ISSUE TITLE
前端使用网络综合治理插件代理下游应用不生效问题

### ISSUE THREAD

**Issue by gobaiy** [goodrain/rainbond#1167]
【问题描述】NODEJS项目构建成功后，使用网络综合治理插件无法代理下游应用，前端nginx日志如下：
![image](https://user-images.githubusercontent.com/49633387/162886546-0e0a093e-844d-4b1c-b732-4cc30b76790c.png)
![image](https://user-images.githubusercontent.com/49633387/162886578-9fabc361-42c6-4bd3-9605-42a245bb9d53.png)

【部署环境】
- Rainbond版本(执行`grctl version`获取): v5.6.0-release
- 操作系统类型和版本:Centos 7
- 离线部署/网络开放：网络开放

尝试处理后恢复：
1、前端构建成功后，添加网络综合治理插件，并重启组件，组件启动不成功，报“host not found in upstream”
2、多次重新构建网络综合治理插件，然后重启前端项目组件，偶尔能启动成功

**Comment by gobaiy** [comment]
网络卡，多提交了一次

**Comment by zzzhangqi** [comment]
> 网络卡，多提交了一次

看起来是生效时间过慢，需要给出更多信息进行排查。

所以现在问题是解决了嘛，如还有问题请在8小时内提问，否则我将关闭此问题。

**Comment by zzzhangqi** [comment]
感谢反馈，我们会根据您提供的步骤进行复现
