### ISSUE TITLE
组件库应用升级，提示“数据中心操作故障，请稍后重试”，升级接口返回错误码code400

### ISSUE THREAD

**Issue by wjn1992** [goodrain/rainbond#1169]
【问题描述】组件库应用升级，提示“数据中心操作故障，请稍后重试”，升级接口返回错误码code400
![image](https://user-images.githubusercontent.com/33511862/162892321-5965443a-d829-4fc8-b762-16439229e34a.png)
![升级接口](https://user-images.githubusercontent.com/33511862/162892097-07ff2164-a68b-4175-9b8b-2602edd3df52.png)

【操作步骤】
1、使用python代码构建v1.0.0应用发布到组件库，修改代码后重新构建发布v1.0.1版本到组件库；
2、从组件库安装v1.0.0版本应用；将应用从v1.0.0升级到v1.0.1时报错。
![217cde6af41b2fffecc93b506c477a2](https://user-images.githubusercontent.com/33511862/162892870-344ec00f-cc16-460d-b5cd-763bce7cc4be.png)

**Comment by yangkaa** [comment]
This issue was fixed in version 5.7.0 , I will close this issue
