### ISSUE TITLE
pig4cloud部署rainbond

### ISSUE THREAD

**Issue by haohao722** [goodrain/rainbond#1170]
可不可以更新一下pig4cloud在rainbond上面的部署，详细一点

**Comment by zzzhangqi** [comment]
部署文档会进行更新，但不是现在，部署过程中有问题随时提出，希望我能帮助到你。

我们正在与 Pig 进行合作，计划产出 Pig 部署在 Rainbond 上的一系列视频，尽请期待！

**Comment by zzzhangqi** [comment]
我将关闭此问题，有问题请随时打开
