### ISSUE TITLE
对接外部NFS存储异常

### ISSUE THREAD

**Issue by wison1001** [goodrain/rainbond#1171]
rainbond平台对接我们公司自己搭建的NAS存储，集群初始化时参照文档安装了NFS-Client-Provisioner，nfs-client.yaml内容如下：
nfs:
  server: 172.16.81.219
  path: /YX_k8s  
  mountOptions: 
  - "vers=3"
  - "nolock"
  - "proto=tcp"
  - "rsize=1048576"
  - "wsize=1048576"
  - "hard,timeo=600"
  - "retrans=2"
  - "no_root_squash"

创建了名称为nfs-client的sc，然后在rainbond平台的组件里面添加存储后，组件启动异常，报错如下：
Mounting arguments: -t nfs -o hard,timeo=600,no_root_squash,nolock,proto=tcp,retrans=2,rsize=1048576,vers=3,wsize=1048576 172.16.81.219:/YX_k8s/dev1-manual72-infrastructure-grbee36d-0-pvc-8ba1bdb4-2b13-454e-b524-dede717513dc /var/lib/kubelet/pods/ea3927b9-f38a-4615-b7b5
-54062dc0ce57/volumes/kubernetes.io~nfs/pvc-8ba1bdb4-2b13-454e-b524-dede717513dcOutput: mount.nfs: an incorrect mount option was specified

创建sc时，如果去掉了no_root_squash参数，nfs倒是可以正常挂载了，但是组件权限应该有问题，一直报错：
![image](https://user-images.githubusercontent.com/103560715/163120055-fa7f7be2-39ef-4a02-a7b6-18d697a8e371.png)

请问该怎么解决呢？

**Comment by zzzhangqi** [comment]
这看起来并不是 Rainbond 的问题。

不清楚你是什么 NAS 存储，很有可能跟你的挂载参数有关系。建议在创建了 sc 后，自己手动创建 pvc 验证 NFS 是否正常工作。

**Comment by zzzhangqi** [comment]
如果您在5天内不再继续提出问题，我将关闭此 issue。
如问题未解决，可以再次打开此 issue

**Comment by zzzhangqi** [comment]
如果您在5天内不再继续提出问题，我将关闭此 issue。
如问题未解决，可以再次打开此 issue

**Comment by zzzhangqi** [comment]
我将关闭此问题，有问题请随时打开
