### ISSUE TITLE
基于从Dockfile构建组件，不能从私有仓库拉去镜像

### ISSUE THREAD

**Issue by briannadev** [goodrain/rainbond#1172]
Dockfile文件中
FROM xxxx  如果是私有仓库的话，构建的时候，提示认证失败。

该如何设置处理？

谢谢。

**Comment by yangkaa** [comment]
你说的这个场景我们之前没遇到过，不过确实是个好场景。目前应该是不支持的。我们后期会进行支持。目前你可以尝试在 rbd-chaos 所在的节点提前拉取下来私有仓库的镜像，再构建，应该可以构建成功。

**Comment by briannadev** [comment]
感谢回复。


刚刚试了一下，按照下面说的，确实是可以构建成功。


也就是说对于私有仓库的话，需提前将镜像pull到本地。


但是私有仓库如果更新镜像了，无法通过自动去更新镜像，只能人为手动pull更新本地。


期待后期版本能支持，谢谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "goodrain/rainbond"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月18日(星期一) 上午10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [goodrain/rainbond] 基于从Dockfile构建组件，不能从私有仓库拉去镜像 (Issue #1172)





 
你说的这个场景我们之前没遇到过，不过确实是个好场景。目前应该是不支持的。我们后期会进行支持。目前你可以尝试在 rbd-chaos 所在的节点提前拉取下来私有仓库的镜像，再构建，应该可以构建成功。

**Comment by yangkaa** [comment]
5.8.0 版本已支持
