### ISSUE TITLE
Use Case helm values upgrade failed.

### ISSUE THREAD

**Issue by pytomtoto** [goodrain/rainbond#1173]
## I modify helm charts values.yaml like this

app_ui:
   images: my.images.repo:tag
   args:
     - some=args
    volumes:
      app-data:
        persistentVolumeClaim:
          claimName: rbd-app-ui
      app-lock:
        persistentVolumeClaim:
          claimName: rbd-app-ui
      app-log:
        persistentVolumeClaim:
          claimName: rbd-app-ui
      ssl:
        secret:
          defaultMode: 420
          secretName: rbd-api-client-cert
    volumeMounts:
      app-data: /data
      app-lock: /app/lock
      app-log: /app/logs/
      ssl: /app/region/ssl
...

## Action:
     helm upgrade ./values.yaml rainbond -n rbd-system

## Error:
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(RbdComponent.spec.volumeMounts[0]): unknown field "persistentVolumeClaim" in io.rainbond.v1alpha1.RbdComponent.spec.volumeMounts, ValidationError(RbdComponent.spec.volumeMounts[0]): missing required field "mountPath" in io.rainbond.v1alpha1.RbdComponent.spec.volumeMounts, ValidationError(RbdComponent.spec.volumeMounts[1]): unknown field "persistentVolumeClaim" in io.rainbond.v1alpha1.RbdComponent.spec.volumeMounts, ValidationError(RbdComponent.spec.volumeMounts[1]): missing required field "mountPath" in io.rainbond.v1alpha1.RbdComponent.spec.volumeMounts, ValidationError(RbdComponent.spec.volumeMounts[2]): unknown field "secret" in io.rainbond.v1alpha1.RbdComponent.spec.volumeMounts, ValidationError(RbdComponent.spec.volumeMounts[2]): missing required field "mountPath" in io.rainbond.v1alpha1.RbdComponent.spec.volumeMounts, ValidationError(RbdComponent.spec.volumeMounts[2]): unknown field "persistentVolumeClaim" in io.rainbond.v1alpha1.RbdComponent.spec.volumeMounts, ValidationError(RbdComponent.spec.volumeMounts[3]): unknown field "secret" in io.rainbond.v1alpha1.RbdComponent.spec.volumeMounts, ValidationError(RbdComponent.spec.volumeMounts[3]): missing required field "mountPath" in io.rainbond.v1alpha1.RbdComponent.spec.volumeMounts]

## WISH:
keep RbdComponent CRD. OR Remove the RbdComponent to use deployment.
...

**Comment by yangkaa** [comment]
Do you need to update the storage ?

According to the error information `missing required field "mountPath" in io.rainbond.v1alpha1.RbdComponent.spec.volumeMounts` , You should add the field `mountpath` in volumemounts.

**Comment by pytomtoto** [comment]
> Do you need to update the storage ?
> 
> According to the error information `missing required field "mountPath" in io.rainbond.v1alpha1.RbdComponent.spec.volumeMounts` , You should add the field `mountpath` in volumemounts.

[v5.6.0-values.yaml](https://github.com/goodrain/rainbond-chart/blob/v5.6.0-release/values.yaml)
I wrote it with reference to this.
```
  ##  volumes:
  ##    testpv:
  ##      persistentVolumeClaim:
  ##        claimName: rbd-cpt-grdate
  ##    testsc:
  ##      secret:
  ##        defaultMode: 420
  ##        secretName: rbd-api-server-cert
  ##  volumeMounts:
  ##    testpv: /data
  ##    testsc: /test
```
 removed the storage settings it works.
I just want update the Component Running Args and Images.
