### ISSUE TITLE
[构建]源码构建遇到问题

### ISSUE THREAD

**Issue by pytomtoto** [goodrain/rainbond#1176]
**Describe the bug**
```
Step 10/15 : RUN go mod vendor
34
---> Running in ce075321e0a9
35
Build app version from source code failure,The command '/bin/sh -c go mod vendor' returned a non-zero code: 1
```
然后查看两个chaos pod日志也只显示了 和上面一样的信息，只能看出执行 go mod vendor 返回了非0 失败了 但是原因不知道。

然后 连接chaos 终端
```
wget https://download.docker.com/linux/static/stable/x86_64/docker-20.10.7.tgz
tar xf docker-20.10.7.tgz
cp docker/* /usr/bin
再进行 git clone && docker build 指令
发现 有条 error指令 具体看下图
```
![image](https://user-images.githubusercontent.com/35906996/165677091-d3c84adb-e110-4194-be38-334edbff9425.png)

```
猜想 chaos只返回了stdout 没有stderr 所以问题定位困难
然后这里从pod里检查网络，没有发现问题。
最终用 docker build --network host -t xxx/xxx . 成功构建
但是这个network host 参数 怎么加到rainbond 里 或有其他方式能解决？
```
**To Reproduce**
故障重现：
直接源码构建 选https://github.com/goodrain/rainbond v5.6.0 tag
```
FROM golang:1.15 as build
WORKDIR /work
ARG APPNAME
ENV GOARCH amd64
ENV GOOS linux
ENV CGO_ENABLED 0
ENV GOPROXY https://goproxy.io
ENV GO111MODULE on
ADD . .
RUN go mod vendor
RUN go mod tidy
RUN go build -trimpath -ldflags "-w -s -X github.com/goodrain/rainbond/cmd.version=v1" -o app ./cmd/$APPNAME

FROM alpine:3.12
COPY --from=build /work/app /
ENTRYPOINT ["/app"]
```
用此Dockerfile APPNAME传api 就能复现问题

**预期
chaos的stdout、stderr都给前端返回。
chaos docker build 网络问题 能有个办法解决。

**Comment by zzzhangqi** [comment]
根据你提供的复现步骤，我这边尝试了可以构建成功。

操作步骤：

1. 安装最新版 Rainbond 单机版 V5.6.0。
2. 根据你提供的 Dockerfile 建立了分支，https://github.com/zzzhangqi/rainbond/tree/test-issues-1176
3. 根据分支源码构建，成功构建。

如步骤有问题，请重新指出复现步骤。

**Comment by zzzhangqi** [comment]
通过 Dockerfile 源码构建的组件确实由于报错信息提示不够导致问题难以定位，后续会改进，我会提个 features 改进此问题

**Comment by pytomtoto** [comment]
> 根据你提供的复现步骤，我这边尝试了也是同样的报错。
> 
> 在 chaos 内执行 docker build 发现无法下载包，是网络问题
> 
> <img alt="image" width="1248" src="https://user-images.githubusercontent.com/39754275/166118510-6ac9d811-fe17-47e5-b826-a2b1dbb17460.png">
> 
> 通过你的截图来看也是网络问题。
> 
> 尝试将 Dockerfile 的 `GOPROXY` 替换为国内代理 `https://goproxy.cn` 构建成功了。
> 
> https://github.com/zzzhangqi/rainbond/blob/test-issues-1176/Dockerfile#L7

可能和我用的awd eks集群有关，https://github.com/awslabs/amazon-eks-ami/issues/183
