### ISSUE TITLE
自定义组件服务--network=host主机网络模式

### ISSUE THREAD

**Issue by superjackwong** [goodrain/rainbond#1179]
Hi，我想自定义git拉取服务启动可以追加--network=host主机网络模式参数，因为目前我碰到nacos注册IP问题，默认应用服务容器里通过ifconfig查看只有10.xx及127.0.0.1两个网段，我需要宿主IP如192.168.1.56对nacos进行注册，而不是目前的10.xx，请帮忙解决处理下，thx

**Comment by zzzhangqi** [comment]
将nacos pod改为 host 网络无法解决你的问题，你想实现的就是 pod 注册到nacos的服务 IP 如何与本地注册到nacos中的 服务 IP 进行通信，你需要打通本地网络与 k8s 网络：
1. 通过vpn的方式，在集群中搭建 vpn，参考 [vpn-ipsec](https://github.com/hwdsl2/setup-ipsec-vpn)
2. [nocalhost](https://nocalhost.dev/)
3. 云端IDE [OpenVScode](https://www.rainbond.com/blog/OpenVscode)

**Comment by superjackwong** [comment]
> 将nacos pod改为 host 网络无法解决你的问题，你想实现的就是 pod 注册到nacos的服务 IP 如何与本地注册到nacos中的 服务 IP 进行通信，你需要打通本地网络与 k8s 网络：
> 
> 1. 通过vpn的方式，在集群中搭建 vpn，参考 [vpn-ipsec](https://github.com/hwdsl2/setup-ipsec-vpn)
> 2. [诺卡尔霍斯特](https://nocalhost.dev/)
> 3. 云端[IDE OpenVScode](https://www.rainbond.com/blog/OpenVscode)

我并不是想打通本地网络与k8s网络，因为这取决于nacos，nacos服务注册和发现需要同一网段的，服务A是rainbond发布，走的是pod的k8s网络10.x.x.x，nacos识别是10.130.6.13，服务B是个人电脑tomcat发布，nacos识别的网络是192.168.1.10，服务B和服务A不能互通，因为两者不在相同的网段，故我想把rainbond的发布pod可以使用主机网络模式，比如我rainbond的EIP是192.168.1.12，那么我pod注册到nacos也是192.168.1.12，而不是k8s内部10.x.x.x，这样就可以解决我目前的问题了

**Comment by zzzhangqi** [comment]
参考文档：https://www.rainbond.com/docs/use-manual/user-manual/component-dev/service-env/#%E5%BA%94%E7%94%A8%E8%BF%90%E8%A1%8C%E6%97%B6%E5%8A%9F%E8%83%BD%E6%8E%A7%E5%88%B6%E5%8F%98%E9%87%8F

**Comment by yangkaa** [comment]
No reply for a long time. I will close this question. If you have any questions, please reopen it
