### ISSUE TITLE
Feature: Show more log about build errors for dockerfile

### ISSUE THREAD

**Issue by zzzhangqi** [goodrain/rainbond#1180]
### User feedback
Components build on dockerfile,In failure,Will only show the final build error report and exit.

For example:
```
The command '/bin/sh -c go mod vendor' returned a non-zero code: 1
```

![](https://user-images.githubusercontent.com/39754275/166118510-6ac9d811-fe17-47e5-b826-a2b1dbb17460.png)

In fact, it's just a network problem.

This will make it difficult for users to locate the problem.

### Improve

Components build based on dockerfile show all build process logs.

**Comment by zzzhangqi** [comment]
#1176

**Comment by yangkaa** [comment]
Merged: https://github.com/goodrain/rainbond/pull/1211
