### ISSUE TITLE
初始化类型插件卸载后，更新组件不生效问题

### ISSUE THREAD

**Issue by pescox** [goodrain/rainbond#1182]
组件安装初始化类型插件后，更新组件，组件中的插件能正常工作，但是卸载插件后，更新组件，组件里的插件仍然存在且工作。此时必须重启组件插件才消失。

Rainbond版本：5.6.0一下版本都有该问题。

**Comment by yangkaa** [comment]
This issue was fixed in version 5.7.0 , I will close this issue
