### ISSUE TITLE
The automatic update feature provided by webhook is not shown in the image deployed application interface

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#119]
If you want to report a bug, please provide the following information:

- [v3.7.1 ] Rainbond versions
- [ ] Kubernetes versions
- [ ] Docker version
- [ ] Operating system and kernel
- [ ] Provider(Aliyun,VirtualBox,...)
- [ ] Install details(Online/Offline,Single node/HA)
- [ ] Steps to reproduce

![image](https://user-images.githubusercontent.com/33855684/45613300-72e1dc00-ba98-11e8-86d9-d0a37df75557.png)
Automatic deployment options are displayed only if the source builds. This is unscientific because our automated deployment supports API calls that can be aware of mirror updates and automatically deployed. You should consider making automatically deployed modules available to all applications.

**Comment by barnettZQG** [comment]
已于3.7.2中改进

**Comment by 27-1** [comment]
已改进，添加返回数据字段support_type来判断该应用是否通过api进行自动部署
