### ISSUE TITLE
主机高可用安装 ‘升级内核版本’ 文档不存在

### ISSUE THREAD

**Issue by minecheney** [goodrain/rainbond#1198]
![image](https://user-images.githubusercontent.com/48551158/173234967-4f95ca52-bf85-4b7a-ad12-e226f790697b.png)

**Comment by yangkaa** [comment]
Thank you for the feedback. We will deal with it as soon as possible.

**Comment by zzzhangqi** [comment]
Thank you for the feedback.problem fixed
