### ISSUE TITLE
Batch delete application error

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#120]
If you want to report a bug, please provide the following information:

- [v3.7.1 ] Rainbond versions
- [ ] Kubernetes versions
- [ ] Docker version
- [ ] Operating system and kernel
- [ ] Provider(Aliyun,VirtualBox,...)
- [ ] Install details(Online/Offline,Single node/HA)
- [ ] Steps to reproduce

When you delete an application in bulk, removing an application that has a plug-in installed will fail, but you won't get any information in the application group control interface

**Comment by 27-1** [comment]
正在改进，感谢您的支持

**Comment by barnettZQG** [comment]
已于3.7.2中改进！
