### ISSUE TITLE
第三方组件健康检测不通过，IP+端口方式添加

### ISSUE THREAD

**Issue by gobaiy** [goodrain/rainbond#1201]
【BUG描述】
添加第三方组件，重启组件状态一直是未就绪状态。试过在不同的应用中添加第三方组件都遇到此问题，第三方组件添加是：IP+端口方式
1、通过添加依赖，应用内部可以通过第三方组件通信；
2、打开对外服务，无法通过对外IP进行访问；
3、第三方组件状态显示为  不健康；
4、在宿主机上通过ServiceIP访问正常
![image](https://user-images.githubusercontent.com/49633387/174419921-64512250-db51-43fd-b52e-159c6d88ee53.png)
![image](https://user-images.githubusercontent.com/49633387/174420139-b2297711-9c4f-4d90-9a61-25cf6207a84e.png)
![image](https://user-images.githubusercontent.com/49633387/174420213-3ebbd00a-0c64-4ddf-bc67-b804a7440a44.png)

【部署环境】
- Rainbond版本(执行`grctl version`获取): v5.7.0-release
- 操作系统类型和版本: Centos 7
- 离线部署/网络开放：网络开放

**Comment by yangkaa** [comment]
需要在更多设置中打开健康检测，更新第三方组件

**Comment by gobaiy** [comment]
> 需要在更多设置中打开健康检测，更新第三方组件
谢谢，解决了，只是看了没点“确定”，只点了“更新“”
![image](https://user-images.githubusercontent.com/49633387/174421348-bfd20007-0ec4-46d5-b872-7c42476955d3.png)
