### ISSUE TITLE
应用备份失败，chaos提示找不到manifest

### ISSUE THREAD

**Issue by runningbeanxl** [goodrain/rainbond#1203]
![图片](https://user-images.githubusercontent.com/42364672/175259418-cc0b2cdd-8deb-4f85-ad0b-1ae89b3a95d1.png)

在chaos节点通过docker manifest inspect 可以获取manifest，通过curl harbor地址的方式也能拿到manifest
![图片](https://user-images.githubusercontent.com/42364672/175260024-10dce428-cf37-49a9-9ec3-43d5262f8457.png)

![图片](https://user-images.githubusercontent.com/42364672/175260239-ede85438-d086-489a-9914-0a256f9cfc1a.png)

**Comment by yangkaa** [comment]
目前这部分报错日志不明确，看不出来具体报错，我基于5.6版本把报错信息打印出来，打了一个镜像

`registry.cn-hangzhou.aliyuncs.com/yangkaa/rbd-chaos:backupLog-dev`

你可以将 rbd-chaos 的镜像替换为该镜像，然后再给出具体报错信息

**Comment by runningbeanxl** [comment]
![图片](https://user-images.githubusercontent.com/42364672/175268228-e0ecf22b-4cd7-4e3d-b191-c21aca608c37.png)
missing signature key 是这个原因吗

**Comment by yangkaa** [comment]
是的

**Comment by runningbeanxl** [comment]
请问这个怎么处理呢，是哪个服务的问题

**Comment by yangkaa** [comment]
`rbd-chaos` 挂载宿主机的 `docker.socket`，也许这个能解决你的问题，https://jfrog.com/knowledge-base/artifactory-how-to-fix-a-missing-signature-key-docker-client-error/，如果不行，你可以搜索 `missing signature key` ，尝试寻找解决方案

**Comment by runningbeanxl** [comment]
chaos默认挂载了宿主的docker.socket，搜索了一些文档没有解决问题，chaos构建镜像都是正常的，只是应用备份的时候有问题，所以怀疑是chaos备份这块是不是有什么特殊的逻辑？

**Comment by yangkaa** [comment]
无特殊处理，仅仅是获取了对应的 Manifest ，可参考 https://github.com/goodrain/rainbond/blob/4cb8099c38a964c42dd352edadf0616e4447058b/builder/exector/groupapp_backup.go#L334。
你尝试重新构建下备份失败的应用下的组件后再备份呢？

**Comment by runningbeanxl** [comment]
重新构建了仍然备份失败。
我看是用的insecure模式，是否和这块有关呢
![图片](https://user-images.githubusercontent.com/42364672/175505293-09ced259-6083-4926-88a4-4052a32ada13.png)

**Comment by runningbeanxl** [comment]
可否增加更多日志，chaos具体是怎么请求manifest文件的

**Comment by yangkaa** [comment]
registry.cn-hangzhou.aliyuncs.com/yangkaa/rbd-chaos:backupLog1-dev 
增加了请求的url，以及获取的镜像信息的日志，你看看是否有有用的信息

**Comment by runningbeanxl** [comment]
根据chaos打印的日志用curl方式获取了manifest信息，是不是返回的manifest信息不符合chaos的要求？
![图片](https://user-images.githubusercontent.com/42364672/175843511-877e9a26-80cf-43dd-9f05-079da273b4ae.png)

**Comment by yangkaa** [comment]
这应该和 docker 相关，chaos 引用的 docker 的类库去序列化你上面手动获取的结果，应该是在这一步报错了。你也许可以参考下这个 https://stackoverflow.com/a/50979841，了解在 Harbor 中如何分配 ACL  ，再重新构建备份试试

**Comment by runningbeanxl** [comment]
harbor用的管理员账户而且仅有这一个账户，手动创建了manifest推送到harbor仍然不行。docker版本是19.03.5，harbor版本是2.4.2，chaos还能有更多日志吗，能不能开启debug模式

**Comment by yangkaa** [comment]
chaos 可以参考这个文档设置 debug 模式，https://www.rainbond.com/docs/ops-guide/component/rbd-chaos。你可以按以下步骤再排查下：

1. 创建应用A，通过 源码 部署一个组件
2. 创建应用B，通过 镜像 部署一个组件
3. 然后备份应用A、备份应用B，看是否能成功备份

如果这两种方式都能备份成功，那么需要看下你这个应用下的组件镜像有什么特殊的？是通过哪种方式构建的。然后单独创建新应用，只部署该组件，再去备份试试。

**Comment by runningbeanxl** [comment]
感谢一直跟进这个问题。开启了debug模式日志还是有限，尝试了你反馈的3种思路仍然不能备份成功
看代码是不是manifest方法这里有错误？https://github.com/goodrain/rainbond/blob/4cb8099c38a964c42dd352edadf0616e4447058b/builder/sources/registry/manifest.go#L36
这个方法请求的详细信息报错信息能不能帮忙打印一下，看看具体是哪一步出问题了
![图片](https://user-images.githubusercontent.com/42364672/176571928-815aa4dc-7e69-4e39-91f6-e94dbcc126f8.png)

**Comment by yangkaa** [comment]
Fix: https://github.com/goodrain/rainbond/pull/1210

manifest 的 `MediaTypeManifest` 导致的兼容性问题，已处理。

你可以使用镜像 `registry.cn-hangzhou.aliyuncs.com/yangkaa/rbd-chaos:backupLog2-dev` 进行测试，会在下个版本修复。

该镜像`registry.cn-hangzhou.aliyuncs.com/yangkaa/rbd-chaos:backupLog2-dev`仅仅基于 5.6.0-release 的 tag 打印了更详细的日志。以及包含了上述 PR 的代码。

**Comment by runningbeanxl** [comment]
chaos用这个镜像registry.cn-hangzhou.aliyuncs.com/yangkaa/rbd-chaos:backupLog2-dev现在看到备份是成功的，但是迁移失败，镜像目录多了一层rainbond字段
![图片](https://user-images.githubusercontent.com/42364672/176650220-0fb33553-3325-44f0-8839-8f115010cf83.png)

**Comment by yangkaa** [comment]
目前看来，这应该是一个明确的bug，我会在周末排查下

**Comment by yangkaa** [comment]
引起该Bug的原因：
1. manifest 的 MediaTypeManifest 导致的兼容性问题，已处理。
2. 迁移失败是因为在处理镜像时，重复处理镜像域名和命名空间，使镜像从 `registry.cn-hangzhou.aliyuncs.com/yangkaa/test:latest` 变成了 `registry.cn-hangzhou.aliyuncs.com/yangkaa/yangkaa/rbd-chaos:backupLog2-dev`，因此恢复时无法正确找到镜像。
3. 恢复后有状态组件没有数据。原因是从 5.5.0 版本开始，支持修改组件英文名，即 statefulset 类型的组件，Pod 名称会被修改。导致恢复时，无法找到对应的数据存储目录。

**Comment by yangkaa** [comment]
5.8.0 版本正式修复
