### ISSUE TITLE
Flunted插件收集不到NODEJS前端nginx日志问题

### ISSUE THREAD

**Issue by gobaiy** [goodrain/rainbond#1207]
是不是因为NODEJ前端构建后，运行容器中nginx日志被重定向，导致日志文件中无内容，Flunted插件读不到日志信息。
以下是测试的过程：
1、日志路径已正常挂载
2、测试组件连接同一个elasticsearch
3、使用相同Flunted插件
![image](https://user-images.githubusercontent.com/49633387/175496493-2e9fb89e-9018-482c-8a65-3baca7911514.png)

问题排查对比过程：
1、云帮构建后的前端nginx日志被重定向，flunted插件收到不到日志
2、直接拉取的nginx镜像日未被重定向，flunted插件可以收件到日志
![2556D570-4212-4da6-BB0D-7F34AB458796](https://user-images.githubusercontent.com/49633387/175497075-7a5a3997-3839-4b13-a5b3-87af0b6142fb.png)
![D975AC14-C791-4bcf-B318-EE471BFE6C59](https://user-images.githubusercontent.com/49633387/175497604-35deacdf-b14f-4fd8-9d08-397855694eef.png)
![17F88A59-F8DE-40ac-AA05-7718F4E913C8](https://user-images.githubusercontent.com/49633387/175497603-848fe7c0-9fa3-4012-bab8-6af03426fd54.png)

【部署环境】
- Rainbond版本(执行`grctl version`获取): rainbond 5.7
- 操作系统类型和版本:centos7
- 离线部署/网络开放：网络开放

**Comment by yangkaa** [comment]
感谢反馈，目前根据你所掌握的情况，看起来是这样的。你的需求是通过源码构建的容器日志也能被 fluentd 收集到吗？

**Comment by gobaiy** [comment]
> 感谢反馈，目前根据你所掌握的情况，看起来是这样的。你的需求是通过源码构建的容器日志也能被 fluentd 收集到吗？

是的，想试试源码构建的容器，日志通过fluentd怎样收集

**Comment by zzzhangqi** [comment]
源码构建的前端项目默认都会将 Nginx 重定向输出到控制台，如果你想通过 Fluentd 收集日志，那么需要修改 Nginx 配置文件让其生成新的 `Nginx-Access.log`

修改 `web.conf`

```shell
server {
    listen 5000;
    # 新增
    access_log  /app/nginx/logs/nginx-access.log  main;
    location / {
        root   /app/www;
        index  index.html index.htm;
    }
}
```

然后挂载存储路径 `/app/nginx/logs/`，修改 Fluentd 配置文件指定收集日志文件名，这样就可以通过 Fluentd 收集到日志啦

**Comment by gobaiy** [comment]
感谢，通过以上方式可以收到日志了。

**Comment by yangkaa** [comment]
我将关闭此 Issue，如还有问题，请重新打开
