### ISSUE TITLE
通过Helm安装命令生成工具生成高可用Rainbond命令安装失败

### ISSUE THREAD

**Issue by hanxinhisen** [goodrain/rainbond#1208]
**Describe the bug**
通过Helm安装命令生成工具生成高可用Rainbond命令安装失败。因为设置外部数据库连接参数时，如果自定义数据库名，如xxx_region和xxx_console，安装过程中实际连得数据库还是region和console，而不是自定义的xxx_region和xxx_console
**To Reproduce**
1.通过helm安装命令生成工具生成高可用版本安装命令
2.填写自定义数据库名
3.进行安装

**Screenshots**
命令行中生成的参数是regionDatabase.dbname=xxxx_region和Cluster.uiDatabase.dbname=xxx_console
而charts中读取的参数
![image](https://user-images.githubusercontent.com/7082486/176067040-38c470e6-df18-4251-a600-02a22d6b0cbd.png)

另外即使我将安装命令改成和charts一致，如regionDatabase.name=xxxx_region和Cluster.uiDatabase.name=xxx_console ，region连得还是默认region库，估计是哪块代码写死了。

**The relevant information:**
 - Rainbond v5.7.0
 - Kubernetes version v1.23.7

**Comment by yangkaa** [comment]
感谢反馈，helm安装命令生成工具已调整，chart 包后续会进行验证调整

**Comment by yangkaa** [comment]
fix: https://github.com/goodrain/rainbond-operator/pull/136

**Comment by yangkaa** [comment]
v5.8.1 版本中已修复，如还有问题，请重新打开
