### ISSUE TITLE
重启应用或重新部署  大概率出现无法访问

### ISSUE THREAD

**Issue by w-a-n-g-s-h-u-n** [goodrain/rainbond#121]
If you want to report a bug, please provide the following information:
重启应用或重新部署  大概率出现无法访问
- [ 3.7.1] Rainbond versions
- [ ] Kubernetes versions
- [1.12.6, build fbecf51 ] Docker version
- [ centos 7.5，3.10.0-862.3.2.el7.x86_64] Operating system and kernel
- [openstack ] Provider(Aliyun,VirtualBox,...)
- [Online,HA ] Install details(Online/Offline,Single node/HA)
- [ ] Steps to reproduce

**Comment by ysicing** [comment]
重启
```
systemctl restart node
systemctl restart rbd-lb
systemctl restart rbd-entrance
```
HA模式，扩容前已经部署有应用运行了吗

**Comment by dazuimao1990** [comment]
查看下rbd-entrance服务的参数
```bash
[root@manage01 ~]# ps -ef | grep rbd-entrance
root      5641     1  0 09:49 ?        00:00:00 docker run --name rbd-entrance --network host --memory 1024M -e DEFAULT_HTTP_PORT=80 -e DEFAULT_HTTPS_PORT=443 -v /opt/rainbond/etc/kubernetes/kubecfg:/opt/rainbond/etc/kubernetes/kubecfg -i goodrain.me/rbd-entrance:3.7.1 --plugin-name=openresty --plugin-opts=urls=http://10.10.10.245:10002 --kube-conf=/opt/rainbond/etc/kubernetes/kubecfg/admin.kubeconfig --log-level=debug --etcd-endpoints=http://10.10.10.245:2379 --run-mode=sync
root     23474  5806  0 10:57 pts/0    00:00:00 grep --color=auto rbd-entrance
```

确认`--plugin-opts=urls`参数设置连接了所有的`rbd-lb`组件的地址；

如果此处配置正确，那么请关注所有`rbd-lb`组件所在的节点的`/opt/rainbond/etc/rbd-lb/dynamics`目录内容是否完全一致。如不一致，则以manage01节点数据为准。拷贝覆盖后重启`rbd-lb`组件。 @w-a-n-g-s-h-u-n

**Comment by w-a-n-g-s-h-u-n** [comment]
@dazuimao1990 执行结果：
root     17617   782  0 11:05 pts/0    00:00:00 grep --color=auto rbd-entrance

**Comment by w-a-n-g-s-h-u-n** [comment]
@ysicing 
扩容前确实已有应用运行
但扩容后我把之前的应用删除 重新构建了

**Comment by ysicing** [comment]
@w-a-n-g-s-h-u-n  检查了rbd-entrance的配置是否一直吗

```
/opt/rainbond/conf/mater.yaml
```

**Comment by w-a-n-g-s-h-u-n** [comment]
@ysicing 
同步了/opt/rainbond/conf/master.yaml和/opt/rainbond/etc/rbd-lb/dynamics之后
执行
systemctl restart node
systemctl restart rbd-lb
systemctl restart rbd-entrance
问题依旧 现在重启出现——重启失败(重启失败，请重试)
重新部署出现——部署失败(滚动升级失败，应用发生重启，请查询应用日志)

日志重复出现
b34379114ad3:stat /etc/kubernetes/kube-proxy.kubeconfig: no such file or directory

b34379114ad3:I0919 14:06:03.774430 1 server.go:145] write /proc/self/oom_score_adj: permission denied

b34379114ad3:I0919 14:06:03.774102 1 oom_linux.go:82] failed to set "/proc/self/oom_score_adj" to "-999": write /proc/self/oom_score_adj: permission denied

**Comment by ysicing** [comment]
@w-a-n-g-s-h-u-n  可以具体描述一下你的操作流程吗

**Comment by barnettZQG** [comment]
@w-a-n-g-s-h-u-n 
关于操作日志中出现 “应用发生重启” 说明你正在操作的应用可能制作有问题。进程启动后由于某种原因退出了。需要查询应用日志。
关于 “stat /etc/kubernetes/kube-proxy.kubeconfig: no such file or directory” 这是个明显的问题。你需要在宿主机上查询一下 /grdata/kubernetes 目录下是否具有kube-proxy.kubeconfig 文件。

**Comment by w-a-n-g-s-h-u-n** [comment]
@barnettZQG kube-proxy.kubeconfig文件存在
我的应用有时是可以成功运行的 但是出现启动不了的情况后  就再也启动不了了  只能删除后重新构建

**Comment by w-a-n-g-s-h-u-n** [comment]
@ysicing 目前已经在重装云帮了  可能和上次断电有关系

**Comment by ysicing** [comment]
@w-a-n-g-s-h-u-n  正常情况下，断电应该是没有影响的，后续有什么操作么
