### ISSUE TITLE
构建pig-ui失败 提示 ELIFECYCEL

### ISSUE THREAD

**Issue by lliyuu520** [goodrain/rainbond#1214]
Rainbond版本: v5.7.1-release-f94223257-2022-07-04-12-allinone
Pig-ui版本: 3.5.1

web.conf:
![image](https://user-images.githubusercontent.com/12896160/177500085-ae69ef9b-1dfb-4f22-ab8d-e9b6e6a8351c.png)

nodestatic.json:
![image](https://user-images.githubusercontent.com/12896160/177500343-9ad7c9a0-885c-46ad-8f60-0dabd7625fa5.png)

报错提示:
<img width="435" alt="912b4705061f9f70af62ad0ef194521" src="https://user-images.githubusercontent.com/12896160/177499501-49f1a739-f68e-45d2-986c-49f87a673a3b.png">

构建源:
![image](https://user-images.githubusercontent.com/12896160/177499826-d756fe4a-62a0-4abf-9ace-bbc63c7caf79.png)
构建参数:
![image](https://user-images.githubusercontent.com/12896160/177499752-2d8f9a23-ada2-4b78-9e02-b126b938d565.png)

**Comment by zzzhangqi** [comment]
Node 版本不匹配，Pig-ui 3.5.1 需要 Node 14+

**Comment by lliyuu520** [comment]
感谢,解决办法是用yarn替换npm来构建
