### ISSUE TITLE
UI styles err

### ISSUE THREAD

**Issue by zzzhangqi** [goodrain/rainbond#1220]
component -> port -> Access policy Click `IP+Port`

<img width="1747" alt="image" src="https://user-images.githubusercontent.com/39754275/178231753-6804cbdf-2a90-426c-8f11-7a81fbfceaae.png">

**Comment by yangkaa** [comment]
Fix: https://github.com/goodrain/rainbond-ui/pull/982

**Comment by yangkaa** [comment]
5.8.0 版本中已修复
