### ISSUE TITLE
带有HTTP网关的应用，发布之后导出模板失败

### ISSUE THREAD

**Issue by joychen-1991** [goodrain/rainbond#1221]
time="2022-07-12T14:20:16+08:00" level=info msg="Build task cacd4c6c3669442f8f1c6868cc3dd6e1 in progress"
time="2022-07-12T14:20:16+08:00" level=error msg="task type: export_app; body: {\"event_id\":\"be1364127d7543acaa821603947374de\",\"group_key\":\"0128b64121164d398debf9ac165792d7\",\"version\":\"4.1\",\"format\":\"rainbond-app\",\"source_dir\":\"/grdata/app/rainbond-app/kgmsv1-4.1\"}; run task: json: cannot unmarshal array into Go struct field IngressHTTPRoute.ingress_http_routes.proxy_header of type map[string]string"
time="2022-07-12T14:20:16+08:00" level=info msg="Build task cacd4c6c3669442f8f1c6868cc3dd6e1 is completed"
time="2022-07-12T14:29:28+08:00" level=info msg="Build task 5404dfee33b04612a4a926d9466e6213 in progress"
time="2022-07-12T14:29:28+08:00" level=error msg="task type: export_app; body: {\"event_id\":\"106aed943f1a429d8398264408ad73ce\",\"group_key\":\"0128b64121164d398debf9ac165792d7\",\"version\":\"4.1\",\"format\":\"rainbond-app\",\"source_dir\":\"/grdata/app/rainbond-app/kgmsv1-4.1\"}; run task: json: cannot unmarshal array into Go struct field IngressHTTPRoute.ingress_http_routes.proxy_header of type map[string]string"
time="2022-07-12T14:29:28+08:00" level=info msg="Build task 5404dfee33b04612a4a926d9466e6213 is completed"

**Comment by ZhangSetSail** [comment]
see https://github.com/goodrain/rainbond-console/pull/1139

**Comment by yangkaa** [comment]
As with this issue https://github.com/goodrain/rainbond/issues/1309, it has been fixed in v5.8.1-release.
