### ISSUE TITLE
提升用户在问题排查时的使用体验

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#1222]
当平台上的服务组件进入红色的运行异常状态时，用户往往不知道如何排查，关注到红色的运行异常时就会下意识的去点击事件右侧的日志，然而实际情况下，这里的日志输出往往是没有意义的。我们应该引导用户去服务组件的 **日志** 页面，看问题日志。

没有意义的日志如下：
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/33855684/178438623-c8d6590c-73e2-4da3-b0d7-b925a25bfa35.png">

可以点击那个运行异常事件右侧的 **日志** 按钮的时候，跳转到服务组件的日志页面。
![image](https://user-images.githubusercontent.com/33855684/178438489-e377d84a-b98f-4e41-b334-095c4e7559b7.png)

**Comment by dazuimao1990** [comment]
> 需要支持哪几种情况呢，如组件异常退出这一种？像 OOMKilled 这类的呢

如果是 OOMkilled 事件，那么与其展现出用户看不懂的日志，还不如直接了当的说明到底是业务容器 oom 还是插件 oom。转化为用户可以理解的语言，比给出一般人看不懂的日志要好。

**Comment by yangkaa** [comment]
是否还有其他情况需要处理呢

**Comment by dazuimao1990** [comment]
> 是否还有其他情况需要处理呢

也经常有用户拿着组件启动超时过程中的那个日志来提问，然而那个日志也是没有意义的。超时就超时，没必要给出摁钮看日志。

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/33855684/178456206-e2869d3d-a5a1-4e36-a2e2-a1515ac19817.png">
