### ISSUE TITLE
Gateway policy is not available after backup recovery

### ISSUE THREAD

**Issue by yangkaa** [goodrain/rainbond#1224]
When a component is restored from a backup, a corresponding gateway policy is generated, but cannot be accessed. Only when you delete the access policy and add it again can you access it normally.

**Comment by yangkaa** [comment]
Feedback from wechat user 李XX

**Comment by yangkaa** [comment]
Fixed: https://github.com/goodrain/rainbond-console/pull/1179

**Comment by zhangdonglin-90528** [comment]
这个问题解决了么?
