### ISSUE TITLE
Log information optimization (日志信息优化)

### ISSUE THREAD

**Issue by yangkaa** [goodrain/rainbond#1227]
当某个组件下的容器异常退出时，如果时间很短暂，那么容器会被重启。此时由于容器被重启，会导致无法收集到上一次容器的日志信息。 因此日志推送不全。需要有一种方式能获取到上一次容器的日志信息并保存。

**Comment by zzzhangqi** [comment]
Stale issue, I will close it, please open again if there is a problem.
