### ISSUE TITLE
安装程序修改了/etc/resolv.conf 文件，导致dns解析异常，不能联网的问题

### ISSUE THREAD

**Issue by allenonline** [goodrain/rainbond#123]
If you want to report a bug, please provide the following information:

- [3.7.1 ] Rainbond versions
- [centos 7.3 ] Operating system and kernel
- [kvm in smartos ] Provider(Aliyun,VirtualBox,...)
- [ Online/Single node] Install details(Online/Offline,Single node/HA)
- [ ] Steps to reproduce

执行./setup.sh，前面正常，在执行到
--- Start install common(step: 1/7) ... ---
时报错，错误提示如下：
---------
          ID: common_packages
    Function: pkg.installed
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit run-8120.scope.
                    Loaded plugins: fastestmirror
                    http://mirrors.ustc.edu.cn/salt/yum/redhat/7/x86_64/archive/2018.3.2/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.ustc.edu.cn; Unknown error"
                    Trying other mirror.
                    https://repo.saltstack.com/yum/redhat/7/x86_64/archive/2018.3.2/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: repo.saltstack.com; Unknown error"
                    Trying other mirror.
————
服务器不能访问相关地址，在错误的前面输出的执行语句是
Name: /etc/resolv.conf - Function: file.replace - Result: Changed Started: - 17:29:18.500187 Duration: 11.409 ms
  Name: /etc/resolv.conf - Function: file.append - Result: Changed Started: - 17:29:18.511918 Duration: 2.489 ms
  Name: /etc/resolv.conf - Function: file.append - Result: Clean Started: - 17:29:18.514656 Duration: 1.538 ms
  Name: /etc/resolv.conf - Function: file.append - Result: Changed Started: - 17:29:18.516437 Duration: 2.197 ms
  Name: /etc/resolv.conf - Function: file.replace - Result: Clean Started: - 17:29:18.518890 Duration: 10.508 ms
  Name: /etc/resolv.conf - Function: file.replace - Result: Clean Started: - 17:29:18.529717 Duration: 10.938 ms
  Name: yum remove -y container-selinux - Function: cmd.run - Result: Clean Started: - 17:29:18.540989 Duration: 37.86 ms

可以看到，修改了/etc/resolv.conf 文件，导致服务器不能联网。不知为何要修改/etc/resolv.conf 文件？要怎么修复这个问题呢？

**Comment by ysicing** [comment]
@allenonline  安装时会默认添加当前机器的ip，重写/etc/resolv.conf文件，重写格式如下的
```bash
cat /etc/resolv.conf
nameserver <当前机器ip>
nameserver <原先机器dns>
```

**Comment by allenonline** [comment]
但是现在执行setup.sh后，/etc/resolv.conf文件会把原来的dns全部注释掉，然后添加当前机器ip，如下
#nameserver 10.16.1.20
#nameserver 10.16.1.21
#nameserver 114.114.114.114
#nameserver 8.8.8.8
nameserver 10.16.3.11
nameserver 10.16.1.20
这样导致无法解析外网域名，我尝试手动配置dns，然后注释掉setup.sh中的相关语句
 Write_Sls_File dns.current "$dns_value"
却没有生效，原来的dns还是被注释掉了，不知为何？

**Comment by allenonline** [comment]
现在碰到的问题是rainbond运行中，会自动把/etc/resolv.conf文件进行复原
[root@manage01 ~]#  cat /etc/resolv.conf
nameserver 10.16.3.11
nameserver 10.16.3.11
nameserver 10.16.1.20
手动修改 /etc/resolv.conf都没用，有个后台进程会自动改回到上面这个。。。不知道要修改哪里解决这个问题

**Comment by ysicing** [comment]
将会在安装中调整，检查默认dns解析情况
