### ISSUE TITLE
组件资源没有限制时，如何展示当前已用的内存

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#1244]
目前 Rainbond 已经支持不限制内存、CPU 的资源分配方式。在这种情况下，会导致伸缩页面的实例资源使用率始终为 0%  （ 已用内存值 / 不限制）。这容易引起用户的误解，因为这看起来像这部分展示功能没有工作。
特此提出建议，当用户将组件的内存资源设置为 0 时（不限制），可以让此处显示 Pod 中所有容器所使用内存的实际值之和。

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/33855684/179895693-b46a2ccd-2a1d-419b-a925-b9fb19479192.png">

切换算法后，获取所有容器的内存实际使用值：

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/33855684/179895778-e2f93143-2719-483a-9a0c-f8923065e386.png">

**Comment by yangkaa** [comment]
Merged: https://github.com/goodrain/rainbond-ui/pull/987/files

**Comment by yangkaa** [comment]
5.8.0 版本已支持
