### ISSUE TITLE
希望能支持containerd

### ISSUE THREAD

**Issue by liwenson** [goodrain/rainbond#1247]
希望能支持containerd 作为容器运行时

**Comment by yangkaa** [comment]
能否说下你们的使用场景呢？是因为现在使用的 Kubernetes 版本已经比较高了吗？containerd 作为容器运行时也确实在后期版本规划之中。

**Comment by liwenson** [comment]
因为我现在的Kubernetes已经是比较高的版本了,已经去除了docker。

**Comment by yangkaa** [comment]
在 v5.9.0 版本中已支持 containerd。https://github.com/goodrain/rainbond/pull/1352
