### ISSUE TITLE
非管理员账号登录后http://xxxx:7070/#/team//region//exception/403

### ISSUE THREAD

**Issue by superjackwong** [goodrain/rainbond#1254]
**Describe the bug**
RT,我通过创建用户时角色权限只给观察者或开发者（非管理员），接着用创建后的用户登录，登录成功后则页面一片空白无法操作，查看地址栏地址登录成功后进入了http://xxxx:7070/#/team//region//exception/403
![image](https://user-images.githubusercontent.com/57210156/181670712-b56877a2-33b5-476f-a574-4cf0704f6258.png)

**To Reproduce**
1. 新增zhangsan用户，角色权限选择观察者
2. 新增成功后用zhangsan用户进行登录
3. 登录成功了，但页面是空白的，地址是http://xxxx:7070/#/team//region//exception/403
4. 无法切换用户也无法回到上一步，只能清空浏览器缓存注销回到登录页

**Screenshots**
![image](https://user-images.githubusercontent.com/57210156/181670247-67d23c89-5cdf-4a82-8ad7-e82d1a0757e5.png)

**The relevant information:**
 - Rainbond Version [v5.7.1-release-f94223257-2022-07-04-12-allinone]
 - Browser [Google Chrome 103.0.5060.53 64bit] (if it is the front-end bugs, please provide)
 - Kubernetes version [e.g 1.16.3]

**Comment by yangkaa** [comment]
问题原因: 平台报警接口默认所需的权限过高导致的。
可以使用 `registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.7.1-patch1254` 替换控制台的镜像临时解决。下个版本发布将正式修复此问题

**Comment by yangkaa** [comment]
5.8.0 版本中已修复
