### ISSUE TITLE
无法将离线应用模版导入

### ISSUE THREAD

**Issue by ZhANGJNG** [goodrain/rainbond#1257]
**Describe the bug**
将应用导出为压缩包存在本地后，在web中将组件、应用全部删除，然后导入离线应用模板，提示应用导入失败

**Screenshots**
![image](https://user-images.githubusercontent.com/38257464/182121628-53eea137-a46a-45d5-ba28-5748fea71364.png)

**The relevant information:**
 - Rainbond Version [5.5]
 - Browser [chrome]
 - Kubernetes version [v1.19.6]

**Log**
![image](https://user-images.githubusercontent.com/38257464/182122155-7f4aa6c6-8752-4c47-8284-e191d39749c9.png)

**Comment by zzzhangqi** [comment]
从图片中看你是上传的 Docker-Compose 压缩包，支持导出 Docker-compose，不支持导入呢

请导入 Rainbond RAM 离线包

**Comment by ZhANGJNG** [comment]
离线导入目前仅支持 Rainbond RAM 离线包
