### ISSUE TITLE
centos 9 安装报错

### ISSUE THREAD

**Issue by stylesmile** [goodrain/rainbond#1261]
**Describe the bug**

**To Reproduce**
1. curl sh.rainbond.com/install_docker | bash
2. export EIP=127.0.0.1
3.

 docker run --privileged -d -p 7070:7070 -p 80:80 -p 443:443 -p 6060:6060 -p 8443:8443 \
--name=rainbond-allinone --restart=on-failure \
-v ~/.ssh:/root/.ssh \
-v ~/rainbonddata:/app/data \
-v /opt/rainbond:/opt/rainbond \
-v ~/dockerdata:/var/lib/docker \
-e ENABLE_CLUSTER=true \
-e EIP=$EIP \
registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.7.1-dind-allinone \
&& docker logs -f rainbond-allinone

**Screenshots**

**The relevant information:**
 - Rainbond Version [e.g. 5.7.1]

![image](https://user-images.githubusercontent.com/50162847/182395892-4e643780-a2be-4459-b951-25a82b7b94b7.png)

**Comment by yangkaa** [comment]
看起来和 https://github.com/goodrain/rainbond/issues/1262 是相同的问题，应该和你安装的docker或系统配置相关。我将关闭这个 issues，在 https://github.com/goodrain/rainbond/issues/1262 下进行讨论。
