### ISSUE TITLE
ubuntu22 安装 raninbond5.7.1安装报错

### ISSUE THREAD

**Issue by stylesmile** [goodrain/rainbond#1262]
**Describe the bug**

**To Reproduce**
curl sh.rainbond.com/install_docker | bash
export EIP=192.168.85.130
docker run --privileged -d -p 7070:7070 -p 80:80 -p 443:443 -p 6060:6060 -p 8443:8443
--name=rainbond-allinone --restart=on-failure
-v ~/.ssh:/root/.ssh
-v ~/rainbonddata:/app/data
-v /opt/rainbond:/opt/rainbond
-v ~/dockerdata:/var/lib/docker
-e ENABLE_CLUSTER=true
-e EIP=$EIP
registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.7.1-dind-allinone
&& docker logs -f rainbond-allinone

**Screenshots**

**The relevant information:**
 - Rainbond Version [e.g. 5.7.1]
![image](https://user-images.githubusercontent.com/50162847/182397351-c6fdfed3-cbd0-449d-bdb2-1a6bfb978f45.png)

**Comment by yangkaa** [comment]
你的Docker版本是什么呢？也许你可以参考这个 https://github.com/microsoft/vscode-docker/issues/1402#issuecomment-561536546 看看是否可以解决

**Comment by stylesmile** [comment]
curl sh.rainbond.com/install_docker | bash用这个安装的docker

**Comment by yangkaa** [comment]
是否有尝试我发的这个解决方案呢 https://github.com/microsoft/vscode-docker/issues/1402#issuecomment-561536546

**Comment by zzzhangqi** [comment]
操作系统：Ubuntu 22.04 LTS (Jammy Jellyfish)
内核：5.15.0-40-generic
Rainbond 版本：v5.7.1-dind

使用 Rainbond 文档中提供的 Docker 版本为 19.03.6 改版本有 Bug，会导致该问题产生
```shell
curl sh.rainbond.com/install_docker | bash
```

#### 如何解决
升级 Docker 版本：
```shell
curl -sfL https://get.docker.com | VERSION=20.10.13 sh -
```

**Comment by stylesmile** [comment]
curl -sfL https://get.docker.com | VERSION=20.10.13 sh -这个命令安装docker报错

**Comment by zzzhangqi** [comment]
麻烦将报错发出来，这是来自 Docker 官方的安装脚本

**Comment by zzzhangqi** [comment]
ubuntu 22 is already supported
