### ISSUE TITLE
helm命令行生成工具参数不生效问题

### ISSUE THREAD

**Issue by hanxinhisen** [goodrain/rainbond#1264]
![1659506100419_1157B22D-2C96-4c87-88F3-9B38A6AF942F](https://user-images.githubusercontent.com/7082486/182544862-8e3b29dd-3d18-4761-8aea-05aa6ccbe85e.png)

![1659506101603_AE5AA1D9-A758-48e6-9003-98E69D0FDCFC](https://user-images.githubusercontent.com/7082486/182544923-04bc3d16-776a-4087-b219-2b918812fb49.png)

上图为helm生成的命令行参数，下图为实际执行的参数。

**Comment by yangkaa** [comment]
问题原因：在使用 Helm 安装命令生成工具时，未填写外网 IP 导致。

解决方案：在指定网关节点时，外网 IP 和内网 IP 以及节点名称均为必填，如果没有外网 IP，可以填写内网 IP，目前官网 Helm 安装命令生成工具未限制必填。需要调整为必填项。

**Comment by yangkaa** [comment]
Helm 安装命令生成工具已调整上线

**Comment by yangkaa** [comment]
多节点仅指定网关节点，不指定构建节点时，则会复现该问题。已修复 https://github.com/goodrain/rainbond-operator/pull/174
