### ISSUE TITLE
centos8安装失败，一直卡在初始化数据

### ISSUE THREAD

**Issue by stylesmile** [goodrain/rainbond#1265]
**Describe the bug**
centos8安装失败，一直卡在初始化数据，半个小时还没好
rainond版本:   5.7.1
docker 版本：19.03.5
linux内核版本：Linux localhost.localdomain 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
第一步：curl sh.rainbond.com/install_docker | bash
第二步：export EIP=192.168.175.139
第三步：docker run --privileged -d -p 7070:7070 -p 80:80 -p 443:443 -p 6060:6060 -p 8443:8443 \
--name=rainbond-allinone --restart=on-failure \
-v ~/.ssh:/root/.ssh \
-v ~/rainbonddata:/app/data \
-v /opt/rainbond:/opt/rainbond \
-v ~/dockerdata:/var/lib/docker \
-e ENABLE_CLUSTER=true \
-e EIP=$EIP \
registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.7.1-dind-allinone \
&& docker logs -f rainbond-allinone

**Screenshots**

**Comment by stylesmile** [comment]
centos8镜像下载地址：http://mirrors.aliyun.com/centos/8-stream/isos/x86_64/CentOS-Stream-8-x86_64-20220728-dvd1.iso

**Comment by yangkaa** [comment]
提供信息过少，是否有参考[问题排查文档](https://www.rainbond.com/docs/installation/install-troubleshoot/dind-install-troubleshoot/)进行排查呢？

**Comment by stylesmile** [comment]
dockerd没起来

`
root@3b5e872b21a3:/app/ui# docker info
Client:
 Context:    default
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
`

**Comment by yangkaa** [comment]
如果可以的话，麻烦贴一下 /app/logs  下面的所有日志文件

**Comment by stylesmile** [comment]
[logs.zip](https://github.com/goodrain/rainbond/files/9258257/logs.zip)

**Comment by stylesmile** [comment]
所有日志打包成压缩包了

**Comment by zzzhangqi** [comment]
我的复现环境：

* 操作系统：Centos 8.5
* 内核：4.18.0-348.7.1.el8_5.x86_64
* Docker：19.03.5
* Rainbond：v5.7.1-dind-allinone

已找到问题所在，因未包含/加载 内核模块 `ip_tables` 导致 docker in docker 无法启动。

1. 查询内核模块 `ip_tables` 是否存在，存在则会打印`filename`；如未存在请 [升级内核](https://t.goodrain.com/d/9-centos)。
```
$ modinfo ip_tables
filename:       /lib/modules/4.18.0-348.7.1.el8_5.x86_64/kernel/net/ipv4/netfilter/ip_tables.ko.xz
```
2. 加载内核模块
```
modprobe ip_tables
```

**Comment by zzzhangqi** [comment]
存在也需要加载模块的哈，在操作系统下执行

**Comment by stylesmile** [comment]
[logs.zip](https://github.com/goodrain/rainbond/files/9267657/logs.zip)
centos8升级内核之后还是报错
```
/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py:65: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016
  monkey.patch_all(subprocess=True)
/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py:65: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016
  monkey.patch_all(subprocess=True)
/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py:65: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016
  monkey.patch_all(subprocess=True)
/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py:65: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016
  monkey.patch_all(subprocess=True)
```

**Comment by stylesmile** [comment]
[logs.zip](https://github.com/goodrain/rainbond/files/9267657/logs.zip)
centos8升级内核之后还是报错

**Comment by zzzhangqi** [comment]
请检查你的网络，关闭 firewalld 并开启 ipv4 内核转发

**Comment by stylesmile** [comment]
关闭 firewalld 并开启 ipv4 内核转发，还是一直加载数据，rainbond后台可以访问，默认的集群和团队没有自动创建

**Comment by ZhangSetSail** [comment]
感谢您在过去提出这个问题，由于时间过于久远，不确定问题是否依然存在。因此，我们将关闭这个问题。我们非常感谢您的贡献，并希望继续得到您的支持。如果您有任何新的问题或需求，请随时开启新的issue。谢谢！
