### ISSUE TITLE
Update node role causes fatal error

### ISSUE THREAD

**Issue by ysicing** [goodrain/rainbond#127]
If you want to report a bug, please provide the following information:

- [ ] Rainbond versions 3.7.1
- [ ] Operating system and kernel Ubuntu 16.04/4.4.0-136-generic

node log:
[node.err.log](https://github.com/goodrain/rainbond/files/2419114/node.err.log)

**Comment by barnettZQG** [comment]
![image](https://user-images.githubusercontent.com/18493394/46118898-59c8f000-c23b-11e8-8d8c-3e84ff0d451f.png)
