### ISSUE TITLE
tenant cpu&memory metrics error

### ISSUE THREAD

**Issue by srcio** [goodrain/rainbond#1279]
**描述**
团队的cpu和内存使用统计数据随着Pod的新建而不断累加上升，但不会随着pod的销毁而消减。

重现步骤：
1. 观察某团队cpu和内存使用情况： 集群=>资源限额
2. 进入团队重启某应用组件
3. 再次观察该团队cpu和内存使用情况： 集群=>资源限额
4. 会发现cpu和内存使用值上升（数据累加了）

 - Rainbond 5.6.x+
 - Kubernetes v1.22.5

**Comment by yangkaa** [comment]
5.8.0 版本中已修复
