### ISSUE TITLE
权限控制有后门

### ISSUE THREAD

**Issue by superjackwong** [goodrain/rainbond#1288]
![image](https://user-images.githubusercontent.com/57210156/184562814-cad29bf7-c07f-4ef6-bd23-c444f1bae941.png)
如图，权限分配为观察者（只有查看），但在上图还是找到程序后门

**Screenshots**

**The relevant information:**
 - Rainbond Version v5.8.0-release-48b2c262e-2022-08-13-05-allinone
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version [e.g 1.16.3]

**Comment by yangkaa** [comment]
这确实是个问题，我们会在下个版本修复

**Comment by yangkaa** [comment]
v5.8.1 版本中已修复，如还有问题，请重新打开
