### ISSUE TITLE
应用运行异常

### ISSUE THREAD

**Issue by allenonline** [goodrain/rainbond#129]
[3.7.1 ] Rainbond versions
[centos 7.3 ] Operating system and kernel
[kvm in smartos ] Provider(Aliyun,VirtualBox,...)
[ Online/Single node] Install details(Online/Offline,Single node/HA)
Steps to reproduce

通过DockerRun命令新建的java springboot应用，启动后通过web访问swagger-ui.html 一直显示
“您的应用正在准备中，请稍等一会儿”

查看操作日志显示
```
16:36:11容器1844ade639725fb77abbbe4e8a69a61c发生重启,重启次数3
16:24:48容器1844ade639725fb77abbbe4e8a69a61c发生重启,重启次数2
16:11:59容器1844ade639725fb77abbbe4e8a69a61c发生重启,重启次数1
16:06:39应用重新启动任务完成
16:06:39开始移除残留的Pod实例
16:06:39实例启动超时，置于后台启动，请留意应用状态
16:06:39移除残留的Pod实例完成
16:06:39创建K8sService资源开始
16:06:39应用重新启动任务工作器退出
16:06:39新版实例数:1,旧版实例数:0,替换完成
16:05:34实例正在启动，当前启动实例数 0,就绪实例数 0, 未启动实例数 1
16:05:34实例(a9c2dc7c14814c31b9b23551499aaef3-78c35)初始化已完成
16:05:34实例正在启动，当前启动实例数 1,就绪实例数 0, 未启动实例数 0
16:05:34实例(d70b9cf5d7c04133997afb7ada8ecac5-g116t)已停止并移除
16:05:34实例开始启动，需要启动实例数 1, 超时时间:65秒
16:05:34扩容结果监听开始
16:05:34实例(a9c2dc7c14814c31b9b23551499aaef3-78c35)调度已完成
16:05:04缩容结果监听开始
16:05:04实例开始关闭，需要关闭实例数 1, 超时时间:40秒
16:05:04重启应用任务创建成功
16:05:04实例正在关闭，当前应用实例数 1
16:05:04创建ReplicationController资源开始
16:05:04新版实例数:1,旧版实例数:0,替换开始
16:05:04开始滚动替换实例
16:05:04实例正在关闭，当前应用实例数 0
16:05:04开始重启ReplicationController
16:05:04应用重新启动任务开始执行
```
应用反复重启，不知道是什么原因？

**Comment by ysicing** [comment]
端口监听对吗，关闭健康检测

**Comment by allenonline** [comment]
端口监听是对的，内部端口是8081，在应用中也添加了8081端口
![image](https://user-images.githubusercontent.com/8249188/46135279-5ce1d180-c277-11e8-8eee-f6754a314d9b.png)
而且在宿主机直接执行docker run，启动容器后，是可以正常访问的。

健康检测要如何关闭呢？

**Comment by ysicing** [comment]
设置里面可以关闭，你可以看下日志之类的，或者参考[应用异常排查](https://www.rainbond.com/docs/stable/user-manual/trouble-shooting/build-app-issue.html#part-a7069f2908eccea0)

**Comment by allenonline** [comment]
参考排查文档，执行命令报500错误

```
[root@manage01 ~]# grctl service get http://10.16.3.11:7070/#/team/jmi9qkpa/region/rainbond/app/gr69a61c
http://10.16.3.11:7070/#/team/jmi9qkpa/region/rainbond/app/gr69a61c
500:Get https://region.goodrain.me:8443/v2/tenants/jmi9qkpa/services/gr69a61c: dial tcp: lookup region.goodrain.me on 114.114.114.114:53: server misbehaving
[root@manage01 ~]# grctl cluster
500:Get https://region.goodrain.me:8443/v2/cluster: dial tcp: lookup region.goodrain.me on 114.114.114.114:53: server misbehaving
[root@manage01 ~]# 

```
似乎所有的grctl命令都显示500

**Comment by allenonline** [comment]
关闭健康检查后，应用没有反复重启了，操作日志中没有error信息。
但是通过web访问swagger-ui.html 还是一直显示
“您的应用正在准备中，请稍等一会儿”

根据应用异常排查的说明，执行ctop可以看到该容器内存是满的，是否内存不足导致的？
![image](https://user-images.githubusercontent.com/8249188/46138133-b5b46880-c27d-11e8-88a1-4f58d1a30582.png)

**Comment by ysicing** [comment]
伸缩里可以扩容内存

**Comment by barnettZQG** [comment]
@allenonline 
1.检查应用监听的地址是否为0.0.0.0
2.检查应用是否能够在容器内部访问

**Comment by allenonline** [comment]
确实是内存不足导致的，扩容后即可正常运行
