### ISSUE TITLE
集群概览页面报错

### ISSUE THREAD

**Issue by stylesmile** [goodrain/rainbond#1292]
**Describe the bug**
集群概览页面报错

**To Reproduce**
1. 点击我的企业
2.点击集群
3.点击集群名称，进入概览页面，点击左侧的概况
在线版5.7.1和5.8.0都报错，系统版本centos7.9,内核版本5.12
![image](https://user-images.githubusercontent.com/50162847/184632329-e7498ac7-0023-4dce-84ee-6e79b51ba3fe.png)

**Comment by yangkaa** [comment]
与 https://github.com/goodrain/rainbond/issues/1293 重复
