### ISSUE TITLE
5.8.0集群的发现和负载均衡页面报错

### ISSUE THREAD

**Issue by stylesmile** [goodrain/rainbond#1293]
**Describe the bug**

**To Reproduce**
To Reproduce

点击我的企业
2.点击集群
3.点击集群名称，进入概览页面，点击左侧的“发现和负载均衡”的“ingresses”
在线版5.8.0报错，系统版本centos7.9,内核版本5.12，5.8.0离线版正常

![image](https://user-images.githubusercontent.com/50162847/184631910-bdde6b58-a753-49b6-96fb-3cce8c3d4654.png)

**Comment by yangkaa** [comment]
单机体验版中集群版本1.22，由于 ingress api 被弃用导致，https://kubernetes.io/zh-cn/docs/reference/using-api/deprecation-guide/#ingress-v122，需要更新 dashboard 版本

**Comment by yangkaa** [comment]
v5.8.1 版本中已修复，如还有问题，请重新打开
