### ISSUE TITLE
单机体验版每次重启后无法打开web页面，且rbd-system空间容器状态异常

### ISSUE THREAD

**Issue by leiyu1982** [goodrain/rainbond#1294]
通过vmware workstation安装rainbond的单机体验版，分配16GB内存，200GB磁盘空间，4CPU。
第一次安装后为正常，一旦虚拟机重启，rbd-system空间中的容器状态就抛异常，如下所示：
![image](https://user-images.githubusercontent.com/50724837/184659269-d2700cd8-52ff-41d1-9f3c-58fc9b09aa2f.png)

**Comment by yangkaa** [comment]
EIP 最开始设置的是什么呢？是否是离线环境，resources-proxy 异常应该是和网络环境有关，只影响平台源码构建。不影响其他功能

**Comment by leiyu1982** [comment]
> EIP 最开始设置的是什么呢？是否是离线环境，resources-proxy 异常应该是和网络环境有关，只影响平台源码构建。不影响其他功能

EIP设置的是虚拟机登陆IP地址，不是离线环境，可以访问外网。web主界面打不开，ready这里很多都是0，不是正常状态。

**Comment by yangkaa** [comment]
麻烦提供下 0/1 Pod 的事件、日志信息，以及 CrashLoopBackOff Pod 的日志信息

**Comment by ZhangSetSail** [comment]
根据我们的记录，该问题已在 5.17.0 版本中得到修复。为了保持问题追踪的清晰和管理的有效性，我将关闭此 issue。如果问题仍然存在或有进一步的讨论，欢迎随时重新打开它。感谢您的贡献和理解！
