### ISSUE TITLE
偶发性出现rdb-worker故障

### ISSUE THREAD

**Issue by zhengxu632** [goodrain/rainbond#1296]
**Describe the bug**
离线安装部署版本v5.8.0部署成功后运行过程中偶发性出现
![image](https://user-images.githubusercontent.com/36351231/185537843-cb9f7dc0-0979-4424-8039-b3d62ed3a682.png)

**Comment by yangkaa** [comment]
指标收集应该有问题：
类似的问题还有：https://github.com/goodrain/rainbond/issues/1289

内存和 CPU 似乎指标也存在问题，如下图：
![image](https://user-images.githubusercontent.com/30614084/186116438-ae6e1257-c3b4-465a-9f6a-b05afcee2783.png)

**Comment by ZhangSetSail** [comment]
see https://github.com/goodrain/rainbond/pull/1313
