### ISSUE TITLE
在v5.8环境里 用原生的方式部署 MySQL Operator for Kubernetes 后无法通过 走第三方应用 方式加入到 Rainbond中

### ISSUE THREAD

**Issue by xuaiguo** [goodrain/rainbond#1297]
我在v5.8环境里 用原生的方式部署 MySQL Operator for Kubernetes，然后通过 此 Operator 部署了一套 MySQL InnoDB Cluster，但是无法加入到 Rainbond中来做网关路由
![1661070220067_F815F279-7CB2-4cc5-BE6E-C536E26346A4](https://user-images.githubusercontent.com/29732916/185790947-9b4bc935-1d1d-4575-b9be-e2a10027cccf.png)

**Comment by yangkaa** [comment]
使用的是 Kubernetes 方式的第三方组件吗？如果第三方组件实例识别错误，出现重复的实例地址。且无法删除的话，可以参考下面的方式解决下。

解决方案：
1. 找到 service 的 ClusterIP，假设现在 mysql 的 service IP 为 10.10.24.14，service 端口为 6446， 6447。那么参考下图创建第三方组件。
<img width="532" alt="image" src="https://user-images.githubusercontent.com/30614084/186086431-ebf1464d-ac83-4778-8316-c5eeca6e53e7.png">

2. 进入第三方组件页面，选择端口，新增端口：6446 和 6447。再在更多设置中配置好健康检测，再打开对外服务，最后启动第三方组件尝试。
