### ISSUE TITLE
arm64 m1 support？

### ISSUE THREAD

**Issue by bulolo** [goodrain/rainbond#1299]
### from docs
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/10026498/187117804-d6839345-d5bb-4829-970c-ba6a3197ce60.png">
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/10026498/187117852-fc7352b6-50b3-4efe-8518-f8bfecac3b43.png">

### from bilibili video
<img width="1750" alt="image" src="https://user-images.githubusercontent.com/10026498/187117890-d6337eae-97b7-4302-8ae3-5e402d5ecf51.png">

**Comment by zzzhangqi** [comment]
5.8.0 Arm64 M1 is not yet supported, Will support in the next few days

5.7.1 supported https://v5.7-docs.rainbond.com/docs/installation/install-with-dind
