### ISSUE TITLE
升级5.8后无法备份控制台

### ISSUE THREAD

**Issue by xushangkun** [goodrain/rainbond#1302]
以下为报错信息
2022-08-31 22:19:43 [ERROR] localhost [export_console_data] /app/ui/console/services/backup_data_service.py:104 /usr/local/lib/python3.6/site-packages/jwt/utils.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.primitives.asymmetric.utils import (
CommandError: Unable to serialize database: (1146, "Table 'rbdconsole.team_registry_auths' doesn't exist")

**Comment by yangkaa** [comment]
安装的是什么版本？目前看起来似乎是你在升级时没有执行正确的sql，所以 team_registry_auths 表不存在。你需要进入控制台的容器中，执行正确的sql，参考 https://www.rainbond.com/docs/upgrade/5.8.0-upgrade 文档

**Comment by xushangkun** [comment]
# curl https://rainbond-script.oss-cn-hangzhou.aliyuncs.com/upgrade-5.8.0.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3192  100  3192    0     0   6705      0 --:--:-- --:--:-- --:--:--  6705
ERROR 1060 (42S21) at line 38: Duplicate column name 'job_strategy'
执行失败

**Comment by xushangkun** [comment]
以下为当前数据库表
+-------------------------------------+
| Tables_in_rbdconsole                |
+-------------------------------------+
| adaptor_app_stores                  |
| adaptor_cloud_access_keys           |
| adaptor_create_kubernetes_tasks     |
| adaptor_custom_clusters             |
| adaptor_init_rainbond_tasks         |
| adaptor_rainbond_cluster_configs    |
| adaptor_rke_clusters                |
| adaptor_task_events                 |
| adaptor_update_kubernetes_tasks     |
| announcement                        |
| app_config_group                    |
| app_config_group_item               |
| app_config_group_service            |
| app_export_record                   |
| app_import_record                   |
| app_market                          |
| app_service_extend_method           |
| app_service_group                   |
| app_upgrade_record                  |
| app_upgrade_snapshots               |
| applicants                          |
| auth_group                          |
| auth_group_permissions              |
| auth_permission                     |
| auth_user                           |
| auth_user_groups                    |
| auth_user_user_permissions          |
| authtoken_token                     |
| autoscaler_rule_metrics             |
| autoscaler_rules                    |
| back_service_install_temp           |
| clound_bang_images                  |
| component_graphs                    |
| component_k8s_attributes            |
| compose_group                       |
| compose_service_relation            |
| console_config                      |
| console_sys_config                  |
| deploy_relation                     |
| django_content_type                 |
| django_migrations                   |
| django_session                      |
| enterprise_user_perm                |
| errlog                              |
| gateway_custom_configuration        |
| group_create_temp                   |
| groupapp_backup                     |
| groupapp_backup_import              |
| groupapp_migrate                    |
| k8s_resources                       |
| labels                              |
| node_labels                         |
| oauth_service                       |
| package_upload_record               |
| perms_info                          |
| phone_code                          |
| plugin_build_version                |
| plugin_config_group                 |
| plugin_config_items                 |
| plugin_share_record_event           |
| publish_group_service_relation      |
| rainbond_center_app                 |
| rainbond_center_app_inherit         |
| rainbond_center_app_tag             |
| rainbond_center_app_tag_relation    |
| rainbond_center_app_version         |
| rainbond_center_plugin              |
| region_app                          |
| region_info                         |
| role_info                           |
| role_perms                          |
| service                             |
| service_attach_info                 |
| service_build_source                |
| service_consume                     |
| service_create_step                 |
| service_domain                      |
| service_domain_certificate          |
| service_event                       |
| service_fee_bill                    |
| service_group                       |
| service_group_relation              |
| service_labels                      |
| service_payment_notify              |
| service_perms                       |
| service_plugin_config_var           |
| service_probe                       |
| service_share_record                |
| service_share_record_event          |
| service_source                      |
| service_tcp_domain                  |
| service_upgrade_record              |
| service_user_perms                  |
| service_webhooks                    |
| team_gitlab_info                    |
| tenant_compose_file                 |
| tenant_consume                      |
| tenant_consume_detail               |
| tenant_enterprise                   |
| tenant_enterprise_token             |
| tenant_fee_bill                     |
| tenant_info                         |
| tenant_l7_info                      |
| tenant_payment_notify               |
| tenant_permission_group             |
| tenant_perms                        |
| tenant_plugin                       |
| tenant_plugin_share                 |
| tenant_recharge                     |
| tenant_region                       |
| tenant_region_pay_model             |
| tenant_region_resource              |
| tenant_service                      |
| tenant_service_auth                 |
| tenant_service_backup               |
| tenant_service_config               |
| tenant_service_delete               |
| tenant_service_env                  |
| tenant_service_env_var              |
| tenant_service_extend_method        |
| tenant_service_group                |
| tenant_service_image_relation       |
| tenant_service_log                  |
| tenant_service_mnt_relation         |
| tenant_service_monitor              |
| tenant_service_plugin_attr          |
| tenant_service_plugin_relation      |
| tenant_service_recycle_bin          |
| tenant_service_relation             |
| tenant_service_relation_recycle_bin |
| tenant_service_rule                 |
| tenant_service_rule_history         |
| tenant_service_statics              |
| tenant_service_volume               |
| tenant_services_port                |
| tenant_user_permission              |
| tenant_user_role                    |
| tenant_user_role_permission         |
| third_party_service_endpoints       |
| user_access_key                     |
| user_administrator                  |
| user_favorite                       |
| user_info                           |
| user_message                        |
| user_oauth_service                  |
| user_role                           |
| wechat_config                       |
| wechat_state                        |
| wechat_unbind                       |
| wechat_user_info                    |
+-------------------------------------+
150 rows in set (0.00 sec)

**Comment by xushangkun** [comment]
可以了，感谢！！！
