### ISSUE TITLE
集群端失去响应，稍后重试

### ISSUE THREAD

**Issue by anchyobi** [goodrain/rainbond#1303]
前几天还好好的，今天突然显示“集群端失去响应，稍后重试”，重启容器也不行，这个怎么解决，我的是单机版安装的

**Comment by zzzhangqi** [comment]
执行以下命令查看日志，
```
docker exec -it rainbond-allinone bash
kubectl get pod -n rbd-system
```
请贴出所有POD状态

**Comment by anchyobi** [comment]
![image](https://user-images.githubusercontent.com/30885206/187816109-ac002cb4-71e4-4bf5-8e4a-34a34477a16a.png)
有很多，这个吗

**Comment by zzzhangqi** [comment]
看起来是磁盘使用率超过 80% 了，请清理或扩容磁盘并重启使其恢复

**Comment by anchyobi** [comment]
需要扩充挂载到哪个目录

**Comment by zzzhangqi** [comment]
宿主机的 /root 目录和 /opt 目录
