### ISSUE TITLE
应用模板导出失败

### ISSUE THREAD

**Issue by superjackwong** [goodrain/rainbond#1309]
我尝试在应用市场导出应用模板，点击应用模型规范导出得到的状态是失败，通过 kubectl logs -fl name=rbd-chaos -n rbd-system查看日志打印的是time="2022-09-06T18:25:15+08:00" level=info msg="Build task a1fe7941c699495a85c8c2155898de23 in progress"
time="2022-09-06T18:25:15+08:00" level=error msg="task type: export_app; body: {\"event_id\":\"2cfb4c7934fb4977967e06029b856170\",\"group_key\":\"687d6a5cd0b349499bd6ec6dcdaae451\",\"version\":\"1.0\",\"format\":\"rainbond-app\",\"source_dir\":\"/grdata/app/rainbond-app/helloworld-1.0\"}; run task: json: cannot unmarshal array into Go struct field IngressHTTPRoute.ingress_http_routes.proxy_header of type map[string]string"
time="2022-09-06T18:25:15+08:00" level=info msg="Build task a1fe7941c699495a85c8c2155898de23 is completed"
后面@Q张工回复说应用发布时组件含域名信息所致，但有些组件创建自动生产域名的，所以看给修复下此问题或导出时给出相应的解决办法也行，要不然只有冷冰冰的失败两个字用户很是无从排查及解决。

**The relevant information:**
 - 平台版本 v5.8.0-release-48b2c262e-2022-08-13-05-allinone
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version [e.g 1.16.3]

**Comment by yangkaa** [comment]
v5.8.1 版本中已修复，如还有问题，请重新打开
