### ISSUE TITLE
基于web界面安装支持ARM架构

### ISSUE THREAD

**Issue by Kyofin** [goodrain/rainbond#1311]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zzzhangqi** [comment]
非常抱歉，目前开源版本只有 Allinone 支持 ARM，其余均不支持 ARM 架构。

由于国产的CPU和操作系统太多，Rainbond 开源版本适配起来工作量较大，如果你有兴趣，可以参与适配。

> Rainbond 企业版本均已适配国内众多操作系统和CPU
