### ISSUE TITLE
构建中的组件在版本记录中可以被删除

### ISSUE THREAD

**Issue by gnsilence** [goodrain/rainbond#1315]
**Describe the bug**
构建中的组件在版本记录列表可以直接被删除，会导致后续一系列故障问题，构建中的组件不应该可以删除
**To Reproduce**

**Screenshots**
![b9705fa7f07f5f248f70084f99dff2c](https://user-images.githubusercontent.com/18021366/189259787-0f4b7fa9-6ed0-4cf8-aaa5-20b6ec9f55a7.jpg)

**The relevant information:**
 - Rainbond Version [e.g. 5.2.0]
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version [e.g 1.16.3]

**Comment by yangkaa** [comment]
v5.8.1 版本中已修复，如还有问题，请重新打开
