### ISSUE TITLE
通过主机添加集群不支持ubuntu22.04系统

### ISSUE THREAD

**Issue by dongasai** [goodrain/rainbond#1319]
报错如下
```
time="2022-09-16T12:58:06+08:00" level=info msg="Initiating Kubernetes cluster"
time="2022-09-16T12:58:06+08:00" level=info msg="[dialer] Setup tunnel for host [192.168.2.71]"
time="2022-09-16T12:58:06+08:00" level=warning msg="Failed to set up SSH tunneling for host [192.168.2.71]: Can't retrieve Docker Info: error during connect: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info\": Unable to access node with address [192.168.2.71:22] using SSH. Please check if you are able to SSH to the node using the specified SSH Private Key and if you have configured the correct SSH username. Error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain"
time="2022-09-16T12:58:06+08:00" level=warning msg="Removing host [192.168.2.71] from node lists"
time="2022-09-16T12:58:06+08:00" level=warning msg="[state] can't fetch legacy cluster state from Kubernetes: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [192.168.2.71]"
time="2022-09-16T12:58:09+08:00" level=info msg="Successfully Deployed state file at [/app/data/cloudadaptor/enterprise/e8f5256b0ea68f7864d5c909bfe9098f/rke/k8sr1/cluster.rkestate]"
time="2022-09-16T12:58:09+08:00" level=info msg="Building Kubernetes cluster"

``

**Comment by lihao6666** [comment]
用20吧，之前用22各种问题

**Comment by zzzhangqi** [comment]
已支持 ubuntu 22

**Comment by qweqe417** [comment]
> 

麻烦问一下哪个版本开始支持的Ubuntu 22

**Comment by qweqe417** [comment]
Please tell me which version starts to support Ubuntu 22

**Comment by qweqe417** [comment]
Please tell me which version starts to support Ubuntu 22

**Comment by yangkaa** [comment]
Version 5.10

**Comment by qweqe417** [comment]
我用5.11也是一样的吧 ，但是部署集群的时候还是不行，端口对外ssh也能连上的

**Comment by qweqe417** [comment]
It's the same when I use 5.11, but it still doesn't work when deploying a cluster, and the port can also be connected to external ssh

**Comment by yangkaa** [comment]
对于 Docker 高版本，可能执行完脚本后需要重启 docker。

如果你在执行脚本时没有出现任何报错或提醒，那麻烦贴出创建集群失败的日志

**Comment by qweqe417** [comment]
time="2023-02-07T18:45:40+08:00" level=info msg="Initiating Kubernetes cluster"
time="2023-02-07T18:45:40+08:00" level=info msg="[dialer] Setup tunnel for host [10.0.16.69]"
time="2023-02-07T18:45:40+08:00" level=warning msg="Failed to set up SSH tunneling for host [10.0.16.69]: Can't retrieve Docker Info: error during connect: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info\": Unable to access node with address [10.0.16.69:2046] using SSH. Please check if you are able to SSH to the node using the specified SSH Private Key and if you have configured the correct SSH username. Error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain"
time="2023-02-07T18:45:40+08:00" level=warning msg="Removing host [10.0.16.69] from node lists"
time="2023-02-07T18:45:40+08:00" level=warning msg="[state] can't fetch legacy cluster state from Kubernetes: Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [10.0.16.69]"
time="2023-02-07T18:45:42+08:00" level=info msg="Successfully Deployed state file at [/app/data/cloudadaptor/enterprise/2591d1b8fba7c6a7948a8cafcfbfcc93/rke/test/cluster.rkestate]"
time="2023-02-07T18:45:42+08:00" level=info msg="Building Kubernetes cluster"

**Comment by yangkaa** [comment]
这看起来是免密登录配置失败，你可以尝试在 allinone 容器中执行 ssh docker@10.0.16.69，看是否能进行免密登录。如果不行，可以从免密配置上来考虑。可以尝试自己手动配置实现使用 docker 用户免密登录到服务器上。

有一个同样问题的 issues 可以参考下：https://github.com/goodrain/rainbond/issues/1530
