### ISSUE TITLE
The source code build failed and the slug package was not properly generated

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#132]
If you want to report a bug or advice, please provide the following information and try to describe your issue in English, If it's a question of use,please read the [documentation](https://www.rainbond.com/docs/stable/) or browse the [community](https://t.goodrain.com/)

- [ v3.7.1] Rainbond versions(eg. grctl version)

- [ ] Kubernetes versions(If you use your own cluster)

- [ centOs7.4] Operating system and kernel

- [ ] Provider(Aliyun,VirtualBox,...)

- [ ] Install details(Online/Offline,SingleNode/HA)

The source code build failed and the slug package was not properly generated
![image](https://user-images.githubusercontent.com/33855684/46242905-add10180-c400-11e8-99d0-a693752a1e01.png)
![image](https://user-images.githubusercontent.com/33855684/46242907-b4f80f80-c400-11e8-8f56-3f7a4e8824a8.png)

**Comment by barnettZQG** [comment]
This looks like the source code compilation failed, Is the source code not compliant or wrong? Reference build log

**Comment by barnettZQG** [comment]
No feedback, this issue will be closed.
How is there still a problem? Please open it again
