### ISSUE TITLE
Page configuration information display error

### ISSUE THREAD

**Issue by maojunxyz** [goodrain/rainbond#1326]
**Describe the bug**
When you add the component, select upload war/jar, inside the parameter settings. The display message inside is wrong. 

**Screenshots**
As shown in the figures：
![image](https://user-images.githubusercontent.com/28778042/190976658-acf199b8-1b17-4520-b2cb-f642c78701cc.png)

![image](https://user-images.githubusercontent.com/28778042/190976751-108a3e8a-0f2f-4714-8ebb-116d673e3440.png)

**The relevant information:**
 - Rainbond Version 
 平台版本 v5.8.1-f5ce140fa-2022-09-16-02-allinone

 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 Chromium: 105.0.5195.127 (Official Build) (64-bit)

**Comment by zzzhangqi** [comment]
would you like to submit a PR to fix this? Looks like the translated id is incorrect
