### ISSUE TITLE
Bug: button prompt is incorrect

### ISSUE THREAD

**Issue by zzzhangqi** [goodrain/rainbond#1328]
Should be "确认"
![image](https://user-images.githubusercontent.com/39754275/191180397-3c8dc8f8-38e6-4c2f-92b2-a11470146b20.png)

![image](https://user-images.githubusercontent.com/39754275/191180497-d351cd1f-ce49-4a1e-b3f7-887ef4567ae5.png)

**Comment by RainBondsongyg** [comment]
https://github.com/goodrain/rainbond-ui/pull/1050
