### ISSUE TITLE
组件发布到组件库后可以保留端口的内部域名

### ISSUE THREAD

**Issue by runningbeanxl** [goodrain/rainbond#1329]
目前服务通过原来k8s service的方式进行内网通信，希望组件发布到组件库后可以保留端口的内部域名

**Comment by yangkaa** [comment]
从 v5.8.0 开始，支持原生 Service 模式发布。内部域名会一同发布。安装时，如果该团队下内部域名不冲突，则使用原有内部域名。如果冲突，则会增加一个后缀，如下图所示。

<img width="1876" alt="image" src="https://user-images.githubusercontent.com/30614084/195304851-0b087dec-73ec-4b18-81c8-fbb600b8c005.png">

**Comment by ZhangSetSail** [comment]
该问题看起来已经得到解决，我将关闭该issue，如果又问题可以随时重新打开。
