### ISSUE TITLE
关于从Docker镜像创建应用时，启动命令的问题 

### ISSUE THREAD

**Issue by ysicing** [goodrain/rainbond#133]
使用docker镜像或者docker run命令创建应用，首次创建时设置的启动命令正常有效，创建成功后，在“设置”里修改启动命令，然后重新构建，则没有效果

**Comment by barnettZQG** [comment]
@27-1 是否修改构建源信息时未将配置信息同步到数据中心

**Comment by barnettZQG** [comment]
@zjhgoodrain Need to confirm, app after rebuild, has cmd been updated?
