### ISSUE TITLE
state file not exist, can not support expansion node

### ISSUE THREAD

**Issue by liuli01** [goodrain/rainbond#1332]
**Describe the bug**

**To Reproduce**
在单节点集群上面，新增两个节点（计算和存储）

**Screenshots**

**The relevant information:**
 - Rainbond Version [e.g. 5.2.0]
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version [e.g 1.16.3]
 - 出现这个报错，怎么解决
![b79480c840961e4be11a6c6e1cb494d](https://user-images.githubusercontent.com/48510338/191678107-1e92a612-9690-4a38-9722-99fdad53ea28.png)

**Comment by zzzhangqi** [comment]
控制台是 docker run 的 allinone 么？
