### ISSUE TITLE
Use Case

### ISSUE THREAD

**Issue by linuxv** [goodrain/rainbond#1336]
组织/公司：成都共生食造科技有限公司
组织/公司Logo：https://zhengxin-pub.cdn.bcebos.com/logopic/162b30615157ff740ee0311b0f9e50af_fullsize.jpg?x-bce-process=image/resize,m_lfit,w_200
网站：none
城市：成都
联系方式：邮箱、微信、钉钉或其他联系方式
使用场景：公司内部持续部署，优化规范开发流程，提高开发效率。对外持续交付，保障生产环境高可用。
Rainbond 网站是否可以展示贵司Logo：是的，我同意

**Comment by zzzhangqi** [comment]
mv https://github.com/goodrain/rainbond/issues/1273#issuecomment-1257207690
