### ISSUE TITLE
openapi增加getToken接口

### ISSUE THREAD

**Issue by wison1001** [goodrain/rainbond#1349]
在调用控制台 OpenAPI 前，需要用户在平台右上角，点击个人中心-访问令牌-新增，创建访问令牌用于授权。这一步骤需要手工操作，可否新增一个getToken接口，用于获取令牌，供后续使用。
getToken接口可传入rainbond账号密码及其他参数，例如
curl -XPOST http://xxx:7070/getToken -H "username=xxx"  -H "passwd=xxx" -H "expire=xxxx"
返回token即可

**Comment by yangkaa** [comment]
你可以尝试调用登录接口，使用用户名和密码，获取响应头中的 Token，如下：
 
<img width="1916" alt="image" src="https://user-images.githubusercontent.com/30614084/195292376-883dcc35-0cef-44b6-bb54-312069176d84.png">

 再通过该 Token 去直接调用生成访问令牌的接口。

**Comment by yangkaa** [comment]
你可以尝试调用登录接口，使用用户名和密码，获取响应头中的 Token，如下：

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/30614084/195293032-18ad2dbb-8c51-467d-9221-85932e441a5c.png">


再通过该 Token 去直接调用生成访问令牌的接口。
