### ISSUE TITLE
v5.8.1 第三方组件详情页按钮显示错误

### ISSUE THREAD

**Issue by hanxinhisen** [goodrain/rainbond#1356]
![ff9feee8fcf4d316ee22c2ab5fa9782](https://user-images.githubusercontent.com/7082486/193764870-b4bda601-40e9-4cd2-8aab-9d1fb6193dd2.png)
![ed7af35773d1d5548cdd1a535b34b92](https://user-images.githubusercontent.com/7082486/193764882-11466f9c-0264-46f3-b12d-c355ba28e8c0.png)
第三方组件详情页按钮，显示错误

**Comment by zzzhangqi** [comment]
翻译错误导致，此处应为 `新增` @RainBondsongyg
