### ISSUE TITLE
ssh协议的git创建组件失败

### ISSUE THREAD

**Issue by dongasai** [goodrain/rainbond#1359]
当我使用ssh的git仓库创建组件的时候检测未通过

![image](https://user-images.githubusercontent.com/16734530/194735981-b214a170-0bba-4e5f-9967-a0e21e8ccd4b.png)

![image](https://user-images.githubusercontent.com/16734530/194735929-885cc822-44fd-4a10-bb75-d7a899e6295b.png)

仓库是一个自建的Gitea服务器,地址如下:
`git@gitea.**.io:im/phpserver.git`

 - Rainbond Version 平台版本 v5.8.0-release

**Comment by dongasai** [comment]
使用自建的gitlab服务器也无法成功,git服务器用户均可以使用git客户端进行代码推,拉,克隆

**Comment by hanxinhisen** [comment]
gitlab 上配置 ssh-key了吗
