### ISSUE TITLE
rbd-resource-proxy

### ISSUE THREAD

**Issue by wulonguncle** [goodrain/rainbond#1371]
1.   通过自建的k8s集群，使用helm部署对接Rainbond.
2. 使用动态存储 sc 作为存储。
3. 启动  rbd-resource-proxy 服务  报错  pvc 有问题，导致 CrashLoopBackOff。
4. 通过修改原有的 deployment sc存储为  hostPath，后该服务启动成功。
5. 过后 该服务 成为两个副本，其中一个失败，  失败原因为 deployment 成为原有的  挂在方式

**Comment by wulonguncle** [comment]
![image](https://user-images.githubusercontent.com/53171745/195984376-42a1e74e-60e8-4a1b-9b89-1e89159a70d8.png)

**Comment by wulonguncle** [comment]
![image](https://user-images.githubusercontent.com/53171745/195984411-92673bc9-053f-433a-8289-2b903c507c28.png)
![image](https://user-images.githubusercontent.com/53171745/195984444-30b6028b-7df9-4e31-a77a-8770224acf10.png)

**Comment by zzzhangqi** [comment]
经排查是自建的 NFS 的参数少了 `no_root_squash` 导致的，该参数的描述是 **root用户具有根目录的完全管理访问权限**
