### ISSUE TITLE
单机安装时，每次到这里就卡住了 什么原因啊？

### ISSUE THREAD

**Issue by 344108150** [goodrain/rainbond#1376]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/90685197/197099347-c638d567-bd7b-4042-a74c-bb92a7c06be0.png">
docker 容器已经正常启动了，但是 UI页面进不去

**Comment by zzzhangqi** [comment]
日志就打印到 load image 这一步？后面没有了么

**Comment by 344108150** [comment]
> 日志就打印到 load image 这一步？后面没有了么

是的 就只到这里 后面就一直卡在那里，

**Comment by zzzhangqi** [comment]
```
docker exec -it rainbond-allinone bash
tail -f /app/logs/k3s.log
```

**Comment by 344108150** [comment]
> 

我换了一种安装方式 就好了

**Comment by zzzhangqi** [comment]
描述一下 allinone 单机安装的环境吧，我这边尝试复现一下你遇到的问题

**Comment by 344108150** [comment]
> 描述一下 allinone 单机安装的环境吧，我这边尝试复现一下你遇到的问题

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/90685197/197122059-fd6db682-d57f-4fd5-a35d-8b1a1ff5ee7e.png">
内存以及磁盘空间都是足够的   系统是 centos 7.4的

**Comment by zzzhangqi** [comment]
启动命令呢

**Comment by 344108150** [comment]
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/90685197/197131828-9d6beb67-31f2-4bce-8d45-4afb80f785cc.png">
启动命令就是这个  然后 $EIP 为127.0.0.1
