### ISSUE TITLE
centos 8.5 单机部署rainbond v5.9.0-dind-allinone 报K3S错误

### ISSUE THREAD

**Issue by xy2019devl** [goodrain/rainbond#1383]
[root@localhost ~]# cat /etc/redhat-release 
CentOS Linux release 8.5.2111
[root@localhost ~]# 
[root@localhost ~]# curl -o install.sh https://get.rainbond.com && bash ./install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9953  100  9953    0     0  15034      0 --:--:-- --:--:-- --:--:-- 15034
./install.sh: line 31: docker: command not found
/usr/bin/which: no docker in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
Ops! Docker has not been installed.
Docker is going to be automatically installed...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4850  100  4850    0     0   6821      0 --:--:-- --:--:-- --:--:--  6811
Unit docker.service could not be found.
[INFO] downloading docker binaries 19.03.5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 60.3M  100 60.3M    0     0  7206k      0  0:00:08  0:00:08 --:--:-- 7829k
[INFO] generate docker service file
[INFO] generate docker config file
[INFO] prepare register mirror for CN
[INFO] turn off selinux in CentOS/Redhat
setenforce: SELinux is disabled
[INFO] enable and start docker
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /etc/systemd/system/docker.service.
[INFO] Docker installed successfully 

###############################################
# The following IP are automatically detected
# You can choose one by enter its index
# If you have an Public IP, Just type it in
# For example: 
#   you can enter "1" to choose the first IP
#   or enter "11.22.33.44" for specific one
###############################################
 
The following IP has been detected:

	1 : 127.0.0.1
	2 : 192.168.3.168
	3 : 192.168.122.1
Enter your choose or a specific IP address:192.168.3.168

###############################################
# Rainbond dind allinone will be installed with:
# Rainbond Version: v5.9.0
# Arch: amd64
# OS: Linux
# Web Site: http://192.168.3.168:7070
# Rainbond Docs: https://www.rainbond.com/docs
# You can submit an issue if you encounter any problems:
#     https://github.com/goodrain/rainbond
###############################################

Generating the installation command:

docker run --privileged -d -p 7070:7070 -p 80:80 -p 443:443 -p 6060:6060 --name=rainbond-allinone --restart=on-failure -v ~/.ssh:/root/.ssh -v ~/rainbonddata:/app/data -v /opt/rainbond:/opt/rainbond -e EIP=192.168.3.168 registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.9.0-dind-allinone

Rainbond dind allinone distribution is installing..
********************过程省略********************

Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.9.0-dind-allinone
140f89f8b9f803045af8e651927494b8d50cf1285168ce2f8c0480cec3a1443b
/usr/lib/python2.7/dist-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2022-10-25 11:00:16,484 CRIT Supervisor running as root (no user in config file)
2022-10-25 11:00:16,489 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-10-25 11:00:17 INFO: Memory: 7741 MB, CPUs: 2, Disk: 60256 MB 
2022-10-25 11:00:17 INFO: Start loaded images, Waiting containerd ready ···························
2022-10-25 11:00:18 INFO: K3s is starting, please wait ············································
2022-10-25 11:00:29 INFO: Containerd is Ready 
2022-10-25 11:00:29 INFO: Start loaded images ···························
time="2022-10-25T11:00:45+08:00" level=fatal msg="failed to ingest \"0ef0f6fa235430e2e5af73b323dd9eac66900fef7f0a04ef79bd6a81b74e8d84/layer.tar\": failed commit on ref \"tar-0ef0f6fa235430e2e5af73b323dd9eac66900fef7f0a04ef79bd6a81b74e8d84/layer.tar\": commit failed: error reading from server: EOF: unavailable"
2022-10-25 11:04:39 ERROR: K3s failed to start. Please use the command to view the k3s log 'docker exec rainbond-allinone /bin/cat /app/logs/k3s.log' 
2022-10-25 11:04:39 INFO: Memory: 7741 MB, CPUs: 2, Disk: 59882 MB 
2022-10-25 11:04:39 INFO: Start loaded images, Waiting containerd ready ···························
2022-10-25 11:04:39 INFO: K3s is starting, please wait ············································
2022-10-25 11:04:41 INFO: Containerd is Ready 
2022-10-25 11:04:41 INFO: Start loaded images ···························
time="2022-10-25T11:04:51+08:00" level=fatal msg="failed to ingest \"0696af2996d59f399e70e76fac4110ec7b5adebdc0580b0701992e9bcc1d526a/layer.tar\": failed commit on ref \"tar-0696af2996d59f399e70e76fac4110ec7b5adebdc0580b0701992e9bcc1d526a/layer.tar\": commit failed: error reading from server: EOF: unavailable"
2022-10-25 11:08:59 ERROR: K3s failed to start. Please use the command to view the k3s log 'docker exec rainbond-allinone /bin/cat /app/logs/k3s.log' 
2022-10-25 11:08:59 INFO: Memory: 7741 MB, CPUs: 2, Disk: 59792 MB 
2022-10-25 11:08:59 INFO: Start loaded images, Waiting containerd ready ···························
2022-10-25 11:09:00 INFO: K3s is starting, please wait ············································
2022-10-25 11:09:01 INFO: Containerd is Ready 
2022-10-25 11:09:01 INFO: Start loaded images ···························
time="2022-10-25T11:09:08+08:00" level=fatal msg="failed to ingest \"0ef0f6fa235430e2e5af73b323dd9eac66900fef7f0a04ef79bd6a81b74e8d84/VERSION\": failed commit on ref \"tar-0ef0f6fa235430e2e5af73b323dd9eac66900fef7f0a04ef79bd6a81b74e8d84/VERSION\": commit failed: error reading from server: EOF: unavailable"
^C
[root@localhost ~]# docker ps
CONTAINER ID        IMAGE                                                                      COMMAND                  CREATED             STATUS              PORTS                                                                                      NAMES
140f89f8b9f8        registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.9.0-dind-allinone   "/usr/bin/supervisord"   12 minutes ago      Up 11 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:6060->6060/tcp, 0.0.0.0:7070->7070/tcp   rainbond-allinone
[root@localhost ~]# docker images
REPOSITORY                                            TAG                    IMAGE ID            CREATED             SIZE
registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond   v5.9.0-dind-allinone   f3b738af6586        34 hours ago        3.66GB

查看日志：

I1025 11:23:12.105041  504050 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
I1025 11:23:12.105048  504050 plugins.go:161] Loaded 11 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,PodSecurity,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
W1025 11:23:12.110621  504050 genericapiserver.go:455] Skipping API apiregistration.k8s.io/v1beta1 because it has no resources.
time="2022-10-25T11:23:12+08:00" level=info msg="Containerd is now running"
time="2022-10-25T11:23:12+08:00" level=info msg="Connecting to proxy" url="wss://127.0.0.1:6443/v1-k3s/connect"
time="2022-10-25T11:23:12+08:00" level=info msg="Handling backend connection request [node]"
time="2022-10-25T11:23:12+08:00" level=warning msg="Disabling CPU quotas due to missing cpu.cfs_period_us"
time="2022-10-25T11:23:12+08:00" level=info msg="Running kubelet --address=0.0.0.0 --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=cgroupfs --client-ca-file=/app/data/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --cni-bin-dir=/app/data/k3s/data/4df8e9805bd5a3f5d7214953c3ba2dffdf7edacf33fe00e8b4c72df76ef2f3ed/bin --cni-conf-dir=/app/data/k3s/agent/etc/cni/net.d --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --container-runtime=remote --containerd=/run/k3s/containerd/containerd.sock --cpu-cfs-quota=false --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --healthz-bind-address=127.0.0.1 --hostname-override=node --kubeconfig=/app/data/k3s/agent/kubelet.kubeconfig --kubelet-cgroups=/k3s --node-labels= --pod-manifest-path=/app/data/k3s/agent/pod-manifests --read-only-port=0 --resolv-conf=/tmp/k3s-resolv.conf --runtime-cgroups=/k3s --serialize-image-pulls=false --tls-cert-file=/app/data/k3s/agent/serving-kubelet.crt --tls-private-key-file=/app/data/k3s/agent/serving-kubelet.key"
Flag --cloud-provider has been deprecated, will be removed in 1.23, in favor of removing cloud provider code from Kubelet.
Flag --cni-bin-dir has been deprecated, will be removed along with dockershim.
Flag --cni-conf-dir has been deprecated, will be removed along with dockershim.
Flag --containerd has been deprecated, This is a cadvisor flag that was mistakenly registered with the Kubelet. Due to legacy concerns, it will follow the standard CLI deprecation timeline before being removed.
I1025 11:23:12.475595  504050 server.go:436] "Kubelet version" kubeletVersion="v1.22.3+k3s1"
I1025 11:23:12.488522  504050 dynamic_cafile_content.go:155] "Starting controller" name="client-ca-bundle::/app/data/k3s/agent/client-ca.crt"
time="2022-10-25T11:23:12+08:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6443/v1-k3s/readyz: 500 Internal Server Error"
I1025 11:23:15.319921  504050 secure_serving.go:266] Serving securely on 127.0.0.1:6444
I1025 11:23:15.319990  504050 dynamic_cafile_content.go:155] "Starting controller" name="request-header::/app/data/k3s/server/tls/request-header-ca.crt"
I1025 11:23:15.320025  504050 dynamic_serving_content.go:129] "Starting controller" name="serving-cert::/app/data/k3s/server/tls/serving-kube-apiserver.crt::/app/data/k3s/server/tls/serving-kube-apiserver.key"
I1025 11:23:15.320040  504050 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I1025 11:23:15.320370  504050 dynamic_serving_content.go:129] "Starting controller" name="aggregator-proxy-cert::/app/data/k3s/server/tls/client-auth-proxy.crt::/app/data/k3s/server/tls/client-auth-proxy.key"
I1025 11:23:15.320646  504050 available_controller.go:491] Starting AvailableConditionController
I1025 11:23:15.320653  504050 cache.go:32] Waiting for caches to sync for AvailableConditionController controller
I1025 11:23:15.337363  504050 customresource_discovery_controller.go:209] Starting DiscoveryController
I1025 11:23:15.337568  504050 apiservice_controller.go:97] Starting APIServiceRegistrationController
I1025 11:23:15.337575  504050 cache.go:32] Waiting for caches to sync for APIServiceRegistrationController controller
I1025 11:23:15.337670  504050 autoregister_controller.go:141] Starting autoregister controller
I1025 11:23:15.337675  504050 cache.go:32] Waiting for caches to sync for autoregister controller
I1025 11:23:15.337982  504050 apf_controller.go:312] Starting API Priority and Fairness config controller
I1025 11:23:15.338309  504050 cluster_authentication_trust_controller.go:440] Starting cluster_authentication_trust_controller controller
I1025 11:23:15.338321  504050 shared_informer.go:240] Waiting for caches to sync for cluster_authentication_trust_controller
I1025 11:23:15.338336  504050 dynamic_cafile_content.go:155] "Starting controller" name="client-ca-bundle::/app/data/k3s/server/tls/client-ca.crt"
I1025 11:23:15.355775  504050 controller.go:85] Starting OpenAPI controller
I1025 11:23:15.355812  504050 naming_controller.go:291] Starting NamingConditionController
I1025 11:23:15.355826  504050 establishing_controller.go:76] Starting EstablishingController
I1025 11:23:15.355837  504050 nonstructuralschema_controller.go:192] Starting NonStructuralSchemaConditionController
I1025 11:23:15.355849  504050 apiapproval_controller.go:186] Starting KubernetesAPIApprovalPolicyConformantConditionController
I1025 11:23:15.355866  504050 crd_finalizer.go:266] Starting CRDFinalizer
I1025 11:23:15.355880  504050 crdregistration_controller.go:111] Starting crd-autoregister controller
I1025 11:23:15.355883  504050 shared_informer.go:240] Waiting for caches to sync for crd-autoregister
I1025 11:23:15.355899  504050 controller.go:83] Starting OpenAPI AggregationController
I1025 11:23:15.392452  504050 dynamic_cafile_content.go:155] "Starting controller" name="client-ca-bundle::/app/data/k3s/server/tls/client-ca.crt"
I1025 11:23:15.392487  504050 dynamic_cafile_content.go:155] "Starting controller" name="request-header::/app/data/k3s/server/tls/request-header-ca.crt"
I1025 11:23:15.520669  504050 cache.go:39] Caches are synced for AvailableConditionController controller
I1025 11:23:15.537643  504050 cache.go:39] Caches are synced for APIServiceRegistrationController controller
I1025 11:23:15.547639  504050 cache.go:39] Caches are synced for autoregister controller
I1025 11:23:15.547889  504050 apf_controller.go:317] Running API Priority and Fairness config worker
I1025 11:23:15.548116  504050 shared_informer.go:247] Caches are synced for cluster_authentication_trust_controller 
I1025 11:23:15.592828  504050 shared_informer.go:247] Caches are synced for crd-autoregister 
I1025 11:23:15.592880  504050 shared_informer.go:247] Caches are synced for node_authorizer 
E1025 11:23:15.693675  504050 controller.go:156] Unable to remove old endpoints from kubernetes service: no master IPs were listed in storage, refusing to erase all endpoints for the kubernetes service
I1025 11:23:16.347725  504050 storage_scheduling.go:148] all system priority classes are created successfully or already exist.
I1025 11:23:17.343799  504050 controller.go:132] OpenAPI AggregationController: action for item : Nothing (removed from the queue).
I1025 11:23:17.343815  504050 controller.go:132] OpenAPI AggregationController: action for item k8s_internal_local_delegation_chain_0000000000: Nothing (removed from the queue).
time="2022-10-25T11:23:17+08:00" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6443/v1-k3s/readyz: 500 Internal Server Error"
time="2022-10-25T11:23:17+08:00" level=info msg="labels have already set on node: node"
time="2022-10-25T11:23:17+08:00" level=info msg="PodCIDR assigned for node node"
I1025 11:23:17.524686  504050 flannel.go:93] Determining IP address of default interface
I1025 11:23:17.525848  504050 kube.go:120] Waiting 10m0s for node controller to sync
I1025 11:23:17.526666  504050 kube.go:378] Starting kube subnet manager
time="2022-10-25T11:23:17+08:00" level=info msg="Kube API server is now running"
time="2022-10-25T11:23:17+08:00" level=info msg="k3s is up and running"
time="2022-10-25T11:23:17+08:00" level=info msg="Waiting for cloud-controller-manager privileges to become available"
I1025 11:23:17.741798  504050 server.go:687] "--cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /"
I1025 11:23:17.741912  504050 container_manager_linux.go:280] "Container manager verified user specified cgroup-root exists" cgroupRoot=[]
I1025 11:23:17.741958  504050 container_manager_linux.go:285] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName:/k3s SystemCgroupsName: KubeletCgroupsName:/k3s ContainerRuntime:remote CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>}]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerPolicyOptions:map[] ExperimentalTopologyManagerScope:container ExperimentalCPUManagerReconcilePeriod:10s ExperimentalMemoryManagerPolicy:None ExperimentalMemoryManagerReservedMemory:[] ExperimentalPodPidsLimit:-1 EnforceCPULimits:false CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
I1025 11:23:17.741975  504050 topology_manager.go:133] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
I1025 11:23:17.741981  504050 container_manager_linux.go:320] "Creating device plugin manager" devicePluginEnabled=true
I1025 11:23:17.742006  504050 state_mem.go:36] "Initialized new in-memory state store"
I1025 11:23:17.742146  504050 kubelet.go:418] "Attempting to sync node with API server"
I1025 11:23:17.742157  504050 kubelet.go:279] "Adding static pod path" path="/app/data/k3s/agent/pod-manifests"
I1025 11:23:17.742169  504050 kubelet.go:290] "Adding apiserver pod source"
I1025 11:23:17.742181  504050 apiserver.go:42] "Waiting for node sync before watching apiserver pods"
I1025 11:23:17.831056  504050 network_policy_controller.go:144] Starting network policy controller
I1025 11:23:17.907920  504050 kuberuntime_manager.go:245] "Container runtime initialized" containerRuntime="containerd" version="v1.5.7-k3s2" apiVersion="v1alpha2"
I1025 11:23:17.908167  504050 server.go:1213] "Started kubelet"
I1025 11:23:17.920873  504050 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
I1025 11:23:17.928084  504050 server.go:149] "Starting to listen" address="0.0.0.0" port=10250
I1025 11:23:17.928558  504050 server.go:409] "Adding debug handlers to kubelet server"
I1025 11:23:17.931516  504050 volume_manager.go:291] "Starting Kubelet Volume Manager"
I1025 11:23:17.931711  504050 desired_state_of_world_populator.go:146] "Desired state populator starts to run"
F1025 11:23:17.963043  504050 network_policy_controller.go:336] Failed to run iptables command to create KUBE-ROUTER-OUTPUT chain due to running [/sbin/iptables -t filter -N KUBE-ROUTER-OUTPUT --wait]: exit status 3: iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
panic: F1025 11:23:17.963043  504050 network_policy_controller.go:336] Failed to run iptables command to create KUBE-ROUTER-OUTPUT chain due to running [/sbin/iptables -t filter -N KUBE-ROUTER-OUTPUT --wait]: exit status 3: iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

goroutine 12295 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x80ee5c0, 0xc000000003, 0x0, 0x0, 0xc0006f3490, 0x0, 0x6983244, 0x1c, 0x150, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:970 +0x805
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printf(0x80ee5c0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x4ffe04e, 0x3b, 0xc00f607520, 0x2, ...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:753 +0x19a
github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatalf(...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1495
github.com/rancher/k3s/pkg/agent/netpol.(*NetworkPolicyController).ensureTopLevelChains(0xc00c5d7180)
	/go/src/github.com/rancher/k3s/pkg/agent/netpol/network_policy_controller.go:336 +0x7a6
github.com/rancher/k3s/pkg/agent/netpol.(*NetworkPolicyController).Run(0xc00c5d7180, 0xc00109a660)
	/go/src/github.com/rancher/k3s/pkg/agent/netpol/network_policy_controller.go:147 +0x125
created by github.com/rancher/k3s/pkg/agent/netpol.Run
	/go/src/github.com/rancher/k3s/pkg/agent/netpol/netpol.go:64 +0x5cd
time="2022-10-25T11:23:19+08:00" level=info msg="Starting k3s v1.22.3+k3s1 (61a2aab2)"
time="2022-10-25T11:23:19+08:00" level=info msg="Cluster bootstrap already complete"
time="2022-10-25T11:23:19+08:00" level=info msg="Configuring sqlite3 database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s"
time="2022-10-25T11:23:19+08:00" level=info msg="Configuring database table schema and indexes, this may take a moment..."
time="2022-10-25T11:23:19+08:00" level=info msg="Database tables and indexes are up to date"
time="2022-10-25T11:23:19+08:00" level=info msg="Kine available at unix://kine.sock"
time="2022-10-25T11:23:19+08:00" level=info msg="Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/app/data/k3s/server/tls/temporary-certs --client-ca-file=/app/data/k3s/server/tls/client-ca.crt --enable-admission-plugins=NodeRestriction --etcd-servers=unix://kine.sock --feature-gates=JobTrackingWithFinalizers=true --insecure-port=0 --kubelet-certificate-authority=/app/data/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/app/data/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/app/data/k3s/server/tls/client-kube-apiserver.key --profiling=false --proxy-client-cert-file=/app/data/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/app/data/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/app/data/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/app/data/k3s/server/tls/service.key --service-account-signing-key-file=/app/data/k3s/server/tls/service.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/app/data/k3s/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/app/data/k3s/server/tls/serving-kube-apiserver.key"
Flag --insecure-port has been deprecated, This flag has no effect now and will be removed in v1.24.
I1025 11:23:19.454912  508494 server.go:581] external host was not specified, using 172.17.0.2
I1025 11:23:19.455167  508494 server.go:175] Version: v1.22.3+k3s1
time="2022-10-25T11:23:19+08:00" level=info msg="Running kube-scheduler --authentication-kubeconfig=/app/data/k3s/server/cred/scheduler.kubeconfig --authorization-kubeconfig=/app/data/k3s/server/cred/scheduler.kubeconfig --bind-address=127.0.0.1 --kubeconfig=/app/data/k3s/server/cred/scheduler.kubeconfig --leader-elect=false --profiling=false --secure-port=10259"
time="2022-10-25T11:23:19+08:00" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/app/data/k3s/server/cred/controller.kubeconfig --authorization-kubeconfig=/app/data/k3s/server/cred/controller.kubeconfig --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-kube-apiserver-client-cert-file=/app/data/k3s/server/tls/client-ca.crt --cluster-signing-kube-apiserver-client-key-file=/app/data/k3s/server/tls/client-ca.key --cluster-signing-kubelet-client-cert-file=/app/data/k3s/server/tls/client-ca.crt --cluster-signing-kubelet-client-key-file=/app/data/k3s/server/tls/client-ca.key --cluster-signing-kubelet-serving-cert-file=/app/data/k3s/server/tls/server-ca.crt --cluster-signing-kubelet-serving-key-file=/app/data/k3s/server/tls/server-ca.key --cluster-signing-legacy-unknown-cert-file=/app/data/k3s/server/tls/client-ca.crt --cluster-signing-legacy-unknown-key-file=/app/data/k3s/server/tls/client-ca.key --configure-cloud-routes=false --controllers=*,-service,-route,-cloud-node-lifecycle --feature-gates=JobTrackingWithFinalizers=true --kubeconfig=/app/data/k3s/server/cred/controller.kubeconfig --leader-elect=false --profiling=false --root-ca-file=/app/data/k3s/server/tls/server-ca.crt --secure-port=10257 --service-account-private-key-file=/app/data/k3s/server/tls/service.key --use-service-account-credentials=true"
time="2022-10-25T11:23:19+08:00" level=info msg="Running cloud-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/app/data/k3s/server/cred/cloud-controller.kubeconfig --authorization-kubeconfig=/app/data/k3s/server/cred/cloud-controller.kubeconfig --bind-address=127.0.0.1 --cloud-provider=k3s --cluster-cidr=10.42.0.0/16 --configure-cloud-routes=false --kubeconfig=/app/data/k3s/server/cred/cloud-controller.kubeconfig --leader-elect=false --node-status-update-frequency=1m0s --port=0 --profiling=false"
time="2022-10-25T11:23:19+08:00" level=info msg="Waiting for API server to become available"
I1025 11:23:19.462826  508494 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
I1025 11:23:19.462841  508494 plugins.go:161] Loaded 11 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,PodSecurity,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
I1025 11:23:19.464447  508494 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
I1025 11:23:19.464459  508494 plugins.go:161] Loaded 11 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,PodSecurity,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
I1025 11:23:19.465940  508494 shared_informer.go:240] Waiting for caches to sync for node_authorizer
time="2022-10-25T11:23:19+08:00" level=info msg="Node token is available at /app/data/k3s/server/token"
time="2022-10-25T11:23:19+08:00" level=info msg="To join node to cluster: k3s agent -s https://172.17.0.2:6443 -t ${NODE_TOKEN}"
W1025 11:23:19.512358  508494 genericapiserver.go:455] Skipping API apiextensions.k8s.io/v1beta1 because it has no resources.
time="2022-10-25T11:23:19+08:00" level=info msg="Wrote kubeconfig /etc/rancher/k3s/k3s.yaml"
time="2022-10-25T11:23:19+08:00" level=info msg="Run: k3s kubectl"
I1025 11:23:19.513010  508494 instance.go:278] Using reconciler: lease
I1025 11:23:19.653726  508494 rest.go:130] the default service ipfamily for this cluster is: IPv4
time="2022-10-25T11:23:19+08:00" level=info msg="certificate CN=node signed by CN=k3s-server-ca@1666666818: notBefore=2022-10-25 03:00:18 +0000 UTC notAfter=2023-10-25 03:23:19 +0000 UTC"
time="2022-10-25T11:23:19+08:00" level=info msg="certificate CN=system:node:node,O=system:nodes signed by CN=k3s-client-ca@1666666818: notBefore=2022-10-25 03:00:18 +0000 UTC notAfter=2023-10-25 03:23:19 +0000 UTC"
time="2022-10-25T11:23:19+08:00" level=info msg="Module overlay was already loaded"
time="2022-10-25T11:23:19+08:00" level=info msg="Module nf_conntrack was already loaded"
time="2022-10-25T11:23:19+08:00" level=info msg="Module br_netfilter was already loaded"
time="2022-10-25T11:23:19+08:00" level=warning msg="Failed to load kernel module iptable_nat with modprobe"
time="2022-10-25T11:23:19+08:00" level=info msg="Set sysctl 'net/bridge/bridge-nf-call-iptables' to 1"
time="2022-10-25T11:23:19+08:00" level=error msg="Failed to set sysctl: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory"
time="2022-10-25T11:23:19+08:00" level=info msg="Logging containerd to /app/data/k3s/agent/containerd/containerd.log"
time="2022-10-25T11:23:19+08:00" level=info msg="Running containerd -c /app/data/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /app/data/k3s/agent/containerd"
W1025 11:23:20.259745  508494 genericapiserver.go:455] Skipping API authentication.k8s.io/v1beta1 because it has no resources.
W1025 11:23:20.260775  508494 genericapiserver.go:455] Skipping API authorization.k8s.io/v1beta1 because it has no resources.
W1025 11:23:20.271195  508494 genericapiserver.go:455] Skipping API certificates.k8s.io/v1beta1 because it has no resources.
W1025 11:23:20.272304  508494 genericapiserver.go:455] Skipping API coordination.k8s.io/v1beta1 because it has no resources.
W1025 11:23:20.276415  508494 genericapiserver.go:455] Skipping API networking.k8s.io/v1beta1 because it has no resources.
W1025 11:23:20.278825  508494 genericapiserver.go:455] Skipping API node.k8s.io/v1alpha1 because it has no resources.
W1025 11:23:20.283241  508494 genericapiserver.go:455] Skipping API rbac.authorization.k8s.io/v1beta1 because it has no resources.
W1025 11:23:20.283250  508494 genericapiserver.go:455] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
W1025 11:23:20.284919  508494 genericapiserver.go:455] Skipping API scheduling.k8s.io/v1beta1 because it has no resources.
W1025 11:23:20.284925  508494 genericapiserver.go:455] Skipping API scheduling.k8s.io/v1alpha1 because it has no resources.
W1025 11:23:20.287878  508494 genericapiserver.go:455] Skipping API storage.k8s.io/v1alpha1 because it has no resources.
W1025 11:23:20.289327  508494 genericapiserver.go:455] Skipping API flowcontrol.apiserver.k8s.io/v1alpha1 because it has no resources.
W1025 11:23:20.295533  508494 genericapiserver.go:455] Skipping API apps/v1beta2 because it has no resources.
W1025 11:23:20.295542  508494 genericapiserver.go:455] Skipping API apps/v1beta1 because it has no resources.
W1025 11:23:20.297653  508494 genericapiserver.go:455] Skipping API admissionregistration.k8s.io/v1beta1 because it has no resources.
I1025 11:23:20.300436  508494 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
I1025 11:23:20.300446  508494 plugins.go:161] Loaded 11 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,PodSecurity,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
W1025 11:23:20.303746  508494 genericapiserver.go:455] Skipping API apiregistration.k8s.io/v1beta1 because it has no resources.
[root@localhost ~]#

**Comment by yangkaa** [comment]
It is supported in the new version v5.10. If you have any more questions, please reopen it.
