### ISSUE TITLE
没有日志产生，无法定位错误

### ISSUE THREAD

**Issue by 344108150** [goodrain/rainbond#1388]
我用docker compose 构建的 Redis  没有日志产生，这样我完全没办法排查错误啊 

`
version: '3.3'
services:
      redis:
        image: redis
        restart: always
        hostname: redis
        container_name: redis
        privileged: true
        ports:
          - 6379:6379
        environment:
          TZ: Asia/Shanghai
        volumes:
          - ./data:/data
          - ./conf/redis.conf:/etc/redis/redis.conf
          - ./logs:/logs
        command: ["redis-server","/etc/redis/redis.conf"]
`

**Comment by zzzhangqi** [comment]
能否贴出 redis 配置文件，以及存储是否挂载了 logs 目录，也许是你配置 redis 日志输出到了日志文件，并非标准输出 stdout

**Comment by 344108150** [comment]
> 能否贴出 redis 配置文件，以及存储是否挂载了 logs 目录，也许是你配置 redis 日志输出到了日志文件，并非标准输出 stdout

我重启了一下 有日志了 ，那我另外请教一个问题，如果我挂载了 logs目录，但是因为配置文件问题，redis组件没有正常启动，那我应该如何看日志呢，因为这时候组件没有正常启动，我不能通过web终端进到logs里看日志啊

**Comment by yangkaa** [comment]
组件伸缩页面，有一条 grctl 命令，你可以安装 grctl 后，去服务器上执行，可以展示出你该组件的存储挂载路径。将该路径挂载到本地，查看该文件即可。
