### ISSUE TITLE
删除应用问题

### ISSUE THREAD

**Issue by lihao6666** [goodrain/rainbond#1390]
# 详情
完全删除应用的组件后，删除应用会提示有绑定的服务
![image](https://user-images.githubusercontent.com/36958251/197920298-d85bc8a9-dc7e-4dea-9fe0-93aeced17a90.png)
# 版本
v5.9.0-release-aa108188a-2022-10-18-08-allinone

**Comment by yangkaa** [comment]
这应该是 console 数据库和 region 数据库数据不一致导致的。在两个连接出现问题时，可能会出现 console 数据库数据成功删除，region 未删除的情况。你能提供一个可复现的步骤吗？

**Comment by lihao6666** [comment]
> 这应该是 console 数据库和 region 数据库数据不一致导致的。在两个连接出现问题时，可能会出现 console 数据库数据成功删除，region 未删除的情况。你能提供一个可复现的步骤吗？

不确定复现的方式，最后我的操作是把团队删除掉就可以了
