### ISSUE TITLE
私有Harbor仓库使用问题

### ISSUE THREAD

**Issue by lihao6666** [goodrain/rainbond#1393]
# 详情
搭建了私有的Harbor仓库，在创建组件界面选择并输入了仓库信息，没有输入账户密码，检测失败，然后输入账户密码后检测成功
![image](https://user-images.githubusercontent.com/36958251/198079852-52a75f9c-721f-4020-8d23-b82d1120578e.png)

在团队管理中镜像仓库授权中添加授权信息后再尝试不输入账户密码依然失败(是不是是这个只是配置docker-hub的，文档中没有找到）
![image](https://user-images.githubusercontent.com/36958251/198080910-12cf58cf-d884-4030-ad5c-705d3192f6b7.png)

# 版本
v5.9.0-release-aa108188a-2022-10-18-08-allinone

**Comment by yangkaa** [comment]
参考这个issues， https://github.com/goodrain/rainbond/issues/1172

当Dockerfile中引用了私有仓库作为基础镜像，那么需要在此配置账号密码信息。如果你直接基于私有仓库镜像构建，那么直接填写账号密码即可

**Comment by lihao6666** [comment]
> 参考这个issues， #1172
> 
> 当Dockerfile中引用了私有仓库作为基础镜像，那么需要在此配置账号密码信息。如果你直接基于私有仓库镜像构建，那么直接填写账号密码即可

意思时那个镜像仓库授权和这个没有关系是吧

**Comment by zzzhangqi** [comment]
是的，团队内镜像仓库授权是为了 Dockerfile 构建时FROM的基础镜像是私有的，此时填写这个配置有效。

创建组件时使用私有仓库镜像直接在当前页面填写用户密码即可
