### ISSUE TITLE
集群内部初始化后pod正常运行，图形化界面显示对接失败

### ISSUE THREAD

**Issue by simon12138-code** [goodrain/rainbond#1398]
**Describe the bug**
集群内部初始化后pod正常运行，图形化界面显示对接失败

**To Reproduce**
1、选择web界面安装
2、按照操作手册输入对应的集群node节点的ip地址
3、运行生成命令
4、watch pod正常运行
5、图形化界面显示对接失败

**Screenshots**
![image](https://user-images.githubusercontent.com/54308158/198547507-33ff030f-e81c-4c75-9f04-6b99053f2fb9.png)
![image](https://user-images.githubusercontent.com/54308158/198547573-7faea753-155a-4117-b391-17772350d436.png)

**Comment by zzzhangqi** [comment]
请提供 `rainbond-operator-8d5cbd5b4-z8tkj` pod 的日志

**Comment by simon12138-code** [comment]
> 请提供 `rainbond-operator-8d5cbd5b4-z8tkj` pod 的日志
谢谢，已经找到问题所在并且更新了，我的k8s版本较低，更新之后就没问题了
