### ISSUE TITLE
应用绑定域名后，关闭应用和删除应用 该自定义的域名不会在openresty配置中删除

### ISSUE THREAD

**Issue by zhouyq** [goodrain/rainbond#14]
当应用绑定了自定义域名，关闭应用和删除应用后

openresty中的配置并没有删除

rbd-lb版本：master-3.4-0.c11cecf

**Comment by Gemrails** [comment]
由于entrance api 获取domains信息的api变更为“v2”版本,  停止应用删除资源时无法获取用户创建的domain信息, 导致删除失败。
