### ISSUE TITLE
在创建应用时，构建镜像成功，但是从对应的仓库拉取失败

### ISSUE THREAD

**Issue by simon12138-code** [goodrain/rainbond#1400]
**Describe the bug**
，查看k8s集群已经调度了对应的pod，然后报错如下
**To Reproduce**
构建镜像成功，已经调度好了pod
但是拉取镜像失败

**Screenshots**
![image](https://user-images.githubusercontent.com/54308158/198819069-dad837e9-322b-49a7-b483-56fecbe02566.png)

**The relevant information:**
 - Rainbond Version [e.g. 5.2.0]
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version [e.g 1.16.3]

**Comment by yangkaa** [comment]
麻烦提供下Rainbond 版本，K8s 集群版本，K8s 集群容器运行时以及环境的部署方式。这是新部署的集群还是旧版本升级呢？

**Comment by simon12138-code** [comment]
> 麻烦提供下Rainbond 版本，K8s 集群版本，K8s 集群容器运行时以及环境的部署方式。这是新部署的集群还是旧版本升级呢？

rainbond: v5.9.0-release-aa108188a-2022-10-27-08-allinone
K8s: 1.21.10
容器运行时：containerd
通过： helm一键生成命令进行部署

**Comment by ikiler** [comment]
+1 我也是这个问题。。

**Comment by simon12138-code** [comment]
> +1 我也是这个问题。。

我已经解决这个问题了

**Comment by simon12138-code** [comment]
你去搜一下docker的私有仓库构建，然后在docker守护进程的配置文件中进行添加，然后重新加载配置文件，再重启docker，不过比较难搞的是先记得将节点驱逐，否则直接重启会导致k8s节点故障

**Comment by zzzhangqi** [comment]
使用 containerd 作为运行时需要修改 containerd 配置文件，配置 goodrain.me 私有仓库。

vim /etc/containerd/config.toml
```
[plugins."io.containerd.grpc.v1.cri".registry.configs]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."goodrain.me"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."goodrain.me".tls]
       insecure_skip_verify = true
```
/etc/containerd/certs.d/goodrain.me/hosts.toml
```
[host."https://goodrain.me"]
  capabilities = ["pull", "resolve","push"]
  skip_verify = true
```
