### ISSUE TITLE
部署组件MySQL5.7.40服务对外无法访问、对内可以正常访问

### ISSUE THREAD

**Issue by liu13430** [goodrain/rainbond#1401]
问题版本5.81、5.8.2、5.9.0 allinone安装模式
![image](https://user-images.githubusercontent.com/19224774/198876242-38c507e0-6442-40d8-a128-9ca8c780f271.png)
![image](https://user-images.githubusercontent.com/19224774/198876279-878f612a-345c-4e51-8826-4f7b2e347517.png)
![image](https://user-images.githubusercontent.com/19224774/198876319-93a91104-3b9a-49f1-bb9a-a1acaffef01e.png)

**Comment by yangkaa** [comment]
因为 allinone 安装模式，只映射了几个端口，所以创建的组件 mysql 监听的 10000 端口实际在容器内部。所以需要你将容器内端口映射出来。比如你可以映射 10000-10020 端口。在执行安装脚本时，将安装脚本生成的 docker 命令，类似于如下命令
```bash
docker run --privileged -d  -p 7070:7070 -p 80:80 -p 443:443 -p 6060:6060 -p 8443:8443 \
--name=rainbond-allinone --restart=on-failure \
-v ~/.ssh:/root/.ssh \
-v ~/rainbonddata:/app/data \
-v /opt/rainbond:/opt/rainbond \
-e EIP=127.0.0.1 \
registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.9.0-dind-allinone 
```

变为如下命令即可。即添加  `-p 10000-10020:10000-10020` 参数。

```bash
docker run --privileged -d  -p 7070:7070 -p 80:80 -p 443:443 -p 6060:6060 -p 8443:8443 -p 10000-10020:10000-10020 \
--name=rainbond-allinone --restart=on-failure \
-v ~/.ssh:/root/.ssh \
-v ~/rainbonddata:/app/data \
-v /opt/rainbond:/opt/rainbond \
-e EIP=127.0.0.1 \
registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.9.0-dind-allinone 
```

**Comment by liu13430** [comment]
感谢大佬的解答，问题已解决。
