### ISSUE TITLE
使用Harbor仓库webhook错误

### ISSUE THREAD

**Issue by lihao6666** [goodrain/rainbond#1404]
# 详情
使用私有harbor构建镜像，当开启自动构建功能，使用harbor的webhook功能，发现并没有触发，在harbor查看日志，发现发送了webhook请求，但是是400
![image](https://user-images.githubusercontent.com/36958251/198916137-fab4c85c-bf23-4e68-b780-334062e23dac.png)

# 版本
rainbond: v5.9.0-release
harbor: v2.6.1

**Comment by yangkaa** [comment]
查看控制台容器， /app/logs/goodrain.log 的日志

**Comment by lihao6666** [comment]
> /app/logs/goodrain.log

![image](https://user-images.githubusercontent.com/36958251/200757344-7f6c8713-f465-4f52-91c6-cc6fc82f8bf4.png)
下面是harbor配置
![image](https://user-images.githubusercontent.com/36958251/200757396-395b136c-b494-40f9-b80b-86ff96b965af.png)

**Comment by JasonJunMa** [comment]
[](https://www.rainbond.com/docs/devops/continuous-deploy/auto-build/)
看官网上面那条：
**组件是由镜像创建，可支持镜像仓库 Webhooks，目前支持 Docker 官方仓库，阿里云镜像仓库。**
估计是暂不支持Habor仓库的webhook，去到/app/ui/console/views/webhook.py 580行那个代码块中加几个判断支持harbor的post请求体就行

**Comment by zzzhangqi** [comment]
> 看官网上面那条： **组件是由镜像创建，可支持镜像仓库 Webhooks，目前支持 Docker 官方仓库，阿里云镜像仓库。** 估计是暂不支持Habor仓库的webhook，去到/app/ui/console/views/webhook.py 580行那个代码块中加几个判断支持harbor的post请求体就行

有兴趣参与贡献一下吗 🤗

**Comment by ZhangSetSail** [comment]
该 issue 5.17.2 已支持，我将关闭它，有问题再重新打开
