### ISSUE TITLE
dockerfile构建报错

### ISSUE THREAD

**Issue by huxianguang** [goodrain/rainbond#1423]
**Describe the bug**
dockerfile构建，偶发会报以下错误，dockerfile在项目根路径下，是以源码的方式构建，自动识别的dockerfile类型，经过测试，多个项目只要是dockerfile类型的都会偶发出现问题，成功构建的几率低

**To Reproduce**
dockerfile构建，偶发会报以下错误
dockerfile内容

FROM python:3.6.6

MAINTAINER hxg  <15789762@qq.com>

RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list

RUN apt-get update

RUN pip install --upgrade pip --index-url https://pypi.douban.com/simple

WORKDIR /app

ADD . /app

RUN pip install -r requirements.txt --index-url https://pypi.douban.com/simple

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

**Screenshots**
![image](https://user-images.githubusercontent.com/52129723/200280130-8f36ed8a-39a2-4386-811d-a36799795a4b.png)
**The relevant information:**
 - Rainbond Version v5.9.0-release-aa108188a-2022-10-27-08-allinone
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version v1.19.6

**Comment by yangkaa** [comment]
我这边没有复现出来。大概多少次构建会触发一次呢？是否跟某次 commit 有关？

**Comment by huxianguang** [comment]
从搭建新版本rainbond开始  一共构建过20多次 只一次成功构建  之前在 v5.8.1-f5ce140fa-2022-09-16-02-allinone版本构建一直正常 代码也一直没有改变过  不仅仅这一个项目有问题  只要是dockerfile的都遇到这类问题

**Comment by yangkaa** [comment]
我这边无法复现，你可以加下我的微信，我协助你排查下
<img width="307" alt="image" src="https://user-images.githubusercontent.com/30614084/200470328-555ee062-bc25-4e2b-873e-5130cf1bd4d5.png">

**Comment by yangkaa** [comment]
经排查，有多个构建节点时，构建 Dockerfile 会失败。偶尔会成功。原因是构建的 Pod 未调度到代码所下载的节点。导致无法获取到正确的代码文件。已修复 https://github.com/goodrain/rainbond/pull/1427 

当前临时可用镜像为 `registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-chaos:1423`，该镜像基于 v5.10.0 版本打包

**Comment by huxianguang** [comment]
好的  已经可以了  感谢
