### ISSUE TITLE
建议新增源码构建手动选择语言的功能

### ISSUE THREAD

**Issue by Alex-lsky** [goodrain/rainbond#1426]
![image](https://user-images.githubusercontent.com/59161352/200490274-575b2fc5-e7c2-45b7-97df-2d8fb704de0f.png)，该项目为一个VUE项目，但目前如果项目下有dockerfile则被识别为dockerfile项目，无法更改构建信息

**Comment by lihao6666** [comment]
+1

**Comment by zzzhangqi** [comment]
6.0 版本中已支持选择是 vue 还是 dockerfile
