### ISSUE TITLE
Istio支持

### ISSUE THREAD

**Issue by ZQiannnn** [goodrain/rainbond#143]
能自行整合Istio的插件吗吗？

**Comment by barnettZQG** [comment]
@ZQiannnn 你想使用istio的哪些功能？

**Comment by ZQiannnn** [comment]
感觉Istio的生态会更好


开 2018年10月18日 在 15:43:39, barnettZQG (notifications@github.com) 写到:

@ZQiannnn 你想使用istio的哪些功能？
