### ISSUE TITLE
macbookpro(Intel) 执行快速安装脚本install.sh报错

### ISSUE THREAD

**Issue by William-ZXS** [goodrain/rainbond#1439]
macbookpro(Intel) 2020款，系统版本：Big Sur 11.5.2 执行快速安装命令`curl -o install.sh https://get.rainbond.com && bash ./install.sh`报错。提示Rainbond do not support i386 architecture。

<img width="888" alt="image" src="https://user-images.githubusercontent.com/54169593/202191073-88193bf2-da2b-40f6-a5e4-f00c4aca9dc8.png">
 
 $(arch) 的值是i386, install.sh 脚本对这种情况没有正确处理，应该归于ARCH_TYPE=amd64

**Comment by dazuimao1990** [comment]
> macbookpro(Intel) 2020款，系统版本：Big Sur 11.5.2 执行快速安装命令`curl -o install.sh https://get.rainbond.com && bash ./install.sh`报错。提示Rainbond do not support i386 architecture。
> 
> <img alt="image" width="888" src="https://user-images.githubusercontent.com/54169593/202191073-88193bf2-da2b-40f6-a5e4-f00c4aca9dc8.png">
> 
> $(arch) 的值是i386, install.sh 脚本对这种情况没有正确处理，应该归于ARCH_TYPE=amd64

M1 芯片的 Macbook 在终端开启 Rosetta 的情况下，也会将系统架构识别为 i386 。这会造成最终使用错误的镜像启动 rainbond-dind-allinone 容器。目前看可以加入一些针对 i386 的特殊提示信息。

<img width="260" alt="image" src="https://user-images.githubusercontent.com/33855684/202337557-60ebce5c-a26d-4605-845f-0f8278bea4e2.png">

**Comment by dazuimao1990** [comment]
> macbookpro(Intel) 2020款，系统版本：Big Sur 11.5.2 执行快速安装命令`curl -o install.sh https://get.rainbond.com && bash ./install.sh`报错。提示Rainbond do not support i386 architecture。
> 
> <img alt="image" width="888" src="https://user-images.githubusercontent.com/54169593/202191073-88193bf2-da2b-40f6-a5e4-f00c4aca9dc8.png">
> 
> $(arch) 的值是i386, install.sh 脚本对这种情况没有正确处理，应该归于ARCH_TYPE=amd64



> > macbookpro(Intel) 2020款，系统版本：Big Sur 11.5.2 执行快速安装命令`curl -o install.sh https://get.rainbond.com && bash ./install.sh`报错。提示Rainbond do not support i386 architecture。
> > <img alt="image" width="888" src="https://user-images.githubusercontent.com/54169593/202191073-88193bf2-da2b-40f6-a5e4-f00c4aca9dc8.png">
> > $(arch) 的值是i386, install.sh 脚本对这种情况没有正确处理，应该归于ARCH_TYPE=amd64
> 
> M1 芯片的 Macbook 在终端开启 Rosetta 的情况下，也会将系统架构识别为 i386 。这会造成最终使用错误的镜像启动 rainbond-dind-allinone 容器。目前看可以加入一些针对 i386 的特殊提示信息。
> 
> <img alt="image" width="260" src="https://user-images.githubusercontent.com/33855684/202337557-60ebce5c-a26d-4605-845f-0f8278bea4e2.png">

@William-ZXS 现在你可以重新下载并执行安装脚本了。

**Comment by William-ZXS** [comment]
> 

ok，已经可以了
