### ISSUE TITLE
CONTRIBUTING.md 文件中‘贡献指南’链接错误

### ISSUE THREAD

**Issue by william-zxs** [goodrain/rainbond#1440]
CONTRIBUTING.md 文件中‘贡献指南’链接错误

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/54169593/202220194-c5f1b19f-c635-47d0-89cf-4260bde789ff.png">

正确的地址是否是[贡献指南](https://www.rainbond.com/community/contribution/)？

**Comment by yangkaa** [comment]
是的，也许你可以提交一个 PR 帮我们修复这个问题？

**Comment by William-ZXS** [comment]
> 

可以的

**Comment by William-ZXS** [comment]
> 

已经提交了pr
