### ISSUE TITLE
对接minio应用备份问题

### ISSUE THREAD

**Issue by lihao6666** [goodrain/rainbond#1444]
# 问题描述
搭建了minio服务，使用rainbond对接s3服务，使用应用备份功能，rbd-chaos报403问题，签名错误，使用python 测试minio接口访问正常，怀疑是不是ssl问题，界面没有ssl选项，是否secure的配置
# 详情
![image](https://user-images.githubusercontent.com/36958251/202606471-d476fee1-fc04-4df4-af68-6a3ca4f22a85.png)
![image](https://user-images.githubusercontent.com/36958251/202606560-7d36253a-5668-4fa5-9c4d-4672f99c8257.png)
![image](https://user-images.githubusercontent.com/36958251/202606646-af194e18-5ad4-4f8a-bfc5-c7158047f560.png)
# 版本
v5.10.0-release-ac13ea276-2022-11-09-03-allinone

**Comment by lihao6666** [comment]
minio版本问题，应该是rainbond内部需要适配才行，这边降低minio版本后成功

**Comment by zzzhangqi** [comment]
@lihao6666 什么版本的minio，后续会适配

**Comment by lihao6666** [comment]
> @lihao6666 什么版本的minio，后续会适配

![image](https://user-images.githubusercontent.com/36958251/202957619-fe975878-c79a-4447-aa93-d43d6d92506b.png)
这个版本是OK的，最新的不行
