### ISSUE TITLE
部署老程序，kubernetes不兼容struts1

### ISSUE THREAD

**Issue by bmowang** [goodrain/rainbond#145]
++>Removed: (class java.util.Locale)org.apache.struts.action.LOCALE
ebfee100a92c:W1024 12:39:13.973987       1 reflector.go:323] k8s.io/kubernetes/pkg/proxy/config/api.go:51: watch of *api.Endpoints ended with: too old resource version: 1610240 (1610871)
ebfee100a92c:W1024 13:44:49.007662       1 reflector.go:323] k8s.io/kubernetes/pkg/proxy/config/api.go:51: watch of *api.Endpoints ended with: too old resource version: 1617090 (1617394)

平台日志报错，内容如上，好像是kubernetes不支持太老的struts

**Comment by barnettZQG** [comment]
@bmowang 看起来应该是应用本身的故障。
关于日志：
```
watch of *api.Endpoints ended with: too old resource version: 1610240 (1610871)
```
确实是mesh层打出的日志，这是由于kubernetes的bug产生，但其不影响功能。

**Comment by barnettZQG** [comment]
No feedback, this issue will be closed.
How is there still a problem? Please open it again
