### ISSUE TITLE
组件依赖UI错乱

### ISSUE THREAD

**Issue by lihao6666** [goodrain/rainbond#1450]
# 详情
![image](https://user-images.githubusercontent.com/36958251/202958745-34032dcb-3898-447e-afe7-232094c3f3b9.png)

# 版本
v5.10.0-release-ac13ea276-2022-11-09-03-allinone

**Comment by zzzhangqi** [comment]
能否描述的再具体些

**Comment by lihao6666** [comment]
> 能否描述的再具体些

就是组件名和应用名搞反了，不是组件隶属于应用吗，第一个应该是应用名称，第二是组件名称

**Comment by zzzhangqi** [comment]
> > 能否描述的再具体些
> 
> 就是组件名和应用名搞反了，不是组件隶属于应用吗，第一个应该是应用名称，第二是组件名称

是的，的确反了。感谢反馈

@RainBondsongyg
