### ISSUE TITLE
BUG: http private registry build error

### ISSUE THREAD

**Issue by zzzhangqi** [goodrain/rainbond#1469]
When building with source code, Failed to push to  `HTTP` private repository.

**Comment by zzzhangqi** [comment]
http 私有镜像仓库通过镜像创建组件无法创建，报错如下：
```
info msg="trying next host" error="failed to do request: Head \"https://8081.gr220c2d.sip8tc5m.280440.grapps.cn:80/v2/test/nginx/manifests/latest\": http: server gave HTTP response to HTTPS client" host="8081.gr220c2d.sip8tc5m.280440.grapps.cn:80"
```

底层配置 http 私有镜像仓库，源码构建时无法拉取builder镜像，如下：
![image](https://user-images.githubusercontent.com/39754275/217797471-4356da7a-fbad-4736-a454-942141ef92d6.png)

**Comment by quyuancheng** [comment]
https://github.com/goodrain/rainbond/pull/1555

**Comment by quyuancheng** [comment]
如果您使用的镜像是来自http类型的私有镜像仓库，那么需要在rbdcomponent中配置相关参数，使镜像能够正常构建使用。
具体操作如下步骤：
1、执行 kubectl edit rbdcomponent rbd-chaos -n rbd-system
2、在 spec 下添加 args 参数 insecure-build=true
      
<img width="462" alt="image" src="https://user-images.githubusercontent.com/67988480/219414069-271011cd-515f-4fdf-b7a8-7de7da04fe6a.png">

**Comment by quyuancheng** [comment]
如果您使用的镜像是来自http类型的私有镜像仓库，那么需要在rbdcomponent中配置相关参数，使镜像能够正常构建使用。
具体操作如下步骤：
1、执行 kubectl edit rbdcomponent rbd-chaos -n rbd-system
2、在 spec 下添加 args 参数 insecure-build=true

<img width="412" alt="image" src="https://user-images.githubusercontent.com/67988480/219416075-018c81cb-141c-4e96-866b-15ff0e3bc4d4.png">

**Comment by quyuancheng** [comment]
如果您使用的镜像是来自http类型的私有镜像仓库，那么需要在rbdcomponent中配置相关参数，使镜像能够正常构建使用。
具体操作如下步骤：
1、执行 kubectl edit rbdcomponent rbd-chaos -n rbd-system
2、在 spec 下添加 args 参数 kaniko-args=--insecure=true,--insecure-pull=true

<img width="475" alt="spiversion rainbond  iov1a Lohat" src="https://user-images.githubusercontent.com/67988480/219645992-63b0af71-e40a-4cf5-8551-e579954f508d.png">
