### ISSUE TITLE
unable to load other apps' s shared mount directory when click mounting shared volume

### ISSUE THREAD

**Issue by justbeay** [goodrain/rainbond#147]
- Rainbond 3.7.2
- CentOS 7.5
As the title says, app' s shared mount directory cannot be listed when trying to add in another app' s setting page, is there any condition needed when sharing mount directory between different directory

**Comment by barnettZQG** [comment]
@justbeay this Issue is incredible. try to upgrade rbd-app-ui

**Comment by barnettZQG** [comment]
No feedback, this issue will be closed.
How is there still a problem? Please open it again
