### ISSUE TITLE
查看用户详情提示服务端异常

### ISSUE THREAD

**Issue by lihao6666** [goodrain/rainbond#1475]
# 描述
在平台管理用户管理界面，点击用户名字查看详细信息，报服务端异常，v.5.10.0版本问题存在，5.10.1仍然存在
# 详情
报错如下
![image](https://user-images.githubusercontent.com/36958251/206382337-32e3f61f-e70b-4799-9bd3-b787b20a9859.png)
后端console日志如下:
![image](https://user-images.githubusercontent.com/36958251/206383093-6ee35366-761a-4cbc-bd09-d27846dcb9b2.png)

# 版本
v5.10.1-release-af00ee8d7-2022-12-01-14-allinone

**Comment by zzzhangqi** [comment]
临时解决：

`vim console/services/team_services.py`
```
401行改成：
app_count = group_repo.get_tenant_region_groups_count(tenant.tenant_id, info.get("region", ""))
```

**Comment by ZhangSetSail** [comment]
在新版本修复https://github.com/goodrain/rainbond-console/pull/1235
