### ISSUE TITLE
建议允许自定义imageHub的账号密码为空

### ISSUE THREAD

**Issue by cwq108** [goodrain/rainbond#1478]
建议允许自定义imageHub的账号密码为空,
当前在使用helm配置安装 rainbond时,将imageHub账号密码设置为空,无法正常启动
kubectl logs rainbond-operator-5fc7797669-787sw -n rbd-system
First login failed [<nil>], login insecure repository hub.docker.local with username  and password 

![image](https://user-images.githubusercontent.com/11314315/206469325-6a0026e1-f1ba-4f05-92d9-e11b15e9811a.png)

**Comment by zzzhangqi** [comment]
当镜像仓库没有密码时，可以填写任意账号和密码让 `rainbond-operator` 通过校验
