### ISSUE TITLE
Duplicate page items when update component with click command button

### ISSUE THREAD

**Issue by epower-cloud** [goodrain/rainbond#1479]
May be some frontend bugs exists in current version:5.10.0，we can recurrent that by click component update button like this:
![image](https://user-images.githubusercontent.com/53629806/206618767-2359920a-6bfd-43df-91e6-0d6a58a4ac5c.png)

Normally,after click will show result on current page,only update some info.but after clicked, I see duplicated page body appears at below of current part that was clicked.
Like this:

![image](https://user-images.githubusercontent.com/53629806/206619292-b49cf2fb-249b-4053-938f-99c8f9845924.png)

**Comment by yangkaa** [comment]
Thank you for your feedback. It seems that this is indeed a problem and we will fix it in the next version.
