### ISSUE TITLE
clusterstatus: unhealthy             | There is a service exception in the cluster

### ISSUE THREAD

**Issue by zmyer** [goodrain/rainbond#148]
If you want to report a bug or advice, please provide the following information and try to describe your issue in English, If it's a question of use,please read the [documentation](https://www.rainbond.com/docs/stable/) or browse the [community](https://t.goodrain.com/)
manage01:K8s node status is NotReady/
- [ ] Rainbond versions(eg. grctl version)
3.7.2
- [ ] Kubernetes versions(If you use your own cluster)

- [ ] Operating system and kernel

- [ ] Provider(Aliyun,VirtualBox,...)

- [ ] Install details(Online/Offline,SingleNode/HA)

**Comment by ysicing** [comment]
```
# check node 
grctl node list
grctl node get <node_uid>
```

**Comment by barnettZQG** [comment]
No feedback, this issue will be closed.
How is there still a problem? Please open it again
