### ISSUE TITLE
.net core通过源代码构建组件失败，提示如下：

### ISSUE THREAD

**Issue by SeptemberTwelve** [goodrain/rainbond#1483]
![lQLPJwplB5lbTYDMgM0Du7AEqB2bbUjTxQOWjx73gEkA_955_128](https://user-images.githubusercontent.com/35290123/207781770-7f664273-053b-4eb5-b5e4-c008e9d50d14.png)
用docker镜像部署.net core6项目是正常的。

**Comment by yangkaa** [comment]
Rainbond 是什么版本呢？使用官方Demo 通过源码构建其他语言的项目，如 maven 是否会出现类似问题？

**Comment by SeptemberTwelve** [comment]
rainbond版本是v5.10.1-release-af00ee8d7-2022-12-01-14-allinone，用官方Demo 
![image](https://user-images.githubusercontent.com/35290123/208336376-3406298c-400b-4e69-81b3-d1508de78dd4.png)构建成功了。

**Comment by sanglirong** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> The rainbow version is v5.10.1-release-af00ee8d7-2022-12-01-14-allinone, use the official Demo ![image](https://user-images.githubusercontent.com/35290123/208336376-3406298c-400b-4e69-81b3-d1508de78dd4.png) was built successfully.

上面是NETCORE 源码部署你这个是JAVA 不一样的，官方NETCore是有问题的。

**Comment by ZhangSetSail** [comment]
下面是netcore源码构建的修改，上面那个引用错了。

**Comment by yangkaa** [comment]
If there are any problems, please reopen it.
