### ISSUE TITLE
运行异常的组建删除不了

### ISSUE THREAD

**Issue by sanglirong** [goodrain/rainbond#1489]
![image](https://user-images.githubusercontent.com/46233444/209489324-833c0ea4-2de1-4f2f-9725-e593b197040f.png)
![image](https://user-images.githubusercontent.com/46233444/209489344-a9473aae-d2db-499d-ab32-556e461b31a4.png)
**一直构建不成功**
![image](https://user-images.githubusercontent.com/46233444/209489399-3046f50e-8dff-476c-8774-3c36e636697e.png)
![image](https://user-images.githubusercontent.com/46233444/209489417-07812259-2c13-4220-a703-5fe04b570de5.png)
停也停不了，删也删不掉

**Comment by yangkaa** [comment]
这个问题可能是由于控制台 sqlite 数据库锁定问题，导致了控制台和集群数据不一致。应该可以用以下方案解决。

1. 先安装 grctl 命令，参考 https://www.rainbond.com/docs/ops-guide/tools/grctl

2. 执行 `grctl service stop <service_alias> -t <tenant_name>`

3. 再次执行删除

备注：`service_alias` 和 `tenant_name` 的取值从路由中获取，在应用页面，选择`列表`，找到你要删除的组件，你的环境中就是那个 `Worker3` 的组件，右键复制链接地址。你能得到类似的链接地址：

`http://192.168.0.38:7070/#/team/eltg4qjc/region/123/components/grd2969d/overview`，

这个地址中参数对应关系如下：

`http://192.168.0.38:7070/#/team/<tenant_name>/region/<region_name>/components/<service_alias>/overview`。

**Comment by yangkaa** [comment]
Fixed in version 5.11.0
