### ISSUE TITLE
快速体验过程竟然需要完整填写个人隐私？

### ISSUE THREAD

**Issue by geekyouth** [goodrain/rainbond#1504]
**Describe the bug**
快速体验，打开 WEBUI，需要填写一堆隐私信息，目的是什么？如何绕过？？？

**To Reproduce**
```
docker run -d -p 7070:7070 \
--name=rainbond-allinone --restart=always \
-v ~/.ssh:/root/.ssh \
-v ~/rainbonddata:/app/data \
registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.10.1-release-allinone
```

**Screenshots**
![image](https://user-images.githubusercontent.com/12899262/210468418-0984487d-d5b0-4773-b65c-a25d7ccb0ae4.png)

**The relevant information:**
 - Rainbond Version: registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.10.1-release-allinone
 - Browser: chrome
 - Kubernetes version null

**Comment by geekyouth** [comment]
![image](https://user-images.githubusercontent.com/12899262/210469055-f01b89b6-9d27-458d-a65b-dad2dd1020f8.png)
文档中只字不提关于隐私收集的内容？？？有什么不方便公开的细节吗？

**Comment by zzzhangqi** [comment]
注册信息可以任意填写

注册这里的确收集了注册信息，也是为了优化安装体验

代码都是开源的，随便看
