### ISSUE TITLE
[ERROR] localhost [get] /app/ui/console/views/public_areas.py:137 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by mumudadi** [goodrain/rainbond#1508]
离线安装成功后，应用市场安装yapi
![3c84584b98011a82fd062f7cc154d3c](https://user-images.githubusercontent.com/31280692/210708040-3e07a6c0-d31d-434e-988c-cfb750458009.png)

**Comment by ZhangSetSail** [comment]
这个问题今天下午已经修改，临时解决办法是按照这个pr进入容器找到对应的文件进行修改
https://github.com/goodrain/rainbond-console/pull/1243
