### ISSUE TITLE
已经配置了外部数据库配置，rbd-ui还是会找rbd-db这个pod

### ISSUE THREAD

**Issue by zhishiguai** [goodrain/rainbond#1509]
执行下面命令后
grctl migrate -p 7071 -r 1 \
-i registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.10.1-release-allinone \
-e MYSQL_HOST=127.0.0.1 \
-e MYSQL_PORT=3306 \
-e MYSQL_PASS=123456 \
-e MYSQL_DB=console

rbd-ui还是会找rbd-db，报错get db info: secret rbd-db/rbd-system not fount: Secret "rbd-db" not found

**Comment by ZhangSetSail** [comment]
感谢您的反馈，这个问题已修改：https://github.com/goodrain/rainbond-operator/pull/183
临时解决办法可以更换operator的镜像：registry.cn-hangzhou.aliyuncs.com/zhangqihang/operator:migration_failed

**Comment by ZhangSetSail** [comment]
临时操作详细步骤：
`kubectl edit deployment rainbond-operator -nrbd-system`
找到 image: 修改后面的内容为 registry.cn-hangzhou.aliyuncs.com/zhangqihang/operator:migration_failed
<img width="786" alt="image" src="https://user-images.githubusercontent.com/101104760/211508196-c550f1d1-4d06-484f-945b-4ea4d8431bec.png">

**Comment by zhishiguai** [comment]
执行完修改以后，重启rainbond-operator  pod 然后在执行
grctl migrate -p 7071 -r 1
-i registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.10.1-release-allinone
-e MYSQL_HOST=127.0.0.1
-e MYSQL_PORT=3306
-e MYSQL_PASS=123456
-e MYSQL_DB=console
是么？

**Comment by zhishiguai** [comment]
> 临时操作详细步骤： `kubectl edit deployment rainbond-operator -nrbd-system` 找到 image: 修改后面的内容为 registry.cn-hangzhou.aliyuncs.com/zhangqihang/operator:migration_failed <img alt="image" width="786" src="https://user-images.githubusercontent.com/101104760/211508196-c550f1d1-4d06-484f-945b-4ea4d8431bec.png">

执行完修改以后，重启rainbond-operator pod 然后在执行
grctl migrate -p 7071 -r 1
-i registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.10.1-release-allinone
-e MYSQL_HOST=127.0.0.1
-e MYSQL_PORT=3306
-e MYSQL_PASS=123456
-e MYSQL_DB=console
是这样么？

**Comment by ZhangSetSail** [comment]
此问题是因为grctl工具未更新，目前已更新，可参考文档重新安装：https://www.rainbond.com/docs/ops-guide/tools/grctl/

**Comment by yangkaa** [comment]
Fixed in version 5.11.0
