### ISSUE TITLE
从镜像构建时能否支持in-secure registry？

### ISSUE THREAD

**Issue by iwin4aids** [goodrain/rainbond#151]
If you want to report a bug or advice, please provide the following information and try to describe your issue in English, If it's a question of use,please read the [documentation](https://www.rainbond.com/docs/stable/) or browse the [community](https://t.goodrain.com/)

- [ 3.7.2 ] Rainbond versions(eg. grctl version)

- [ ] Kubernetes versions(If you use your own cluster)

- [centos7.5/kernel 3.10 ] Operating system and kernel

- [VMware Fusion] Provider(Aliyun,VirtualBox,...)

- [Offline] Install details(Online/Offline,SingleNode/HA)

如题，目前我的私有registry使用harbor http模式，docker默认pull使用https api进行拉取，这里感觉有些不便，是否可以支持in-secure registry？

**Comment by ysicing** [comment]
可以修改管理节点docker的配置文件(`/opt/rainbond/envs/docker.sh`),添加`--insecure-registry`

**Comment by iwin4aids** [comment]
> 可以修改管理节点docker的配置文件(`/opt/rainbond/envs/docker.sh`),添加`--insecure-registry`

感谢回复~非常迅速 赞👍
