### ISSUE TITLE
应用设置伸缩会出现这个报错，自动伸缩失败

### ISSUE THREAD

**Issue by loyabe** [goodrain/rainbond#1514]
failed to get memory utilization: unable to get metrics for resource memory: unable to fetch metrics from resource metrics API: an error on the server ("Internal Server Error: \"/apis/metrics.k8s.io/v1beta1/namespaces/877e0d19c7d94b1980d440e73f253fe3/pods?labelSelector=name%3Dgre8be13%2Cservice_id%3D2187ccadb9e5186d8303979a42e8be13%2Ctenant_id%3D877e0d19c7d94b1980d440e73f253fe3\": the server could not find the requested resource") has prevented the request from succeeding (get pods.metrics.k8s.io)

<img width="931" alt="1182e36268438a75481679258d40c56" src="https://user-images.githubusercontent.com/2858525/212004167-dd2a0442-bad1-4e20-b1a9-66c962f5bda4.png">

![image](https://user-images.githubusercontent.com/2858525/212004244-d4b916e7-61dd-44b3-82ad-9fdd2fdb8b53.png)

请问这个要怎么处理

**Comment by yangkaa** [comment]
K8s 版本和 Rainbond 版本分别是什么？你是否在集群中有单独部署过 metrics-server？

你可以执行 `kubectl get --raw /apis/metrics.k8s.io/v1beta1` 查看输出，如果找不到对应的资源，可以执行 `kubectl get po -A | grep metrics-server` 查看是否有对应的部署？

如果没有，则需要部署 metrics-server，有的话，则查看其日志

**Comment by loyabe** [comment]
k8s  v1.22.12 
rainbond 是最新版本 

![image](https://user-images.githubusercontent.com/2858525/212800607-b0c5cc68-461f-4cac-a9e0-7c28b937dd69.png)
![image](https://user-images.githubusercontent.com/2858525/212800691-561fb692-9c04-4bb6-9126-056bae8d3604.png)

**Comment by loyabe** [comment]
![image](https://user-images.githubusercontent.com/2858525/212800859-def291cf-d261-47b1-bc75-7d8e3f6e63fc.png)

**Comment by yangkaa** [comment]
metrics-server 升级下到 0.4.x 以上。Rainbond 安装的 metrics-server 应该是 0.3.6，根据[官方文档](https://github.com/kubernetes-sigs/metrics-server#compatibility-matrix)，0.3.x 版本不支持 1.22 的K8s
