### ISSUE TITLE
已有的k8s项目导入 rainbond 导入失败

### ISSUE THREAD

**Issue by loyabe** [goodrain/rainbond#1521]
**Describe the bug**
之前用别的部署的项目，现在转移到rainbond 上
安装ok后使用k8s导入。选择命名空间就会一直在等待

![image](https://user-images.githubusercontent.com/2858525/212801326-1a6911d3-5fd7-4f10-ba5f-51a303f976d5.png)
pod yaml
：apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.233.92.113/32
    cni.projectcalico.org/podIPs: 10.233.92.113/32
    kubesphere.io/containerSecrets: '{"container-12xw0s":"ali"}'
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2023-01-13T15:37:08Z"
  generateName: pickta-admin-v1-8d698dd55-
  labels:
    app: pickta-admin
    app.kubernetes.io/name: pickta-admin
    app.kubernetes.io/version: v1
    pod-template-hash: 8d698dd55
    version: v1
  name: pickta-admin-v1-8d698dd55-z25qw
  namespace: prod
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: pickta-admin-v1-8d698dd55
    uid: c1773140-2eff-4108-b219-e020cf309768
  resourceVersion: "10465694"
  uid: 7f27fe52-6c22-42c0-819e-ee56b8230030
spec:
  affinity: {}
  containers:
  - image: registry.cn-shanghai.aliyuncs.com/miyamama_mh/pickta-admin:prod-1.0-SNAPSHOT-20221128061024
    imagePullPolicy: IfNotPresent
    name: container-12xw0s
    ports:
    - containerPort: 9103
      name: http-9103
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-b9t96
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: ali
  nodeName: node3
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-b9t96
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-01-13T15:37:08Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-01-16T04:27:53Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-01-16T04:27:53Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-01-13T15:37:08Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://1cf02a51904d432bdfc1087ea316fca828ca2c6a9310ed95bb905b657999b785
    image: registry.cn-shanghai.aliyuncs.com/miyamama_mh/pickta-admin:prod-1.0-SNAPSHOT-20221128061024

这是控制台打印的日志
[goodrain.log](https://github.com/goodrain/rainbond/files/10430779/goodrain.log)

**Screenshots**

**The relevant information:**
 - Rainbond Version [e.g. 5.2.0]
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version [e.g 1.16.3]

**Comment by ZhangSetSail** [comment]
接口请求超时了，设置的超时时间过短，感谢反馈下个版本会优化。
