### ISSUE TITLE
rbd-monitor申请1G存储满了后出错

### ISSUE THREAD

**Issue by zhishiguai** [goodrain/rainbond#1525]
集群使用CEPH做存储，存储集群空间未满，rbd-monitor满了后不会自动扩容，导致异常，报错：
write /prometheusdata/wal/00000008: disk quota exceeded"
<img width="972" alt="截屏2023-01-13 10 16 49" src="https://user-images.githubusercontent.com/39476487/212860197-5e83a6a2-4ae9-48f4-9737-a65064a3cc97.png">
<img width="343" alt="截屏2023-01-13 10 27 31" src="https://user-images.githubusercontent.com/39476487/212860195-2cd027d1-78c2-45b8-9679-80b2daeb65ed.png">
<img width="1401" alt="截屏2023-01-17 17 26 10" src="https://user-images.githubusercontent.com/39476487/212860196-be136234-1201-4229-b98b-256c39cd859a.png">

**Comment by quyuancheng** [comment]
该问题已在5.13.0版本中修复
