### ISSUE TITLE
node.js项目从源码构建的问题和建议

### ISSUE THREAD

**Issue by iwin4aids** [goodrain/rainbond#153]
If you want to report a bug or advice, please provide the following information and try to describe your issue in English, If it's a question of use,please read the [documentation](https://www.rainbond.com/docs/stable/) or browse the [community](https://t.goodrain.com/)

- [3.7.2 ] Rainbond versions(eg. grctl version)

- [ ] Kubernetes versions(If you use your own cluster)

- [centos7.5 / 3.10 ] Operating system and kernel

- [Vmware fusion] Provider(Aliyun,VirtualBox,...)

- [offline] Install details(Online/Offline,SingleNode/HA)

应用从源码构建的方式感觉还是有很多不足，难以适配目前复杂的编译、运行环境变化。
以node.js应用为例：
我查了下从node源码的构建过程好像是从semver.io查询下载对应版本的node和npm环境
我的应用基于vue-cli3要求node版本最少是8.11以上，但是这个版本无论如何无法下载
更高版本如10.11.x也是一样，而官方demo里面使用的版本实在太低了，那个版本是可以的
希望能够解决一下这个问题，过程也非常好重现

另外现在一般很多项目使用yarn代替npm，希望也能支持yarn的启动

比如我在Procfile里面写的：
`web: npm run serve`
替换成yarn
`web: yarn serve`
提示未安装yarn，希望能默认把yarn和npm都支持一下，如果实在不行只能从镜像构建了，这种方式比较万能，但是就是需要自己先编译构建然后打包，或许期待5.0大版本能支持类似pipeline的能力。

以下是我的部署构建日志：

部署失败(Build app version from source code failure)@admin收起
Info日志Debug日志Error日志
14:23:00builder:
14:23:00Build app version from source code failure
14:23:00Build app version from source code failure,Run build return 2
14:23:00builder:
14:23:00builder: Goodrain.
14:23:00builder: Love,
14:23:00builder:
14:23:00builder: http://doc.goodrain.com/usage/181950
14:23:00builder: If you're stuck, please submit a ticket so we can help:
14:23:00builder:
14:23:00builder: http://doc.goodrain.com/usage/181950
14:23:00builder: We're sorry this build is failing! You can troubleshoot common issues here:
14:23:00builder:
14:23:00builder:-----> Build failed
14:23:00builder:
14:23:00builder: tar: Error is not recoverable: exiting now
14:23:00builder: tar: Child returned status 1
14:23:00builder: gzip: stdin: not in gzip format
14:22:59builder: NPM_CONFIG_PRODUCTION=true
14:22:59builder: Downloading and installing node 8.11.0...
14:22:59builder: NPM_CONFIG_LOGLEVEL=error
14:22:59builder:
14:22:59builder:
14:22:59builder: engines.node (package.json): 8.11.0
14:22:59builder:-----> Creating runtime environment
14:22:59builder: engines.npm (package.json): 5.10.x
14:22:59builder: NODE_ENV=production
14:22:59builder: NODE_MODULES_CACHE=true
14:22:59builder:
14:22:59builder:-----> Installing binaries
14:22:59Start compiling the source code

**Comment by ysicing** [comment]
目前node版本是从`https://nodebin.herokai.com`获取node,yarn版本
源码构建方面会优化,升级node版本，考虑支持yarn

**Comment by iwin4aids** [comment]
> 目前node版本是从`https://nodebin.herokai.com`获取node,yarn版本
> 源码构建方面会优化,升级node版本，考虑支持yarn

嗯，yarn其实还好，npm也可以替代，但是支持的node版本希望能尽快升级下

**Comment by ysicing** [comment]
@iwin4aids  近期会更新node版本
