### ISSUE TITLE
Exception components cannot be removed

### ISSUE THREAD

**Issue by lihao6666** [goodrain/rainbond#1539]
**Exception components cannot be removed**
When an error occurs in the creation of the component, re-entering the component shows that it has been run, and the cancellation of the creation fails, prompting that the component needs to be closed

**To Reproduce**
1. Create redis component from docker-hub
2. Enter the details, build directly without selecting the component type(double click)
3. Prompt data center error, and then re-enter the application can not cancel the creation

**Screenshots**
![image](https://user-images.githubusercontent.com/36958251/217451921-efee54d4-10de-4a1c-91e5-4bdab460286b.png)
![image](https://user-images.githubusercontent.com/36958251/217452266-83648c5c-69e9-410b-9605-de81a0bbb8df.png)
![1675824806965_60A62C43-0898-439a-861F-9BFEFE6C05C3](https://user-images.githubusercontent.com/36958251/217452543-7b3736fe-7d1a-4999-b88f-47393ed0644d.png)

**The relevant information:**
 - Rainbond Version [5.11.0]
 - Browser [chrome]
 - Kubernetes version [1.19.6]

**Comment by yangkaa** [comment]
Thanks for the feedback, we will verify the repair in time.
