### ISSUE TITLE
应用构建操作日志界面的时间显示bug（Safari浏览器）

### ISSUE THREAD

**Issue by iwin4aids** [goodrain/rainbond#154]
If you want to report a bug or advice, please provide the following information and try to describe your issue in English, If it's a question of use,please read the [documentation](https://www.rainbond.com/docs/stable/) or browse the [community](https://t.goodrain.com/)

- [ 3.7.2 ] Rainbond versions(eg. grctl version)

- [ ] Kubernetes versions(If you use your own cluster)

- [ centos7.5 / 3.10 ] Operating system and kernel

- [ VMware Fusion ] Provider(Aliyun,VirtualBox,...)

- [ offline ] Install details(Online/Offline,SingleNode/HA)

一个小issue，很好复现，3.7版本都有这个问题····历史动作的时间戳全是NaN
<img width="647" alt="wechatimg22" src="https://user-images.githubusercontent.com/16768783/48181824-f666cd80-e363-11e8-9237-63f6ebec71fa.png">

**Comment by ysicing** [comment]
请问火狐浏览器吗

**Comment by iwin4aids** [comment]
> Firefox浏览器么

Safari 版本 12.0.1 (14606.2.104.1.1)

**Comment by iwin4aids** [comment]
> Firefox浏览器么

经测试和浏览器有关，chrome下显示ok 我更新一下标题
