### ISSUE TITLE
springboot应用部署到rainbond上无法连接postgreSQL数据库:服务器不支援 SSL 连线。

### ISSUE THREAD

**Issue by dldahua** [goodrain/rainbond#1540]
**Describe the bug**
本地或者部署到其他服务上的springboot应用可以正常访问到postgreSQL数据库,但是同样的配置与环境部署到rainbond(v5.4.0-release) 上就展示错误:

**PoolInitializationException: Failed to initialize pool: 服务器不支援 SSL 连线。**

连接地址也添加了ssl=false; 数据库ssl也禁了;查询很多地方也没有提示:服务器不支援 SSL 连线。
麻烦看看是否服务器对SSL做了什么限制呢?

![Uploading 848eddb45883c0b15050cd3a50a0208.png…]()

**Comment by dldahua** [comment]
测试demo: https://gitee.com/kpcode/pgtest1.git

**Comment by dldahua** [comment]
@zzzhangqi Java demo: https://gitee.com/kpcode/pgtest1.git  里面有配置好的测试数据库

**Comment by zzzhangqi** [comment]
v6 版本已对此类问题进行整体升级并解决，请再次尝试！
