### ISSUE TITLE
Connect Uwsgi Error under Nginx(ServiceMesh)

### ISSUE THREAD

**Issue by lihao6666** [goodrain/rainbond#1541]
**Describe the bug**
After updating rainbow to 5.11.0, the original project (ServiceMesh) had an interface access error problem. After checking the details, it was found that the previous uwsgi service could not be connected through Nginx. Then use the 5.10.0 version(another server) to run normally, and the configuration has not been modified。
**Temporary solution**
Open the port for external services, and then modify the environment variable address to solve the problem
**Screenshots**
![image](https://user-images.githubusercontent.com/36958251/217477752-9d3e3cca-1d07-4c93-b94a-faf26c9e08a8.png)
![image](https://user-images.githubusercontent.com/36958251/217478147-e4ed7a9a-684c-46d9-a54b-4463c51f9918.png)
![image](https://user-images.githubusercontent.com/36958251/217478895-b0b94051-cb2b-44bd-92ba-c0d8c06f198c.png)

**The relevant information:**
 - Rainbond Version [5.11.0]
 - Browser [chrome ]
 - Kubernetes version [e.g 1.19.6]

**Comment by zzzhangqi** [comment]
5.11.0 The default governance mode of the application is k8s native mode, so the connection mode of 127.0.0.1 is unavailable

Change to ${XXX_HOST} both governance modes are available, which is the best use

**Comment by lihao6666** [comment]
> 5.11.0 The default governance mode of the application is k8s native mode, so the connection mode of 127.0.0.1 is unavailable
> 
> Change to ${XXX_HOST} both governance modes are available, which is the best use
   Now I am using the ServiceMesh mode. The configuration in the screenshot above still cannot be used. You must open the port for external access and then configure the specific IP+Host before it can be used.
    I also tried to use the ServiceMesh (127.0.0.1) mode in other projects, all of which are connected normally, only uwsgi cannot connect (TCP)

**Comment by zzzhangqi** [comment]
So you are saying that 127.0.0.1 mode is not available?
Does the k8s mode work properly

**Comment by lihao6666** [comment]
> So you are saying that 127.0.0.1 mode is not available?
> Does the k8s mode work properly

Yes, the 127.0.0.1 mode for uwsgi (tcp) cannot be used, and other common http connections are normal. I have not tried the k8s mode because the previous projects are based on ServiceMesh configuration

**Comment by zzzhangqi** [comment]
> > So you are saying that 127.0.0.1 mode is not available?
> > Does the k8s mode work properly
> 
> Yes, the 127.0.0.1 mode for uwsgi (tcp) cannot be used, and other common http connections are normal. I have not tried the k8s mode because the previous projects are based on ServiceMesh configuration

Can you give me an example project? I'll try to repeat the error
