### ISSUE TITLE
导入k8s的yaml时，containers.env 自定义环境变量导入不正确，会丢失一部分

### ISSUE THREAD

**Issue by thomascatlee** [goodrain/rainbond#1542]
大致是隔一条丢一条的样子。

**Comment by yangkaa** [comment]
能否提供一个可复现的yaml文件呢

**Comment by thomascatlee** [comment]
我又试了一下，是一部分定义在环境配置的自定义环境变量里，另一部分在其他设置的kubernetes属性的env里，以yaml形式存储。所以自定义环境变量里就不全。不知道为啥这样。
另外导入yaml时，lables会丢，要自己重新手工在kubernetes属性里面手工添加。

**Comment by yangkaa** [comment]
因为在组件的环境变量配置中，目前只支持键值对类型的环境变量。如果使用了 envFrom 这类方式，就无法正常支持，所以会放在其他设置中。

labels 全部都会丢吗

**Comment by thomascatlee** [comment]
spec.template.metadata.labels 下面的都会丢。不管导入的是Deployment还是StatefulSet

**Comment by yangkaa** [comment]
v5.12 中已修复
