### ISSUE TITLE
Rainbond on k3s（default sc is rook-cephfs） cann't mount the volume

### ISSUE THREAD

**Issue by jameswangjz** [goodrain/rainbond#1545]
**Describe the bug**
1、Rainbond on k3s（default sc is rook-cephfs） cann't  mount the volume
2、Rainbond on k3s（default sc is rook-cephfs） cann't  fount the rook-cephfs  sc

**To Reproduce**
1. deploy k3s （single host -172.25.5.108、cluster+ceph--172.24.4.155-172.24.4.158）and ceph (reference by:https://note.youdao.com/s/ZLaETVnV)
2. deploy rainbond on the singlehost k3s （reference by:https://note.youdao.com/s/86umr0vn），than add the cluster (k3s-cluster-155) with parameters: --set Cluster.RWX.enable=true --set Cluster.RWX.config.storageClassName=rook-cephfs --set Cluster.RWO.enable=true --set Cluster.RWO.storageClassName=rook-cephfs
3. deploy a app on the k3s-cluster-155 cluster: refercen by:https://www.rainbond.com/docs/quick-start/getting-started
4. the status of mysql component is starting，the status of the instance is not ready。
![image](https://user-images.githubusercontent.com/33087032/218352247-45369bef-c751-473f-bc8e-6faabb11836d.png)
![image](https://user-images.githubusercontent.com/33087032/218352325-6623a552-38fa-4ca0-aaaa-3d6d5ab8e5e8.png)
5. the error in logs of rbd-worker is:
![image](https://user-images.githubusercontent.com/33087032/218352675-24814d87-bd28-4a02-a333-3c6fc14b9ce2.png)，so we change the storage_class_detail attribution by: alter table tenant_services_volume_type  modify storage_class_detail varchar(8192); ,the we can see the rook-cephfs in table tenant_services_volues_type
![image](https://user-images.githubusercontent.com/33087032/218354126-d782a621-9fc7-4481-b2be-8390b275963a.png)
and we can see the rook-ceph sc on the web
![image](https://user-images.githubusercontent.com/33087032/218354221-00048ace-fd4e-4a28-aef8-9ac8a20a0020.png)
but the status of volume is unmount
![image](https://user-images.githubusercontent.com/33087032/218354777-0fd65e06-ab47-4910-9d73-8ec4685291af.png)

6.
cat << EOF | kubectl create -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storagetest11
  namespace: bb382d68f0284280acacd9ffca6823c5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rainbondsssc
EOF

the error log of rbd-worker likes this:
time="2023-02-13T13:48:20+08:00" level=info msg="provision \"bb382d68f0284280acacd9ffca6823c5/storagetest11\" class \"rainbondsssc\": started"
time="2023-02-13T13:48:20+08:00" level=info msg="Event(v1.ObjectReference{Kind:\"PersistentVolumeClaim\", Namespace:\"bb382d68f0284280acacd9ffca6823c5\", Name:\"storagetest11\", UID:\"9f370af3-d4a8-400d-8ed6-6d61d54941d8\", APIVersion:\"v1\", ResourceVersion:\"3214286\", FieldPath:\"\"}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim \"bb382d68f0284280acacd9ffca6823c5/storagetest11\""
time="2023-02-13T13:48:20+08:00" level=warning msg="Retrying syncing claim \"bb382d68f0284280acacd9ffca6823c5/storagetest11\" because failures 0 < threshold 15"
E0213 13:48:20.664989       1 controller.go:693] error syncing claim "bb382d68f0284280acacd9ffca6823c5/storagetest11": failed to provision volume with StorageClass "rainbondsssc": can not parse volume id
time="2023-02-13T13:48:20+08:00" level=info msg="Event(v1.ObjectReference{Kind:\"PersistentVolumeClaim\", Namespace:\"bb382d68f0284280acacd9ffca6823c5\", Name:\"storagetest11\", UID:\"9f370af3-d4a8-400d-8ed6-6d61d54941d8\", APIVersion:\"v1\", ResourceVersion:\"3214286\", FieldPath:\"\"}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass \"rainbondsssc\": can not parse volume id"

**Screenshots**

**The relevant information:**
 - Rainbond Version [v5.11.0-release-1340c6c32-2023-02-01-06-allinone]
 - k3s [v1.25.5+k3s2]
 - ceph [v1.10.8]
 - Browser [版本 109.0.5414.121（正式版本） （64 位）]
 - os/kernal:Centos7.9/3.10.0-957.el7.x86_64

**Comment by ZhangSetSail** [comment]
你的第一个问题字短长度过短已经修改，第二个问题看起来不是 Rainbond 的问题，可参考https://github.com/ceph/ceph-csi/issues/3929
同时支持了共享存储自定义存储。详细使用方式：
1. 等待 Rainbond v5.14.3 版本的发布后升级。
2. 确定自定义存储的 storageclass 名称。
3. 编辑 rbdcomponent  类型资源 的 rbd-worker
```
kubectl edit rbdcomponent rbd-worker -nrbd-system
```
spec字段中添加如下行
```
spec:
  args:
  - --shared-storageclass=你的自定义存储的storageclass名称
```
