### ISSUE TITLE
关于 v5.11.0 版本健康检测配置为 重启 时 滚动更新无效的问题

### ISSUE THREAD

**Issue by hanxinhisen** [goodrain/rainbond#1548]
版本 v5.11.0-release-1340c6c32-2023-02-01-06-allinone ,可能之前版本也有这个问题

健康检测改为 重启 时，更新实例时，不是滚动更新。 改为 下线 模式时，滚动更新正常。

![image](https://user-images.githubusercontent.com/7082486/218629843-f7cb1129-619c-47cb-8d78-c5559b595100.png)

**Comment by yangkaa** [comment]
`健康检测改为 重启 时，更新实例时，不是滚动更新` 是什么意思呢？

我尝试过以下四种情况，都是没有问题的。

1. 组件健康检测设置为重启，然后再启动组件，再进行更新，有滚动更新的流程。
2. 组件健康检测设置为下线，然后再启动组件，再进行更新，有滚动更新的流程。
3. 组件健康检查先设置为下线，启动组件，再调整为重启，再进行更新，有滚动更新的流程。
4. 组件健康检查先设置为重启，启动组件，再调整为下线，再进行更新，有滚动更新的流程。

**Comment by Wildmanli** [comment]
复现步骤：
1、选择一个启动时间相对较长的应用（例如：平均4分钟启动完成）
2、健康检查配置信息：
（1）初始等待时间：240秒（保持与应用平均启动时长接近）
（2）检测间隔时间：3秒
（3）检测超时时间：20秒
（4）连续成功次数：1
（5）不健康处理方式：重启
![image](https://github.com/goodrain/rainbond/assets/31447317/acacd286-71e6-48a8-9283-8e71dc0a22c1)
3、当前运行实例：1个运行中
![image](https://github.com/goodrain/rainbond/assets/31447317/32215bc6-6b39-429f-a953-b8bd41f9e534)
4、点击“更新（滚动）”：可以发现1秒钟完成了组件升级，但是应用实际上还处于启动中，无法正常提供服务
![image](https://github.com/goodrain/rainbond/assets/31447317/b9c453b0-473a-4ca0-a9c7-93901f34a958)
![image](https://github.com/goodrain/rainbond/assets/31447317/ebe1a096-3f19-4e96-9879-eb1c475cbd43)

**Comment by yangkaa** [comment]
这部分暂时考虑增加K8s属性的配置，在K8s属性中配置的优先级比界面配置优先级高。计划在 5.15.3 或 5.16 版本优化

**Comment by ZhangSetSail** [comment]
该问题在5.17版本已经通过支持高级属性解决，所以我将关闭这个问题，如果问题依然存在，可以随时将它打开。
