### ISSUE TITLE
组件部署时候，rainbond自动生成的环境变量不要用“PORT”这种通用的名字

### ISSUE THREAD

**Issue by thomascatlee** [goodrain/rainbond#1549]
PORT环境变量，可能会被某些应用用到，比如eurekaClient开了autoconfiguration之后，会去解析PORT环境变量。

改成RAINPORT或者类似的都可以吧。

**Comment by yangkaa** [comment]
具体是指哪一块的环境变量呢，端口自动生成的环境变量吗？一般会是 GRXXX_PORT 这样的环境变量啊，可以在组件端口，点击别名进行修改

**Comment by thomascatlee** [comment]
我看是rainbond生成deployment的时候，自动加的环境变量；和PORT一起的还有LOGGER_DRIVER_NAME PROTOCOL MONITOR_PORT等变量。

**Comment by zzzhangqi** [comment]
在 v6 版本中，改为了 `_PORT`，其他默认注入的变量也是如此，以`_`开头
