### ISSUE TITLE
3.7.2在线安装的问题

### ISSUE THREAD

**Issue by iwin4aids** [goodrain/rainbond#155]
If you want to report a bug or advice, please provide the following information and try to describe your issue in English, If it's a question of use,please read the [documentation](https://www.rainbond.com/docs/stable/) or browse the [community](https://t.goodrain.com/)

- [3.7.2 ] Rainbond versions(eg. grctl version)

- [ ] Kubernetes versions(If you use your own cluster)

- [ centos7.5] Operating system and kernel

- [vmware fusion ] Provider(Aliyun,VirtualBox,...)

- [online singlenode ] Install details(Online/Offline,SingleNode/HA)

我记得以前3.7.1安装有一个步骤是备份/etc/yum.repos.d下的yum源文件到backup目录
然后创建好雨的一个在线repo具体地址忘了，但是今天在线安装试了很多次发现这一步好像没了
不知道是什么原因，我的环境之前离线安装过，然后我使用grctl reset清理过，docker也手动删掉了
然后尝试在线安装，错误日志提示无法获取gr-docker-engine的安装包，我由于一般配的阿里云的yum源所以肯定不能安装gr-docker-engine这个包，我最开始估计是安装脚本没能写入好雨yum源的问题，后来发现是因为每次安装过程会写/etc/resolve.conf把域名解析改成了本地ip，很奇怪为什么要去改这个文件，如下所示，注释掉了我默认的nameserver 223.5.5.5换成了我本机ip。

```
#nameserver 223.5.5.5
nameserver 192.168.144.150
```

可以清楚的从日志看出这个包需要从**repo.goodrain.com**去下载，这样肯定是下载报错的，我安装时也没有指定 --install-type offline，默认应该是在线安装模式才对吧。

另外，我想知道安装过rainbond的机器如何彻底的清理环境，grctl reset能做一部分工作，删除salt和一些组件，但是有些遗留配置依然存在，这些存在的遗留配置是不是会影响到下次安装？

比如我目前踩到的坑：
1、/etc/hosts 文件需要恢复
2、/etc/resolve.conf 中的默认域名服务器也需要恢复
其它未知的还待补充。。

详细安装错误日志如下：

 --- Start install docker(step: 3/6) ... ---

manage01:
  Name: /opt/rainbond/envs/docker.sh - Function: file.managed - Result: Clean Started: - 01:13:03.303419 Duration: 43.841 ms
  Name: /etc/goodrain/envs/docker.sh - Function: file.managed - Result: Clean Started: - 01:13:03.347591 Duration: 32.5 ms
  Name: /etc/docker/certs.d/goodrain.me/server.crt - Function: file.managed - Result: Clean Started: - 01:13:03.380422 Duration: 31.723 ms
  Name: /etc/docker/daemon.json - Function: file.managed - Result: Clean Started: - 01:13:03.412468 Duration: 33.115 ms
  Name: docker-repo - Function: pkgrepo.managed - Result: Clean Started: - 01:13:03.506623 Duration: 590.346 ms
----------
          ID: gr-docker-engine
    Function: pkg.installed
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:

              errors:
                  - Running scope as unit run-14083.scope.
                    Loaded plugins: fastestmirror
                    Loading mirror speeds from cached hostfile
                     * base: mirrors.aliyun.com
                     * extras: mirrors.aliyun.com
                     * updates: mirrors.aliyun.com
                    http://mirrors.aliyun.com/centos/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.aliyun.com; Unknown error"
                    Trying other mirror.
                    http://mirrors.cloud.aliyuncs.com/centos/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.cloud.aliyuncs.com; Unknown error"
                    Trying other mirror.
                    http://mirrors.aliyuncs.com/centos/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.aliyuncs.com; Unknown error"
                    Trying other mirror.
                    http://repo.goodrain.com/centos/7/3.6/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: repo.goodrain.com; Unknown error"
                    Trying other mirror.
                    http://mirrors.aliyun.com/epel/7/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.aliyun.com; Unknown error"
                    Trying other mirror.
                    http://mirrors.aliyun.com/centos/7/extras/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.aliyun.com; Unknown error"
                    Trying other mirror.
                    http://mirrors.cloud.aliyuncs.com/centos/7/extras/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.cloud.aliyuncs.com; Unknown error"
                    Trying other mirror.
                    http://mirrors.aliyuncs.com/centos/7/extras/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.aliyuncs.com; Unknown error"
                    Trying other mirror.
                    http://mirrors.ustc.edu.cn/salt/yum/redhat/7/x86_64/archive/2018.3.2/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.ustc.edu.cn; Unknown error"
                    Trying other mirror.
                    http://mirrors.aliyun.com/centos/7/updates/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.aliyun.com; Unknown error"
                    Trying other mirror.
                    http://mirrors.cloud.aliyuncs.com/centos/7/updates/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.cloud.aliyuncs.com; Unknown error"
                    Trying other mirror.
                    http://mirrors.aliyuncs.com/centos/7/updates/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.aliyuncs.com; Unknown error"
                    Trying other mirror.
                    Resolving Dependencies
                    --> Running transaction check
                    ---> Package gr-docker-engine.x86_64 0:1.12.6-115.gfbecf51.el7 will be installed
                    --> Processing Dependency: gr-docker-engine-selinux >= 1.12.6-115.gfbecf51.el7 for package: gr-docker-engine-1.12.6-115.gfbecf51.el7.x86_64
                    --> Running transaction check
                    ---> Package gr-docker-engine-selinux.noarch 0:1.12.6-115.gfbecf51.el7 will be installed
                    --> Finished Dependency Resolution

                    Dependencies Resolved

                    ================================================================================
                     Package                   Arch    Version                   Repository    Size
                    ================================================================================
                    Installing:
                     gr-docker-engine          x86_64  1.12.6-115.gfbecf51.el7   docker-repo   19 M
                    Installing for dependencies:
                     gr-docker-engine-selinux  noarch  1.12.6-115.gfbecf51.el7   docker-repo   28 k

                    Transaction Summary
                    ================================================================================
                    Install  1 Package (+1 Dependent package)

                    Total download size: 19 M
                    Installed size: 80 M

▽
                    Downloading packages:
                    http://repo.goodrain.com/centos/7/3.6/x86_64/Packages/gr-docker-engine-selinux-1.12.6-115.gfbecf51.el7.noarch.rpm: [Errno 14] curl#6 - "Could not resolve host: repo.goodrain.com; Unknown error"
                    Trying other mirror.
                    http://repo.goodrain.com/centos/7/3.6/x86_64/Packages/gr-docker-engine-1.12.6-115.gfbecf51.el7.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: repo.goodrain.com; Unknown error"
                    Trying other mirror.

                    Error downloading packages:
                      gr-docker-engine-selinux-1.12.6-115.gfbecf51.el7.noarch: [Errno 256] No more mirrors to try.
                      gr-docker-engine-1.12.6-115.gfbecf51.el7.x86_64: [Errno 256] No more mirrors to try.
     Started: 01:13:04.107607
    Duration: 4839.507 ms
     Changes:

Summary for manage01
------------
Succeeded: 5
Failed:    1
------------
Total states run:     6
Total run time:   5.571 s
ERROR: Minions returned with non-zero exit code
 FAILED  install failed... get help from https://t.goodrain.com

**Comment by ysicing** [comment]
默认修改本机dns，是因为当前节点会启动dns服务接管当前集群域名解析工作，默认情况下dns配置文件
```
nameserver 本机ip
nameserver 默认dns(取原先/etc/resolve.conf 第一个nameserver)
```
因为你是重置后的机器，会导致默认dns和本机ip一致导致域名无法解析

**Comment by iwin4aids** [comment]
> 默认修改本机dns，是因为当前节点会启动dns服务接管当前集群域名解析工作，默认情况下dns配置文件
> 
> ```
> nameserver 本机ip
> nameserver 默认dns(取原先/etc/resolve.conf 第一个nameserver)
> ```
> 因为你是重置后的机器，会导致默认dns和本机ip一致导致域名无法解析

 但是是我已经手动修改了/etc/resolve.conf修改会正常的dns，再次安装时安装程序依然要改成本地dns这是为什么呢？ 我使用的是在线安装

**Comment by ysicing** [comment]
不管在线安装还是离线安装都会修改默认dns解析的

**Comment by iwin4aids** [comment]
> 不管在线安装还是离线安装都会修改默认dns解析的

修改了dns解析 基本外网域名都解析不了了，官网demo从源码部署方式是否也都用不了了？因为要访问外网域名的repo

**Comment by iwin4aids** [comment]
> 不会，默认rbd-dns添加上游dns。离线环境暂不支持源码构建

感谢回复
