### ISSUE TITLE
离线合理吗

### ISSUE THREAD

**Issue by wuzedewuze** [goodrain/rainbond#1553]
**Describe the bug**
kubectl create namespace rbd-system

helm install rainbond ./rainbond-cluster -n rbd-system \
--set Cluster.rainbondImageRepository=192.168.1.20:9005/k8s/registry.cn-hangzhou.aliyuncs.com/goodrain \
--set operator.image.name=192.168.1.20:9005/k8s/registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond-operator \
--set Cluster.enableEnvCheck=false \
--set Component.rbd_app_ui.env.DISABLE_DEFAULT_APP_MARKET=true \
--set Component.rbd_resource_proxy.image=192.168.1.20:9005/k8s/registry.cn-hangzhou.aliyuncs.com/goodrain/resource-proxy:v5.10.0-release \
--set Component.nfs_provisioner.image="192.168.1.20:9005/k8s/registry.cn-hangzhou.aliyuncs.com/goodrain/nfs-provisioner"

Component.nfs_provisioner.image 参数指定镜像不生效，其他镜像都可从本地库获取到

**The relevant information:**
 - Rainbond Version v5.11.0-release
 - Kubernetes version 1.23.12

**Comment by yangkaa** [comment]
感谢反馈，目前还有 DISABLE_DEFAULT_APP_MARKET 参数不生效的问题，会一并修复。
