### ISSUE TITLE
 manage node status running(unhealthy)

### ISSUE THREAD

**Issue by iwin4aids** [goodrain/rainbond#156]
If you want to report a bug or advice, please provide the following information and try to describe your issue in English, If it's a question of use,please read the [documentation](https://www.rainbond.com/docs/stable/) or browse the [community](https://t.goodrain.com/)

- [ 3.7.2] Rainbond versions(eg. grctl version)

- [ ] Kubernetes versions(If you use your own cluster)

- [centos7.5 ] Operating system and kernel

- [VMware Fusion ] Provider(Aliyun,VirtualBox,...)

- [offline ] Install details(Online/Offline,SingleNode/HA)

offline安装后，显示为unhealthy状态，

安装命令是./grctl init --role master ，我想知道加和不加--role master对单节点的影响是什么？是否加了这个参数，必须是3节点那种模式，后续需要添加compute节点才能运行应用？

[root@manage01 install]# grctl node list
+--------------------------------------+-----------------+----------+----------------+----------+----------------------+
| Uid                                  | IP              | HostName | NodeRole       | NodeMode | Status               |
+--------------------------------------+-----------------+----------+----------------+----------+----------------------+
| a3964d56-a507-b0de-5fe4-a244138a4394 | 192.168.144.150 | manage01 | manage,compute | master   |  running(unhealthy)  |
+--------------------------------------+-----------------+----------+----------------+----------+----------------------+

grctl get node a3964d56-a507-b0de-5fe4-a244138a4394
-------------------service health-----------------------
+-------------------------+---------+-----------------------------------+
| Title                   | Result  | Message                           |
+-------------------------+---------+-----------------------------------+
|  Ready                  |  false  |                                   |
| NodeInit                |  true   |                                   |
| rbd-eventlog            |  true   |                                   |
| rbd-monitor             |  true   |                                   |
| rbd-worker              |  true   |                                   |
| rbd-webcli              |  true   |                                   |
| rbd-mq                  |  true   |                                   |
| rbd-chaos               |  true   |                                   |
| rbd-api                 |  true   |                                   |
| rbd-entrance            |  true   |                                   |
| rbd-repo                |  true   |                                   |
| rbd-hub                 |  true   |                                   |
| rbd-app-ui              |  true   |                                   |
| rbd-db                  |  true   |                                   |
| kube-controller-manager |  true   |                                   |
| kube-scheduler          |  true   |                                   |
| kube-apiserver          |  true   |                                   |
| kubelet                 |  true   |                                   |
| rbd-lb                  |  true   |                                   |
| etcd                    |  true   |                                   |
| local-dns               |  true   |                                   |
| storage                 |  true   |                                   |
| docker                  |  true   |                                   |
| rbd-dns                 |  true   |                                   |
| calico                  |  true   |                                   |
| OutOfDisk               |  true   | Kubelet never posted node status. |
| MemoryPressure          |  true   | Kubelet never posted node status. |
| DiskPressure            |  true   | Kubelet never posted node status. |
+-------------------------+---------+-----------------------------------+

**Comment by ysicing** [comment]
离线需要指定offline参数，单节点默认master,worker属性
```
master: 管理节点
worker: 计算节点
```
单节点离线正确安装
```
./grctl init --install-type offline
```

**Comment by iwin4aids** [comment]
已解决
