### ISSUE TITLE
oauth链接gitlab构建项目时，branch 只能显示20个

### ISSUE THREAD

**Issue by buzilong** [goodrain/rainbond#1560]
**Describe the bug**
oauth链接gitlab构建项目时，branch 只能显示20个，超过20个branch的项目也只显示20个

**Screenshots**
<img width="676" alt="image" src="https://user-images.githubusercontent.com/19564702/219872215-bc7e8205-f692-41b2-902d-7ab3c2fabaee.png">

**The relevant information:**
 - Rainbond Version [5.11.0]

**Comment by yangkaa** [comment]
v5.12 版本已修复
