### ISSUE TITLE
 NodeJSStatic 方式构建的项目，默认的nginx 配置文件跟文档中不一致

### ISSUE THREAD

**Issue by buzilong** [goodrain/rainbond#1561]
**Describe the bug**
帮助文档中关于nginx默认配置的描述如下。
[文档链接](https://www.rainbond.com/docs/devops/app-deploy/react-vue#webconf)
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/19564702/219872432-5239d44e-158b-42b4-944a-d752c3b3e965.png">
而实际如果没有配置web.conf到项目中，默认的nginx配置中是没有 **try_files $uri $uri/ /index.html;** 这句的。

**The relevant information:**
 - Rainbond Version [5.11.0]

**Comment by zzzhangqi** [comment]
默认的 nginx 配置肯定是不够业务使用的，建议还是自定义 nginx 配置文件：
* 可以在 `组件 -> 环境配置 -> 添加配置文件`
* 路径写 `/app/nginx/conf.d/web.conf`
* 其他自定义
