### ISSUE TITLE
网关新添加条目时，不会生效，只有选择一条编辑再保存才生效

### ISSUE THREAD

**Issue by buzilong** [goodrain/rainbond#1565]
**Describe the bug**
网关新添加条目的时候，不会生效，只有选择一条编辑再保存才会生效，看了apigateway的log，在新增的时候没有触发配置文件的更新

**The relevant information:**
 - Rainbond Version [5.11.1]

**Comment by yangkaa** [comment]
麻烦提供下完整的复现步骤，还有你的版本是单机体验版还是集群版？http 策略还是 tcp 策略

**Comment by buzilong** [comment]
> 麻烦提供下完整的复现步骤，还有你的版本是单机体验版还是集群版？http 策略还是 tcp 策略
目前发现的的是tcp策略。
重现步骤：网关->访问策略管理->添加策略->确定。
此时添加的策略并不会生效

**Comment by quyuancheng** [comment]
在5.11.1版本中对该问题进行了验证，操作流程为：创建组件->网关->访问策略管理->选择TCP/UDP添加策略->确认创建。
分别在应用管理界面和团队管理界面进行了网关操作，结果是能正常访问的。可能和部署的服务有关系，可以尝试更换其他服务验证一下。
