### ISSUE TITLE
网关访问策略希望可以指定匹配顺序

### ISSUE THREAD

**Issue by buzilong** [goodrain/rainbond#1566]
**Is your feature request related to a problem? Please describe.**

我测试下来发现，网关访问策略里面的顺序很奇怪，有点琢磨不清，如果我用同一个网址 通过location转发到不同的组件。
如果location是**"/"** 和 **"/api/"**，有时候配置好候访问 http://xxx/api/ 会被 ”/“ 优先匹配到，导致进入错误的组件，有时候则会http://xxx/api/ 会被 ”/api/“ 匹配到。但是我确定我两次的配置都是一样的。（ps:在同一次的配置里，只会匹配到同一个组件，删了从新配置，就有可能匹配到另一个组件上） 

**Describe the solution you'd like**
策略上面添加优先级字段，用来指定匹配顺序，确保匹配的确定性

**Comment by yangkaa** [comment]
两次配置顺序也是一样的吗？可以给出一个明确可复现的步骤，如果是bug，将会修复它

**Comment by buzilong** [comment]
> 两次配置顺序也是一样的吗？可以给出一个明确可复现的步骤，如果是bug，将会修复它

两次配置的顺序是不一样的，并且页面上没有办法调整顺序，如果我新加规则的时候，总不能把原来的全删掉吧？

**Comment by ZhangSetSail** [comment]
由于你 location 配置的是   /   和   /api   ，/api 是 / 的更精确值，所以这里域名的匹配机制是优先匹配 /api ，匹配成功则会将域名路由至 /api 对应的后端服务，匹配不上则会再向下级 / 路径进行匹配。
平台的网关是通过 Nginx 实现，这一层处理也是 Nginx 的处理方式。
所谓的优先级，是否可以直接关闭你认为低优先级的网关，只保留最高优先级的网关来实现。
