### ISSUE TITLE
最新的3.7.2离线包安装时salt启动超时问题

### ISSUE THREAD

**Issue by iwin4aids** [goodrain/rainbond#157]
If you want to report a bug or advice, please provide the following information and try to describe your issue in English, If it's a question of use,please read the [documentation](https://www.rainbond.com/docs/stable/) or browse the [community](https://t.goodrain.com/)

- [ 3.7.2] Rainbond versions(eg. grctl version)

- [ ] Kubernetes versions(If you use your own cluster)

- [ centos7.4] Operating system and kernel

- [ 物理机 ] Provider(Aliyun,VirtualBox,...)

- [ offline ] Install details(Online/Offline,SingleNode/HA)

今天我下载了最新的阿里云离线安装包测试离线安装时

又出现了salt无法启动的问题，日志如下，一直卡在waiting to start salt，过了很久就显示exit status 1退出了，而且也没有任何其他日志，请问如何解决呢？

 --- Install Salt-Master & Salt-Minion ---
manage01:
  Name: salt-master-install - Function: pkg.installed - Result: Clean Started: - 10:53:28.852353 Duration: 2202.046 ms
  Name: /etc/salt/master.d/master.conf - Function: file.managed - Result: Clean Started: - 10:53:31.055829 Duration: 124.214 ms
  Name: salt-master - Function: service.running - Result: Clean Started: - 10:53:31.181357 Duration: 142.59 ms
  Name: salt-minion-install - Function: pkg.installed - Result: Clean Started: - 10:53:31.324487 Duration: 555.132 ms
  Name: /etc/salt/minion.d/minion.conf - Function: file.managed - Result: Clean Started: - 10:53:31.881060 Duration: 77.085 ms
  Name: /tmp/salt-minion-install - Function: file.managed - Result: Clean Started: - 10:53:31.958667 Duration: 72.21 ms
  Name: bash -x /tmp/salt-minion-install - Function: cmd.run - Result: Changed Started: - 10:53:32.031395 Duration: 40.372 ms
  Name: salt-minion - Function: service.running - Result: Clean Started: - 10:53:32.073597 Duration: 88.261 ms

Summary for manage01
------------
Succeeded: 8 (changed=1)
Failed:    0
------------
Total states run:     8
Total run time:   3.302 s
 --- Waiting to start salt. ---

............................................................exit status 1

**Comment by ysicing** [comment]
只能修改`/opt/rainbond/install/setup.sh` 来调整默认的超时时间，当前默认超时时间是`timeout 3`推荐修改为`timeout 600`

**Comment by iwin4aids** [comment]
> 只能修改`/opt/rainbond/install/setup.sh` 来调整默认的超时时间，当前默认超时时间是`timeout 3`推荐修改为`timeout 600`

最新更新，我使用10-24的离线包没这个问题了，最新的11-10离线包 始终卡在salt start这一步上，我再尝试手动先卸载salt试试

**Comment by iwin4aids** [comment]
> 只能修改`/opt/rainbond/install/setup.sh` 来调整默认的超时时间，当前默认超时时间是`timeout 3`推荐修改为`timeout 600`

受限于机器原因，默认的timeout 3 很可能在低配虚拟机上运行超时，设置成600确实没问题了
