### ISSUE TITLE
团队的应用列表里-通过镜像方式构建组件失败

### ISSUE THREAD

**Issue by zhangj-923** [goodrain/rainbond#1572]
在团队的应用列表里--通过镜像的形式去构建组件
报错显示服务端异常

1. 添加镜像
![微信图片_20230228131339](https://user-images.githubusercontent.com/67679447/221760328-5aac9dfc-8e3b-4b95-b512-f2b017b4a71a.png)

2. 控制台日志输出
![微信图片_20230228131409](https://user-images.githubusercontent.com/67679447/221760382-52cb925f-e5be-40c4-82a6-258b9edb205f.png)

**Comment by zhangj-923** [comment]
平台版本
![企业微信截图_20230228131522](https://user-images.githubusercontent.com/67679447/221760602-1f51d282-e0d6-4c40-a527-7ea74b35bc5a.png)

**Comment by zzzhangqi** [comment]
fix: https://github.com/goodrain/rainbond-console/pull/1266

fix: v5.12.0-release
