### ISSUE TITLE
helm 安装失败，报类型转换错误

### ISSUE THREAD

**Issue by xiaobaibai668** [goodrain/rainbond#1577]
helm install rainbond rainbond/rainbond-cluster -n rbd-system

E0305 22:26:50.075827   22537 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
...
E0305 22:26:58.355948   22537 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
Error: INSTALLATION FAILED: Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type `string`

**Comment by zzzhangqi** [comment]
What version of Kubernetes @xiaobaibai668

**Comment by xiaobaibai668** [comment]
> 固定。请执行继续安装。 @xiaobaibai668`helm repo update`
更新过了的
