### ISSUE TITLE
麻烦   Webhook 支持空key和有key

### ISSUE THREAD

**Issue by ice-leng** [goodrain/rainbond#1579]
麻烦   Webhook 支持空key和有key

**Comment by buzilong** [comment]
确实不支持空key带来不方便，有时候项目提交不是很频繁，或者测试分支merge后就有自动部署的需求，但是webhook必须加关键字这个拦在前面很难受。另外不支持自由配置的做法也干扰到了项目管理流程，使得有些场景不得不放弃s2i的使用转用Jenkins

**Comment by zzzhangqi** [comment]
5.17、6.0版本中已支持
