### ISSUE TITLE
rdb-repo组件一直是unhealthy状态

### ISSUE THREAD

**Issue by iwin4aids** [goodrain/rainbond#158]
If you want to report a bug or advice, please provide the following information and try to describe your issue in English, If it's a question of use,please read the [documentation](https://www.rainbond.com/docs/stable/) or browse the [community](https://t.goodrain.com/)

- [3.7.2 ] Rainbond versions(eg. grctl version)

- [ ] Kubernetes versions(If you use your own cluster)

- [centos7.4 ] Operating system and kernel

- [物理机 ] Provider(Aliyun,VirtualBox,...)

- [offline ] Install details(Online/Offline,SingleNode/HA)

如下图所示，我集群所有节点部署好后使用grctl cluster查看状态只有这个rdb-repo是unhealthy，导致无法从源码部署，请问有什么办法调试或者重新部署吗？
<img width="714" alt="2018-11-10 15 03 31" src="https://user-images.githubusercontent.com/16768783/48298550-3364c880-e4fa-11e8-9ae9-1c1e8cc323b5.png">

**Comment by ysicing** [comment]
离线环境暂不支持源码构建, 后面会优化离线环境移除rbd-repo

**Comment by iwin4aids** [comment]
> 离线环境暂不支持源码构建, 后面会优化离线环境移除rbd-repo

好的，不过我觉得应该支持从私有gitlab这种仓库构建吧 不一定非要是外网的repo

**Comment by ysicing** [comment]
@iwin4aids  这类是没有问题，但是源码构建还需要一些依赖包之类，目前我们都是统一放在对象存储上的，源码构建时本地获取相关依赖包，如果没有rbd-repo会从对象存储上缓存到本地。目前也在处理离线环境相关依赖包的问题。
