### ISSUE TITLE
The rest api [/console/enterprise/xxxx/regions/rainbond/nodes] return http 500 when node role labels don't exist

### ISSUE THREAD

**Issue by jthann** [goodrain/rainbond#1583]
**Describe the bug**
In some managed kubernetes cluster like aliyun ACK，when accessing rainbond console，in cluster node list page，the rest api [/console/enterprise/xxxx/regions/rainbond/nodes] return http 500，after investigation in code，it is because the managed kubernetes cluster nodes miss ```node-role.kubernetes.io``` and ```kubernetes.io/role``` labels， and the golang api service return null，python service throw error when handling concatenation in ```console/services/enterprise_services.py:443```

**Comment by quyuancheng** [comment]
该问题已在5.13.0版本中修复
