### ISSUE TITLE
添加跨应用依赖时，无法访问相应的端口

### ISSUE THREAD

**Issue by hanxinhisen** [goodrain/rainbond#1584]
版本号v5.12.0（v5.11.0也有问题）

B应用中组件添加A应用某个组件为依赖时，B应用中组件无法访问A应用组件，B应用中也未监听相应的依赖端口。之前没有问题，最近才发现。

**Comment by yangkaa** [comment]
从 5.11 开始，默认应用治理模式变更为原生 Service 模式。所以不会在应用中监听对应的依赖端口。你通信的环境变量建议使用`端口`中的`组件别名`，这样在内置ServiceMesh模式下，组件别名是`127.0.0.1`，在原生Service 模式下，是组件的`内部域名`。
