### ISSUE TITLE
通过git仓库创建的组件无英文名称，需要构建后才能修改，并更新

### ISSUE THREAD

**Issue by bryant-rh** [goodrain/rainbond#1596]
在通过 git 仓库创建组件的时候，无法填写英文名称，默认是个随机值，需要构建完成后，才能修改，还需要更新。
<img width="543" alt="image" src="https://user-images.githubusercontent.com/43403977/226589967-03d4c0b8-679a-4e1b-9cc1-c78461c61e30.png">
<img width="606" alt="image" src="https://user-images.githubusercontent.com/43403977/226589986-65779b50-8b09-40fe-9490-097cdea4fbe0.png">
<img width="815" alt="image" src="https://user-images.githubusercontent.com/43403977/226590000-55f65c7f-53ca-4a2a-9cfb-ee920740edfc.png">

而看了另外两种通过源码创建的方式都可以编辑组件名称，觉得这里不太合理，因为个人觉得企业内部，应该是用这种直接通过git仓库创建的场景居多。

**Comment by quyuancheng** [comment]
该问题已在5.13.0版本中修复
