### ISSUE TITLE
demo在线安装v3.7.2报找不到6100端口

### ISSUE THREAD

**Issue by liuzhao2015** [goodrain/rainbond#160]
If you want to report a bug or advice, please provide the following information and try to describe your issue in English, If it's a question of use,please read the [documentation](https://www.rainbond.com/docs/stable/) or browse the [community](https://t.goodrain.com/)

- [ ] Rainbond versions(eg. grctl version)
v3.7.2
- [ ] Kubernetes versions(If you use your own cluster)

- [ ] Operating system and kernel
CentOS Linux release 7.4.1708 (Core)
- [ ] Provider(Aliyun,VirtualBox,...)
vmware
- [ ] Install details(Online/Offline,SingleNode/HA)
Online demo

安装报错信息如下
--- Start pull image(step: 4/7) --- 
Nov 14 05:14:53 kubeapi dockerd: time="2018-11-14T05:14:53.468197874-05:00" level=error msg="discover event_log_event_http app endpoints error, Get http://127.0.0.1:6100/v2/apps/event_log_event_http/discover: dial tcp 127.0.0.1:6100: getsockopt: connection refused"

**Comment by ysicing** [comment]
@liuzhao2015 
是全新环境吗，正常情况下这步仅仅是docker pull/push相关镜像，未启动相关服务。重新执行安装也不可行吗

**Comment by liuzhao2015** [comment]
@ysicing 
重试了三次拉下来21个镜像，然后一直不停重复报上述错误连接6100端口被拒绝。我去netstat查看没看到6100端口有进程监听。还有请教下6100端口具体是什么作用，能否公开一份端口的通讯矩阵出来进行参考

**Comment by ysicing** [comment]
@liuzhao2015  6100是我们node组件监听的端口,相关端口可以参考[平台组件说明
](https://www.rainbond.com/docs/stable/operation-manual/component-description.html)和[组件参数说明](https://www.rainbond.com/docs/stable/operation-manual/cluster-management/manager-services/rbd-api.html)

**Comment by liuzhao2015** [comment]
@ysicing 
```
这个问题是在没有进行部署的时候去请求node服务导致的，但是安装运行失败的根因是拉取镜像超时。
netstat -anlp|grep nginx会发现443的端口没有监听
需要执行dc-compose stop
cclear
命令清理掉原来的仓库，然后重新进行安装。
```
