### ISSUE TITLE
rainbond-operator helm安装失败

### ISSUE THREAD

**Issue by liukai12** [goodrain/rainbond#1602]
**Describe the bug**
![image](https://user-images.githubusercontent.com/24822691/227863735-f9385ffc-1493-4bc8-95ac-18991f99945d.png).
通过github operator 仓库下的 2.2.0 tag下手动创建失败
报错信息：
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]

**The relevant information:**
 - Rainbond Version [5.4.0]
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version [ 1.19.6]

**Comment by ZhangSetSail** [comment]
能否提供一下你的安装命令，我在测试环境复现一下
