### ISSUE TITLE
通过仓库构建dockerfile项目时，推送镜像失败

### ISSUE THREAD

**Issue by xggz** [goodrain/rainbond#1603]
**Describe the bug**
通过仓库构建dockerfile项目时，推送镜像失败。

**To Reproduce**
构建到最后推送镜像时提示：error pushing image；
但是通过仓库构建maven项目时是可以正常推送镜像的。

**Screenshots**
![image](https://user-images.githubusercontent.com/8168663/227873920-b97a3212-87f0-496c-be00-e2c3f8860d5e.png)

**The relevant information:**
 - Rainbond Version [5.10.0、5.13.0]
 - Browser [chrome] 
 - Kubernetes version [1.23.10]

**Comment by ZhangSetSail** [comment]
你的docker版本是什么，方便把push失败的这个 dockerfile 分享出来吗，我在我的环境测试一下定位一下问题。

**Comment by xggz** [comment]
Docker version 20.10.9, build c2ea9bc

dockerfile精简了一下，大概这样的：

`FROM openjdk:11-jre as java_builder

LABEL MAINTAINER="xggz"

ARG MY_SERVER_FILE=tc-basic-data-app.jar
ADD ./target/${MY_SERVER_FILE} /app/jar/server.jar


FROM ubuntu:20.04

LABEL MAINTAINER="xggz"

ENV TZ=Asia/Shanghai
RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y wget
ENV TDENGINE_VERSION=2.6.0.34
RUN wget -c https://www.taosdata.com/assets-download/TDengine-client-${TDENGINE_VERSION}-Linux-x64.tar.gz \
   && tar xvf TDengine-client-${TDENGINE_VERSION}-Linux-x64.tar.gz \
   && cd TDengine-client-${TDENGINE_VERSION} \
   && ./install_client.sh \
   && cd ../ \
   && rm -rf TDengine-client-${TDENGINE_VERSION}-Linux-x64.tar.gz TDengine-client-${TDENGINE_VERSION}

ENV JAVA_OPTS="-Xms128m -Xmx384m -Djava.security.egd=file:/dev/./urandom"

COPY --from=java_builder /app/jar/server.jar /app/jar/server.jar
COPY --from=java_builder /usr/local/openjdk-11 /usr/local/openjdk-11

EXPOSE 7803

CMD ["/usr/local/openjdk-11/bin/java", "$JAVA_OPTS", "-jar", "/app/jar/server.jar"]`

**Comment by ZhangSetSail** [comment]
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/101104760/229776130-79c6b336-db9f-4dbf-a02e-adfcdba493cc.png">
我尝试复现你这个问题，好像因为缺少某些文件导致无法构建，没有成功复现，可否重新给我一个 Dockerfile

**Comment by xggz** [comment]
> <img alt="image" width="1509" src="https://user-images.githubusercontent.com/101104760/229776130-79c6b336-db9f-4dbf-a02e-adfcdba493cc.png">
> 
> 我尝试复现你这个问题，好像因为缺少某些文件导致无法构建，没有成功复现，可否重新给我一个 Dockerfile

我弄了一个仓库，你可以试试通过这个仓库构建服务：https://github.com/xggz/jar-dockerfile.git

**Comment by xggz** [comment]
@ZhangSetSail  您好，有测试结果吗

**Comment by ZhangSetSail** [comment]
抱歉，久等了，这看起来是个bug，将在下个版本修复。

**Comment by ZhangSetSail** [comment]
临时解决办法，修改 chaos。
`kubectl edit rbdcomponent rbd-chaos -nrbd-system`

添加 args
`args:`
`- --kaniko-args=--reproducible`

效果如下：
<img width="471" alt="image" src="https://user-images.githubusercontent.com/101104760/233600544-f3da416f-12b3-4733-b14d-fe1860e1689f.png">

**Comment by ZhangSetSail** [comment]
编辑完成后保存退出，等待 chaos 的 pod 资源重启后，再次构建。
构建成功
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/101104760/233601714-a378830c-08f9-44d2-832b-8a65e31ceb66.png">
