### ISSUE TITLE
gateway 配置文件生成错误，导致gateway起不来

### ISSUE THREAD

**Issue by hanxinhisen** [goodrain/rainbond#1604]
![微信截图_20230328110812](https://user-images.githubusercontent.com/7082486/228176349-cee71928-d614-49e9-98df-a1a5db2f11a4.png)
生成了两遍location /

简单排查了下，发现云邦上配置端口，居然有两个相同的域名，我尝试了下，直接在端口页面加提示重复加不上，但是可以从其他界面改成一样的。

![微信截图_20230328110750](https://user-images.githubusercontent.com/7082486/228176851-93125b4d-a0ce-4cc1-87d8-41f19c99d55c.png)

**Comment by hanxinhisen** [comment]
![1679992393322](https://user-images.githubusercontent.com/7082486/228177821-c2dc311c-c6fd-4601-90ec-078763f8a891.png)

**Comment by persistence** [comment]
加油

**Comment by ZhangSetSail** [comment]
感谢你的反馈，这看起来是编辑的时候没有控住，这个问题会安排在下个版本修复。
