### ISSUE TITLE
Rbd-lb errors result in rbd-entracne errors

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#161]
If you want to report a bug or advice, please provide the following information and try to describe your issue in English, If it's a question of use,please read the [documentation](https://www.rainbond.com/docs/stable/) or browse the [community](https://t.goodrain.com/)

- [ v3.7.2 ] Rainbond versions(eg. grctl version)

- [ CentOS7.4 3.10] Operating system and kernel

- [ The physical machine ] Provider(Aliyun,VirtualBox,...)

- [ Online HA ] Install details(Online/Offline,SingleNode/HA)

I have three manage nodes，One of them went down, and I found out that my application couldn't bind to a domain name anymore.It will not regenerate into the correct configuration file in `/opt/rainbond/etc/rbd-lb/dynamics/dynamic_servers`.
When I remove the invalid `rbd-lb` address from the `rbd-entrance` configuration,The system is back to normal.
Perhaps rbd-blots can monitor rbd-lb health detection.

**Comment by GLYASAI** [comment]
Rbd-lb will be completely replaced by rbd-gateway in version V5.0, and this issue will be resolved

**Comment by GLYASAI** [comment]
Rbd-lb will be completely replaced by rbd-gateway in version V5.0, and this issue will be resolved
