### ISSUE TITLE
多节点Rainbond安装rbd-resource-prxoy出现异常

### ISSUE THREAD

**Issue by lihao6666** [goodrain/rainbond#1619]
**Describe the bug**
多节点安装rainbond其中一个节点的rbd-resource-prxoy出现异常，报错multi-attach, 其它pod都是正常的

**Screenshots**
![image](https://user-images.githubusercontent.com/36958251/231171147-93b96cd4-db0c-4240-9fa3-61bdaea2fb7f.png)
![image](https://user-images.githubusercontent.com/36958251/231171498-85dfaba6-1f48-4f1d-86f7-0fea239b6a97.png)

**The relevant information:**
 - Rainbond Version [5.12.0]
 - Kubernetes version [1.23.10]

**Comment by yangkaa** [comment]
rbd-resource-proxy 挂载的 PVC 类型是 RWO 的，只能被单个节点挂载。所以你需要将其实例缩为单实例，或使用 RWX 类型 PVC。

它的主要作用是源码构建时，反向代理远端仓库，多实例意义不大。
