### ISSUE TITLE
使用ceph存储导致monitor统计Disk出错(影响一些Rainbond功能使用)

### ISSUE THREAD

**Issue by lihao6666** [goodrain/rainbond#1621]
**Describe the bug**
高可用Rainbond配置Ceph存储后导致Monitor统计Disk失败，影响一些功能使用(上传RAW格式的应用包，体积过大就无法上传，提示disk空间不足)

**Screenshots**
![image](https://user-images.githubusercontent.com/36958251/231337687-2f5ec15b-61e2-42f6-8caf-9eb7ffac53d0.png)

**The relevant information:**
 - Rainbond Version [5.12.0]
 - Kubernetes version [e.g 1.23.10]

**Comment by yangkaa** [comment]
1. `导致Monitor统计Disk失败` 是什么意思？

2. 磁盘空间不足应该是 PV、PVC 大小限制的问题，rbd-system 命名空间下的 PVC 大小都是多少呢？

**Comment by lihao6666** [comment]
> 1. `导致Monitor统计Disk失败` 是什么意思？
> 2. 磁盘空间不足应该是 PV、PVC 大小限制的问题，rbd-system 命名空间下的 PVC 大小都是多少呢？

![image](https://user-images.githubusercontent.com/36958251/231652386-acaa013f-6c33-4110-af78-a97b980e19c7.png)

**Comment by yangkaa** [comment]
安装 Rainbond 时 grdata 存储容量默认请求值为 1g ，在 NFS 或 GFS 场景下，这个限制不生效所以没有问题，Ceph 对容量有严格限制，所以导致只能实际使用 1g，下个版本会支持在安装平台时，允许指定 grdata 的容量。
