### ISSUE TITLE
集群资硬件源CPU、内存统计不准，如何修复？

### ISSUE THREAD

**Issue by gobaiy** [goodrain/rainbond#1630]
![image](https://user-images.githubusercontent.com/49633387/233817825-aabfc49b-632c-4cb2-8815-7be8e89a5ab2.png)

**Comment by yangkaa** [comment]
集群中是否存在磁盘压力，导致有被驱逐的 Pod 呢？被驱逐的 Pod 可能导致使用量错误统计，清理掉这些被驱逐无法调度的 Pod 即可

**Comment by gobaiy** [comment]
> 集群中是否存在磁盘压力，导致有被驱逐的 Pod 呢？被驱逐的 Pod 可能导致使用量错误统计，清理掉这些被驱逐无法调度的 Pod 即可

确实有比较多的Pod被驱逐，清理掉后恢复正常了。
