### ISSUE TITLE
操作记录里面，滚动升级组件和删除构建版本 没有记录 操作人

### ISSUE THREAD

**Issue by buzilong** [goodrain/rainbond#1642]
**Describe the bug**
操作记录里面，滚动升级组件和删除构建版本 没有记录 操作人

**Screenshots**
<img width="1660" alt="image" src="https://github.com/goodrain/rainbond/assets/19564702/5afd2f7a-8b82-483e-b531-35be5e0fcca5">

**Comment by quyuancheng** [comment]
主动执行的事件会记录操作人信息，比如创建、构建，升级，删除；
滚动升级组件是由构建成功后触发的，所以就没有记录操作人。
