### ISSUE TITLE
自动签发证书失败

### ISSUE THREAD

**Issue by wshlfx** [goodrain/rainbond#1652]
**Describe the bug**
自动签发证书失败,证书签发的阿里云key都已正常配置好，签发证书的pod也已启动，签发证书的环境变量中控制台地址跟访问密钥等参数也均设置好，每个域名都试过，出现如下图的错误，尝试过好个域名都没有签发成功过

**To Reproduce**

**Screenshots**
![image](https://github.com/goodrain/rainbond/assets/30335651/3a2b23dd-c390-4007-85fa-e9d0298941dc)

**The relevant information:**
 - Rainbond Version [v5.14.0-release-5151e89fb-2023-05-17-10-allinone]
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version [1.25.9+k3s1]

**Comment by yangkaa** [comment]
原因：由于 [OpenAPI 异常](https://github.com/goodrain/rainbond/issues/1663 )导致的，所以自动签发证书申请到证书后，无法正确更新控制台的证书数据，导致反复申请，触发了 Let's Encrypt 的限制。目前在 v5.14.1 版本中修复了 OpenAPI 的问题。

解决方案：升级控制台到 v5.14.1 版本。然后等待 Let's Encrypt 对[重复证书限制](https://letsencrypt.org/zh-cn/docs/duplicate-certificate-limit/)过期后，大概是一周时间，应该就可以成功申请到证书了。
