### ISSUE TITLE
编辑Http访问策略提示策略已存在

### ISSUE THREAD

**Issue by xggz** [goodrain/rainbond#1660]
修改Http访问策略的超时时间，点击保存出错，提示策略已存在

**The relevant information:**
 - Rainbond Version v5.13.0
 - Browser chrome

**Comment by ZhangSetSail** [comment]
该问题5.14.0版本已修复，修复的[pr](https://github.com/goodrain/rainbond-console/pull/1292)，临时解决办法可以按照pr去修改 allinone 容器的 python 代码，或者升级平台到5.14.0[升级文档]( https://www.rainbond.com/docs/upgrade/latest-version)

**Comment by ZhangSetSail** [comment]
该Issues将关闭，如果操作上有什么问题再次开启或者在微信群里咨询。
