### ISSUE TITLE
500 error encountered when adding repository to Helm.

### ISSUE THREAD

**Issue by China256** [goodrain/rainbond#1661]
**Describe the bug**

After deploying a clean k8s cluster using kubekey, encountering a 500 Internal Server Error when adding the Rainbond repository using Helm.

**Screenshots**
<img width="793" alt="image" src="https://github.com/goodrain/rainbond/assets/13843510/6b5b08d3-f666-42e7-b439-5116e54a9eaa">

**The relevant information:**
 - Rainbond Version [e.g. 5.2.0]
 - Kubernetes version [e.g 1.23.10]
 - Kubekey version [e.g v3.0.7]

**Comment by zzzhangqi** [comment]
Fixed. There was an issue with the chart service.

**Comment by zzzhangqi** [comment]
@China256
