### ISSUE TITLE
网关websocket配置

### ISSUE THREAD

**Issue by yymagicer** [goodrain/rainbond#1669]
发布到组件库的模版，如果网关策略打开了websocket开关，通过组件库创建组件后，网关策略没有自动打开websocket开关

**Comment by ZhangSetSail** [comment]
你是什么版本呢，我在本地测试没有问题，如果版本较低，可能需要升级一下最新版本。

**Comment by zzzhangqi** [comment]
Stale issue, I will close it, please open again if there is a problem.
