### ISSUE TITLE
rbd-node产生日志太多, 占满硬盘

### ISSUE THREAD

**Issue by xuh-code** [goodrain/rainbond#1675]
**Describe the bug**
rbd-node组件, 日志打印太多,占满硬盘.

**To Reproduce**
1. 部署方式使用helm方式部署, 

helm install --set Cluster.gatewayIngressIPs=10.xxx.xx.xx \
--set Cluster.enableHA=false \
--set Cluster.imageHub.enable=true \
--set Cluster.imageHub.domain=xxx.xxxxxxx.com \
--set Cluster.imageHub.namespace=rain \
--set Cluster.imageHub.username=xxxx \
--set Cluster.imageHub.password=xx123456 \
--set Cluster.uiDatabase.host=10.xx.xx.xx \
--set Cluster.uiDatabase.port=3306 \
--set Cluster.uiDatabase.username=xxxxx \
--set Cluster.uiDatabase.password=xx123456 \
--set Cluster.uiDatabase.name=rain-console \
--set Cluster.uiDatabase.enable=true \
--set Cluster.regionDatabase.host=10.xx.xx.xx \
--set Cluster.regionDatabase.port=3306 \
--set Cluster.regionDatabase.username=root \
--set Cluster.regionDatabase.password=xx123456 \
--set Cluster.regionDatabase.name=rain-region \
--set Cluster.regionDatabase.enable=true \
--set Cluster.nodesForChaos[0].name=node2 \
--set Cluster.nodesForGateway[0].name=node2 \
--set Cluster.nodesForGateway[0].externalIP=10.xx.xx.xx \
--set Cluster.nodesForGateway[0].internalIP=10.xx.xx.xx \
rainbond rainbond/rainbond-cluster -n rbd-system

使用外部数据库, 外部harbor镜像仓库. 

**Screenshots**

部署后, rbd-node产生的日志非常多

![image](https://github.com/goodrain/rainbond/assets/22283916/ddb0a098-171d-4a4d-9b64-ece343a10a2d)
![image](https://github.com/goodrain/rainbond/assets/22283916/b6474022-7571-4eae-ba3c-048b8997beff)
![image](https://github.com/goodrain/rainbond/assets/22283916/301657c2-b6d7-452c-8363-a385656f6ece)

**The relevant information:**
 - Rainbond Version rainbond-cluster-5.14.1
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version  v1.23.1

**Comment by yangkaa** [comment]
重启这个 rbd-node 的 pod 会自动清理掉这些日志文件。下个版本会减少 rbd-node 这个组件打印的日志。

**Comment by xuh-code** [comment]
time="2023-06-26T09:06:06+08:00" level=info msg="docker container log path /data/docker/containers/9916da71b5ab91133115a3898cc99e5252f75bc9243e5d02fef3d8d579d0a39c/9916da71b5ab91133115a3898cc99e5252f75bc9243e5d02fef3d8d579d0a39c-json.log"
time="2023-06-26T09:06:06+08:00" level=info msg="docker container log path /data/docker/containers/5c57ffc0733fc9b4b90ffb86e66eacedcff3ac6467c64e6e04b62f499230ded9/5c57ffc0733fc9b4b90ffb86e66eacedcff3ac6467c64e6e04b62f499230ded9-json.log"
time="2023-06-26T09:06:06+08:00" level=error msg="create logger failure open /data/docker/containers/9916da71b5ab91133115a3898cc99e5252f75bc9243e5d02fef3d8d579d0a39c/9916da71b5ab91133115a3898cc99e5252f75bc9243e5d02fef3d8d579d0a39c-json.log: no such file or directory"
time="2023-06-26T09:06:06+08:00" level=info msg="docker container log path /data/docker/containers/5c57ffc0733fc9b4b90ffb86e66eacedcff3ac6467c64e6e04b62f499230ded9/5c57ffc0733fc9b4b90ffb86e66eacedcff3ac6467c64e6e04b62f499230ded9-json.log"
time="2023-06-26T09:06:06+08:00" level=info msg="docker container log path /data/docker/containers/1ebf9d302791f28f1018455bf7a27637149792c4a8d9ce1da15b6c342dac72fa/1ebf9d302791f28f1018455bf7a27637149792c4a8d9ce1da15b6c342dac72fa-json.log"
time="2023-06-26T09:06:06+08:00" level=info msg="docker container log path /data/docker/containers/ac4683920e9b2a311e2ff26333e6c1118cd59774ecfc4386bb504bdd3220c7b1/ac4683920e9b2a311e2ff26333e6c1118cd59774ecfc4386bb504bdd3220c7b1-json.log"
time="2023-06-26T09:06:06+08:00" level=info msg="docker container log path /data/docker/containers/ac4683920e9b2a311e2ff26333e6c1118cd59774ecfc4386bb504bdd3220c7b1/ac4683920e9b2a311e2ff26333e6c1118cd59774ecfc4386bb504bdd3220c7b1-json.log"
time="2023-06-26T09:06:06+08:00" level=info msg="docker container log path /data/docker/containers/3c20123d1f5c49e90e9ba85dcb0fe5debbf79c01f0e4aa3d7ae3c2b91ba12ab8/3c20123d1f5c49e90e9ba85dcb0fe5debbf79c01f0e4aa3d7ae3c2b91ba12ab8-json.log"
time="2023-06-26T09:06:06+08:00" level=error msg="create logger failure open /data/docker/containers/ac4683920e9b2a311e2ff26333e6c1118cd59774ecfc4386bb504bdd3220c7b1/ac4683920e9b2a311e2ff26333e6c1118cd59774ecfc4386bb504bdd3220c7b1-json.log: no such file or directory"

基本都是.log文件找不到的日志. 

我的docker目录是放在/data/docker下的. 软链到了/var/lib/docker下了. 导致日志文件找不到. 

@yangkaa  建议在rbd-node 轮询日志的时候, 减少日志打印.

**Comment by yangkaa** [comment]
好的，这块会进行优化的。那么在你的场景下，平台组件日志功能还存在其他问题吗？
