### ISSUE TITLE
通过添加第三方组件时， all in one 模式下无法使用 127.0.0.1 作为组件地址

### ISSUE THREAD

**Issue by mx2913** [goodrain/rainbond#1679]
**The relevant information:**
 - 平台版本：v5.14.1-4b0690d54-2023-06-08-04-allinone
 - Rainbond Version [v5.14.1-release-2f45c815e-2023-06-08-04]
 - Kubernetes version [1.22.3+k3s1 ]

**Comment by mx2913** [comment]
<img width="1160" alt="图片" src="https://github.com/goodrain/rainbond/assets/15864713/16d64f71-133e-40ed-9952-edf70bcadc06">

**Comment by yangkaa** [comment]
你需要指定明确的 ip 地址，因为 allinone 是一个容器，所以使用容器的 127.0.0.1 创建第三方组件没有意义，也无法访问到你的业务。

**Comment by mx2913** [comment]
macOS 本地安装的 All in One 模式如何通过 rainbond 的网关功能反向代理域名(例如 `randbond.local.example.com`，HTTP 应用后缀为 `local.example.com`) 来访问 rainbond 控制台呢，尝试过上面的方法，但是无效

**Comment by yangkaa** [comment]
直接编辑 /etc/hosts 文件，randbond.local.example.com 127.0.0.1 不就可以了吗，如果你觉得这样通过域名访问还要加 7070 端口，那么你可以找到容器的安装命令，把 -v 参数中的 7070:7070 改成 80:7070 就行

**Comment by mx2913** [comment]
通过在网卡上新建了个 `172.17.0.1` 的私有 ip 解决了这个问题
![图片](https://github.com/goodrain/rainbond/assets/15864713/80cdbfdf-c687-4213-883f-7b16bb37e7ad)
