### ISSUE TITLE
Etcd cluster is unhealthy

### ISSUE THREAD

**Issue by thapld** [goodrain/rainbond#1680]
**Describe the bug**
Connect all nodes and install kubernetes cluster. The time consumption depends on the network condition.

[etcd] Failed to bring up Etcd Plane: etcd cluster is unhealthy: hosts [15.235.203.241] failed to report healthy. Check etcd container logs on each host for more information

**lsb_release -a:**
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

**docker logs etcd:**

{"level":"info","ts":"2023-06-23T17:23:11.959Z","caller":"embed/etcd.go:479","msg":"starting with peer TLS","tls-info":"cert = /etc/kubernetes/ssl/kube-etcd-15-235-203-241.pem, key = /etc/kubernetes/ssl/kube-etcd-15-235-203-241-key.pem, client-cert=, client-key=, trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true, crl-file = ","cipher-suites":["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"]}
{"level":"info","ts":"2023-06-23T17:23:11.959Z","caller":"embed/etcd.go:368","msg":"closing etcd server","name":"etcd-15.235.203.241","data-dir":"/var/lib/rancher/etcd/","advertise-peer-urls":["https://15.235.203.241:2380"],"advertise-client-urls":["https://15.235.203.241:2379"]}
{"level":"info","ts":"2023-06-23T17:23:11.959Z","caller":"embed/etcd.go:370","msg":"closed etcd server","name":"etcd-15.235.203.241","data-dir":"/var/lib/rancher/etcd/","advertise-peer-urls":["https://15.235.203.241:2380"],"advertise-client-urls":["https://15.235.203.241:2379"]}
{"level":"fatal","ts":"2023-06-23T17:23:11.959Z","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"listen tcp 0.0.0.0:2380: bind: address already in use","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/go/src/go.etcd.io/etcd/release/etcd/server/etcdmain/etcd.go:204\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/go/src/go.etcd.io/etcd/release/etcd/server/etcdmain/main.go:40\nmain.main\n\t/go/src/go.etcd.io/etcd/release/etcd/server/main.go:32\nruntime.main\n\t/go/gos/go1.16.15/src/runtime/proc.go:225"}

I cannot add cluster to rainbond. Please help me?

**Comment by yangkaa** [comment]
```
{"level":"fatal","ts":"2023-06-23T17:23:11.959Z","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"listen tcp 0.0.0.0:2380: bind: address already in use"}
```

The last line of your log indicates that the 2380 port on this node is occupied, causing etcd to fail to start. So you need to find out which program on that node occupies port 2380 and process it.

**Comment by thapld** [comment]
No. I think it's a bug during rainbond installation.
Checking:
**1. netstat -ano -p tcp | grep 2380**
tcp        0      0 15.235.203.241:2380     0.0.0.0:*               LISTEN      37209/etcd           off (0.00/0/0)

**2. kill -9 37209**
**3. install init-node**
export SSH_RSA="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAeBQySHRqeXwrDIvx+mfRKjxCwvvLvh6eHeR2L15hEzpB/udZAmcnSR3DiGovT+QpDlnTvqua9rEttXQ4ih36DL+19yrXFXiXQr7dgX4JNq+10ii3ydaV/6/YNLK4nR2AbAOnLUDP8aQl1hBVPkF4KOPfwpQjDYjbFu5g6UJsPEqI8AM+Eoj2kRaXoqUv2DQ7kw4/qSeP2ulFM9ypPU89C8Yg3XUAksPmK9AthSV5H9t2dyzMEzTXNGdiSrJIXOBC1MF/9/GjSq9IUIcP+GuVKIVghIiVcRaQKG43owA38WszZ/kEjLTgtsEjEA2KPJ9MFSAEppGHJ/huO6RZ2BmD" && curl -sfL https://get.rainbond.com/init_node | bash

**4. recheck port 2380**
tcp        0      0 15.235.203.241:2380     0.0.0.0:*               LISTEN      37265/etcd           off (0.00/0/0)

**5. kill -9 37265**
**6. Click OK web UI to install cluster**
Connect all nodes and install kubernetes cluster. The time consumption depends on the network condition.

[etcd] Failed to bring up Etcd Plane: etcd cluster is unhealthy: hosts [15.235.203.241] failed to report healthy. Check etcd container logs on each host for more information

{"level":"info","ts":"2023-06-25T15:33:29.057Z","caller":"embed/etcd.go:479","msg":"starting with peer TLS","tls-info":"cert = /etc/kubernetes/ssl/kube-etcd-15-235-203-241.pem, key = /etc/kubernetes/ssl/kube-etcd-15-235-203-241-key.pem, client-cert=, client-key=, trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true, crl-file = ","cipher-suites":["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"]}
{"level":"info","ts":"2023-06-25T15:33:29.058Z","caller":"embed/etcd.go:368","msg":"closing etcd server","name":"etcd-15.235.203.241","data-dir":"/var/lib/rancher/etcd/","advertise-peer-urls":["https://15.235.203.241:2380"],"advertise-client-urls":["https://15.235.203.241:2379"]}
{"level":"info","ts":"2023-06-25T15:33:29.058Z","caller":"embed/etcd.go:370","msg":"closed etcd server","name":"etcd-15.235.203.241","data-dir":"/var/lib/rancher/etcd/","advertise-peer-urls":["https://15.235.203.241:2380"],"advertise-client-urls":["https://15.235.203.241:2379"]}
{"level":"fatal","ts":"2023-06-25T15:33:29.058Z","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"listen tcp 0.0.0.0:2380: bind: address already in use","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/go/src/go.etcd.io/etcd/release/etcd/server/etcdmain/etcd.go:204\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/go/src/go.etcd.io/etcd/release/etcd/server/etcdmain/main.go:40\nmain.main\n\t/go/src/go.etcd.io/etcd/release/etcd/server/main.go:32\nruntime.main\n\t/go/gos/go1.16.15/src/runtime/proc.go:225"}


I think have a bug in your project.
I can provide my vps for checking.

**Comment by yangkaa** [comment]
Etcd is run by the docker container, so your kill process etcd will still be automatically restarted and may need to clean up the environment. I can help you on slack.

**Comment by thapld** [comment]
I did reset ubuntu and reinstall docker and rainbond. It's work.
Thank you so much!
