### ISSUE TITLE
Pig component cannot load config from pig-register

### ISSUE THREAD

**Issue by thapld** [goodrain/rainbond#1684]
**Describe the bug**
pig-upms-biz component cannot load config from pig-register, so it cannot start

**Screenshots**
![image](https://github.com/goodrain/rainbond/assets/38736191/3543f429-6b71-4e61-a0d8-477d2d5991be)

![image](https://github.com/goodrain/rainbond/assets/38736191/8bda9972-b51f-4aac-94b2-3e3d9ea20624)

![image](https://github.com/goodrain/rainbond/assets/38736191/cfd9bb45-b18c-4b31-9e3a-9e1ca322fa89)

![image](https://github.com/goodrain/rainbond/assets/38736191/d30ed959-afd5-4cd6-a42d-01d850d96a42)

![image](https://github.com/goodrain/rainbond/assets/38736191/0f50312b-9795-4b6a-91cb-59f4246dca0c)

**The relevant information:**
 - Rainbond Version [e.g. 5.14.2]

**Comment by yangkaa** [comment]
I think maybe you can deploy a Pig application through the application market first. Our application store already has a Pig that you can use directly.

**Comment by thapld** [comment]
I cannot register market with international phone.

**Comment by thapld** [comment]
Thank you so much

**Comment by yangkaa** [comment]
> I cannot register market with international phone.

If anyone's international mobile phone number cannot access the application market, you can contact me for authorization.
