### ISSUE TITLE
无状态组件实现挂载到自己搭建的CEPH集群上

### ISSUE THREAD

**Issue by identify4cloud** [goodrain/rainbond#1687]
现在每次构建完组件都得再删一次存储，改成有状态组件，在重新挂载存储，感觉挺浪费时间的，不知能否实现无状态组件也可以挂载到自己搭建的存储集群上

**Comment by yangkaa** [comment]
后续打算支持直接使用集群中的 sc 作为共享存储。目前针对你说的这种情况，可以在组件创建的引导流程中直接设置。
<img width="1439" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/d576cabb-5aa3-4cfc-911d-737343131661">

<img width="1429" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/52280f2f-695e-4619-bf96-16a59e9d2a3a">

**Comment by ZhangSetSail** [comment]
支持了共享存储自定义存储。详细使用方式：
1. 等待 Rainbond v5.14.3 版本的发布后升级。
2. 确定自定义存储的 storageclass 名称。
3. 编辑 rbdcomponent  类型资源 的 rbd-worker
```
kubectl edit rbdcomponent rbd-worker -nrbd-system
```
spec字段中添加如下行
```
spec:
  args:
  - --shared-storageclass=你的自定义存储的storageclass名称
```
