### ISSUE TITLE
UG REPORT: Invalid Semantic Version node when Publishing the components of node

### ISSUE THREAD

**Issue by nzb15555196162** [goodrain/rainbond#1690]
## The requirements?
Publish the components of node

error Invalid Semantic Version node
![image](https://github.com/goodrain/rainbond/assets/18350673/8fe4bf26-5d97-4ce3-b09c-1edae97f3246)

**Comment by yangkaa** [comment]
Can you provide the corresponding Rainbond version and the configuration of the build source parameters for this component?

You might be able to try building with other node versions

**Comment by nzb15555196162** [comment]
> Can you provide the corresponding Rainbond version and the configuration of the build source parameters for this component?
> 
> You might be able to try building with other node versions

I'm currently investigating Rainbond, publishing the nodejs program according to the official document.
Using the official demo, switching all the official node versions, it is the same error.
Below is my component configuration:
Rainbond version:  v5.14.2-43ce18361-2023-06-20-14-allinone
BUILD_NODE_ENV: production
NPM MIRROR_URL: https://registry.npmmirror.com
YARN MIRROR_URL: https://registry.npmmirror.com
![image](https://github.com/goodrain/rainbond/assets/18350673/b318d1f4-41c0-4db1-b9c0-907967980ab3)
![image](https://github.com/goodrain/rainbond/assets/18350673/9b50e0e2-3634-435e-833e-294a84545c58)

**Comment by nzb15555196162** [comment]
> Can you provide the corresponding Rainbond version and the configuration of the build source parameters for this component?
> 
> You might be able to try building with other node versions

hava you any idea about this problem?

**Comment by yangkaa** [comment]
Does your machine have access to the external network? It seems that [this part of the code](https://github.com/goodrain/builder/blob/aebde6fee643e27420b7bae93cec7bc698e16ff2/buildpacks/heroku-buildpack-nodejs/lib/failure.sh#L183) failed to install the node binary. Or you can check whether the rbd-resource-proxy under the rbd-system namespace is working properly?

**Comment by nzb15555196162** [comment]
> 

have fixed node download but build stage error message:
![image](https://github.com/goodrain/rainbond/assets/18350673/486f827d-0ba7-441d-bb12-a07898060a34)
how to fix permission error

**Comment by yangkaa** [comment]
You may want to check whether the rbd-gateway or rbd-hub in the cluster is working properly. The real mistake is “connect: no route to host”, So you have to make sure that the image registry is working properly.

**Comment by ivannie153177** [comment]
have been fixed

**Comment by nzb15555196162** [comment]
have been fied, but do not reason, because just redeploy
