### ISSUE TITLE
GitLab 部署后无法修改配置文件

### ISSUE THREAD

**Issue by Sunzhuokai** [goodrain/rainbond#1692]
**Describe the bug**
安装应用商店的Gilab后，想修改配置文件，通过配置文件设置后无法生效，日志报`cp: cannot create regular file '/home/git/gitlab/config/gitlab.yml': Read-only file system`错误
![image](https://github.com/goodrain/rainbond/assets/8599906/f260c172-ee3b-408c-b2c4-ad1fab79153d)

**To Reproduce**
![image](https://github.com/goodrain/rainbond/assets/8599906/2475f898-501c-4d41-b339-c6571aa35ce3)
当挂载路径换一个名字，和容器内的配置文件不一样时可以成功

**The relevant information:**
 - Rainbond Version [v5.14.2]
 - Kubernetes version [1.22.3+k3s1]

**Comment by zzzhangqi** [comment]
这不应是 Rainbond 的问题，应用商店 Gitlab 基于 [docker-gitlab](https://github.com/sameersbn/docker-gitlab) 构建，请在该仓库中查询 Issue 并解决
