### ISSUE TITLE
基于镜像构建组件方式配置启动命令未生效

### ISSUE THREAD

**Issue by Wildmanli** [goodrain/rainbond#1698]
**Describe the bug**
rainbond版本：5.14.0
指定 redis:5.0.7 进行镜像部署并指定了启动命令发现不生效（通过查看yaml文件中无指定的command信息）

![image](https://github.com/goodrain/rainbond/assets/31447317/5313db65-8f49-4108-af38-9bdfab9ce581)
![image](https://github.com/goodrain/rainbond/assets/31447317/23b3ca2f-f8d5-4a61-ac45-5efab2b54c88)
![image](https://github.com/goodrain/rainbond/assets/31447317/fdda8961-2846-4b63-8234-e77ac78014d0)

**Comment by quyuancheng** [comment]
我基于5.15.0版本测试了一下，设置启动命令后yaml文件中是有args参数的。
修改构建源的参数需要重新构建，你设置后是否有重新构建
<img width="375" alt="image" src="https://github.com/goodrain/rainbond/assets/67988480/ebff7205-3835-451c-9e03-d835bec41147">

**Comment by quyuancheng** [comment]
我基于5.15.0版本测试了一下，设置启动命令后yaml文件中是有args参数的。
修改构建源的参数需要重新构建，如果还有问题的话可以继续沟通
<img width="532" alt="image" src="https://github.com/goodrain/rainbond/assets/67988480/97d38809-87ac-4c77-b847-80f632bdfa83">
