### ISSUE TITLE
创建java类应用，由于未指定服务器而无法构建

### ISSUE THREAD

**Issue by goodrainzh** [goodrain/rainbond#17]
java类应用构建时在高级选项模块没有指定服务器，官方的默认使用webapp-runner不能实现。

查看builder与buildpack-java-war

- 由于builder预编译时未检测到来自buildpack的procfile变量故没有将服务器信息写入$BUILD_DIR/webserver

- 在buildpack下WEBSERVER变量赋值时报错

**Comment by t5r4e3w2q1** [comment]
构建war包应用时，在war包根目录添加procfile、webserver
- procfile 
格式：web: java $JAVA_OPTS -jar ./webapp-runner.jar --port $PORT ./*.war
示例：web: java -jar ./webapp-runner.jar --port 5000 --session-store redis ./*.war
示例解释：默认端口8080，可指定端口--port 5000。可指定session存储--session-store redis。加载当前目录下所有war包 ./*.war
- webserver
写入现平台支持webapp-runner版本
webapp-runner-7.0.57.2.jar
webapp-runner-8.0.18.0-M1.jar
webapp-runner-8.5.5.2.jar
