### ISSUE TITLE
容器内默认编码设置不正确

### ISSUE THREAD

**Issue by xggz** [goodrain/rainbond#1701]
**Describe the bug**
![image](https://github.com/goodrain/rainbond/assets/8168663/b09fae07-51e0-4092-8750-bb2c6e26d9cd)
容器内默认的编码错误，临时解决办法是增加环境变量：
![image](https://github.com/goodrain/rainbond/assets/8168663/d58a70da-0717-4019-b7a4-619f3691ee3f)

OS：centos 7.9

**To Reproduce**

**Screenshots**

**The relevant information:**
 - Rainbond Version [e.g. 5.14.2]
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version [e.g 1.16.3]

**Comment by yangkaa** [comment]
v5.15.0 has been fixed
