### ISSUE TITLE
建议增加默认使用的配置文件好让用户修改

### ISSUE THREAD

**Issue by lengyue-ck** [goodrain/rainbond#1702]
## 可以增加默认的配置文件
好多虽然有默认的配置文件来运行服务，比如nginx，无需配置直接就可以直接启动起来，但是我们不知道要修改一些什么配置文件，自己去整一份挂载也不知道挂载哪里，挂载了也不知道修改的对不对，所以，直接将服务用的默认的配置文件直接在【环境配置】-【配置文件设置】中直接挂载默认的配置，如果用户需要修改什么就修改什么，而不需要自己再整一整套配置文件
...

**Comment by yangkaa** [comment]
你这个需求具体的场景是什么呢？你部署一个服务，其相关的配置文件就是需要你去查看其文档进行配置的呀。平台如何能判断你的业务所需的配置文件在什么路径下，有什么默认配置？

就拿你说的nginx，它可能有一个根配置文件 nginx.conf，里面会定义 include http/*/*_servers.conf 这样的语句，也就是说 http/*/*_servers.conf 这个目录下的conf文件也都会生效，那平台怎么处理这层呢？

**Comment by lengyue-ck** [comment]
您说的根目录配置文件 ```nginxf.con```平台并没有列出其具体位置，配置文件也没有，我应该如何修改这个主配置文件呢？

**Comment by yangkaa** [comment]
> 您说的根目录配置文件 `nginx.conf`平台并没有列出其具体位置，配置文件也没有，我应该如何修改这个主配置文件呢？

nginx.conf 只是举例，不代表实际文件。配置文件具体如何配置，需要查看对应业务的镜像文档。参考它的文档把配置文件挂载进容器覆盖即可
