### ISSUE TITLE
集群：基于主机创建保持Cannot proceed with upgrade of controlplane since 1 host(s) cannot be reached prior to upgrade

### ISSUE THREAD

**Issue by lengyue-ck** [goodrain/rainbond#1703]
添加两个ssh信息之后等待好久出现

Cannot proceed with upgrade of controlplane since 1 host(s) cannot be reached prior to upgrade

在此之前是可以成功添加集群的，后来我在软件商店安装了【elasticsearch集群版】莫名其妙集群通信异常，之后，我服务器卡死了，我重启后我集群通信还是异常，我想要重新规划集群，但是遇到了上述错误

**Comment by lengyue-ck** [comment]
连接所有节点安装 Kubernetes 集群，耗时取决于网络状况。

[etcd] Failed to bring up Etcd Plane: etcd cluster is unhealthy: hosts [192.168.50.20] failed to report healthy. Check etcd container logs on each host for more information


删除集群重启的时候会报错如下，一直无法创建集群了

**Comment by yangkaa** [comment]
集群通信异常可以参考这个文档排查下：https://www.rainbond.com/docs/troubleshooting/use/cluster-connect

有可能是elasticsearch占用资源过高，服务器资源不够导致的。而你在重新规划集群时，根据这个报错，你需要去对应的服务器查看etcd日志，可以用 docker logs etcd 这个命令查看
