### ISSUE TITLE
构建nodejs应用时Retrieving image goodrain.me/runner:latest-amd64 from registry goodrain.me 

### ISSUE THREAD

**Issue by lengyue-ck** [goodrain/rainbond#1707]
昨天还可以正常构建，今天清了一下集群后再构建提示如下信息，但是其他组件例如mysql，还是可以正常构建，仅仅nodejs应用无法构建，看样子好像是镜像源的问题

builder: Procfile declares types -> web
60
builder: Default process types for Node.js -> web
61
builder:-----> Compiled slug size is 98M
62
code build success
63
create build code job success
64
INFO[0000] Retrieving image goodrain.me/runner:latest-amd64 from registry goodrain.me
65
INFO[0000] Retrieving image manifest goodrain.me/runner:latest-amd64
66
error building image: GET https://goodrain.me/v2/runner/manifests/latest-amd64: MANIFEST_UNKNOWN: manifest unknown; map[Tag:latest-amd64]
67
build image goodrain.me/default-html-parser-nodejs-parser:20230715022422 of new version failure
68
Build runner image failure
69
Build app version from source code failure,build runner image failure
70
建议查看日志定位代码错误

**Comment by yangkaa** [comment]
参考这篇文档https://www.rainbond.com/docs/troubleshooting/use/build#%E7%A7%81%E6%9C%89%E4%BB%93%E5%BA%93%E4%B8%AD-builder-%E9%95%9C%E5%83%8F%E4%B8%A2%E5%A4%B1。但是按照你的报错，可能需要给该镜像打tag为goodrain.me/runner:latest-amd64，再 push 到 goodrain.me
