### ISSUE TITLE
使用官方文档进行部署后，rbd-db-0无法初始化

### ISSUE THREAD

**Issue by whwhw** [goodrain/rainbond#1717]
问题：
rbd-db-0 pod 的rbd-db容器数据库密码错误
步骤：
我在kubenetes上进行 rainbond的部署，参考了官方文档，安装命令如下
`helm install rainbond rainbond/rainbond-cluster -n rbd-system`
在初始化后，rbd-db-0 describe提示
Readiness probe failed: mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
后手动登录rbd-db，使用命令mysql -uroot -p786d0327 提示无法登录
环境描述：
kubenetes，rbd-db镜像为：registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-db:8.0.19

**Comment by yangkaa** [comment]
该密码是从哪里查询的？k8s 版本是什么？
