### ISSUE TITLE
nacos-client 2.2.1无法获取配置

### ISSUE THREAD

**Issue by WhoisX** [goodrain/rainbond#1719]
使用 nacos-client 版本>2.1.2 的项目 会因为容器自动注入了 tenant.id 而导致nacos-client 认为当前运行在 mse环境 从而导致nacos的namespace 错误 而无法获取到nacos server内的配置信息

**Comment by yangkaa** [comment]
rainbond 中的 tenant_id ，会用来收集组件日志信息，或者作为一些筛选条件使用。如果你想要去掉这个环境变量注入，可以删除这行代码，https://github.com/goodrain/rainbond/blob/c1b43e515647fe4e2d5707f7e8edf600c3765e5f/worker/appm/conversion/version.go#L403

然后参考这个文档，重新打包 worker 替换即可。https://rainbond.com/community/contribution/compile/region/

但是可能会导致平台部分功能不可用，具体需要你自己验证。

**Comment by buzilong** [comment]
提供一个临时解决方案
可以通过禁用nacos读取系统TENANT_ID来解决

**Comment by yangfukai** [comment]
![image](https://github.com/goodrain/rainbond/assets/17331289/97cb5b70-c8c7-4916-83f0-6fd15e701c1f)
像我一样，将nacos-client客户端版本降低使用，我尝试了很多办法，只有这个办法是可行的，应该是2.0+的client暂时没有被rainbond兼容

**Comment by WhoisX** [comment]
![image](https://github.com/goodrain/rainbond/assets/4144417/7b342243-ee04-4ff2-b359-bcdce8aaf0c0)
我是这样搞定的 2.2+的客户端可以支持

> ![image](https://user-images.githubusercontent.com/17331289/273557118-97cb5b70-c8c7-4916-83f0-6fd15e701c1f.png) 像我一样，将nacos-client客户端版本降低使用，我尝试了很多办法，只有这个办法是可行的，应该是2.0+的client暂时没有被rainbond兼容

**Comment by shun634501730** [comment]
本质上是都用了tenant_id这个环境变量导致的，具体分析及规避解决详见https://blog.csdn.net/u012383839/article/details/135115269

**Comment by zzzhangqi** [comment]
Rainbond v6 版本已将所有默认注入的变量开头都增加了 _，例如 `_TENANT_ID`，所以不会再跟 Nacos 变量冲突
