### ISSUE TITLE
在同个团队应用模板，会导致第二个应用取消共享挂载

### ISSUE THREAD

**Issue by thrfox** [goodrain/rainbond#1724]
**Describe the bug**
发布的应用每次部署或者升级，共享存储都会消失
经测试，只有在同个团队，应用了多个同组件的情况下会发生

步骤见图
![522c48b8694990843c33eeb707dba2c9](https://github.com/goodrain/rainbond/assets/29697925/cb39b039-92bc-49ff-821e-5af69fafa184)

 - Rainbond Version 5.14.2

**Comment by ZhangSetSail** [comment]
经过测试，并没有复现你所说的问题。
我的步骤如下：
1. 在X团队创建O应用后部署两个组件A、B； A组件依赖B组件的共享存储。
2. 发布A、B组件，版本为1.0
3. 修改A、B组件的存储挂载路径
4. 发布A、B组件，版本为2.0
5. 切换至Y团队的P应用安装1.0版本模版；效果：正常安装且共享存储挂载没问题。
6. 切换Y团队的Q应用内再次安装1.0版本模版；效果：正常安装且共享存储挂载没问题。
7. 升级Q应用内的应用，升级至2.0版本；效果：正常升级且共享存储挂载没问题。
我复现的步骤是否存在遗漏，麻烦对我的步骤进行一下补充。

**Comment by ZhangSetSail** [comment]
该问题长时间没有更新，我将关闭此issue，如果有问题你可以随时重新打开。
