### ISSUE TITLE
OpenAPI没有通过源码创建组件接口

### ISSUE THREAD

**Issue by Juke-github** [goodrain/rainbond#1731]
## The requirements?
OpenAPI没有通过源码创建组件接口，建议开放

## Way:
...

**Comment by yangkaa** [comment]
源码构建需要识别语言，下载代码，传入相应的构建参数。中间涉及到的接口较多。不是一个接口就可以直接完成的。所以目前没有该接口。

你需要该接口的具体场景是什么呢？

**Comment by ZhangSetSail** [comment]
问题长时间没更新，我将关闭它，有问题可以再重新打开
