### ISSUE TITLE
接入自建集群时 后台日志报错

### ISSUE THREAD

**Issue by ElfenSterben** [goodrain/rainbond#1738]
**Describe the bug**
接入自建集群时 后台日志报错
`
15:22 [ERROR] localhost [get] /app/ui/console/views/enterprise.py:602 'NoneType' object has no attribute 'region_id'
File "/app/ui/console/views/enterprise.py", line 597, in get
region_resource = region_services.conver_region_info(region, "yes")
File "/app/ui/console/services/region_services.py", line 595, in conver_region_info
region_resource = self.__init_region_resource_data(region, level)
File "/app/ui/console/services/region_services.py", line 553, in __init_region_resource_data
region_resource["region_id"] = region.region_id
'NoneType' object has no attribute 'region_id'
`

**Screenshots**
![image](https://github.com/goodrain/rainbond/assets/19554131/aa8b9877-e300-4699-8071-f3c6a07d4ba3)

**The relevant information:**
 - Rainbond Version:  v5.15.0-release-dc96b875e-2023-08-01-13-allinone
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version: 1.27.4

**Comment by yangkaa** [comment]
通过哪种方式安装并接入的？

**Comment by ElfenSterben** [comment]
> 通过哪种方式安装并接入的？

通过 docker 启动 rainbond 的 allinone 镜像之后，选择 平台管理 > 集群 -> 添加集群 -> 接入自建集群，然后按照  接入自建集群 的指示操作完成安装之后，在 rainbond 的集群接入等待页面依旧提示错误，查看 rainbond 的日志发现如问题所示的错误

**Comment by yangkaa** [comment]
那这可能是一个bug，你现在应该可以通过以下方式绕过

1. 安装 grctl 命令行工具 https://www.rainbond.com/docs/ops-guide/tools/grctl
2. 在已经安装好 rainbond 集群端的集群中，执行 grctl config
3. 复制输出的所有内容后回到控制台
4. 平台管理 > 集群 -> 添加集群，此时右上角有三个横着的点，鼠标移动上去，选择接入已安装平台集群，如下图所示
<img width="1371" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/2a8694ae-6409-4474-9711-7b0db1ed3fb8">
5. 把第三步复制的内容，粘贴在配置里，上面的集群ID和集群名自定义即可。点击保存应该就可以对接成功

**Comment by zzzhangqi** [comment]
在5.17、6.0版本中已解决
