### ISSUE TITLE
希望支持构建镜像缓存自动回收机制，避免长期占用磁盘资源

### ISSUE THREAD

**Issue by Wildmanli** [goodrain/rainbond#1739]
![image](https://github.com/goodrain/rainbond/assets/31447317/f10cd4a7-e06a-4762-a13e-3216b2bced98)

**Comment by ZhangSetSail** [comment]
https://github.com/goodrain/rainbond/pull/1732

**Comment by yangkaa** [comment]
在 v5.15.2 中已支持内部镜像仓库的构建版本自动回收。默认保留 5 个版本
