### ISSUE TITLE
第三方应用安装报错 无法pull应用镜像

### ISSUE THREAD

**Issue by zht1026020644** [goodrain/rainbond#1742]
【需求描述】(非需求请删除本行)
 
【BUG描述】(非BUG请删除本行)

【部署环境】
- Rainbond版本(执行`grctl version`获取): [请填写此处]
- 操作系统类型和版本:[请填写此处]
- 离线部署/网络开放：[请填写此处]
![image](https://github.com/goodrain/rainbond/assets/52768979/7299ae8f-80c8-474b-8ec2-dcd16ac1bc0a)
 Pulling image "goodrain.me/zjlab-mysql-gr1b417e:20230822165802"
  Warning  Failed            4m28s (x4 over 5m58s)  kubelet            Failed to pull image "goodrain.me/zjlab-mysql-gr1b417e:20230822165802": failed to pull and unpack image "goodrain.me/zjlab-mysql-gr1b417

**Comment by yangkaa** [comment]
这是因为 goodrain.me 是一个自签发证书，不受信，你可以参考这个文档配置下证书。

https://www.rainbond.com/docs/troubleshooting/use/build/#%E6%B2%A1%E6%9C%89%E9%85%8D%E7%BD%AE-containerd-%E7%A7%81%E6%9C%89%E9%95%9C%E5%83%8F%E4%BB%93%E5%BA%93%E8%AF%81%E4%B9%A6

**Comment by yangkaa** [comment]
是完全按照文档操作过了吗？需要重启每个节点的 containerd 才行。你也可以直接搜下 containerd x509 如何解决

**Comment by zht1026020644** [comment]
> 是完全按照文档操作过了吗？需要重启每个节点的 containerd 才行。你也可以直接搜下 containerd x509 如何解决

是的

**Comment by zht1026020644** [comment]
> 

![image](https://github.co
![image](https://github.com/goodrain/rainbond/assets/52768979/3a892fee-dd97-4cd5-a4d2-21af9eb9d7b4)
![image](https://github.com/goodrain/rainbond/assets/52768979/26593c04-3567-48a4-9ac7-e6b538e93740)

m/goodrain/rainbond/assets/52768979/e5ec9dba-8d8d-4b27-b469-ee60f2599729)

**Comment by zht1026020644** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > 
> 
> ![image](https://github.co ![image](https://user-images.githubusercontent.com/52768979/264514300-3a892fee-dd97-4cd5-a4d2-21af9eb9d7b4.png) ![image](https://user-images.githubusercontent.com/52768979/264514361-26593c04-3567-48a4-9ac7-e6b538e93740.png)
> 
> m/goodrain/rainbond/assets/52768979/e5ec9dba-8d8d-4b27-b469-ee60f2599729)
![image](https://github.com/goodrain/rainbond/assets/52768979/7c1b628c-4b87-4195-bbee-6e88f312b2ee)

**Comment by yangkaa** [comment]
不太确定你上面的 disable-plugins 是否有影响，如果 goodrain.me 实在无法配置好，你还可以尝试更换为外部镜像仓库，可以参考 https://www.rainbond.com/docs/ops-guide/management/switch-registry/ ，这样就直接 push 到外部镜像仓库了，就不会用 goodrain.me 这个证书。

**Comment by zht1026020644** [comment]
> 不太确定你上面的 disable-plugins 是否有影响，如果 goodrain.me 实在无法配置好，你还可以尝试更换为外部镜像仓库，可以参考 https://www.rainbond.com/docs/ops-guide/management/switch-registry/ ，这样就直接 push 到外部镜像仓库了，就不会用 goodrain.me 这个证书。

使用第三方仓库需要类似goodrain.me配置吗 类似harbor containerd需要配置吗

**Comment by yangkaa** [comment]
如果你的证书是可信证书，那就不需要配置，只要 kubelet 能正常拉取镜像，那就没问题。

证书如果也是自签发证书，则需要配置。

如果使用公有云厂商的，也不需要额外配置。
