### ISSUE TITLE
应用商店电话号码验证不支持19号段

### ISSUE THREAD

**Issue by NeufHuang** [goodrain/rainbond#1746]
**Describe the bug**
如图：
![rainbond-bug](https://github.com/goodrain/rainbond/assets/56258692/5974d5b2-a130-4e2f-81d2-7c9397b8dda3)
**To Reproduce**

**Screenshots**

**The relevant information:**
 - Rainbond Version [e.g. 5.2.0]
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version [e.g 1.16.3]

**Comment by RainBondsongyg** [comment]
应用市场已支持19号段，我将关闭该问题，如还有问题请重新打开。
