### ISSUE TITLE
拓扑图使用的是什么插件？

### ISSUE THREAD

**Issue by pluslicy** [goodrain/rainbond#175]
If you want to report a bug or advice, please provide the following information and try to describe your issue in English, If it's a question of use,please read the [documentation](https://www.rainbond.com/docs/stable/) or browse the [community](https://t.goodrain.com/)

- [ ] Rainbond versions(eg. grctl version)

- [ ] Kubernetes versions(If you use your own cluster)

- [ ] Operating system and kernel

- [ ] Provider(Aliyun,VirtualBox,...)

- [x] Install details(Online/Offline,SingleNode/HA)

**Comment by barnettZQG** [comment]
@pluslicy We are happy to answer your questions. Please complete your questions

**Comment by barnettZQG** [comment]
Issues timeout closed.
