### ISSUE TITLE
由docker run命令创建的应用，不显示docker run命令

### ISSUE THREAD

**Issue by hanxinhisen** [goodrain/rainbond#1753]
版本:v5.15.0,其实之前版本也不现实，还以为故意隐藏。但在请求的api中找到该参数，觉得应该是个前端bug，故提之。
![image](https://github.com/goodrain/rainbond/assets/7082486/47ad4216-73c1-4363-a6e6-b257e1dcf661)

![image](https://github.com/goodrain/rainbond/assets/7082486/64c37228-4feb-401f-a01b-a949c03ca48c)

**Comment by yangkaa** [comment]
启动命令是你在镜像最后跟的参数。例如 
```bash
docker run --name seata-server -p 8091:8091 -e SEATA_CONFIG_NAME=file:/root/seata-config/registry  seataio/seata-server:1.7.0 start
```
那么最后的启动命令识别出来就是 start。如果你后面不指定参数，那就为空。

不展示完整命令是因为这里面的存储、端口、环境变量都已经转换成了平台的组件模型，识别到对应属性下了。如果用户手动命令里的值，比如环境变量。就和配置里的变量值不符，不易管理。

**Comment by hanxinhisen** [comment]
其实显示出来，也不是为了改啥，而是在其他云邦环境中，想部署相同的应用时， 找不到对应的docker run命令了
