### ISSUE TITLE
rainbond部署nacos 2.2.0版本,服务列表无法显示其他组件

### ISSUE THREAD

**Issue by chengshuaigithub** [goodrain/rainbond#1757]
问题如下:
在rainbond部署的nacos组件,服务列表没有显示其他已经注册的
![05f5d3d6e25b48655f9df112b6dc825](https://github.com/goodrain/rainbond/assets/22317516/1caa89ad-f793-4278-a5c7-30b30d67f5a5)
![e43364372357212dccb18025d7c1f25](https://github.com/goodrain/rainbond/assets/22317516/ca936b14-47da-4ed5-99be-cee731d020fe)
![eda526861a433221451ec325be28122](https://github.com/goodrain/rainbond/assets/22317516/05883ac7-08da-4c81-8e86-4ac064611a59)
![fdc8a3abbce4659840b41e09bda70ab](https://github.com/goodrain/rainbond/assets/22317516/56afc3e4-6c85-41ef-93b0-54c6a4a2030a)

这是rainbond nacos端口配置, 终端telnet和本地telnet结果, 浏览器可以正常访问 ip:端口/nacos  但是其他组件在rainbond上可以启动成功, 无法显示在nacos服务列表,  本地组件无法连接, 有人遇到过相同问题吗 ? 帮忙提供个排查思路

**Comment by hanxinhisen** [comment]
其他应用通过添加依赖的方式访问nacos的吗，如果是，就把服务治理模式改成内置。
![image](https://github.com/goodrain/rainbond/assets/7082486/ccfdfcd7-ec20-40e7-aaf2-0b8c7cee3f65)

**Comment by chengshuaigithub** [comment]
> 其他应用通过添加依赖的方式访问nacos的吗，如果是，就把服务治理模式改成内置。 ![image](https://user-images.githubusercontent.com/7082486/265943382-ccfdfcd7-ec20-40e7-aaf2-0b8c7cee3f65.png)

是的, 应用的治理模式是, 并且组件依赖关系已经建立, 通过对内域名连接和别名连接都试过
![1693989699452](https://github.com/goodrain/rainbond/assets/22317516/b0cff057-530a-43a6-9f4c-0efacbfc1124)
![微信截图_20230906164510](https://github.com/goodrain/rainbond/assets/22317516/ed9ed3e7-854f-457a-81b1-632de6cf4437)
