### ISSUE TITLE
java实例伸缩的内存设置3G/5G时，内存优化失败

### ISSUE THREAD

**Issue by xggz** [goodrain/rainbond#1759]
Optimizing java process for 1G Memory....
Picked up JAVA_TOOL_OPTIONS: -Xms720m -Xmx720m -Xss512k -XX:MaxDirectMemorySize=96M -Dfile.encoding=UTF-8

Optimizing java process for 2G Memory....
Picked up JAVA_TOOL_OPTIONS: -Xms1420m -Xmx1420m -Xss512k -XX:MaxDirectMemorySize=192M -Dfile.encoding=UTF-8

这是3G的失败日志：
The environment variable $MEMORY_SIZE was not identified,The Java process will not be optimized....
Since there is no limit on instance memory, JVM memory is not set

Optimizing java process for 4G Memory....
Picked up JAVA_TOOL_OPTIONS: -Xms2840m -Xmx2840m -Xss512k -XX:MaxDirectMemorySize=384M -Dfile.encoding=UTF-8

这是5G的失败日志：
The environment variable $MEMORY_SIZE was not identified,The Java process will not be optimized....
Since there is no limit on instance memory, JVM memory is not set

**Comment by xggz** [comment]
除了设置为1G，估计其它奇数内存都会优化失败

**Comment by DokiDoki1103** [comment]
请问您的builer 的版本是多少？

**Comment by xggz** [comment]
之前忘记哪个版本了，升级到5.16后没有这个问题了
