### ISSUE TITLE
使用harbor作为镜像仓库 部署第三方应用没有问题 不是自己的java项目构建时出现这个问题

### ISSUE THREAD

**Issue by zht1026020644** [goodrain/rainbond#1765]
![image](https://github.com/goodrain/rainbond/assets/52768979/8460ecba-d06f-4fe3-a62a-aa879219954f)
使用harbor作为镜像仓库 部署第三方应用没有问题 不是自己的java项目构建时出现这个问题 而且harbor认证是配置好了的？这个怎么解决呀？

**Comment by zht1026020644** [comment]
是需要配置maven和setting?

**Comment by yangkaa** [comment]
IP 是你的 Harbor 仓库地址吗？可以通过以下命令，先查出 rbd-system 命名空间下的 configmap
```bash
kubectl get cm -nrbd-system
```

然后找到名称为 `goodrain-me` 或 你自己 harbor 地址的 configmap。编辑它。主要编辑以下内容

```yaml
apiVersion: v1
data:
  buildkittoml: |-
    debug = true
    [registry."goodrain.me"]
      http = false
      insecure = true
    [registry."192.168.46.21"]
      http = false
      insecure = true
kind: ConfigMap
```
如果你的仓库有证书，就如我上面配置就行。如果仓库没有证书，就设置 `http = true` 一个参数就行

**Comment by zht1026020644** [comment]
> IP 是你的 Harbor 仓库地址吗？可以通过以下命令，先查出 rbd-system 命名空间下的 configmap
> 
> ```shell
> kubectl get cm -nrbd-system
> ```
> 
> 然后找到名称为 `goodrain-me` 或 你自己 harbor 地址的 configmap。编辑它。主要编辑以下内容
> 
> ```yaml
> apiVersion: v1
> data:
>   buildkittoml: |-
>     debug = true
>     [registry."goodrain.me"]
>       http = false
>       insecure = true
>     [registry."192.168.46.21"]
>       http = false
>       insecure = true
> kind: ConfigMap
> ```
> 
> 如果你的仓库有证书，就如我上面配置就行。如果仓库没有证书，就设置 `http = true` 一个参数就行

![image](https://github.com/goodrain/rainbond/assets/52768979/41cb6154-c762-4f05-aaf1-9c7997027032)
好像没有

**Comment by zht1026020644** [comment]
没有的话自己创建一个名为ip地址的cm？

**Comment by zht1026020644** [comment]
> ```yaml
> [registry."goodrain.me"]
>       http = false
>       insecure = true
> ```

![image](https://github.com/goodrain/rainbond/assets/52768979/263ebcb8-d543-4547-a6ce-d5b172039985)
好像还是不行

**Comment by zht1026020644** [comment]
我直接在本地docker直接pull和push是没问题的

**Comment by zht1026020644** [comment]
![image](https://github.com/goodrain/rainbond/assets/52768979/ba0baa02-761b-4eb1-b8a4-807e476aeffe)
而且我直接部署第三方应用是没有问题的

**Comment by zht1026020644** [comment]
需要在cm中加入账号密码？

**Comment by zht1026020644** [comment]
> IP 是你的 Harbor 仓库地址吗？可以通过以下命令，先查出 rbd-system 命名空间下的 configmap
> 
> ```shell
> kubectl get cm -nrbd-system
> ```
> 
> 然后找到名称为 `goodrain-me` 或 你自己 harbor 地址的 configmap。编辑它。主要编辑以下内容
> 
> ```yaml
> apiVersion: v1
> data:
>   buildkittoml: |-
>     debug = true
>     [registry."goodrain.me"]
>       http = false
>       insecure = true
>     [registry."192.168.46.21"]
>       http = false
>       insecure = true
> kind: ConfigMap
> ```
> 
> 如果你的仓库有证书，就如我上面配置就行。如果仓库没有证书，就设置 `http = true` 一个参数就行

是不是因为不同命名空间下无法使用这个configmap 因为我的创建的应用在test项目里，也就自动创建了一个test的命名空间 而这个configmap在rbd-system命名空间下。

**Comment by yangkaa** [comment]
配置了以后，构建日志失败原因是什么呢？那个 cm 就是在 rbd-system 下就行

**Comment by zht1026020644** [comment]
> 配置了以后，构建日志失败原因是什么呢？那个 cm 就是在 rbd-system 下就行
原因还是权限，还是和第一张图结果一样

**Comment by yangkaa** [comment]
```yaml
apiVersion: v1
data:
  buildkittoml: |-
    debug = true
    [registry."goodrain.me"]
      http = false
      insecure = true
    [registry."192.168.46.21"]
      http = true
kind: ConfigMap
```
尝试参考以上内容，只使用 http 协议，查看是否可以构建成功，或者不要使用自签发证书

**Comment by ZhangSetSail** [comment]
该issue长时间未更新，我先关闭，如果有问题再重新打开
