### ISSUE TITLE
对接集群多次出现通信异常的情况，始终无法恢复

### ISSUE THREAD

**Issue by Juke-github** [goodrain/rainbond#1766]
![image](https://github.com/goodrain/rainbond/assets/61927670/0c1d313c-047c-4520-9b92-edc8104fce1b)
对接集群多次出现通信异常的情况，始终无法恢复，只能通过删除集群后再对接解决，如果部署集群部署了大量应用，无法恢复通信，就会存在巨大隐患。
日志出现过以下异常
![image](https://github.com/goodrain/rainbond/assets/61927670/a3d6425f-c978-4419-8c33-8cef7a1f178d)
对接集群中的rbd-api服务也无法重启

**Comment by ZhangSetSail** [comment]
是否有前因呢，光从通信异常看不出来问题，比如 服务器是否重启后 ip 变更；或者 rbd-api 未启动成功；集群网络问题；等等因可能导致的因素，你可以按照 [通信异常排查文档](https://www.rainbond.com/docs/troubleshooting/use/cluster-connect/) 逐步排查一下，如果有问题可以继续在此issues沟通，不过在微信群问的话解决起来会快一些。

**Comment by shengrongchun** [comment]
我也遇到了同样的情况，请问如何解决呢

**Comment by ZhangSetSail** [comment]
> 我也遇到了同样的情况，请问如何解决呢

麻烦提供下详细的日志

**Comment by shengrongchun** [comment]
这个问题估计就是rainbond的bug,因为一直都是好好的，然后构建一个组件，不知道是不是这个原因导致的，就集群异常了，有时候会自己好，有时候就一直这样

**Comment by KeKouShi** [comment]
的确也遇见了这个情况，每日崩一次，每次遇到就得重启机器。
1. 目前看到的现象是控制台显示集群通信异常，rbd-api 状态显示没有 ready，通过查看日志显示
event log server rbd-eventlog:6366 connect error: context canceled. auto retry after 10 seconds "
time="2024-08-20T00:48:56+08:00" level=error msg="create event client error.context canceled
2. 物理机执行 df -h卡顿，在集群中手动删除rbd-api，删除后pod状态会显示ContainerCreating， Warning  FailedMount  2m10s  kubelet            Unable to attach or mount volumes: unmounted volumes=[grdata], unattached volumes=[grdata kube-api-access-686sb]: timed out waiting for the condition

**Comment by zzzhangqi** [comment]
这类问题可以算是架构设计上的问题，在 v5 版本中，Rainbond 强依赖 NFS 存储才能启动，通常在 v5 版本中大多数都是对接外部存储，大概率不会遇到存储挂载不上导致服务无法启动或者通信异常的问题。而大多数用户都不会对接外部存储，而是选择使用默认的 NFS 存储，默认 NFS 存储是运行在 Pod 中，通过 Service IP进行 Mount 挂载操作，一旦 K8s 集群间的 Service IP 无法通信那就会导致存储无法挂载，从而导致集群异常，部分强依赖存储的服务无法启动。

在已发布的 v6 版本中，Rainbond 所有服务对于 NFS 存储的强依赖已移除，也就是说这类问题以后不会在 v6 版本中出现。
