### ISSUE TITLE
部署java应用出错

### ISSUE THREAD

**Issue by zht1026020644** [goodrain/rainbond#1767]
![image](https://github.com/goodrain/rainbond/assets/52768979/25b14ec0-5e02-41a6-86e0-29f7f5770a1a)
![f70fbba6ec30ecfd7e6d615d25582a7c](https://github.com/goodrain/rainbond/assets/52768979/4f155690-302c-4e40-bcbc-da1c845ab7eb)
![image](https://github.com/goodrain/rainbond/assets/52768979/0e274fde-4f28-4939-95eb-5d42b23b1f8d)
![image](https://github.com/goodrain/rainbond/assets/52768979/e75d5227-fad5-4151-8c89-1087c187aadc)
![image](https://github.com/goodrain/rainbond/assets/52768979/17aa3b51-8996-43e4-8fb0-088e530924b7)
命名空间test下有harbor hub账号密码 而且cm配置了仓库

**Comment by ZhangSetSail** [comment]
查看一下 rbd-system 命名空间下是否有一个类似于你镜像仓库地址的 cm（configmap）资源。查看是否有创建出来。
