### ISSUE TITLE
新增集群运行时使用的containerd会部署失败

### ISSUE THREAD

**Issue by ly-wjj** [goodrain/rainbond#1771]
新增集群时，使用的k8s 1.26版本，runtime是containerd。生成的部署命令中不存在运行的环境变量增加，会导致部署失败。
建议增加一个容器运行时的选择，保证变量能够改变。--set operator.env[3].name=CONTAINER_RUNTIME --set operator.env[3].value=containerd

**Comment by zzzhangqi** [comment]
v5.17.1 已解决，参考文档进行[升级](https://www.rainbond.com/docs/upgrade/latest-version) @ly-wjj
