### ISSUE TITLE
helm安装应用启动时异常

### ISSUE THREAD

**Issue by wshlfx** [goodrain/rainbond#1777]
**Describe the bug**

**To Reproduce**
1. 直接在k8s集群的master机器中执行 helm upgrade --install mongodb    --set db.username=admin     --set db.password=fdeb0332e9483     --set storage.size=50Gi  coding/mongodb 可以安装成功
2. 在rainbond中执行 helm install mongodb coding/mongodb   --set db.username=admin     --set db.password=fdeb0332e9483     --set storage.size=50Gi   安装不成功，在私有应用商店中选择安装也是一样，错误信息如下：

cp: missing file operand
2
Try 'cp --help' for more information.

**Screenshots**
<img width="785" alt="88f7056e57bee7d5dbc7f38b047db5e" src="https://github.com/goodrain/rainbond/assets/30335651/d73a47cd-fd7f-43a2-8df2-254e0c03707b">

![d99e52c9a162ae0bb02980bda78482b](https://github.com/goodrain/rainbond/assets/30335651/880141fb-9915-4d4f-9a64-2614520a9191)

**The relevant information:**
 - Rainbond  5.15.2-release-599daa51b-2023-09-10-15-allinone
 - Browser hromium 101.0.4951.64 
 - Kubernetes version 1.23.10

**Comment by ZhangSetSail** [comment]
This is partly because our command line attribute fields have limitations, and we need to consider how to design them.

**Comment by ZhangSetSail** [comment]
5.17.2版本已发布，该问题在5.17.2已经得到修复，你可以参考[升级文档](https://rainbond.com/docs/upgrade/latest-version)进行升级，我将关闭此issue，如果有问题你可以随时重新打开。
