### ISSUE TITLE
SpringCloud Nacos Rainbond 负载均衡问题

### ISSUE THREAD

**Issue by lokywang** [goodrain/rainbond#1787]
我们使用Rainbond 作为PaaS平台,治理模式为:内置 ServiceMesh 模式

服务为SpringCloud框架的微服务,Nacos作为服务的注册发现.
Nacos部署在物理机上
![image](https://github.com/goodrain/rainbond/assets/28672424/0d27e239-c915-44a7-951f-ed1a140c4478)

通过第三方引用的方式,其他服务可以在Nacos注册发现
![image](https://github.com/goodrain/rainbond/assets/28672424/53c4b229-f10d-488b-bad7-9b11ab691f9a)

![image](https://github.com/goodrain/rainbond/assets/28672424/e8893ce7-7c98-4485-91cc-5ad65ea02461)

现在碰到的问题是服务之间没有负载均衡调用
![image](https://github.com/goodrain/rainbond/assets/28672424/794568e1-2dd5-4653-b441-578b6996ea4e)
![image](https://github.com/goodrain/rainbond/assets/28672424/c5954fef-3383-4711-9a7c-f507cbf7eda8)

会出现服务满载,而其他服务负载很低的情况,通过Nacos进行下线高负载应用时,另一台服务CPU则服务满载

这种情况应该是什么问题导致的呢?
Service Mesh的负载均衡机制问题吗?

查询了一些资料,还是没有头绪~
感谢帮助~~~

**Comment by zzzhangqi** [comment]
@lokywang 

在没有 nacos 作为注册中心和服务发现时，使用内置 Service Mesh模式，默认情况下 A 组件访问 B 组件，A 通过 127.0.0.1:port 访问 B，当 B 存在多个实例时，会默认负载均衡代理。

采用 Nacos 作为注册中心和服务发现时，仅仅起到服务注册到 Nacos 时的负载均衡，服务之间的调用还是通过 Nacos 代理和分配。

举个例子：有 A 服务（2实例）和 B 服务（2实例）和 Nacos，这时相当于有 4 个实例注册到 Nacos，在 Nacos 中会展示实例注册的 POD IP，当 A 服务调用 B 服务时，A 服务会在 Nacos 中查到 B 服务并获取 B 服务所注册的 POD IP，A 具体访问 B 服务的哪个实例由 Nacos 决定。

所以这一层应该排查你的 Nacos 配置或者代码中的配置，同时我发现你的截图中有 Gateway，这一层是否有 fegin 代理。

从我的经验来看，这个问题跟 Service Mesh 治理模式无关。以上是一些思路，具体还需你再排查，给出更多的排查结果才能更进一步的详细分析问题。

**Comment by ZhangSetSail** [comment]
问题是否得到解决，如果没有什么问题该issues将在明天关闭
