### ISSUE TITLE
Golang 仓库构建时无法保存 GOPRIVATE

### ISSUE THREAD

**Issue by 2997215859** [goodrain/rainbond#1794]
**Describe the bug**

**To Reproduce**

**Screenshots**

**The relevant information:**
 - Rainbond Version [e.g. 5.2.0]
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version [e.g 1.16.3]

![image](https://github.com/goodrain/rainbond/assets/13400243/44be0b54-d6d4-4a2a-a4c7-f555ce05e0a4)
5.16 版本，如图所示，填写完私有仓库地址之后，保存修改，然后重新刷新，参数没有被保存。在环境变量里设置 GOPRIVATE 也并没有生效

**Comment by ZhangSetSail** [comment]
收到，这确实是个问题，在 5.16.0 功能测试的时候漏掉了，近两周将会发小版本修复。
