### ISSUE TITLE
基于主机安装的集群添加新的节点，新节点内存占用过高

### ISSUE THREAD

**Issue by 2997215859** [goodrain/rainbond#1795]
**Describe the bug**

**To Reproduce**

**Screenshots**

**The relevant information:**
 - Rainbond Version [e.g. 5.2.0]
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version [e.g 1.16.3]

基于主机安装的集群添加新的节点，新节点内存占用过高，新节点内存共 128G。
加入集群前，占用 1G 不到；加入集群后（初始化、组件安装）之后达到 99.7 G。
请教下，不知道是不是合理的，现在怀疑自己是不是哪里的操作有问题。
<img width="1662" alt="img_v3_025s_fbe21e1b-827c-400f-ac02-34bd7f6336bg" src="https://github.com/goodrain/rainbond/assets/13400243/49e4ddd2-1a23-46c8-a342-f715a234aada">

**Comment by 2997215859** [comment]
我把 /usr/sbin/rpc.statd 进程 kill 掉了。好像不会对集群有影响。

**Comment by yangkaa** [comment]
/usr/sbin/rpc.statd 是 NFS 的一部分。应该是用于监控 NFS 客户端和服务器连接状态的。这部分应该和 rainbond 无关。如果是生产环境，建议使用稳定的文件存储。如公有云厂商的NAS、Ceph等存储解决方案。

**Comment by ZhangSetSail** [comment]
看看这个[文档](https://www.rainbond.com/docs/installation/install-with-ui/)呢，配置外部存储就不会安装默认的nfs-provisioner。

<img width="1114" alt="image" src="https://github.com/goodrain/rainbond/assets/101104760/ca1de673-1d5c-4d52-b844-1490a50eac1b">

**Comment by ZhangSetSail** [comment]
问题是否得到解决，我可以关闭这个issues了吗

**Comment by 2997215859** [comment]
> 问题是否得到解决，我可以关闭这个issues了吗

可以奥~感谢
