### ISSUE TITLE
重启/关闭按钮改为非强制关闭，给pod中的应用留点关闭时间

### ISSUE THREAD

**Issue by shun634501730** [goodrain/rainbond#1803]
# Bug 描述
问题：RainBond 中的重启/关闭按钮是强行杀掉 pod，导致 pod 中的进程在收到 SIGTERM 信号后，还没有来得及做关闭操作，就被杀掉了。

典型情况：微服务注册到 Nacos，微服务关闭时会从 Nacos 取消注册。如果使用 RainBond 重启/关闭按钮后，则不会从 Nacos 取消注册。继而导致后续请求到这个被杀掉的实例上去，用户看到的效果为请求超时。

版本说明：
● RainBond v5.13.0-release-8e429bff3-2023-04-12-05-allinone
● Kubernetes 1.18
● Docker 19.03.15
● JDK 1.8 + Nacos 2.2.0 + SpringBoot 2.7.17

# 重现步骤
## 第 1 步：创建 微服务 demo
这个是一个微服务 Demo，会注册到 Nacos。
[rainbond-nacos-test.zip](https://github.com/goodrain/rainbond/files/13669970/rainbond-nacos-test.zip)
### Dockerfile 
其 Dockerfile 如下：
```
# 基础镜像
FROM eclipse-temurin:8u342-b07-jdk-centos7
ENV TZ=Asia/Shanghai

# 指定工作目录
WORKDIR /ganlan-cloud

# 添加war/jar到容器内
ARG APP_NAME
ENV APP_NAME=${APP_NAME}
ADD target/${APP_NAME} ${APP_NAME}

# 指定启动脚本
ADD start.sh start.sh
RUN chmod a+x start.sh && sed -i 's/\r//' start.sh

# 容器启动时的执行命令
CMD ["sh", "start.sh"]`

# 基础镜像
FROM eclipse-temurin:8u342-b07-jdk-centos7
ENV TZ=Asia/Shanghai

# 指定工作目录
WORKDIR /ganlan-cloud

# 添加war/jar到容器内
ARG APP_NAME
ENV APP_NAME=${APP_NAME}
ADD target/${APP_NAME} ${APP_NAME}

# 指定启动脚本
ADD start.sh start.sh
RUN chmod a+x start.sh && sed -i 's/\r//' start.sh

# 容器启动时的执行命令
CMD ["sh", "start.sh"]
```
对应的 start.sh 脚本如下：
```
#!/bin/bash
exec java -jar $APP_NAME
```

请自行推送到镜像仓库，假设为 172.24.3.241:5000/enterprise/rainbond-nacos-test:2.7.17。

### shutdown hook
shutdown hook 是 JVM 的一个关闭钩子，用于优雅关闭服务。本质上来说，是 JVM 收到了 SIGTERM 信号后，就会调用我们自己编写 shutdown hook 。

我在代码里加了这样的钩子，方便后面看日志调试。如下：
● 钩子的逻辑：JVM 关闭时，输出日志到控制台，并且延迟 2 秒
```java
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;

import java.time.LocalDateTime;


@EnableDiscoveryClient
@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println(LocalDateTime.now() + "：关闭服务中...........1");
            System.out.println(LocalDateTime.now() + "关闭服务中...........2");
            System.out.println(LocalDateTime.now() + "关闭服务中...........3");
            System.out.println(LocalDateTime.now() + "关闭服务中...........4");
            System.out.println(LocalDateTime.now() + "关闭服务中...........5");
            System.out.println(LocalDateTime.now() + "等我2秒再关闭...");
            try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
            System.out.println(LocalDateTime.now() + "关闭服务中...........6");
            System.out.println(LocalDateTime.now() + "关闭服务中...........7");
            System.out.println(LocalDateTime.now() + "关闭服务中...........8");
            System.out.println(LocalDateTime.now() + "关闭服务中...........9");
            System.out.println(LocalDateTime.now() + "关闭服务中...........10");
        }));
    }

}
```

正常关闭 JVM 应用的日志如下：
● 可以看到，正常情况下，至少会有 NacosServiceRegistry 取消注册的回调
● 其次，有我们自己编写的回调
```
...前面的不重要，略..
2023-12-14 14:56:02.077  INFO 19732 --- [           main] c.a.cloud.examples.DemoApplication       : Started DemoApplication in 9.329 seconds (JVM running for 9.738)
2023-12-14 14:56:50.577  WARN 19732 --- [       Thread-5] c.a.nacos.common.notify.NotifyCenter     : [NotifyCenter] Start destroying Publisher
2023-12-14 14:56:50.577  WARN 19732 --- [       Thread-5] c.a.nacos.common.notify.NotifyCenter     : [NotifyCenter] Destruction of the end
2023-12-14 14:56:50.577  WARN 19732 --- [       Thread-8] c.a.n.common.http.HttpClientBeanHolder   : [HttpClientBeanHolder] Start destroying common HttpClient
2023-12-14 14:56:50.577  WARN 19732 --- [       Thread-8] c.a.n.common.http.HttpClientBeanHolder   : [HttpClientBeanHolder] Destruction of the end
2023-12-14T14:56:50.581：关闭服务中...........1
2023-12-14T14:56:50.581关闭服务中...........2
2023-12-14T14:56:50.581关闭服务中...........3
2023-12-14T14:56:50.581关闭服务中...........4
2023-12-14T14:56:50.581关闭服务中...........5
2023-12-14T14:56:50.581等我2秒再关闭...
2023-12-14 14:56:50.692  INFO 19732 --- [ionShutdownHook] c.a.c.n.registry.NacosServiceRegistry    : De-registering from Nacos Server now...
2023-12-14 14:56:50.695  INFO 19732 --- [ionShutdownHook] c.a.c.n.registry.NacosServiceRegistry    : De-registration finished.
2023-12-14T14:56:52.585关闭服务中...........6
2023-12-14T14:56:52.585关闭服务中...........7
2023-12-14T14:56:52.585关闭服务中...........8
2023-12-14T14:56:52.585关闭服务中...........9
2023-12-14T14:56:52.585关闭服务中...........10
```

## 第 2 步：搭建 Nacos Server
在 RainBond 中搭建一个 Nacos Server，版本选择 2.2.0。
![image](https://github.com/goodrain/rainbond/assets/13994196/32bb6b73-3a76-48bb-af89-642dfa62188f)

## 第 3 步：添加微服务组件
添加 rainbond-nacos-test 作为 RainBond 组件：
![image](https://github.com/goodrain/rainbond/assets/13994196/4e645e12-3620-46a6-9b19-874a7bcf5e32)

并把前面的 Nacos 2.2.0 作为依赖：
![image](https://github.com/goodrain/rainbond/assets/13994196/8da2032b-0bf4-4a37-b4f3-97f4c2772a84)

第 4 步：启动 rainbond-nacos-test 
启动 rainbond-nacos-test  组件：ip 是 192.168.102.240
![image](https://github.com/goodrain/rainbond/assets/13994196/1e692507-0a38-4f02-840f-e62031f26a63)

观察日志，成功注册到 Nacos：
![image](https://github.com/goodrain/rainbond/assets/13994196/eea694a0-cbbb-42a9-8efa-2f835debc734)

再看 Nacos：成功注册
![image](https://github.com/goodrain/rainbond/assets/13994196/88643002-7c70-4b33-ae4b-86bef4035d26)

## 第 5 步：重启/关闭 rainbond-nacos-test 
前面正常情况的关闭，是会取消注册到 Nacos 的。也就是说，Nacos 上的实例会消失。

如果使用 RainBond 关闭/重启的情况下，原有实例不会消失，而且也很难打印出 shutdown hook 相关的完整日志（有时候能打印出一丢丢，有时候一行都打印不出来）。

如果重启 2 次，则 Nacos 中就会产生 2 个实例。加上第一次启动的，具有 3 个实例了。
![image](https://github.com/goodrain/rainbond/assets/13994196/4aa0e112-6d72-42c9-a7da-996a4ec13616)

然而，rainbond-nacos-test 真正只有一个实例是活着的。
![image](https://github.com/goodrain/rainbond/assets/13994196/9f71402d-5875-4c09-b912-2dd4368911b5)

这样就会导致后续请求，可能会请求到另外两个被 kill 掉的实例上，继而引发请求超时问题。

# 诉求
考虑 关闭/强制关闭 按钮的逻辑，不要 --force 强制删除 pod。
或者改成 超过特定时间后，才进行强制删除呢？

**Comment by yangkaa** [comment]
目前，在重启和关闭时，是会去直接删除底层的 Deployment 资源的。实际上，如果你直接使用K8s的Yaml文件部署，再删除，也会遇到相同的问题。

你现在在业务中使用了钩子，所以收到删除pod信号时，你的代码会优雅退出。但是 Kubelet 删除 pod 却几乎是同步的。这就导致了代码正在优雅关闭服务时，就被强行终止了。

但是 K8s 也提供了 preStop Hook，可以参考[文档](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks)，配置这个以后，你可以让 kubelet 收到删除 Pod 的事件时，先等待一段时间，再强行删除。

在Rainbond中它的位置在组件的K8s属性中，如下图所示：
<img width="424" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/8fc5d663-9d06-4000-be81-ba0d1d7b8934">

你可以在 Rainbond 中进行如下配置，这样在关闭该组件时，将会休眠10秒再删除 pod

```yaml
preStop:
   exec:
       command: ["sh", "-c", "sleep 10"]
```

**Comment by shun634501730** [comment]
这个之前也尝试过，没有任何效果。取消注册的日志并没有打印出来，Nacos中的实例依然没有取消注册。
![image](https://github.com/goodrain/rainbond/assets/13994196/051571c3-faa5-467e-a00c-9fc68a6ab233)

**Comment by yangkaa** [comment]
1. 你可以先确认这个属性是否确实生效了，可以在组件运行时查看其yaml文件，是否包含你设置的字段

2. 如果这个属性生效，那么你的程序优雅退出的时间需要多久？默认情况下 Kubernetes 为删除容器留了最大 30s 的宽限时间，如果程序的优雅关闭时间和 preStop Hook 时间之和超过 30s，也依然会被删除。如果是这种情况，那还可以通过设置 terminationGracePeriodSeconds 字段来处理。不过这个字段当前 Rainbond 还不支持

**Comment by yangkaa** [comment]
目前我没有K8s 1.18的环境，因此我拿你给的例子在单机版本和基于主机安装的 Rainbond 中做了试验，并未复现该问题。我并未设置任何健康检测、prestop等相关字段。

两个环境如下：
1. 单机版默认K3s为 v1.25.15-k3s1，Rainbond 版本为 v5.16.0-release，使用containerd运行时。
2. 基于主机安装K8s版本为1.23.10，Rainbond 版本为 v5.16.0-release，使用docker运行时，docker 版本为24.0.7

我的操作步骤如下：
1. 下载你提供的代码，并在服务器上打出镜像
2. 在应用市场直接安装 nacos 单机版，2.2.0 版本。
3. 通过镜像部署，并依赖 nacos
4. 代码启动完成后，可以查看到 nacos 注册信息。
5. 关闭组件，nacos 服务列表自动清空，更新组件，nacos 服务列表，先清空，后更新了最新地址。重启组件和更新结果一致。同时日志完整输出。

详细步骤截图如下：

1. 应用完整部署拓扑图如下，probe是你提供的压缩包打出的镜像，nacos是从应用市场安装的2.2.0版本。
<img width="1369" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/43cacc38-ad34-421b-9264-9d49734b4116">

2. 注册日志、服务列表、服务详情如下，可以看到服务 ip 地址一致。
<img width="1435" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/01a77c57-0a80-410d-9a60-7257cb8e9a8a">
<img width="1437" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/8ae59182-9e78-48cd-97eb-3ef2d0d6ab31">
<img width="1433" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/4b66a18f-8ce2-48c9-b815-9b956cdedaea">

3. 执行关闭操作，日志正常打印，nacos服务列表为空，详细截图如下
<img width="1439" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/e9de6a2a-e4be-4562-88a5-e4af2e4f20aa">
<img width="1438" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/5978691e-ce07-43e9-b598-685dcb8c93e8">

4. 重新启动组件，此时注册日志、服务列表、服务详情如下，可以看到服务 ip 地址依然一致。
<img width="1438" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/2d104a49-7be5-450d-935b-909fc9ce5069">
<img width="1439" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/07a40ae9-2c9a-4300-abd3-16d0ee069be9">
<img width="1439" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/81b23188-8209-4610-8614-78a16d5ea671">

5. 此时进行更新操作，查看日志实例IP为10.42.0.58，此时回到nacos查看服务列表和服务详情，截图如下
<img width="1438" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/7396ac3e-32b5-4b05-aa6a-f27b51326f9d">
<img width="1439" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/f64c325a-febc-465b-b7a0-63ef7787413a">
<img width="1439" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/fc2af482-ce07-4b14-a3dd-5fb32797d4c9">
<img width="1439" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/ffc1f86f-1741-412b-9f23-7845441fa466">

6. 再次尝试重启操作，注册日志、服务列表、服务详情如下
<img width="1439" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/2cd61238-1614-43cd-a8b5-77645e3095a7">
<img width="1439" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/f15780ff-b6fa-4712-bdaf-8f4937cce033">
<img width="1439" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/dc1f2106-19f0-45a2-a012-c232358fbb6b">
<img width="1439" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/a9340aeb-be52-4d50-bc8b-5186a77c21e4">

7. 至于僵尸进程，从我执行以上操作到结束，整个服务器的僵尸进程为0，无增长
<img width="926" alt="image" src="https://github.com/goodrain/rainbond/assets/30614084/1ce6adb2-8afe-4edb-b450-69e3617faadb">

**Comment by yangkaa** [comment]
如果没有进一步的可复现步骤，我将在新版本发布时关闭此 issue
