### ISSUE TITLE
Rainbond 官网生产 helm 功能挂了

### ISSUE THREAD

**Issue by mx2913** [goodrain/rainbond#1804]
https://rainbond.cn/helm 网页生成 helm 安装命令时， https://cloud.goodrain.com/enterprise-server/api/v1/helm/chart 出现跨域请求失败

**Comment by yangkaa** [comment]
感谢你的提醒，已修复，如还有问题请重新打开。

helm 安装目前我们更推荐直接修改 values.yaml 文件。因为 --set 的参数，后续修改参数或再找之前设定的参数会比较麻烦。
