### ISSUE TITLE
网关参数配置时，如果在header、cookie等处使用了特殊符号，会导致网关生成的配置出错，影响应用访问。

### ISSUE THREAD

**Issue by yangkaa** [goodrain/rainbond#1826]
网关参数配置时，如果在header、cookie等处使用了特殊符号，会导致网关生成的配置出错，影响应用访问。

前后端都需要对网关参数做合理的校验

**Comment by DokiDoki1103** [comment]
https://github.com/goodrain/rainbond-console/pull/1421 

https://github.com/goodrain/rainbond-console/pull/1421
