### ISSUE TITLE
建议vnc 连接虚拟机控制台支持命令复制粘贴

### ISSUE THREAD

**Issue by 2363830288** [goodrain/rainbond#1832]
建议vnc 连接虚拟机控制台支持命令复制粘贴

**Comment by ZhangSetSail** [comment]
虚拟机这里使用的是 kubevirt 现成的插件，我会在他们社区进行反馈，等待他们vnc插件更新后，我们会同步更新。

**Comment by ZhangSetSail** [comment]
这个问题长时间没有更新，因此我将暂时关闭这个 issue。如果你仍然遇到这个问题，请随时重新打开并提供更多细节。
