### ISSUE TITLE
导入 Kubernetes 资源 Bug

### ISSUE THREAD

**Issue by anhao** [goodrain/rainbond#1834]
如果现有的matchLabels存在 app.kubernetes.io/managed-by 则会冲突，会导入失败

![0565288ee1fbf54c3a26274513bcdad](https://github.com/goodrain/rainbond/assets/9844218/77dc61ca-8c45-4c3e-8896-db0b7a23d7b1)

![54db59ecab3b79d59c777fa4dd022d5](https://github.com/goodrain/rainbond/assets/9844218/4009117e-5ae6-49aa-b4d5-22ad0117bb1a)

**Comment by ZhangSetSail** [comment]
好的，感谢反馈。本周五安排时间修复。

**Comment by yangkaa** [comment]
该问题我们预计在 5.18 版本进行修复

**Comment by ZhangSetSail** [comment]
该issue在5.17.2已经得到了解决，我将关闭，有问题再重新打开
