### ISSUE TITLE
应用商店安装应用失败，

### ISSUE THREAD

**Issue by emf1002** [goodrain/rainbond#1857]
**Describe the bug**
配置自己的了镜像仓库 应用商店安装应用，看日志镜像推送成功了，仓库里却没有

**Screenshots**
![e9d5e8a1b62ae128ab7c4b6f44d6eb60](https://github.com/goodrain/rainbond/assets/559902/9122510b-165c-4cab-849a-8c4eaffc0f3d)
**The relevant information:**
 - Rainbond Version [5.16.0]
 - Kubernetes version [1.28.0]

**Comment by yangkaa** [comment]
能否详细描述下你的操作步骤和流程，你的镜像仓库是 http 的还是 https 的？基于镜像/源码构建是否能够成功

**Comment by emf1002** [comment]
后来测试使用https镜像是可以推送成功的，使用http仓库时修改了BuildKit构建参数，看文档是要修改goodrain.me ConfigMap,但是提示goodrain.me不存在，我就手动创建了一个，但是看最终效果应该是没有生效

> 能否详细描述下你的操作步骤和流程，你的镜像仓库是 http 的还是 https 的？基于镜像/源码构建是否能够成功

**Comment by yangkaa** [comment]
goodrain.me 这个 ConfigMap 只在你使用了内置的镜像仓库时才会被创建。如果你是对接的私有仓库，比如私有仓库域名是 dev.registry.com ,那么应该创建的 ConfigMap 名称是 dev-registy-com，改这个才会生效

**Comment by emf1002** [comment]
经过反复测试 http镜像仓库没有推送成功，但是日志显示是成功的。使用内置的镜像仓库时，goodrain.me 这个 ConfigMap没有被创建，对接私有仓库时，对应的ConfigMap也没有自动创建，同时手动创建后也不起作用。

**Comment by ZhangSetSail** [comment]
由于这个issue已经有一段时间没有更新，我打算关闭它以保持项目的整洁。如果您在未来还有任何问题或需要进一步的帮助，请随时重新打开此issue或创建一个新的issue。
