### ISSUE TITLE
代码构建禁用缓存无法关闭

### ISSUE THREAD

**Issue by buzilong** [goodrain/rainbond#1861]
版本： v5.17.0
问题描述：这是一个node js的项目，部署方式是NodeJSStatic，会偶发无法关闭禁用缓存开关，导致每次构建时间很长，这是第二次出这个问题，上次我把项目删了重新创建的，过了几天有自动出现这个问题了。

https://github.com/goodrain/rainbond/assets/19564702/62a477c2-9efb-4366-bd1e-27988dbda2a8

**Comment by zzzhangqi** [comment]
v5.17.1 已解决，参考文档进行[升级](https://www.rainbond.com/docs/upgrade/latest-version)
