### ISSUE TITLE
【需求】希望rainbond 增加vue项目pnpm构建的方式

### ISSUE THREAD

**Issue by DreamWorksFactory2021** [goodrain/rainbond#1864]
现在很多前端项目都会使用pnpm 做依赖管理，现有的rainbond 只支持npm 和yarn 的构建方式，pnpm 创建的项目是无法使用这两者取构建的。

**Comment by yangkaa** [comment]
合并到 https://github.com/goodrain/rainbond/issues/1829 一起处理。
