### ISSUE TITLE
openApi：组件构建接口调用问题

### ISSUE THREAD

**Issue by ldsdsy** [goodrain/rainbond#1874]
**Describe the bug**
当调用组件构建接口更新镜像时，确实更新了镜像也触发了构建。但组件构建源页面里的版本却没有同步更新。

**To Reproduce**
1. 部署一个组件test是用镜像：xxxxxxxx:202401120255-94ab95
2. 调用构建接口更新镜像为：xxxxxx:202401120306-3036d4
$ curl --location --request POST "http://10.32.212.127:7070/openapi/v1/teams/nawlie0s/regions/rainbond/apps/1/services/3b60d295d4ecfef9080ed71164019f70/build" \
  --header "Authorization: xxxxxxx" \
  --header 'Content-Type: application/json' \
  --data-raw "{
      \"build_type\": \"docker_image\",
      \"repo_url\": \"xxxxxxxx:202401120306-3036d4\",
      \"username\": \"xxxxxx\",
      \"password\": \"xxxxx\"
  }"
3. 查看组件构建源页面发现版本还是 202401120255-94ab95

**Screenshots**
调用之前：
<img width="1053" alt="old" src="https://github.com/goodrain/rainbond/assets/29426776/690538b6-034b-432c-aa88-70c3767bf744">
调用之后：
<img width="848" alt="new" src="https://github.com/goodrain/rainbond/assets/29426776/cb749874-7df5-4bb5-8545-90b1e1c2961b">

**The relevant information:**
 - Rainbond Version [v5.15.2-release]
 - Browser [chrome, safari] 
 - Kubernetes version [v1.24]

**Comment by ZhangSetSail** [comment]
5.17.2版本已发布，该问题在5.17.2已经得到修复，你可以参考[升级文档](https://rainbond.com/docs/upgrade/latest-version)进行升级，我将关闭此issue，如果有问题你可以随时重新打开。
