### ISSUE TITLE
配置私有镜像仓库，Dockerfile构建拉取私有仓库镜像，授权失败

### ISSUE THREAD

**Issue by wangwen11** [goodrain/rainbond#1875]
按照文档说明「团队视图 -> 管理 -> 镜像仓库授权信息 中配置私有镜像仓库地址以及账户和密码」配置未生效
使用的是阿里云的镜像仓库，仓库设置为私有的，无法拉取到Dockerfile中的镜像

`Build app version from source code start
Start clone source code from https://codeup.aliyun.com/652971a192acde2cf1828016/yc/bcp-oss.git
pull or clone code successfully, start code build
CodeVersion:56885dc Author:liqiujie Commit:Dockerfile
Start parse Dockerfile
create build code job success
INFO
[0000] Retrieving image manifest registry.cn-guangzhou.aliyuncs.com/middlewaress/middleware:bcp-maven-3.9.6-01
INFO
[0000] Retrieving image registry.cn-guangzhou.aliyuncs.com/middlewaress/middleware:bcp-maven-3.9.6-01 from registry registry.cn-guangzhou.aliyuncs.com
INFO
[0000] Resolved base name registry.cn-guangzhou.aliyuncs.com/middlewaress/middleware:bcp-maven-3.9.6-01 to builder
error building image: GET https://registry.cn-guangzhou.aliyuncs.com/v2/middlewaress/middleware/manifests/bcp-maven-3.9.6-01: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:middlewaress/middleware Type:repository]]
build code job exec failed
Build app version from source code failure,build code job exec failure
Compiling the source code failure
建议查看日志定位代码错误`

**Comment by paterleng** [comment]
新版本添加私有仓库地址「平台管理-设置-镜像仓库-添加私有镜像仓库」
![WechatIMG27](https://github.com/goodrain/rainbond/assets/117519642/a29ffe15-8541-410e-8213-f48a6937eac4)

**Comment by ZhangSetSail** [comment]
新版镜像仓库应该能解决你说的问题，该issue长时间没有更新，我先关闭该issue，如果有问题你可以重新打开
