### ISSUE TITLE
银河麒麟V10，基于主机安装后添加集群，rpcinfo CPU占用99%，触发OOM killer

### ISSUE THREAD

**Issue by orionpax1997** [goodrain/rainbond#1888]
**银河麒麟V10，基于主机安装后添加集群，rpcinfo CPU占用99%，触发OOM killer**

后续只要重启机器，很快就会再次宕机

**To Reproduce**
1. 执行启动 All-In-One 控制台命令
2. 添加集群基于主机安装全部默认

**Screenshots**
![image](https://github.com/goodrain/rainbond/assets/95059095/b6c77cb8-aaee-4f60-9124-ab952561e5d4)
![image](https://github.com/goodrain/rainbond/assets/95059095/e08ea7fb-77c8-414e-a708-8f79bd7e0115)

**The relevant information:**
 - Rainbond Version [v5.17.1-release-allinone]
 - Kylin-Server-V10-SP3-General-Release-2303-X86_64

**Comment by zzzhangqi** [comment]
临时解决：

docker pull registry.cn-hangzhou.aliyuncs.com/goodrain/nfs-provisioner:v4.0.8
docker tag registry.cn-hangzhou.aliyuncs.com/goodrain/nfs-provisioner:v4.0.8 registry.cn-hangzhou.aliyuncs.com/goodrain/nfs-provisioner:latest
kubectl delete pod nfs-provisioner-0 -n rbd-system
已经在麒麟V10测试过可以正常工作

因其他操作系统还未验证，会在v5.18彻底解决

**Comment by orionpax1997** [comment]
> 临时解决，替换`nfs-provisioner`镜像：
> 
> ```shell
> docker pull registry.cn-hangzhou.aliyuncs.com/goodrain/nfs-provisioner:v4.0.8
> docker tag registry.cn-hangzhou.aliyuncs.com/goodrain/nfs-provisioner:v4.0.8 registry.cn-hangzhou.aliyuncs.com/goodrain/nfs-provisioner:latest
> kubectl delete pod nfs-provisioner-0 -n rbd-system
> ```
> 
> 已经在麒麟V10测试过可以正常工作
> 
> 因其他操作系统无法验证，会在v5.18彻底解决

感谢
