### ISSUE TITLE
Anolis OS release 7.9 基于主机安装后添加集群，安装集群组件会卡住

### ISSUE THREAD

**Issue by orionpax1997** [goodrain/rainbond#1897]
**Anolis OS release 7.9 基于主机安装后添加集群，安装集群组件会卡住**

**To Reproduce**
1. 执行启动 All-In-One 控制台命令
2. 添加集群基于主机安装全部默认

**Screenshots**
![image](https://github.com/goodrain/rainbond/assets/95059095/84aa868f-b2c0-45b3-b999-2651a6d09d16)

**The relevant information:**
 - Rainbond Version [v5.17.1-release-allinone]
 - Anolis OS release 7.9 [kernel 4.19.91-25.2.an7.x86_64]

**Comment by 0478yhl** [comment]
@orionpax1997 
<img width="516" alt="image" src="https://github.com/goodrain/rainbond/assets/124012440/3593549a-ff7b-4344-b996-33df74ea79bf">
我刚开机器试了下没有这个问题呀，这两个我都试着安装了下，都挺顺利的。你看镜像一样吗？
这种状态 你等了多久

**Comment by orionpax1997** [comment]
破案了，是 Docker 的问题，我使用的 Docker version 20.10.9

**Comment by 0478yhl** [comment]
👍
