### ISSUE TITLE
云帮环境异常

### ISSUE THREAD

**Issue by xggz** [goodrain/rainbond#1899]
**Describe the bug**
昨天11点突然出现的问题，23:22左右所有服务都自动重启了，但是云帮界面上没有服务重启记录。

**Screenshots**
这是云帮的网关日志：
e7e3b1e001a3:time="2024-03-26T23:00:27+08:00" level=warning msg="172.24.138.90:10254 lid[3ec28be059071556] keepAlive err: context deadline exceeded, try to reset..."

e7e3b1e001a3:time="2024-03-26T23:00:42+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:00:46+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:00:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:00:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:01:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:01:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:01:42+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:01:46+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:01:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:01:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:02:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:02:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:02:42+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:02:46+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:02:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:2024/03/26 23:02:42 [error] 577#577: *203714272 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 100.121.112.114, server: xxx.com, request: "POST /openapi/query/project_equipment_details_equip HTTP/1.1", upstream: "http://10.42.4.11:7600/openapi/query/project_equipment_details_equip", host: "xxx.com"

e7e3b1e001a3:2024/03/26 23:02:53 [error] 577#577: *203714806 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 100.121.112.43, server: xxx.com, request: "POST /openapi/query/project_equipment_details_equip HTTP/1.1", upstream: "http://10.42.4.11:7600/openapi/query/project_equipment_details_equip", host: "xxx.com"

e7e3b1e001a3:time="2024-03-26T23:02:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:03:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:03:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:03:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:03:47+08:00" level=info msg="update nginx server config file."

e7e3b1e001a3:time="2024-03-26T23:03:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:04:12+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:04:16+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:04:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:04:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:2024/03/26 23:04:31 [error] 577#577: *203719240 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 100.121.111.243, server: xxx.com, request: "POST /openapi/query/project_equipment_details_equip HTTP/1.1", upstream: "http://10.42.4.11:7600/openapi/query/project_equipment_details_equip", host: "xxx.com"

e7e3b1e001a3:time="2024-03-26T23:04:42+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:04:46+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:04:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:04:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:05:12+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:05:16+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:05:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:05:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:05:42+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:05:46+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:05:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:05:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:06:12+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:06:16+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:06:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:06:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:06:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:06:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:2024/03/26 23:06:54 [error] 577#577: *203725368 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 100.121.113.162, server: xxx.com, request: "POST /openapi/query/project_equipment_details_equip HTTP/1.1", upstream: "http://10.42.4.11:7600/openapi/query/project_equipment_details_equip", host: "xxx.com"

e7e3b1e001a3:time="2024-03-26T23:07:12+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:07:16+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:07:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:07:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:2024/03/26 23:07:26 [error] 577#577: *203726893 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 100.121.112.46, server: xxx.com, request: "POST /openapi/query/project_equipment_details_equip HTTP/1.1", upstream: "http://10.42.4.11:7600/openapi/query/project_equipment_details_equip", host: "xxx.com"

e7e3b1e001a3:time="2024-03-26T23:07:42+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:07:46+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:07:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:07:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:08:12+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:08:16+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:08:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:08:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:08:42+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:08:46+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:08:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:08:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:2024/03/26 23:09:08 [error] 580#580: *203731521 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 100.121.111.214, server: xxx.com, request: "POST /openapi/query/itemlist HTTP/1.1", upstream: "http://10.42.4.11:7600/openapi/query/itemlist", host: "xxx.com"

e7e3b1e001a3:time="2024-03-26T23:09:12+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:09:16+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:09:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:09:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:09:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:09:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:10:12+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:10:16+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:10:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:10:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:10:42+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:10:46+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:10:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:10:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:11:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:11:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:11:42+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:11:46+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:11:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:11:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:12:12+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:12:16+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:12:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:12:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:12:42+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:12:46+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:12:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:12:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:13:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:13:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:13:42+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:13:46+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:13:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:13:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:14:12+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:14:16+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:14:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:14:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:14:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:14:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:15:12+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:15:16+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:15:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:15:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:15:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:15:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:2024/03/26 23:16:00 [error] 577#577: *203750607 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 100.121.111.227, server: xxx.com, request: "POST /openapi/query/project_equipment_details_equip HTTP/1.1", upstream: "http://10.42.4.11:7600/openapi/query/project_equipment_details_equip", host: "xxx.com"

e7e3b1e001a3:time="2024-03-26T23:16:12+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:16:16+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:16:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:16:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:16:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:16:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:2024/03/26 23:17:00 [error] 580#580: *203753472 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 100.121.112.6, server: xxx.com, request: "POST /openapi/query/project_equipment_details_equip HTTP/1.1", upstream: "http://10.42.4.11:7600/openapi/query/project_equipment_details_equip", host: "xxx.com"

e7e3b1e001a3:time="2024-03-26T23:17:12+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:17:16+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:17:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:17:27+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:17:46+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:17:57+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:2024/03/26 23:18:00 [error] 577#577: *203756176 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 100.121.112.110, server: xxx.com, request: "POST /openapi/query/project_equipment_details_equip HTTP/1.1", upstream: "http://10.42.4.11:7600/openapi/query/project_equipment_details_equip", host: "xxx.com"

e7e3b1e001a3:time="2024-03-26T23:18:13+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:18:14+08:00" level=info msg="nginx config reload success"

e7e3b1e001a3:time="2024-03-26T23:18:14+08:00" level=info msg="update nginx server config file."

e7e3b1e001a3:time="2024-03-26T23:18:15+08:00" level=info msg="nginx config reload success"

e7e3b1e001a3:time="2024-03-26T23:18:16+08:00" level=warning msg="keep alive ip key failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:18:16+08:00" level=error msg="put gateway ip to etcd failure context deadline exceeded"

e7e3b1e001a3:time="2024-03-26T23:18:28+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:18:43+08:00" level=warning msg="172.24.138.90:10254 set lid err: context deadline exceeded, try to reset after 10 seconds..."

e7e3b1e001a3:time="2024-03-26T23:18:44+08:00" level=warning msg="keep alive ip key failure etcdserver: requested lease not found"

e7e3b1e001a3:time="2024-03-26T23:18:44+08:00" level=info msg="gateway init add ip 172.24.138.90"

e7e3b1e001a3:time="2024-03-26T23:18:44+08:00" level=warning msg="keep alive ip key failure etcdserver: requested lease not found"

e7e3b1e001a3:time="2024-03-26T23:18:44+08:00" level=info msg="gateway init add ip 10.42.0.0"

e7e3b1e001a3:time="2024-03-26T23:18:53+08:00" level=info msg="Register a gateway server endpoint 172.24.138.90:10254 to cluster"

e7e3b1e001a3:time="2024-03-26T23:18:53+08:00" level=info msg="172.24.138.90:10254 set lid[3ec28be059383a59] success"

**The relevant information:**
 - Rainbond Version v5.17.0
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version 1.23.10

**Comment by zzzhangqi** [comment]
@xggz 从报错日志看像是 k8s 出问题了，你能确定当时的k8s是处于正常状态吗

**Comment by xggz** [comment]
> @xggz 从报错日志看像是 k8s 出问题了，你能确定当时的k8s是处于正常状态吗

当时云帮能正常访问和操作服务，而且里面的服务也是正常的，业务没有影响（有一个服务有问题，手动重启了服务）

**Comment by ZhangSetSail** [comment]
由于这个issue已经有一段时间没有更新，我打算关闭它以保持项目的整洁。如果您在未来还有任何问题或需要进一步的帮助，请随时重新打开此issue或创建一个新的issue。
