### ISSUE TITLE
本地文件zip包创建的组建，重新传包 ->构建时不会将新的zip包解压到nginx目录下

### ISSUE THREAD

**Issue by buzilong** [goodrain/rainbond#1903]
**Describe the bug**
使用本地文件上传创建组建，zip包格式，nginx服务器，创建的时候，可以正常将zip包解压到nginx下。当zip包更新重新上传后，然后点击构建，不会将新的zip包解压，nginx下是空的。
ps:如果上传zip包后，点一下重新检测，然后再点构建，这个时候会将zip包正常解压到nginx下。
 

**The relevant information:**
 - Rainbond Version  : v5.17.1

**Comment by ZhangSetSail** [comment]
没有复现你所说的这个问题，我上传的zip包可以正常的上传构建，请提供具体的错误截图和zip包

**Comment by ZhangSetSail** [comment]
问题太久没更新了，我先关闭，有问题再随时打开
