### ISSUE TITLE
多集群环境时, 只能在一个集群创建Gateway API

### ISSUE THREAD

**Issue by geeknonerd** [goodrain/rainbond#1904]
多集群环境时, 只能在一个集群创建Gateway API, 另一个集群创建Gateway API时会出现命名空间已存在

Gateway API文档:
https://www.rainbond.com/docs/kubernetes-native-guide/gateway-api

**Comment by ZhangSetSail** [comment]
是否尝试过 一个团队绑定多个集群的方式，通过进入相同团队 进入不同集群来创建gateway API的相关应用。

**Comment by geeknonerd** [comment]
嗯,是的,这种方式可以

**Comment by geeknonerd** [comment]
> 是否尝试过 一个团队绑定多个集群的方式，通过进入相同团队 选择不同集群来创建gateway API的相关应用。

嗯,是的,这种方式可以
