### ISSUE TITLE
如何打开rbd-gateway内的nginx的access_log

### ISSUE THREAD

**Issue by Libertad-904483782** [goodrain/rainbond#1909]
碰到了一些ingress访问的问题，需要能打开特定域名的access log，发现页面上的网关配置中，没有关于日志的选项，直接修改ingress加注解会被刷掉。请教下，有办法打开吗

**Comment by zzzhangqi** [comment]
@Libertad-904483782 

kubectl edit rbdcomponent rbd-gateway -n rbd-system

```
spec:
  args:
  - --access-log=/dev/stdout
```

**Comment by yangkaa** [comment]
https://github.com/goodrain/rainbond/blob/f0d3a471eb2ec23c269bddec0c4417b494568dff/cmd/gateway/option/option.go#L107 对应这个参数。你可以参考如下方式设置。

1. 编辑 rbd-gateway 的 crd 资源。

```bash
kubectl edit rbdcomponent rbd-gateway -nrbd-system
```

2. 增加上面的 access-log 参数,如下所示

```bash
apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-gateway
  namespace: rbd-system
spec:
  args:
  - --access-log=/logs/access.log
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-gateway:v5.17.0-release
```

3. 上面的 access-log 定义的地址，就是accesslog文件。进入 rbd-gateway 容器下该路径查看即可。

**Comment by ZhangSetSail** [comment]
由于这个issue已经有一段时间没有更新，我打算关闭它以保持项目的整洁。如果您在未来还有任何问题或需要进一步的帮助，请随时重新打开此issue或创建一个新的issue。
