### ISSUE TITLE
快速安装的时候docker 无法启动  Failed to start docker.service - Docker Application Container Engine

### ISSUE THREAD

**Issue by youngqj** [goodrain/rainbond#1911]
debian 新购主机 什么都没有安装执行命令
curl -o install.sh https://get.rainbond.com && bash ./install.sh
然后docker 无法启动 
报错Failed to start docker.service - Docker Application Container Engine

**Comment by zzzhangqi** [comment]
那你的debian版本应该在11往上，在安装时应该会有这样的报错，
```
iptables not installed, Please install iptables manually 'apt-get update && apt install -y iptables-persistent', Execute the script again after the installation is complete.
```
安装 iptables 后重新执行脚本

**Comment by ZhangSetSail** [comment]
由于这个issue已经有一段时间没有更新，我打算关闭它以保持项目的整洁。如果您在未来还有任何问题或需要进一步的帮助，请随时重新打开此issue或创建一个新的issue。
