### ISSUE TITLE
组件删除报错，无法删除

### ISSUE THREAD

**Issue by buzilong** [goodrain/rainbond#1915]
**Describe the bug**
添加java maven多模块项目的场景，输入git信息后，会进入多模块选择界面，此时rbd会先创建一个组件，当我在多模块界面配置好模块点击确认构建后，正常应该只添加多模块内的组件，然后把一开始创建的那个组件删除掉，但是现在模块内的组件创建好了，但是一开始创建的那个组件无法删除，会报错无法删除。返回到组件列表页面后，也无法手动删除这个无用的组件。
![cdeb9ab4871fdacd7a7d9a1fe0b4578](https://github.com/goodrain/rainbond/assets/19564702/ae2c2163-e00f-49d0-acc5-8756877e7886)

 

**The relevant information:**
 - Rainbond Version  5.17.1-release

**Comment by yangkaa** [comment]
可以提供“平台管理-日志-控制台日志”看看
