### ISSUE TITLE
离线环境安装rbd-db启动失败

### ISSUE THREAD

**Issue by keymean6** [goodrain/rainbond#1917]
**Describe the bug**
离线环境安装rainbond一直卡在rbd-db-0只ready一个，关联chaos、eventlog、work等均启动失败。

**To Reproduce**
1. 离线环境安装docker；
2. 离线环境单机安装k3s，配置k3s的service --docker --disable traefik；启动k3s后，通过kubectl get pods -n kube-system查看有local-path-provisioner、coredns、三个ready的POD，另外还有两个delete-traefik的状态为Complate；
3. 按rainbond的离线安装文档安装，同时修改了安装所需的默认端口；
4. 通过watch kubectl get po -n rbd-system显示rbd-db-0的两个容器只有operator处于ready状态，通过日志发现另一个容器rbd-db的探针执行失败；

**The relevant information:**
 - Rainbond Version [e.g. 5.17.1]
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version [e.g k3s v1.25.12+k3s1]

**Comment by yangkaa** [comment]
请提供具体pod的事件信息或日志，以及 rbd-system命名空间下的pod状态

**Comment by ZhangSetSail** [comment]
由于这个issue已经有一段时间没有更新，我打算关闭它以保持项目的整洁。如果您在未来还有任何问题或需要进一步的帮助，请随时重新打开此issue或创建一个新的issue。
