### ISSUE TITLE
应用发布无法修改镜像tag

### ISSUE THREAD

**Issue by zzk8s** [goodrain/rainbond#1918]
Success Pull Image：**********xc-mysql80:20240425162716
change image tag：**************-xc-mysql80:20240425162716 -> *********96e4c48177d94a728e3c52a39d71fe52/e7775a1ad19b4669bf55d0f8e9733dfe:20240425162716
分享应用任务执行失败
修改镜像tag: *****-mysql80:20240425162716 -> **************96e4c48177d94a728e3c52a39d71fe52/e7775a1ad19b4669bf55d0f8e9733dfe:20240425162716 失败
创建分享结果成功,分享失败

**Comment by yangkaa** [comment]
请在发布时，提供构建日志，入口在“平台管理-日志-构建日志”
