### ISSUE TITLE
api接口无法更换镜像地址名称提示NOT FOUND

### ISSUE THREAD

**Issue by yszansx** [goodrain/rainbond#1919]
Describe the bug
api接口无法更换镜像地址名称。提示找不到资源。The requested resource was not found on this server.
文档地址：https://www.rainbond.com/docs/api/application/changeImageName
To Reproduce
可以正常获取组件信息，但是需要修改docker镜像的名称接口提示NOT FOUND
![9234b07d9a771ad0583a2c32aa02257](https://github.com/goodrain/rainbond/assets/43443722/1f489f30-60d9-4aea-9695-01cd4663b31c)

Screenshots
The relevant information:
Rainbond Version: v5.17.0-release
Browser：Chrome
Kubernetes version：1.28.3

**Comment by yszansx** [comment]
> 请提供你请求的服务地址，以及你是否有配置{team_id}、{app_id}等这些路径参数呢
![image](https://github.com/goodrain/rainbond/assets/43443722/292cd4f5-3e05-46a9-8a5a-ffceda3d9038)

**Comment by ZhangSetSail** [comment]
接口确实不存在，安排在v5.18版本添加。

**Comment by ZhangSetSail** [comment]
5.17.2版本已发布，该问题在5.17.2已经得到修复，你可以参考[升级文档](https://rainbond.com/docs/upgrade/latest-version)进行升级，我将关闭此issue，如果有问题你可以随时重新打开。
