### ISSUE TITLE
如何更改公网IP

### ISSUE THREAD

**Issue by yuki-xin** [goodrain/rainbond#192]
- [ ] Rainbond versions(eg. grctl version)
V5.0
- [ ] Kubernetes versions(If you use your own cluster)

- [ ] Operating system and kernel
CentOS 7.4
- [ ] Provider(Aliyun,VirtualBox,...)
Aliyun
- [ ] Install details(Online/Offline,SingleNode/HA)
SingleNode

创建时指定了公网IP，如果公网IP被收回或弹性公网IP更换，如何更换Rainbond中对应的公网IP

**Comment by ysicing** [comment]
可以参考 [调整已有域名解析](https://www.rainbond.com/docs/v3.7/operation-manual/trouble-shooting/domain-ops.html#part-3a9557cd9dab533c)

**Comment by yuki-xin** [comment]
应该是 eip，不是域名。。比如控制台会默认连接 eip:6060，然后机器绑定的eip变更了，如果变更控制台连接的Ip地址

**Comment by ysicing** [comment]
需要更新数据库 @yuki-xin 
```
docker exec -it rbd-db mysql -e "update console.region_info set wsurl='ws://<公网ip>:6060',tcpdomain='<公网ip>';"
```
