### ISSUE TITLE
通过源码构建golang微服务的文档和demo项目比较老，能更新下吗？

### ISSUE THREAD

**Issue by lsh5** [goodrain/rainbond#1920]
通过源码构建golang微服务的文档和demo项目比较老，构建go项目的流程，Golang 项目源码规范，不是很清晰

**Comment by ZhangSetSail** [comment]
由于这个issue已经有一段时间没有更新，我打算关闭它以保持项目的整洁。如果您在未来还有任何问题或需要进一步的帮助，请随时重新打开此issue或创建一个新的issue。
