### ISSUE TITLE
Please provide support for 1.29 / 1.30

### ISSUE THREAD

**Issue by fzhan** [goodrain/rainbond#1924]
**Is your feature request related to a problem? Please describe.**
Apart from KubeSphere / Rancher you are one of the most up-to-date low code GUI for k8s DevOps. Please upgrade version support for 1.29

**Describe the solution you'd like**
Please upgrade version support for 1.29

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ZhangSetSail** [comment]
感谢您的建议和耐心等待！我们非常重视您的需求，但由于当前版本的开发计划已满，我们计划将此支持推迟到下下个版本（V5.19）进行开发。

**Comment by ZhangSetSail** [comment]
经测试v5.17.2版本 ，rainbond平台可以对接1.29版本，我将关闭该issue，有问题再重新打开
