### ISSUE TITLE
安装pipeline，流水线展示不完全

### ISSUE THREAD

**Issue by zzk8s** [goodrain/rainbond#1925]
“流水线”按钮只在安装pipeline的团队有展示，其余团队没有相关按钮；
其他问题：
若登陆后先进入安装pipeline的团队，切换团队后会有“流水线”按钮，但无法使用，点击后界面一直转圈不响应，刷新web界面后，流水线按钮消失
若登陆后先进入其他团队，在切换到安装pipeline团队，pipeline团队也不展示流水线按钮，刷新web界面后才能使用流水线

**Comment by ZhangSetSail** [comment]
感谢反馈，这看起来确实存在一些问题，安排在 5.18 版本修复

**Comment by 0478yhl** [comment]
> “流水线”按钮只在安装管道的团队有展示，其余团队没有相关按钮； 其他问题： 若登陆后先进入安装管道的团队，切换团队后会有“流水线”按钮，但无法使用，点击后界面一直转圈不响应，刷新web界面后，流水线按钮消失 若登陆后先进入其他团队，在切换到安装管道团队，管道团队也不展示流水线按钮，刷新web界面后才能使用流水线

经过我们测试，您所提及的问题并没有复现。您可以尝试以下思路排查下

1. 检测Pipeline所配置的URL是否可以正常访问
2. 服务组件是否正常启动
<img width="371" alt="image" src="https://github.com/goodrain/rainbond/assets/124012440/378cdf82-7f20-45fd-8d3a-777b2ae26529">

3.详细参考以下两篇文档步骤是否有遗漏
[GitLab CI 使用](https://www.rainbond.com/docs/devops/app-deploy/ci-tools/gitlab-ci/)
[Pipeline 安装](https://rainbond.com/docs/devops/pipeline/install/)

**Comment by zzk8s** [comment]
> > “流水线”按钮只在安装管道的团队有展示，其余团队没有相关按钮； 其他问题： 若登陆后先进入安装管道的团队，切换团队后会有“流水线”按钮，但无法使用，点击后界面一直转圈不响应，刷新web界面后，流水线按钮消失 若登陆后先进入其他团队，在切换到安装管道团队，管道团队也不展示流水线按钮，刷新web界面后才能使用流水线
> 
> 经过我们测试，您所提及的问题并没有复现。您可以尝试以下思路排查下
> 
> 1. 检测Pipeline所配置的URL是否可以正常访问
> 2. 服务组件是否正常启动
> 
> <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/124012440/336408103-378cdf82-7f20-45fd-8d3a-777b2ae26529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTgxMzIsIm5iZiI6MTcxODA5NzgzMiwicGF0aCI6Ii8xMjQwMTI0NDAvMzM2NDA4MTAzLTM3OGNkZjgyLTdmMjAtNDVmZC04ZDNhLTc3N2IyYWUyNjUyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwOTIzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTE0NzUzMTkwOGNkYWQ3Zjg3ZGUzNzk1OTA0NzY0MjczNjRmYmE2YzFjMjFjMTg2ZGUxZTE1YmExYjI5OWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P9TLCywMO1r0MTzjgwZbLOthO0zj2LFYQWjBJly8hog">
> 3.详细参考以下两篇文档步骤是否有遗漏 [GitLab CI 使用](https://www.rainbond.com/docs/devops/app-deploy/ci-tools/gitlab-ci/) [Pipeline 安装](https://rainbond.com/docs/devops/pipeline/install/)

![屏幕截图 2024-06-11 172452](https://github.com/goodrain/rainbond/assets/154494878/8f6f03df-16fb-46d6-818c-27154bf51a78)
组件均正常运行，但是pipeline的对外访问地址访问会提示401，没有权限，需要在哪做下配置吗

**Comment by ZhangSetSail** [comment]
将pipeline对外暴露的端口协议改成 tcp 试试

**Comment by ZhangSetSail** [comment]
将pipeline对外暴露的端口协议改成 tcp 试试

**Comment by ZhangSetSail** [comment]
该问题长时间没有更新，我先关闭该issue，有问题你可以随时重新打开
