### ISSUE TITLE
搭建的阿里云日志收集插件，在更新使用配置的时候，提示 update complex error, save plugin config failure:database is locked

### ISSUE THREAD

**Issue by unionstep** [goodrain/rainbond#1934]
一、使用镜像地址 registry.cn-hangzhou.aliyuncs.com/log-service/logtail:latest，构建

二、配置组管理：
属性名: ALIYUN_LOGTAIL_USER_ID属性类型: string可否修改: 可修改简短说明: 阿里云用户 ID
属性名: ALIYUN_LOGTAIL_USER_DEFINED_ID属性类型: string可否修改: 可修改简短说明: 日志服务机器自定义标识
属性名: ALIYUN_LOGTAIL_CONFIG属性类型: string可否修改: 可修改简短说明: 日志服务的配置文件
属性名: ALIYUN_LOG_ENV_TAGS属性类型: string可否修改: 可修改简短说明: 日志标签

<img width="2885" alt="image" src="https://github.com/goodrain/rainbond/assets/27877366/7a94389a-c16a-4a03-810f-7e75a0418b4c">

三、安装插件，更新配置
<img width="2001" alt="image" src="https://github.com/goodrain/rainbond/assets/27877366/83d45a22-ac85-4bb9-b3d5-eccdfb51b652">

四、接口报错：/console/teams/0fl34oza/apps/grb96b9f/plugins/3fa05c06a58446d588adfdc4a2a16206/configs
<img width="920" alt="image" src="https://github.com/goodrain/rainbond/assets/27877366/274d0a10-de96-471f-af33-fca9aa0f67aa">

**Comment by ZhangSetSail** [comment]
很明确的BUG，安排在5.18修复

**Comment by ZhangSetSail** [comment]
我这没有复现，是否能提供更详细的复现流程
<img width="1496" alt="image" src="https://github.com/goodrain/rainbond/assets/101104760/cbfdc9ce-6fe6-47f7-8a6d-dd6a0cbe10f3">

**Comment by unionstep** [comment]
步骤已经罗列的很详细了，如果还原不了，就算了吧。我已经换其他的插件来实现了。

**Comment by ZhangSetSail** [comment]
你是哪个版本呢，是不是快速安装的，我测试的helm和主机安装，可能跟这个有关，因为快速安装是sqlite的数据库，这个我今天再测试一下快速安装吧。

**Comment by 0478yhl** [comment]
> Step 已经罗列的很详细了，如果还原不了，就算了吧。我已经换了其他的插件来实现了。
万分感谢！！！我们成功的在5.17.1的快速安装里复现了此BUG，我们计划将在5.17.2版本修复。

**Comment by ZhangSetSail** [comment]
5.17.2版本已发布，该问题在5.17.2已经得到修复，你可以参考[升级文档](https://rainbond.com/docs/upgrade/latest-version)进行升级，我将关闭此issue，如果有问题你可以随时重新打开。

**Comment by unionstep** [comment]
好的。
