### ISSUE TITLE
关于网关配置X-Forwarded-For获取真实IP问题

### ISSUE THREAD

**Issue by anhao** [goodrain/rainbond#1947]
默认配置 https://github.com/goodrain/rainbond/blob/8a3186c9b57cf0fbabbcbe3b7bca09695fd06c80/gateway/controller/config/config.go#L108
```
"X-Forwarded-For":   "$remote_addr"
```
默认为 $remote_addr ，这样如果上层配置了CDN，会获取不到真实IP , 需要改成 `$proxy_add_x_forwarded_for;`

临时解决方案是 在网关策略里手动配置请求头

**Comment by ZhangSetSail** [comment]
是否有兴趣参与贡献一下呐。
