### ISSUE TITLE
希望支持maven多线程

### ISSUE THREAD

**Issue by xggz** [goodrain/rainbond#1952]
在使用maven构建代码时，即使配置了多线程参数也没有效果。

**Comment by ZhangSetSail** [comment]
问题概括：在使用 Maven 构建代码时，即使配置了多线程参数 (-T 参数)，也没有看到多线程构建的效果。你希望我们的项目能够更好地支持 Maven 的多线程构建。

为了帮助我们更好地理解和解决这个问题，能否请你提供一下以下信息：
1. 你使用的 Maven 版本。
2. 你在构建时使用的具体命令和参数。
3. 构建过程中是否有任何错误信息或者警告提示。

此外，如果你有任何关于如何配置或者优化多线程构建的建议或方案，我们非常愿意听取并尝试。具体来说，如果你有任何配置示例、调试步骤或者其他成功的经验分享，都将对我们非常有帮助。

**Comment by ZhangSetSail** [comment]
该问题长时间没有更新，我将暂时关闭，有问题再随时打开吧。
