### ISSUE TITLE
v5.17.2-release-8a3186c9b-2024-06-15-07，应用 资源监控下没有数据展示出来

### ISSUE THREAD

**Issue by unionstep** [goodrain/rainbond#1953]
应用 资源监控下没有数据展示出来

<img width="3021" alt="iShot_2024-07-03_16 52 16" src="https://github.com/goodrain/rainbond/assets/27877366/32c4839b-255f-4883-912b-06dd9f5b78aa">

**Comment by ZhangSetSail** [comment]
确实存在这个问题。我们已经安排在这两天进行修复，并会重新打包并覆盖 5.17.2 版本，修复打包后我会在这里进行补充

**Comment by ZhangSetSail** [comment]
<img width="1511" alt="image" src="https://github.com/goodrain/rainbond/assets/101104760/0875dea3-3170-43d1-bf5a-dca74173f5e9">
没问题了，重新拉一下5.17.2镜像就好

**Comment by ZhangSetSail** [comment]
先关了，有问题再反馈
