### ISSUE TITLE
【多集群异构CPU架构】应用模版导出helm chart包失败

### ISSUE THREAD

**Issue by jeanphorn** [goodrain/rainbond#1955]
我有两种类型的集群（arm架构和x86架构）在一个rainbond上管理， rainbond UI 控制端装在了x86集群上， 管理两个集群。 在arm64集群上发布了应用组件，在导出Helm Chart包时，提示架构不匹配。

![image](https://github.com/goodrain/rainbond/assets/5744511/b3abd3ec-185f-4dc3-acd5-8d6269e7b59d)

**Comment by ZhangSetSail** [comment]
很明确的bug，下个版本修复

**Comment by ZhangSetSail** [comment]
5.17.3 版本已发布，经验证问题已解决，我将关闭该 issue ，如果后续有问题再随时打开。
