### ISSUE TITLE
🎉V6.0 Version Release Plan

### ISSUE THREAD

**Issue by zzzhangqi** [goodrain/rainbond#1957]
当前的 V5 版本后续不会在发布新的功能特性，会持续维护 V5.18 小版本并修复 Bug。即将发布的 V6 版本是 Rainbond 下一个大版本，Rainbond V6 版本主要围绕平台底层架构精简以及扩展新的插件体系展开。

### rbd-eventlog 模块调整
- [x] 构建日志输出到共享存储进行实时推送
- [x] 实时推送组件运行日志，不储存组件运行日志
- [ ] 移除 rbd-eventlog 组件

### 移除 ETCD 依赖

- [x] 集群端所有组件都不再依赖 ETCD

### rbd-node 模块调整

- [x] 移除 rbd-node 组件
- [x] 移除内置 ServiceMesh 功能
- [ ] 使用其他服务替代 rbd-node 向主机写入 hosts 以及镜像仓库证书功能

### rbd-monitor 模块调整

- [x] #1978

### rbd-worker 模块调整

- [x] 平台默认注入环境变量调整 #1719 

### rbd-webcli 模块调整

- [x] 组件 Web 终端功能合并到 rbd-api 组件

### Websocket 端口调整

- [x] 不再对外暴露 Websocket 6060 端口，通过控制台 UI 7070 端口做代理访问

### 优化对共享存储的依赖

- [ ] 梳理底层组件存储依赖关系，不需要挂载的存储移除
- [ ] 优化用户找存储的途径

## 新功能

- [x] 支持界面化在线升级平台
- [ ] 主机安装升级
- [x] 权限升级，支持更细粒度的权限控制，支持到应用、组件级别的权限控制
- [ ] 支持 K8s Serverless 集群
- [x] 网关升级

## 平台插件

- [ ] 实现平台级的插件扩展

## UI 调整

- [x] 样式统一升级、调整
- [x] 前端框架版本升级

---

No new features will be released in the current V5 release, and V5.18 minor releases will be maintained and bugs fixed on an ongoing basis. The upcoming V6 release is the next big version of Rainbond, which focuses on streamlining the underlying architecture of the platform and expanding the new plug-in architecture.

### rbd-eventlog module adjustment
- [x] Build log output to shared storage for real-time push
- [x] Push component run logs in real time. Component run logs are not stored
- [ ] Remove `rbd-eventlog` component

### Remove ETCD dependencies

- [x] All components at the cluster end no longer rely on ETCD

### rbd-node module adjustment

- [x] Remove the rbd-node component
- [x] Remove the built-in ServiceMesh
- [ ] Use other services instead of rbd-node to write to hosts and mirror the warehouse certificate

### rbd-monitor module adjustment

- [x] The official Prometheus image is used directly, and the custom parts are defined through the configuration file

### rbd-worker module adjustment

- [x] Adjust the environment variables injected by the platform default #1719 

### rbd-webcli module adjustment

- [x] Component Web terminal functionality is incorporated into the rbd-api component

### Websocket port adjustment

- [x] The Websocket 6060 port is not exposed to the outside, and the console UI port 7070 is used for proxy access

### Optimize your reliance on shared storage

- [ ] The storage dependencies of the underlying components are sorted out and the storage that does not need to be mounted is removed
- [ ] Optimize the way users find storage

## Features

- [x] Supports the GUI online upgrade platform
- [ ] Host installation and upgrade
- [x] Upgrade permissions to support fine-grained permission control at the application and component levels
- [ ] Supports K8s Serverless clusters
- [x] Gateway upgrade

## Platform plug-in

- [ ] Implement platform-level plug-in extensions

## UI adjustment

- [x] Styles are upgraded and adjusted in a unified manner
- [x] The front-end framework version is upgraded

**Comment by shanmu-raoyunfei** [comment]
When is it scheduled for release?

**Comment by zzzhangqi** [comment]
> When is it scheduled for release?

A beta version will be released in September

**Comment by zzzhangqi** [comment]
Postponed to end of November

**Comment by Fitz-devs** [comment]
ipv6有计划支持吗，或者网关支持设置监听某个网卡

**Comment by zzzhangqi** [comment]
v6.0.0 released

**Comment by nebstudio** [comment]
请问当前已经安装并处于生产环境中的V5版本如何升级到V6版本呢？
