### ISSUE TITLE
HELM 创建组件出现异常，有部分 K8S 资源创建失败，但界面显示成功

### ISSUE THREAD

**Issue by MISAKIGA** [goodrain/rainbond#1958]
**Describe the bug**
When utilizing the Helm model to create the RAM application, errors occur in the creation of K8s sources. However, the UI indicates a successful creation. Running the RAM component gets blocked, with no pods and no logs.

**To Reproduce**
Steps to replicate the behavior:
On the page 'New -> Helm -> Image Source (Upload)'
Click 'Confirm Creation'
Initiate the component
The page continuously shows 'Starting', and upon inspection, no new pods emerge on k8s, while the k8s resource page indicates a successful creation.
Execute kubectl get deployment -n {Team}; kubectl get deployment -n {Team} common-vaultwarden -o yaml to observe an error message: message: 'pods "common-vaultwarden-6c787c5cb5-" is forbidden: error looking up service account msga-cn/vaultwarden-svc: serviceaccount "vaultwarden-svc" not found'

**Describe the bug**
当使用 Helm 模型创建 RAM 应用程序时，K8s 资源的创建出现错误。然而，用户界面（UI）显示创建成功。运行 RAM 组件时出现阻塞，没有 Pod 且没有日志。

**To Reproduce**
1. 页面 '新建-> Helm -> 镜像来源(上传)'
2. 点击 '确认创建'
3. 启动组件
4. 页面一直显示启动中，查看 k8s 上没有新 pod 出现，k8s 资源页面显示创建成功。
5. 执行 `kubectl get deployment -n {团队} ; kubectl get deployment -n {团队} common-vaultwarden -o yaml` 查看有报错：message: 'pods "common-vaultwarden-6c787c5cb5-" is forbidden: error looking up
      service account msga-cn/vaultwarden-svc: serviceaccount "vaultwarden-svc" not
      found'

**Screenshots**
![2087fa29a1fcc8abd6beaeeb9b2c433](https://github.com/user-attachments/assets/cc13f322-cf6d-4a91-80c2-81619d3ec7c2)

**The relevant information:**
 - Rainbond Version [v5.17.2]
 - Browser [edge] 
 - Kubernetes version [v1.29.6+k3s2]

**Comment by ZhangSetSail** [comment]
明确的bug，下个版本解决。

**Comment by ZhangSetSail** [comment]
5.17.3 版本已发布，经验证问题已解决，我将关闭该 issue ，如果后续有问题再随时打开。
