### ISSUE TITLE
自建集群添加节点时，若节点系统为centos，则主机添加集群时报错

### ISSUE THREAD

**Issue by KeKouShi** [goodrain/rainbond#1962]
错误日志为：
"Failed to set up SSH tunneling for host [XXXXX]: Can't retrieve Docker Info: error during connect: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info\": Unable to access the Docker socket (/var/run/docker.sock). Please check if the configured user can execute `docker ps` on the node, and if the SSH server version is at least version 6.7 or higher. If you are using RedHat/CentOS, you can't use the user `root`. Please refer to the documentation for more instructions. Error: ssh: rejected: administratively prohibited (open failed)"

**Comment by zzzhangqi** [comment]
> 错误日志为： "Failed to set up SSH tunneling for host [XXXXX]: Can't retrieve Docker Info: error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": Unable to access the Docker socket (/var/run/docker.sock). Please check if the configured user can execute `docker ps` on the node, and if the SSH server version is at least version 6.7 or higher. If you are using RedHat/CentOS, you can't use the user `root`. Please refer to the documentation for more instructions. Error: ssh: rejected: administratively prohibited (open failed)"

https://www.rainbond.com/docs/troubleshooting/installation/ui#rejected-administratively-prohibited

**Comment by ZhangSetSail** [comment]
问题是否得到解决了呢，解决了的话我就关闭这个issue了
