### ISSUE TITLE
系统崩溃后，基于备份的 rainbonddata 目录，恢复的控制台，导出的应用模型无法离线导入

### ISSUE THREAD

**Issue by orionpax1997** [goodrain/rainbond#1965]
**系统崩溃后，基于备份的 rainbonddata 目录，恢复的控制台，导出的应用模型无法离线导入**

观察了一下是导出的包有问题，应用没有插件但是导出的压缩包中包含了 plugin-images.tar，并且其中只有一个 manifest.json 文件，其中是 `null` 字符串。应用模型的导出日志在平台上没有找到位置查看。

**Screenshots**
![image](https://github.com/user-attachments/assets/721dda96-db8a-413d-894f-c196a9ce33a6)
![image](https://github.com/user-attachments/assets/6a4e2d96-f0b3-44ef-8939-73fc4f891f42)
![image](https://github.com/user-attachments/assets/0120f80c-c80a-44f6-a2a4-56b833251392)
![image](https://github.com/user-attachments/assets/cc0482e8-3cb1-4c01-9221-243ef2f2d31d)

**The relevant information:**
 - Rainbond Version v5.17.1-release
 - Kubernetes version 1.23.10

**Comment by ZhangSetSail** [comment]
说明一下平台版本还有安装方式

**Comment by orionpax1997** [comment]
> 说明一下安装方式

基于主机安装的

**Comment by ZhangSetSail** [comment]
抱歉，我又重新看了一下问题，如果你发布的应用未携带插件的话，临时解决办法就是把这个plugin包删除掉，应该就可以成功导入了。
你是切换了容器运行时吗。

**Comment by orionpax1997** [comment]
> 抱歉，我又重新看了一下问题，如果你发布的应用未携带插件的话，临时解决办法就是把这个plugin包删除掉，应该就可以成功导入了。 你是切换了容器运行时吗。

服务器宕机起不来了，救援模式给 rainbonddata 目录拿出来，然后重新用基于主机安装的流程，给 rainbonddata 目录挂载上去启动的。除了离线导入的问题，其他目前一切正常。

**Comment by ZhangSetSail** [comment]
你发布的应用包含插件吗，提供一下导出的时候rbd-chaos日志吧。

**Comment by orionpax1997** [comment]
> 你发布的应用包含插件吗，提供一下导出的时候rbd-chaos日志吧。

我测试了包含插件的没有问题，可以正常导出。不包含插件的会出问题，生成了错误的 plugin-images.tar。

导出时chaos没有日志产生，但是历史日志中有如下报错。

```log
time="2024-08-30T13:26:14+08:00" level=error msg="rbd-hub exec cmd fail: failed to garbage collect: failed to mark: filesystem: Path not found: /docker/registry/v2/repositoriescommand terminated with exit code 1"
time="2024-08-30T14:26:14+08:00" level=error msg="rbd-hub exec cmd fail: failed to garbage collect: failed to mark: filesystem: Path not found: /docker/registry/v2/repositoriescommand terminated with exit code 1"
time="2024-08-30T15:26:14+08:00" level=error msg="rbd-hub exec cmd fail: failed to garbage collect: failed to mark: filesystem: Path not found: /docker/registry/v2/repositoriescommand terminated with exit code 1"
time="2024-08-30T16:26:15+08:00" level=error msg="rbd-hub exec cmd fail: failed to garbage collect: failed to mark: filesystem: Path not found: /docker/registry/v2/repositoriescommand terminated with exit code 1"
time="2024-08-30T17:26:15+08:00" level=error msg="rbd-hub exec cmd fail: failed to garbage collect: failed to mark: filesystem: Path not found: /docker/registry/v2/repositoriescommand terminated with exit code 1"
time="2024-08-30T18:26:15+08:00" level=error msg="rbd-hub exec cmd fail: failed to garbage collect: failed to mark: filesystem: Path not found: /docker/registry/v2/repositoriescommand terminated with exit code 1"
```

**Comment by ZhangSetSail** [comment]
我会尝试装一个5.17.1版本去复现你的问题

**Comment by ZhangSetSail** [comment]
检查一下chaos版本，我测试5.17.1没问题，如果没有插件导出的包里不会有plugin的tar包

**Comment by orionpax1997** [comment]
> 检查一下chaos版本，我测试5.17.1没问题，如果没有插件导出的包里不会有plugin的tar包

版本是一样的，chaos 的导出日志我没有看到。是发布应用会输出日志，还是导出的时候会输出日志？我感觉是不是这个报错导致的
`rbd-hub exec cmd fail: failed to garbage collect: failed to mark: filesystem: Path not found: /docker/registry/v2/repositoriescommand terminated with exit code 1`
 
![image](https://github.com/user-attachments/assets/147b5a52-c1f5-4f72-bfaa-80016f0cfc0d)

**Comment by ZhangSetSail** [comment]
你在微信群吗，我远程给你看看

**Comment by orionpax1997** [comment]
> 你在微信群吗，我远程给你看看

😂不太方便提供远程，或者说我可以给 chaos 加点日志，重新编译一下替换个镜像看看。

**Comment by ZhangSetSail** [comment]
你试试换一下最新的chaos镜像，v5.17.3 的，看看能不能解决问题，不会影响生产。

**Comment by orionpax1997** [comment]
> 你试试换一下最新的chaos镜像，v5.17.3 的，看看能不能解决问题，不会影响生产。

感谢，已经解决了。确实是 chaos 的问题，之前控制台配置了两个集群，我默认是发布镜像的那个团队下面的集群负责打包，实际上是另外的一个集群去打包了，我给 chaos 升级了就好了。
