### ISSUE TITLE
双集群共用一个控制台的问题

### ISSUE THREAD

**Issue by Hanxc-erds** [goodrain/rainbond#1966]
**Describe the bug**
情况是先使用一个控制台创建了一个K8S集群，这个集群里存在 rbd-app-ui 组件，后续使用相同的控制台创建了另一个集群，两个集群共用同一个控制台，但是后续创建的这个集群里没有 rbd-app-ui 组件，没有监听 7070 端口，导致在控制台中编辑第二个集群的节点时提示 “API请求错误”，打开 F12 开了一下，访问的是 7070端口。这种情况该怎么解决？

**To Reproduce**
1. 先使用一个控制台创建一个 K8S 集群 A，A集群中存在 rbd-app-ui 组件
2. 再使用同一个控制台创建第二个 K8S 集群 B，B集群中不存在 rbd-app-ui 组件
3. 进入控制台，进入 B 集群的集群管理页面，点击编辑节点
4. 出现报错，API 请求错误
5. 查看请求地址，请求的是 7070 端口
6. 查看 B 集群，没有 rbd-app-ui 组件，没有监听 7070 端口
7. 查看控制台日志，有报错，报错信息请查看下方第2，第3张图片

**Screenshots**
![00](https://github.com/user-attachments/assets/381b4240-0d42-4197-a5c7-a83f2f7bb89a)
![11](https://github.com/user-attachments/assets/b0ba9379-7117-4466-9c51-5ed7ec3d5bdd)
![22](https://github.com/user-attachments/assets/ccf339a8-d52d-48e0-88b5-dfdc529ecaa8)
![33](https://github.com/user-attachments/assets/efd5c1f5-eec2-4fcb-913a-85d7bbc5a0da)
![44](https://github.com/user-attachments/assets/5ca18a72-25e0-4055-a857-f0b2860347db)
![55](https://github.com/user-attachments/assets/851892ac-44ae-4c7e-a290-2a2b56b04c9f)

**The relevant information:**
 - Rainbond Version [e.g. 5.17.3]
 - Kubernetes version [e.g 1.23.10]

**Comment by ZhangSetSail** [comment]
明确的bug，安排在下个版本修复

**Comment by zzzhangqi** [comment]
在 6.0.1 版本中已解决
