### ISSUE TITLE
关于使用rainbond组建集群安装无法对接的问题

### ISSUE THREAD

**Issue by IffyWu** [goodrain/rainbond#1967]
**Describe the bug**
使用云服务器安装rainbond后，通过rainbond面板构建集群。会遇到构建失败，对接不了集群的问题。原因是集群需要的容器镜像所需要开放的端口不一致导致。官方文档只写了80，443，6060，7070，8443这5个端口开放，实际allinone安装是只需要这5个端口。集群不只这5个端口。虽然可以用全端口开放来临时解决。但最好把rainbond集群所需要开放的端口都列出来，以便运维方便网络管理。

**Comment by ZhangSetSail** [comment]
详细端口如下：10250,111,20048,2049,2379,2380,32803,6060,6443,662,7070,8443,875,10248,10249,10256,49917,905,38548,68,123,8472
