### ISSUE TITLE
能否提供关于 历史镜像的清理？ 目前磁盘空间不足

### ISSUE THREAD

**Issue by blackwait** [goodrain/rainbond#1974]
能否提供关于 历史镜像的清理？ 目前磁盘空间不足，每次构建 都会导致硬盘资源增加，而历史残留的镜像，很多都是不需要使用的，服务器 /root/rainbonddata 根目录的磁盘空间 有限，无法对外扩展。

**Comment by 0478yhl** [comment]
看下这个文章是否能帮助到你清理下镜像

[清理镜像地址](https://t.goodrain.com/d/21-rbd-hub)

**Comment by zzzhangqi** [comment]
如未解决请再次开启此issue
