### ISSUE TITLE
run LightGBM with multithreading on rainbond will cause LightGBM to hang

### ISSUE THREAD

**Issue by CCYYGO** [goodrain/rainbond#1976]
**Describe the bug**
I finished the ci/cd pipeline and run the programs on Rainbond, I find the program be stucked.I try to solve this problem and find the [#issue](https://lightgbm.readthedocs.io/en/latest/FAQ.html#lightgbm-hangs-when-multithreading-openmp-and-using-forking-in-linux-at-the-same-time) on LightGBM FAQ.
I try to set nthread=1, it solve the problem that program not be stucked, but it run slowly. 
So, i want to know that how i can using multithreading LightGBM on Rainbond

**Comment by ZhangSetSail** [comment]
尝试一下 调整 CPU、内存 资源，调整 nthread 参数，设置为适合的线程数（比如与 CPU 核心数相匹配）

**Comment by CCYYGO** [comment]
谢谢，我的问题被解决了。
我还有一写额外的疑问：

- 是否只要是小于等于线程数即可？还是说需要与核心数相等？
- 其背后的原理是否和 rainbond 启用多线程的方式相关？还是说与编译方式有关？我在本地的docker容器直接跑源码是没有遇见这个问题的

**Comment by ZhangSetSail** [comment]
第一个问题，小于等于都可以，等于的话是最佳配置。
第二个问题，还不能确定，你这个项目有自己的 dockerfile 吗，尝试用自己的 dockerfile 构建看看是否会出现这个问题。

**Comment by ZhangSetSail** [comment]
还有问题吗，没问题我将关闭这个issue了

**Comment by CCYYGO** [comment]
好的，暂时没什么问题，谢谢

---- Replied Message ----
| From | ***@***.***> |
| Date | 10/18/2024 14:20 |
| To | goodrain/rainbond ***@***.***> |
| Cc | CCYYGO ***@***.***>,
Author ***@***.***> |
| Subject | Re: [goodrain/rainbond] run LightGBM with multithreading on rainbond will cause LightGBM to hang (Issue #1976) |

Closed #1976 as completed.
