### ISSUE TITLE
控制台不能实现高可用

### ISSUE THREAD

**Issue by loucongV** [goodrain/rainbond#1989]
**Describe the bug**
当 rbd-api-ui 组件多 Pod 部署的时候，会出现调用 A Pod 登录接口获取的 Token，在 B Pod 上没有办法解析，导致会重新登录

**To Reproduce**
1. rbd-api-ui 启动多个 Pod
2. 使用管控台进行登录

**The relevant information:**
 - Rainbond Version [e.g. 5.17.3]
 - k8s version [e.g 1.30.2]

**Comment by ZhangSetSail** [comment]
感谢反馈。这个问题较为明确，我们将安排在近期进行修复。

**Comment by zzzhangqi** [comment]
fix in v6.0.1-releaes
