### ISSUE TITLE
按照在线安装文档，安装访问7070报数据库连接错误

### ISSUE THREAD

**Issue by kevin24067** [goodrain/rainbond#20]
`bash <(curl -s http://repo.goodrain.com/install/3.4.1/start.sh)`

![image](https://user-images.githubusercontent.com/8542021/34403957-5ec69cdc-ebe6-11e7-9a62-a48cd84b1331.png)

**Comment by ysicing** [comment]
检查rbd-app-ui和rbd-db服务是否Up
`dc-compose ps | egrep "(rbd-app-ui|rbd-db)"`
通过`grctl configs get`获取数据库配置，检查`/etc/goodrain/console`中关于数据库配置是否匹配
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
       .....<具体配置>
    },
}
```

**Comment by ysicing** [comment]
如果还有问题，reopen issue
