### ISSUE TITLE
脚本一键安装报错curl: (35) OpenSSL SSL_connect: 连接被对方重设 in connection to get.rainbond.com:443

### ISSUE THREAD

**Issue by chiyuanhua** [goodrain/rainbond#2006]

**Comment by chiyuanhua** [comment]
![image](https://github.com/user-attachments/assets/3c82223b-4a8b-4edb-a531-658b0fc8fe7e)

**Comment by ZhangSetSail** [comment]
检查下你的防火墙配置 和网络

**Comment by chiyuanhua** [comment]
防火墙和网络都是正常的，curl别的网站也是正常的

**Comment by ZhangSetSail** [comment]
说一下环境信息，我尝试复现一下

**Comment by ZhangSetSail** [comment]
说一下环境信息，我尝试复现一下

**Comment by chiyuanhua** [comment]
centos

**Comment by chiyuanhua** [comment]
我试过centos、debian、欧拉等系统，都不行，是我的网络策略有问题吗
我curl百度是正常的

**Comment by chiyuanhua** [comment]
我试过centos、debian、欧拉等系统，都不行，是我的网络策略有问题吗
我curl百度是正常的

**Comment by chiyuanhua** [comment]
我试过centos、debian、欧拉等系统，都不行，是我的网络策略有问题吗
我curl百度是正常的

**Comment by ZhangSetSail** [comment]
好的，今天我复现一下

**Comment by zzzhangqi** [comment]
https://get.rainbond.com 由阿里云 OSS 提供服务，也许是您与阿里云网络存在问题，请排查自己的网络问题，我将关闭这个 issue
