### ISSUE TITLE
应用离线导入失败，导致集群重启

### ISSUE THREAD

**Issue by KeKouShi** [goodrain/rainbond#2053]
1.应用离线导入时，会占用磁盘io极高
2.导致集群响应超时，集群自动重启
3.rainbond组件重启后提示应用导入失败
![image](https://github.com/user-attachments/assets/de90c659-be2b-4904-83c8-9970a667d295)

**Comment by zzzhangqi** [comment]
看起来不像是 rainbond 的问题，您应该解决磁盘性能问题
