### ISSUE TITLE
快速安装成功 端口都开放了 单位是访问不了ip:7070 

### ISSUE THREAD

**Issue by chenlei0615** [goodrain/rainbond#2082]
快速安装成功 端口都开放了 单位是访问不了ip:7070 

日志：
k8s.io/client-go@v1.30.4-k3s1/tools/cache/reflector.go:232: watch of *v1.Job ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding

**Comment by zzzhangqi** [comment]
@chenlei0615 从您的问题中我没有得到任何有效的信息，请提供更多信息可供排查，例如安装命令、启动日志、问题现状等等，以及截图说明

**Comment by zzzhangqi** [comment]
长时间未得到回复，我将关闭它，如有问题请再次打开
