### ISSUE TITLE
这是什么问题？

### ISSUE THREAD

**Issue by skemdddd** [goodrain/rainbond#211]
ERROR MESSAGE SUMMARY **********************************************************
[Slave2]: Ansible UNREACHABLE! => playbook: setup.yml; TASK: Gathering Facts; message: {"changed": false, "msg": "SSH Error: data could not be sent to remote host \"10.25.81.226\". Make sure this host can be reached over ssh", "unreachable": true}
Ask for help:
Contact us: rainbond@goodrain.com
Community: https://t.goodrain.com
It seems that you encounter some problems. You can send an email to the above email address, attached with the rainbond-ansible/inventory/hosts and rainbond-ansible/log/rainbond.log files and the error message, or new issue on https://github.com/goodrain/rainbond-ansible/issues. We'll try our best to help you deploy a Rainbond cluster. Thanks. :-)
Tuesday 29 January 2019  11:16:27 +0800 (0:01:39.535)       0:01:39.659 ******* 

安装在阿里云服务器上

**Comment by ysicing** [comment]
你需要确定你当前机器能ssh 10.25.81.226

**Comment by barnettZQG** [comment]
This issues has timed out with no response
