### ISSUE TITLE
WEB界面在Safari显示问题

### ISSUE THREAD

**Issue by iwin4aids** [goodrain/rainbond#214]
测试版本safari-12.0.2，safari浏览器显示的问题，部分弹窗按钮无法点击，如：
<img width="1086" alt="wechatimg51" src="https://user-images.githubusercontent.com/16768783/52623267-e6243880-2ee6-11e9-9af2-230ab9e138e0.png">

以下是对比chrome的显示：
<img width="486" alt="wechatimg50" src="https://user-images.githubusercontent.com/16768783/52623272-e7edfc00-2ee6-11e9-980d-14cea5034caf.png">

另外一直以来safari的时间显示都是NaN，如下：
<img width="600" alt="wechatimg55" src="https://user-images.githubusercontent.com/16768783/52623418-33a0a580-2ee7-11e9-8b39-d5910bab7f7b.png">

**Comment by zsl1549** [comment]
已修改 请关注下个版本的更新，谢谢。

**Comment by barnettZQG** [comment]
https://github.com/goodrain/rainbond-ui/pull/65
