### ISSUE TITLE
Http类型的应用能不能不要强制域名，某些内部应用客户没有DNS，把应用弄成TCP有感觉怪怪的

### ISSUE THREAD

**Issue by liyang-live** [goodrain/rainbond#224]
If you want to report a bug or advice, please provide the following information and try to describe your issue in English, If it's a question of use,please read the [documentation](https://www.rainbond.com/docs/stable/) or browse the [community](https://t.goodrain.com/)

- [x] Rainbond versions(eg. grctl version)

- [ ] Kubernetes versions(If you use your own cluster)

- [ ] Operating system and kernel

- [ ] Provider(Aliyun,VirtualBox,...)

- [ ] Install details(Online/Offline,SingleNode/HA)

**Comment by barnettZQG** [comment]
@liyang-live 将你的问题描述清楚一些便于我们理解你的用意

**Comment by liyang-live** [comment]
> @liyang-live 将你的问题描述清楚一些便于我们理解你的用意

内网环境下，客户没有dns服务器（医院/企业等内部应用），这个时候的http应用没发直接通过ip进行访问，如果要访问就要把协议改成tcp才能直接通过ip，但是改成TCP实施人员有感觉怪怪的

**Comment by barnettZQG** [comment]
@liyang-live  
应用网关-访问策略管理-添加TCP访问策略
无需设置端口协议为Http

**Comment by barnettZQG** [comment]
问题已回复，无反馈
