### ISSUE TITLE
通过自建的GitLab新建应用报错'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by aidisheng** [goodrain/rainbond#27]
GitLab是云帮安装的，项目设置为public，是Eureka-Server项目，并写了Dockerfile，该项目是网上的开源找的，源码地址：https://github.com/forezp/SpringCloudLearning/tree/master/chapter11/eureka-server
，把这个文件夹，push到gitlab的一个项目根目录下。

新建项目时填写的Git地址：http://80.gr4aba28.afa.11lx7.goodrain.org/afa/eureka-server.git，浏览器可以直接打开。

日志信息：[main.log](https://github.com/goodrain/rainbond/files/1605590/main.log)

**Comment by zhouyq** [comment]
首先来说：https://github.com/forezp/SpringCloudLearning/tree/master/chapter11/eureka-server 的代码是可以直接在云帮通过源代码的方式部署的。

但这个项目需要使用 https://repo.spring.io/milestone/ 仓库中的jar包。

java源码构建，云帮平台会将所有的maven仓库mirror到 maven.goodrain.me 这个地址，也就是云帮内部的maven仓库，可以通过 http://管理节点ip:8081 访问，用户名：admin，密码：admin

默认情况下云帮内部的maven仓库并没有代理 https://repo.spring.io/milestone/ 仓库，因此，需要手动添加这个maven仓库。相关文档参见：http://www.rainbond.com/docs/stable/best-practice/connection-maven-repository.html
