### ISSUE TITLE
Need oauth2.0 sso support

### ISSUE THREAD

**Issue by netroby** [goodrain/rainbond#299]
Need oauth2.0 sso support, for enterprise , company need to control their users . so an oauth2.0 sso login is much more better .
hope rainbond support oauth 2.0 sso login

**Comment by barnettZQG** [comment]
@netroby  TODO

**Comment by panda-zxs** [comment]
在v5.1.9中，我们已经加入此功能，详细信息可参考https://www.rainbond.com/docs中的相关文档
