### ISSUE TITLE
创建应用卡在代码同步

### ISSUE THREAD

**Issue by ysicing** [goodrain/rainbond#30]
![image](https://user-images.githubusercontent.com/8605565/34701864-82712b8c-f525-11e7-9e4a-2c6d354df8ce.png)

日志：

![image](https://user-images.githubusercontent.com/8605565/34701880-985aad1a-f525-11e7-9739-b83d06a2d2b4.png)

**Comment by Gemrails** [comment]
#### 非bug
请检查rbd-lb组件中的forward.conf配置是否生效，将console.goodrain.me请求正确的转向到对应服务器的7070端口
