### ISSUE TITLE
第三方服务实例地址支持域名

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond#317]
需求说明： 第三方服务集成云厂商提供的数据库服务是Rainbond用户常用的场景，例如阿里云提供的RDS资源默认的访问地址都是域名的形式，目前5.1版本中只能添加IP地址，我们需要支持域名。
预计版本:    5.1.6

**Comment by barnettZQG** [comment]
开发周期调整到v5.1.8

**Comment by fanyangyang** [comment]
#445
