### ISSUE TITLE
应用服务重启时平台的内存统计出错

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#328]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ 私有云 ] 部署环境：公有云、私有云

在gitlab和"ServiceMesh电商业务微服务架构示例"同时运行时，会由于服务重启造成平台的内存统计错误。
![image](https://user-images.githubusercontent.com/33855684/61678865-c9621b80-ad36-11e9-8e14-bef9031bb4d6.png)
![image](https://user-images.githubusercontent.com/33855684/61678873-cebf6600-ad36-11e9-94d9-f4ad93a24c69.png)
平台统计的内存使用远大于实际使用内存。

**Comment by barnettZQG** [comment]
看起来由于错误的POD导致统计错误，需要修复这个BUG

**Comment by barnettZQG** [comment]
https://github.com/goodrain/rainbond/issues/326
