### ISSUE TITLE
无法挂载本地目录

### ISSUE THREAD

**Issue by luoqiz** [goodrain/rainbond#329]
1：镜像创建的无持久化目录
![image](https://user-images.githubusercontent.com/22161059/61843549-b1bd9b00-aece-11e9-8ba6-ff2a296a3f85.png)
2：命令创建的使用持久化（本地）存储无法启动
 版本：5.1.5

**Comment by barnettZQG** [comment]
无法启动时请提供更加详细的说明：
1. grctl service get 命令执行结果
2. 集群状态是否正常，特别时存储服务。

**Comment by barnettZQG** [comment]
我们将关闭这个issues,如果未解决请重新打开。
