### ISSUE TITLE
get container detail info failure

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond#331]
- [x] Rainbond版本(执行grctl version获取)
5.1.5
get container detail info failure and causes null pointer exception
![image](https://user-images.githubusercontent.com/18493394/61870373-878ccd00-af10-11e9-9b39-9e9334727367.png)

**Comment by barnettZQG** [comment]
由于从docker中获取容器列表，有容器无法获取详情导致了空指针BUG，已修复。

**Comment by 651016236** [comment]
5目前5.1.5怎么更新修复这个问题

**Comment by dazuimao1990** [comment]
```
docker pull rainbond/cni:rbd_V5.1-dev
docker run -ti --rm -v /tmp:/tmp rainbond/cni:rbd_V5.1-dev tar xf /pkg.tgz -C /tmp
systemctl stop node 
cp -p /tmp/bin/* /usr/local/bin/
systemctl start node
```
@651016236
