### ISSUE TITLE
应用市场安装 elasticsearch_kibana报错

### ISSUE THREAD

**Issue by xiaoqing0729** [goodrain/rainbond#334]
![image](https://user-images.githubusercontent.com/16095288/61920816-70d88b80-af8d-11e9-96f6-67f4e6acbdfc.png)
从应用市场安装elasticsearch_kibana报错，麻烦大佬看下什么情况

**Comment by xiaoqing0729** [comment]
安装rabbitmq也是一样的错

**Comment by barnettZQG** [comment]
管理节点网络是否可以正常从image.goodrain.com获取镜像？

**Comment by barnettZQG** [comment]
经过测试目前发现此应用确实镜像无法获取，我们将尽快修复这个问题。

**Comment by barnettZQG** [comment]
故障已修复，请尝试重新安装。
我将关闭此问题，如果还有故障请重新打开。
