### ISSUE TITLE
rainbond控制台管理实例unable to upgrade connection: pod does not exist如何修复

### ISSUE THREAD

**Issue by yszansx** [goodrain/rainbond#337]
BUG

一共两台部署rainband
安装类型: manage,compute,gateway + compute 
问题
水平扩展实例，容器实例落在节点compute ，rainband控制台显示正常运行。

但是rainband 控制台--管理容器--实例管理 提示如下报错。

Defaulting container name to 29011a506d3bbb44d6aee35a5266095b.
Use 'kubectl describe pod/gr66095b-1 -n 08c70243e9904346a88c351aa35f24e1' to see all of the containers in this pod.
error: unable to upgrade connection: pod does not exist

到控制台可以连的实例里面ping 08c70243e9904346a88c351aa35f24e1 可以通。且控制台正常运行。
集群状态正常 dns解析正常。

- [ ] Rainbond版本(执行grctl version获取)
Rainbond grctl v5.1.5-release-78d829c-2019-07-08-10
- [ ] 操作系统类型和版本
Rainbond版本:5.1.5
操作系统:CentOS Linux release 7.6.1810 (Core)
内核版本:3.10.0-957.21.3.el7.x86_64
- [ ] 部署环境：公有云、私有云
私有云 esxi

**Comment by yszansx** [comment]
https://t.goodrain.com/t/unable-to-upgrade-connection-pod-does-not-exist/1090/1

**Comment by barnettZQG** [comment]
提示Pod不存在时可以手动检查一下pod是否真的不存在。
两个途径：
1. 执行报错中的引导命令： kubectl describe pod/gr66095b-1 -n 08c70243e9904346a88c351aa35f24e1
2.  执行grctl service get命令确认当前服务部署pod名称

**Comment by yszansx** [comment]
[root@kubeapi gr66095b-0]# grctl service get gr66095b -t jinbrkto
Namespace:      	08c70243e9904346a88c351aa35f24e1
ServiceID:      	29011a506d3bbb44d6aee35a5266095b
ReplicationType:	statefulset                     
ReplicationID:  	gr66095b                        
Status:         	running                         
------------Service------------
+---------------------+---------------+------------+
| Name                | IP            | Port       |
+---------------------+---------------+------------+
| gr66095b            | None          | (TCP:8848) |
| service-109-8848    | 11.2.169.157  | (TCP:8848) |
| service-109-8848out | 11.11.199.240 | (TCP:8848) |
+---------------------+---------------+------------+

------------Ingress------------
+----------------------------------+-----------------------------------------+
| Name                             | Host                                    |
+----------------------------------+-----------------------------------------+
| 7493a6ea4525e64ac8e44948126c2f60 | 8848.gr66095b.jinbrkto.771648.grapps.cn |
| 46adccd1b5378d8dc61e41aa7047da10 | 8848.gr66095b.jinbrkto.771648.grapps.cn |
+----------------------------------+-----------------------------------------+

-------------------Pod_1-----------------------
PodName:      	gr66095b-2                                                                                                                          
PodStatus:    	Initialized : True  Ready : True  PodScheduled : True                                                                               
PodIP:        	10.0.81.98                                                                                                                          
PodHostIP:    	192.168.10.212                                                                                                                      
PodHostName:  	959eba4b-6bbe-4ad5-ba0f-ecfad17d378d                                                                                                
PodVolumePath:	/grdata/tenant/08c70243e9904346a88c351aa35f24e1/service/29011a506d3bbb44d6aee35a5266095b/home/nacos/logs/gr66095b-2:/home/nacos/logs
              	                                                                                                                                    
PodStratTime: 	2019-08-01T16:37:40+08:00                                                                                                           
Containers:   	                                                                                                                                    
+--------------+-----------------------------------------+-------------------------------------------------------------------------------+------------------------------------+
| ID           | Name                                    | Image                                                                         | State                              |
+--------------+-----------------------------------------+-------------------------------------------------------------------------------+------------------------------------+
| c7c1a3a384ab | 29011a506d3bbb44d6aee35a5266095b        | goodrain.me/geeboo/nacos:20190717165604                                       | Running(2019-08-01T19:44:54+08:00) |
| c1fdf7ef94c3 | plugin-f49b821b723f437fb533d9d778bc5b40 | goodrain.me/plugin_tcm_f49b821b723f437fb533d9d778bc5b40:latest_20190718094426 | Running(2019-08-01T19:44:57+08:00) |
+--------------+-----------------------------------------+-------------------------------------------------------------------------------+------------------------------------+

-------------------Pod_2-----------------------
PodName:      	gr66095b-0                                                                                                                     
PodStatus:    	Initialized : True  Ready : True  PodScheduled : True                                                                          
PodIP:        	10.0.207.98                                                                                                                    
PodHostIP:    	192.168.10.101                                                                                                                 
PodHostName:  	d7ac90c5-3fb7-46f4-9d3c-c05667252f71                                                                                           
PodVolumePath:	/grdata/tenant/08c70243e9904346a88c351aa35f24e1/service/29011a506d3bbb44d6aee35a5266095b/home/nacos/gr66095b-0:/home/nacos/logs
              	                                                                                                                               
PodStratTime: 	2019-08-01T16:37:30+08:00                                                                                                      
Containers:   	                                                                                                                               
+--------------+-----------------------------------------+-------------------------------------------------------------------------------+------------------------------------+
| ID           | Name                                    | Image                                                                         | State                              |
+--------------+-----------------------------------------+-------------------------------------------------------------------------------+------------------------------------+
| 5474a424c7d2 | 29011a506d3bbb44d6aee35a5266095b        | goodrain.me/geeboo/nacos:20190717165604                                       | Running(2019-08-01T16:37:32+08:00) |
| dcde47ddfb4c | plugin-f49b821b723f437fb533d9d778bc5b40 | goodrain.me/plugin_tcm_f49b821b723f437fb533d9d778bc5b40:latest_20190718094426 | Running(2019-08-01T16:37:32+08:00) |
+--------------+-----------------------------------------+-------------------------------------------------------------------------------+------------------------------------+

-------------------Pod_3-----------------------
PodName:      	gr66095b-1                                                                                                                          
PodStatus:    	Initialized : True  Ready : True  PodScheduled : True                                                                               
PodIP:        	10.0.81.83                                                                                                                          
PodHostIP:    	192.168.10.212                                                                                                                      
PodHostName:  	959eba4b-6bbe-4ad5-ba0f-ecfad17d378d                                                                                                
PodVolumePath:	/grdata/tenant/08c70243e9904346a88c351aa35f24e1/service/29011a506d3bbb44d6aee35a5266095b/home/nacos/logs/gr66095b-1:/home/nacos/logs
              	                                                                                                                                    
PodStratTime: 	2019-08-01T16:37:37+08:00                                                                                                           
Containers:   	                                                                                                                                    
+--------------+-----------------------------------------+-------------------------------------------------------------------------------+------------------------------------+
| ID           | Name                                    | Image                                                                         | State                              |
+--------------+-----------------------------------------+-------------------------------------------------------------------------------+------------------------------------+
| e6a5ffa846ce | 29011a506d3bbb44d6aee35a5266095b        | goodrain.me/geeboo/nacos:20190717165604                                       | Running(2019-08-01T19:44:54+08:00) |
| a24aef69df16 | plugin-f49b821b723f437fb533d9d778bc5b40 | goodrain.me/plugin_tcm_f49b821b723f437fb533d9d778bc5b40:latest_20190718094426 | Running(2019-08-01T19:44:57+08:00) |
+--------------+-----------------------------------------+-------------------------------------------------------------------------------+------------------------------------+

**Comment by yszansx** [comment]
[root@kubeapi gr66095b-0]# kubectl describe pod/gr66095b-0 -n 08c70243e9904346a88c351aa35f24e1
Name:           gr66095b-0
Namespace:      08c70243e9904346a88c351aa35f24e1
Node:           d7ac90c5-3fb7-46f4-9d3c-c05667252f71/192.168.10.101
Start Time:     Thu, 01 Aug 2019 16:37:30 +0800
Labels:         controller-revision-hash=gr66095b-57c495c69f
                creater=Rainbond
                creater_id=1564648650249765656
                name=gr66095b
                service_alias=gr66095b
                service_id=29011a506d3bbb44d6aee35a5266095b
                statefulset.kubernetes.io/pod-name=gr66095b-0
                tenant_id=08c70243e9904346a88c351aa35f24e1
                tenant_name=jinbrkto
                version=20190731213754
Annotations:    <none>
Status:         Running
IP:             10.0.207.98
Controlled By:  StatefulSet/gr66095b

**Comment by yszansx** [comment]
[root@kubeapi gr66095b-0]# kubectl describe pod/gr66095b-0 -n 08c70243e9904346a88c351aa35f24e1
Name:           gr66095b-0
Namespace:      08c70243e9904346a88c351aa35f24e1
Node:           d7ac90c5-3fb7-46f4-9d3c-c05667252f71/192.168.10.101
Start Time:     Thu, 01 Aug 2019 16:37:30 +0800
Labels:         controller-revision-hash=gr66095b-57c495c69f
                creater=Rainbond
                creater_id=1564648650249765656
                name=gr66095b
                service_alias=gr66095b
                service_id=29011a506d3bbb44d6aee35a5266095b
                statefulset.kubernetes.io/pod-name=gr66095b-0
                tenant_id=08c70243e9904346a88c351aa35f24e1
                tenant_name=jinbrkto
                version=20190731213754
Annotations:    <none>
Status:         Running
IP:             10.0.207.98
Controlled By:  StatefulSet/gr66095b

**Comment by yszansx** [comment]
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                       node.kubernetes.io/unreachable:NoExecute for 300s

**Comment by yszansx** [comment]
[root@kubeapi ~]# grctl cluster
               	Used/Total  	Use of
CPU            	 3/44       	7%    
Memory         	15296/126493	12%   
DistributedDisk	66Gb/99Gb   	66.31%
+-------------------------+-----------------------+---------+
| Service                 | HealthyQuantity/Total | Message |
+-------------------------+-----------------------+---------+
| ClusterStatus           | healthy               |         |
| rbd-db                  | 1/1                   |         |
| rbd-eventlog            | 1/1                   |         |
| rbd-worker              | 1/1                   |         |
| docker                  | 2/2                   |         |
| kube-apiserver          | 1/1                   |         |
| nfs_server              | 2/2                   |         |
| rbd-app-ui              | 1/1                   |         |
| etcd                    | 1/1                   |         |
| kube-controller-manager | 1/1                   |         |
| rbd-webcli              | 1/1                   |         |
| rbd-dns                 | 2/2                   |         |
| rbd-repo                | 1/1                   |         |
| etcd-proxy              | 1/1                   |         |
| rbd-api                 | 1/1                   |         |
| rbd-chaos               | 1/1                   |         |
| storage                 | 2/2                   |         |
| NodeUp                  | 2/2                   |         |
| calico                  | 2/2                   |         |
| kubelet                 | 2/2                   |         |
| local-dns               | 2/2                   |         |
| rbd-monitor             | 1/1                   |         |
| rbd-mq                  | 1/1                   |         |
| KubeNodeReady           | 2/2                   |         |
| kube-scheduler          | 1/1                   |         |
| rbd-gateway             | 1/1                   |         |
| rbd-hub                 | 1/1                   |         |
| Ready                   | 2/2                   |         |
+-------------------------+-----------------------+---------+

+--------------------------------------+----------------+--------------------------------------+------------------------+---------+
| Uid                                  | IP             | HostName                             | NodeRole               | Status  |
+--------------------------------------+----------------+--------------------------------------+------------------------+---------+
| 959eba4b-6bbe-4ad5-ba0f-ecfad17d378d | 192.168.10.212 | kubeapi.goodrain.me                  | manage,compute,gateway | running |
+--------------------------------------+----------------+--------------------------------------+------------------------+---------+
| d7ac90c5-3fb7-46f4-9d3c-c05667252f71 | 192.168.10.101 | d7ac90c5-3fb7-46f4-9d3c-c05667252f71 | compute                | running |
+--------------------------------------+----------------+--------------------------------------+------------------------+---------+

**Comment by GLYASAI** [comment]
> ```
> [root@kubeapi gr66095b-0]# kubectl describe pod/gr66095b-1 -n 08c70243e9904346a88c351aa35f24e1
> Name:           gr66095b-1
> Namespace:      08c70243e9904346a88c351aa35f24e1
> Node:           959eba4b-6bbe-4ad5-ba0f-ecfad17d378d/192.168.10.212
> Start Time:     Thu, 01 Aug 2019 16:37:37 +0800
> Labels:         controller-revision-hash=gr66095b-57c495c69f
>                 creater=Rainbond
>                 creater_id=1564648650249765656
>                 name=gr66095b
>                 service_alias=gr66095b
>                 service_id=29011a506d3bbb44d6aee35a5266095b
>                 statefulset.kubernetes.io/pod-name=gr66095b-1
>                 tenant_id=08c70243e9904346a88c351aa35f24e1
>                 tenant_name=jinbrkto
>                 version=20190731213754
> Annotations:    <none>
> Status:         Running
> IP:             10.0.81.83
> Controlled By:  StatefulSet/gr66095b
> .......略...............
> pod的describe信息最后面有提示这个。
> Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
>                        node.kubernetes.io/unreachable:NoExecute for 300s
> 
> 
> pod 是存在的两边检验都有，集群状态也正常。就是控制台不能链接实例管理@barnettZQG
> ```

可以省略的pod信息也提供一下吗? 可能需要观察pod的events信息.

**Comment by yszansx** [comment]
[root@kubeapi ~]# kubectl describe pod/gr66095b-1 -n 08c70243e9904346a88c351aa35f24e1
Name:           gr66095b-1
Namespace:      08c70243e9904346a88c351aa35f24e1
Node:           959eba4b-6bbe-4ad5-ba0f-ecfad17d378d/192.168.10.212
Start Time:     Sun, 04 Aug 2019 17:25:03 +0800
Labels:         controller-revision-hash=gr66095b-5b8dfc6d6
                creater=Rainbond
                creater_id=1564910699580802001
                name=gr66095b
                service_alias=gr66095b
                service_id=29011a506d3bbb44d6aee35a5266095b
                statefulset.kubernetes.io/pod-name=gr66095b-1
                tenant_id=08c70243e9904346a88c351aa35f24e1
                tenant_name=jinbrkto
                version=20190731213754
Annotations:    <none>
Status:         Running
IP:             10.0.81.87
Controlled By:  StatefulSet/gr66095b
Containers:
  29011a506d3bbb44d6aee35a5266095b:
    Container ID:   docker://cb5acc8de3efc9cb1a89e3768d947c1f2c2b3aac76d459affe831ae484038ae4
    Image:          goodrain.me/geeboo/nacos:20190731213754
    Image ID:       docker-pullable://goodrain.me/geeboo/nacos@sha256:8b02f9e72e0d3f380bec3724b3436096ba89ab8ec4fc8ca4f997eb750dbd97d6
    Port:           8848/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 05 Aug 2019 11:26:12 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1780m
      memory:  2Gi
    Requests:
      cpu:     480m
      memory:  2Gi
    Environment:
      LOGGER_DRIVER_NAME:             streamlog
      REVERSE_DEPEND_SERVICE:         gr94a3b8:a4c54cf84344d247fd1029fd3c94a3b8,gr589768:62fd86c1422e58ce500abd5ab0589768,grae9d9e:da95f895fc45e2ea0805bdf0f2ae9d9e,gr35d8b1:d7cba36147218b236314e8138c35d8b1,gre593d6:69ee67818ccaecb9671090ff12e593d6,gr9fc4ae:2544e4daf85dfe8668b233c7c79fc4ae
      PORT:                           8848
      PROTOCOL:                       http
      DOMAIN_8848:                    8848.gr66095b.jinbrkto.771648.grapps.cn
      DOMAIN_PROTOCOL_8848:           http
      DOMAIN:                         8848.gr66095b.jinbrkto.771648.grapps.cn
      DOMAIN_PROTOCOL:                http
      MONITOR_PORT:                   8848
      CUR_NET:                        midonet
      TIME_ZONE:                      Asia/Shanghai
      PREFER_HOST_MODE:               hostname
      JAVA:                           /usr/lib/jvm/java-1.8.0-openjdk/bin/java
      JVM_XMX:                        2g
      JVM_MS:                         128m
      JAVA_HOME:                      /usr/lib/jvm/java-1.8.0-openjdk
      NACOS_USER:                     nacos
      NACOS_DEBUG:                    n
      TOMCAT_ACCESSLOG_ENABLED:       false
      MODE:                           cluster
      BASE_DIR:                       /home/nacos
      CLASSPATH:                      .:/home/nacos/conf:
      CLUSTER_CONF:                   /home/nacos/conf/cluster.conf
      FUNCTION_MODE:                  all
      JVM_MMS:                        320m
      JVM_XMS:                        2g
      JVM_XMN:                        1g
      NACOS_SERVERS:                  gr66095b-0.gr66095b.08c70243e9904346a88c351aa35f24e1.svc.cluster.local. gr66095b-1.gr66095b.08c70243e9904346a88c351aa35f24e1.svc.cluster.local. gr66095b-2.gr66095b.08c70243e9904346a88c351aa35f24e1.svc.cluster.local.
      MYSQL_MASTER_SERVICE_DB_NAME:   nacos
      MYSQL_MASTER_SERVICE_HOST:      192.168.10.122
      MYSQL_MASTER_SERVICE_PASSWORD:  123456
      MYSQL_MASTER_SERVICE_PORT:      3306
      MYSQL_MASTER_SERVICE_USER:      mysqltest
      GBREGISTER_HOST:                127.0.0.1
      GBREGISTER_PORT:                8848
      TENANT_ID:                      08c70243e9904346a88c351aa35f24e1
      SERVICE_ID:                     29011a506d3bbb44d6aee35a5266095b
      MEMORY_SIZE:                    2xlarge
      SERVICE_NAME:                   gr66095b
      SERVICE_EXTEND_METHOD:          stateless
      SERVICE_POD_NUM:                3
      HOST_IP:                         (v1:status.hostIP)
      POD_IP:                          (v1:status.podIP)
    Mounts:
      /home/nacos/logs from manual4 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-nmcmv (ro)
  plugin-f49b821b723f437fb533d9d778bc5b40:
    Container ID:   docker://d822de5b9922f19c736f63481258d38f316decf999d58f827704d1a609b94a38
    Image:          goodrain.me/plugin_tcm_f49b821b723f437fb533d9d778bc5b40:latest_20190718094426
    Image ID:       docker-pullable://goodrain.me/plugin_tcm_f49b821b723f437fb533d9d778bc5b40@sha256:34886c71c872767966a225174be32ba961703961bf9bad36206529ac2c2ac630
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Mon, 05 Aug 2019 11:26:15 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  64Mi
    Requests:
      memory:  64Mi
    Environment:
      LOGGER_DRIVER_NAME:             streamlog
      REVERSE_DEPEND_SERVICE:         gr94a3b8:a4c54cf84344d247fd1029fd3c94a3b8,gr589768:62fd86c1422e58ce500abd5ab0589768,grae9d9e:da95f895fc45e2ea0805bdf0f2ae9d9e,gr35d8b1:d7cba36147218b236314e8138c35d8b1,gre593d6:69ee67818ccaecb9671090ff12e593d6,gr9fc4ae:2544e4daf85dfe8668b233c7c79fc4ae
      PORT:                           8848
      PROTOCOL:                       http
      DOMAIN_8848:                    8848.gr66095b.jinbrkto.771648.grapps.cn
      DOMAIN_PROTOCOL_8848:           http
      DOMAIN:                         8848.gr66095b.jinbrkto.771648.grapps.cn
      DOMAIN_PROTOCOL:                http
      MONITOR_PORT:                   8848
      CUR_NET:                        midonet
      TIME_ZONE:                      Asia/Shanghai
      PREFER_HOST_MODE:               hostname
      JAVA:                           /usr/lib/jvm/java-1.8.0-openjdk/bin/java
      JVM_XMX:                        2g
      JVM_MS:                         128m
      JAVA_HOME:                      /usr/lib/jvm/java-1.8.0-openjdk
      NACOS_USER:                     nacos
      NACOS_DEBUG:                    n
      TOMCAT_ACCESSLOG_ENABLED:       false
      MODE:                           cluster
      BASE_DIR:                       /home/nacos
      CLASSPATH:                      .:/home/nacos/conf:
      CLUSTER_CONF:                   /home/nacos/conf/cluster.conf
      FUNCTION_MODE:                  all
      JVM_MMS:                        320m
      JVM_XMS:                        2g
      JVM_XMN:                        1g
      NACOS_SERVERS:                  gr66095b-0.gr66095b.08c70243e9904346a88c351aa35f24e1.svc.cluster.local. gr66095b-1.gr66095b.08c70243e9904346a88c351aa35f24e1.svc.cluster.local. gr66095b-2.gr66095b.08c70243e9904346a88c351aa35f24e1.svc.cluster.local.
      MYSQL_MASTER_SERVICE_DB_NAME:   nacos
      MYSQL_MASTER_SERVICE_HOST:      192.168.10.122
      MYSQL_MASTER_SERVICE_PASSWORD:  123456
      MYSQL_MASTER_SERVICE_PORT:      3306
      MYSQL_MASTER_SERVICE_USER:      mysqltest
      GBREGISTER_HOST:                127.0.0.1
      GBREGISTER_PORT:                8848
      TENANT_ID:                      08c70243e9904346a88c351aa35f24e1
      SERVICE_ID:                     29011a506d3bbb44d6aee35a5266095b
      MEMORY_SIZE:                    2xlarge
      SERVICE_NAME:                   gr66095b
      SERVICE_EXTEND_METHOD:          stateless
      SERVICE_POD_NUM:                3
      HOST_IP:                         (v1:status.hostIP)
      POD_IP:                          (v1:status.podIP)
      XDS_HOST_IP:                     (v1:status.hostIP)
      API_HOST_PORT:                  6100
      XDS_HOST_PORT:                  6101
      DISCOVER_URL:                   http://172.30.42.1:6100/v1/resources/08c70243e9904346a88c351aa35f24e1/gr66095b/f49b821b723f437fb533d9d778bc5b40
      DISCOVER_URL_NOHOST:            /v1/resources/08c70243e9904346a88c351aa35f24e1/gr66095b/f49b821b723f437fb533d9d778bc5b40
      PLUGIN_ID:                      f49b821b723f437fb533d9d778bc5b40
    Mounts:
      /home/nacos/logs from manual4 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-nmcmv (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  manual4:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  manual4-gr66095b-1
    ReadOnly:   false
  default-token-nmcmv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-nmcmv
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

**Comment by GLYASAI** [comment]
@yszansx 会一直报这个错, 说pod不存在吗? 会不会那个时候pod确实不存在, 后面正常了呢?

**Comment by yszansx** [comment]
kubectl get pod有存在，且正常运行。但是控制台实例管理一直报错，从来就没能成功连上。这个pod落在计算节点上。

**Comment by yszansx** [comment]
操作系统换成ubuntu 16.4以上问题解决。 centos7  rainband 5.1.5 升级到5.1.6不能升级 适配不行。不想折腾按官方的文档来了。

**Comment by GLYASAI** [comment]
我先关闭这个issue了, 如果还有同样的问题, 随时重开这个issue.
