### ISSUE TITLE
持久化目录权限不够

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#340]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ 5.1-dev ] Rainbond版本(执行grctl version获取)

- [ubuntu1604 ] 操作系统类型和版本

- [ 公有云] 部署环境：公有云、私有云

![image](https://user-images.githubusercontent.com/33855684/62414213-92e7a300-b64a-11e9-8090-601fd82b9465.png)
操作步骤：
- 为了重置有状态应用的数据，我将服务关闭，在服务器端删除了其对应的目录
- 重启应用
- 应用报错持久化目录创建文件权限不足
- 观察重新生成的持久化路径
- 为目录赋权
- 应用启动成功

**Comment by GLYASAI** [comment]
问题无需处理
