### ISSUE TITLE
更改服务存储设置时提示系统异常

### ISSUE THREAD

**Issue by Barrett-M82A1** [goodrain/rainbond#347]
Rainbond版本:5.1
操作系统:centos7
内核版本:
环境:本地服务器，centos
节点配置:
安装类型:
如何复现:点击编辑存储设置，修改后确认则提示系统异常。查看返回的JSON值里有这么一句提示：【The volume_type field must contain one of these values config-file】
尝试解决: 
1.尝试更改其他服务的存储路径，如：mysql，pgsql，gitlab都不能更改。
2.尝试未构建服务时修改，未成功。
3.尝试先在服务器创建了对应目录后再修改，未成功。
4.尝试关闭服务后再修改，未成功。
5.尝试更换目录路径，无论是在SSD还是挂载的机械盘上均未成功。
错误提示的JSON如下：
```
{
	"msg": {
		"url": "https://region.goodrain.me:8443/v2/tenants/54mdi31s/services/gr276e4a/volumes",
		"body": {
			"validation_error": {
				"volume_type": ["The volume_type field must contain one of these values config-file"]
			}
		},
		"httpcode": 400,
		"method": "PUT",
		"apitype": "Not specified"
	},
	"code": 500,
	"data": {
		"bean": {},
		"list": []
	},
	"msg_show": "系统异常"
}
```

**Comment by barnettZQG** [comment]
支持修改存储的挂载路径，但是需要注意的是不会更改持久化存储路径，意味着已经被使用的挂载路径，更改后如果重新使用，将复用持久化存储路径。
