### ISSUE TITLE
离线应用包导入后，个别安装方式失败

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#351]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取) 5.1.5

- [ ] 操作系统类型和版本 CentOS7.4

- [ ] 部署环境：私有云

从互联网上的公有云 导出了应用离线包，
在离线的Rainbond环境下导入后。

![image](https://user-images.githubusercontent.com/33855684/62604474-c1a39900-b92a-11e9-900f-115c9266b623.png)

从这种方式安装会报错，具体报错 见 https://t.goodrain.com/t/topic/1109

![image](https://user-images.githubusercontent.com/33855684/62604600-fc0d3600-b92a-11e9-854a-9f63b27d0ca9.png)

这种就没有问题

**Comment by barnettZQG** [comment]
https://github.com/goodrain/rainbond-ui/issues/172 
与上诉问题一致，将于5.1.6 版本中修复。
5.1.5 可从应用市场-本地应用安装。
