### ISSUE TITLE
从镜像创建应用时，用户名长度的限制应该放宽

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#352]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [V5.1-dev ] Rainbond版本(执行grctl version获取)

- [ubuntu1604 ] 操作系统类型和版本

- [ 公有云 ] 部署环境：公有云、私有云

如题，目前从镜像构建时，用户名默认不可以超过32字节。但是 aliyun镜像仓库生成的用户名，默认就已经超过了这个限制。
所以，需要放宽。

PS： 别的地方是不是也会有这个限制

```
alter table console.service_source modify user_name varchar(255);
```
这是目前手动解决方案，在 rbd-db 中修改表的属性。

**Comment by barnettZQG** [comment]
关于账号密码长度的限制应该增大。

**Comment by GLYASAI** [comment]
这个issue已经被挪到 https://github.com/goodrain/rainbond-console/issues/199
