### ISSUE TITLE
使用性能分析插件时，会产生大量错误日志，且无法屏蔽

### ISSUE THREAD

**Issue by lxm** [goodrain/rainbond#354]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ V5.1-dev-381a1da-2019-07-12-14] Rainbond版本(执行grctl version获取)

- [CentOS7 ] 操作系统类型和版本

- [公有云 ] 部署环境：公有云、私有云

![image](https://user-images.githubusercontent.com/1918195/62618402-b5c5d000-b946-11e9-817e-9b62c62427d4.png)

**Comment by lxm** [comment]
应用中有websocket通信，怀疑是decode时，未对websocket协议进行处理

**Comment by barnettZQG** [comment]
调整日志级别为debug日志，默认情况下将不打印。
临时更新，请将性能分析插件使用以下镜像：rainbond/plugins-tcm:5.1.7
