### ISSUE TITLE
应用网关编辑https访问策略可能导致同一个证书的其他策略失效

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond#355]
应用网关编辑https访问策略可能导致同一个证书的其他策略失效, 需要查询并定位原因。

- [x] Rainbond版本(执行grctl version获取)
   5.1.5

**Comment by GLYASAI** [comment]
@barnettZQG 无法复现问题. 我准备了四个域名abc.goodrain.com, 123.goodrain.com, 2048.goodrain.com和nginx.goodrain.com, 然后随意的修改他们相关的策略, 一切都正常.

![image](https://user-images.githubusercontent.com/21967570/63766209-4287fc00-c8fd-11e9-801d-fd342c72e670.png)
