### ISSUE TITLE
应用实例通过nslookup找寻主机IP地址失败

### ISSUE THREAD

**Issue by fanyangyang** [goodrain/rainbond#360]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

应用多实例启动，在实例中通过`nslookup ${SERVICE_NAME}`的方式找主机IP地址，会出现失败的情况，指令结果见下图
![image](https://user-images.githubusercontent.com/14025359/62908751-343dca00-bdac-11e9-8355-085cb5730c15.png)

**Comment by barnettZQG** [comment]
没有复现这个问题，可否提供复现方式？
有状态服务启动后执行 nslookup ${SERVICE_NAME} 可能有两种结果：
1. 返回127.0.0.1 解析结果，这个是在有状态配置Service还没在DNS服务中生效时DNS默认会解析为127.0.0.1
2. 返回实际的实例IP地址列表。
