### ISSUE TITLE
无法拉取位于阿里云镜像仓库中的镜像

### ISSUE THREAD

**Issue by hl-a-k** [goodrain/rainbond#363]
尝试使用 dockercompose 创建应用
镜像位于阿里云私有镜像仓库中
已经在各个节点执行过 docker login
提示应用检测未通过

![微信截图_20190815163811](https://user-images.githubusercontent.com/7145708/63083367-225e5180-bf7b-11e9-960e-9981db8b76be.png)

**Comment by fanyangyang** [comment]
错误信息：“请确认{image_name}服务镜像名称是否正确或镜像仓库访问是否正常”。

根据错误信息有进行排错吗？
@hl-a-k 

是否有提供私有仓库的账号密码呢？请参阅文档第3章 使用手册》3.3 应用&服务创建》docker镜像支持规范，如下图
![image](https://user-images.githubusercontent.com/14025359/63086790-3312c580-bf83-11e9-8ed0-c790719cf456.png)

**Comment by hl-a-k** [comment]
尝试 指定镜像 方式创建应用是可以拉取镜像的。

**Comment by fanyangyang** [comment]
@hl-a-k 在 `builder/parser/`路径下有`docker-compose_test.go`测试文件，我个人写了一个测试用例测试了一下是可以通过应用检测的。我的测试代码如下
```
var account = `version: '2'
services:
  geeboo-user:
    image:   registry.cn-hangzhou.aliyuncs.com/hangzhou-fyy/mysql:5.6
    ports:
      - "8102:8102"
    environment:
      HUB_USER: "username"
      HUB_PASSWORD: "password"
      SENTINEL_HOST: "sentinel"
      MYSQL_ROOT_PASSWORD: "root"
      NACOS_HOST: "192.168.10.51"`

func TestDockerComposeParseUsingAccount(t *testing.T) {
	dockerclient, err := client.NewEnvClient()
	if err != nil {
		t.Fatal(err)
	}
	p := CreateDockerComposeParse(account, dockerclient, "", "", event.GetTestLogger())
	if err := p.Parse(); err != nil {
		logrus.Errorf(err.Error())
		return
	}
	fmt.Printf("ServiceInfo:%+v \n", p.GetServiceInfo())
	errList := p.Parse()
	if errList != nil {
		fmt.Println(errList)
	}

}
```
另外我在`builder/parser/docker-compose.go`的`Parse()`函数中打印了`exist`变量，显示我上传的镜像确实存在，并且我使用上面变量`account`中的compose内容在我们平台确实成功启动了MySQL的服务，确定是可以用的

不妨通过这种方式测试一下阿里镜像仓库的可用性以排查问题
