### ISSUE TITLE
第三方服务无法正常上线

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#369]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

平台挂接的第三方服务，有些时候遇到问题被健康检查下线后，即使服务恢复正常也无法正常上线，需要手动重新开关对内服务的端口，才能上线

**Comment by fanyangyang** [comment]
@dazuimao1990 可否说明一下是哪种第三方服务？我们方便问题的复现
