### ISSUE TITLE
重新构建多次后有概率遇到两个k8s BUG，导致每次构建都非常慢

### ISSUE THREAD

**Issue by 651016236** [goodrain/rainbond#373]
- [ V5.1-dev-04222b6-2019-07-25-11] Rainbond版本(执行grctl version获取)
- [ centos7] 操作系统类型和版本
- [ 阿里云] 部署环境：公有云
使用命令查看k8s日志：
journalctl -xefu kubelet 
这次遇到是这个：
![image](https://user-images.githubusercontent.com/5875767/63502092-631c1480-c4ff-11e9-883b-06d1d241bf8f.png)
之前一直遇到这个问题日志：
 are still present on disk : There were a total of 209 errors similar to this. Turn up verbosity to see them.
E0221 18:41:48.315531    9906 kubelet_volumes.go:140] Orphaned pod "00335013-c220-11e8-960e-60da833fa102" found, but volume paths
 are still present on disk : There were a total of 209 errors similar to this. Turn up verbosity to see them.
E0221 18:41:50.276365    9906 kubelet_volumes.go:140] Orphaned pod "00335013-c220-11e8-960e-60da833fa102" found, but volume paths
 are still present on disk : There were a total of 209 errors similar to this. Turn up verbosity to see them.
E0221 18:41:52.308534    9906 kubelet_volumes.go:140] Orphaned pod "00335013-c220-11e8-960e-60da833fa102" found, but volume paths
 are still present on disk : There were a total of 209 errors similar to this. Turn up verbosity to see them.
然后我看到k8s官方有个issue，说已经修复了这个问题，不知道rainbond怎么修复
[具体的k8s官方issue地址，看最后一条](https://github.com/kubernetes/kubernetes/issues/60987)

**Comment by barnettZQG** [comment]
@651016236 
这里的问题分离来看：
1. kubelet的报错，语义很清晰，应用的持久化存储目录是一直保留的，所以导致kubelet会有此报错，但是这个错误是可以忽略的。
2. 服务构建缓慢，看得出来应该是指服务构建完成后的升级过程缓慢，建议查看是旧实例关闭缓慢还是新实例启动缓慢，定位原因后便于问题的解决。
另外在5.1.7版本中：我们将升级过程重点体现，方便用户直接在UI中辨别升级的过程卡壳点。

**Comment by 651016236** [comment]
kubelet开始报错后，就会出现旧实例关闭缓慢的问题

**Comment by barnettZQG** [comment]
kubelet异常问题只能通过升级kubernetes来解决，Rainbond计划在5.2版本中升级内置安装的kubernetes。并与kubernetes完全解耦合

**Comment by 651016236** [comment]
好的谢谢

**Comment by GLYASAI** [comment]
kubernetes 官方暂时还没有解决这个问题, 即使在最新的 1.18 版本中
