### ISSUE TITLE
第一个实例启动时，有状态服务的service没有创建成功导致解析失败

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#383]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ 5.1.6-release ] Rainbond版本(执行grctl version获取)

- [ Ubuntu604 ] 操作系统类型和版本

- [ 私有云 ] 部署环境：公有云、私有云

### 如题，制作有状态集群时，首个实例启动时，会将 ${SERVICE_NAME}解析为127.0.0.1 而不是真实IP地址

**Comment by barnettZQG** [comment]
有状态服务启动时会同步创建DNS解析服务名称所需要的Service资源，但是Service资源在DNS服务中生效完成是有一定的时间延迟，这个延迟是不能避免的，这里建议的方式是：
1. 如果返回结果是127.0.0.1 延迟1秒重新获取解析结果，大多数情况下重试一次即可获取成功。

**Comment by barnettZQG** [comment]
我已经关闭这个问题，如还有疑问重新打开
