### ISSUE TITLE
安装内部市场mysql5.7应用出现，服务异常

### ISSUE THREAD

**Issue by zeroByzero** [goodrain/rainbond#430]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)
离线安装5.04 后，现在升级到v5.1.5-release-50c570c-2019-07-24-09
- [ ] 操作系统类型和版本
CentOS Linux release 7.4.1708 (Core)
- [ ] 部署环境：公有云、私有云
私有云
![a4263288c1f9a84d8c11b827d29192388a1fe896](https://user-images.githubusercontent.com/7357057/64511687-67299e00-d317-11e9-9f05-2ed783ea01d3.jpg)
![b82dc8e710cf28699c3435c186054e5a95e981b4](https://user-images.githubusercontent.com/7357057/64511705-70b30600-d317-11e9-9d02-2088b217d064.jpg)
![38ea4c97f2f7b7834b5f8f2e9a1d09f103df323a](https://user-images.githubusercontent.com/7357057/64511712-73156000-d317-11e9-8766-181513933273.jpg)

**Comment by barnettZQG** [comment]
@zeroByzero 你的环境是否不能请求公网？

**Comment by fanyangyang** [comment]
@zeroByzero 通过日志分析，确定问题是无法正常获取使用应用导致。新版rainbond中针对网络条件不好做了处理，在无法正常获取市场应用时会给出`网络不稳定，无法获取云端应用`的提示，可以尝试更新版本

**Comment by barnettZQG** [comment]
我将关闭这个问题，如有疑问请重新打开
