### ISSUE TITLE
环境变量删除失败，操作无响应

### ISSUE THREAD

**Issue by 1909490139** [goodrain/rainbond#434]
添加环境变量后，对其进行更改删除操作，均无响应
<img width="970" alt="屏幕快照 2019-09-10 18 47 41的副本" src="https://user-images.githubusercontent.com/55137659/64607658-826dd980-d3fb-11e9-9362-51bd0ccb9899.png">

<img width="1277" alt="屏幕快照 2019-09-10 18 42 17的副本" src="https://user-images.githubusercontent.com/55137659/64607587-5d796680-d3fb-11e9-8f03-6d05a039008f.png">

**Comment by fanyangyang** [comment]
@1909490139 从请求路径上看，您设置的环境变量的Key=discovery.type
这个问题是由于我们设置的路由匹配规则不支持这种写法，所以在路由匹配上找不到

可以先手动将其删除
