### ISSUE TITLE
离线安装应该禁用云端应用市场

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#439]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

如题，需求 ： 离线安装应该禁用云端应用市场

**Comment by barnettZQG** [comment]
1. 企业版本支持从后台关闭云端应用市场功能
2. 开源版本若离线环境下有效提示“无法连接网络”
