### ISSUE TITLE
支持应用复制

### ISSUE THREAD

**Issue by lxm** [goodrain/rainbond#446]
# 场景

当一个应用创建完成后，通过复制应用，快速创建出两条环境一直，数据隔离的环境，适用于开发环境隔离、开发环境与线上环境隔离等场景

# 为什么不用应用市场

使用应用市场发布后，通过应用市场创建的应用构建源为应用市场，首先是产生了依赖关系，想要更新应用，必须先更新源应用，发布新版，之后进行更新，另外对于原有的持续部署流程改动也会较大

**Comment by barnettZQG** [comment]
已于5.2版本中支持
