### ISSUE TITLE
内部市场手动导入应用失败

### ISSUE THREAD

**Issue by fanyangyang** [goodrain/rainbond#449]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

5.1.6版本导出的应用在导入到5.1.7版本的内部市场时，导入失败
导入到5.1.5版本的内部市场时，导入成功，但安装失败

在5.1.7版本导入失败时，rbd-chaos的日志如下
![image](https://user-images.githubusercontent.com/14025359/65222050-dad66280-daf0-11e9-8522-67415a329ad8.png)

**Comment by dazuimao1990** [comment]
@barnettZQG 验证通过
