### ISSUE TITLE
5.1.7在创建应用时无法正确保存ARG参数

### ISSUE THREAD

**Issue by 1909490139** [goodrain/rainbond#453]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [5.1.7 ] Rainbond版本(执行grctl version获取)

- [ centos7.4] 操作系统类型和版本

- [ 阿里云] 部署环境：公有云、私有云
添加ARG参数
<img width="1280" alt="屏幕快照 2019-09-24 09 16 04" src="https://user-images.githubusercontent.com/55137659/65473849-10da6480-deac-11e9-8ce3-15df1c3054c9.png">
提示修改成功后就没有了
<img width="1280" alt="屏幕快照 2019-09-24 09 16 11" src="https://user-images.githubusercontent.com/55137659/65473875-37000480-deac-11e9-8b99-cf0ab61ef00f.png">

**Comment by zsl1549** [comment]
fix https://github.com/goodrain/rainbond-ui/pull/229
