### ISSUE TITLE
5.1.7在创建应用时挂载共享存储不生效

### ISSUE THREAD

**Issue by 1909490139** [goodrain/rainbond#454]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ 5.1.7] Rainbond版本(执行grctl version获取)

- [centos7.4 ] 操作系统类型和版本

- [阿里云 ] 部署环境：公有云、私有云
在创建应用时选择挂载共享存储，此处有显示
<img width="1280" alt="屏幕快照 2019-09-24 09 38 19" src="https://user-images.githubusercontent.com/55137659/65474612-16857980-deaf-11e9-9e19-f8f29aae9c0b.png">
但在容器内部没有挂载目录，重新挂载之后正常
<img width="1280" alt="屏幕快照 2019-09-24 09 40 06" src="https://user-images.githubusercontent.com/55137659/65474679-5d736f00-deaf-11e9-88b1-9eee4387aa5f.png">

**Comment by barnettZQG** [comment]
@1909490139 重新挂载之后正常什么意思？

**Comment by liaoyizhi** [comment]
取消挂载后再重新挂载的意思

**Comment by barnettZQG** [comment]
@liaoyizhi 是否在增加共享存储后重启或更新组件？
