### ISSUE TITLE
应用共享其他服务存储设置后不生效

### ISSUE THREAD

**Issue by 1909490139** [goodrain/rainbond#456]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ 5.1.7] Rainbond版本(执行grctl version获取)

- [ ubuntu/16.04] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

共享其他服务存储设置后不生效

数据库region库tenant_services_mnt_relation表volume_type字段为空
<img width="1280" alt="屏幕快照 2019-09-27 16 19 58" src="https://user-images.githubusercontent.com/55137659/65754521-ce32b980-e143-11e9-8426-f3f96d4965af.png">

**Comment by fanyangyang** [comment]
@1909490139 请问您region数据库的tenant_services_volume表中
service_id=7ac835XXXXXX743ec7ed
volume_name=geocloud_data的这条数据的volume_type是什么呢？
