### ISSUE TITLE
应用状态变更后，原有数据不会被删除

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#459]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ v5.1.7 ] Rainbond版本(执行grctl version获取)

- [ Ubuntu1604 ] 操作系统类型和版本

- [ 私有云 ] 部署环境：公有云、私有云

如题，调整应用状态后，提示数据会丢失，但是实际上并没有删除原有数据。时间长了会造成磁盘垃圾数据过多，建议定期清理

同理，在删除某个具有持久化目录的应用后，原数据是否有清理策略？

**Comment by GLYASAI** [comment]
调整应用状态后，并不会删除原有数据.  这些数据会在删除组件时, 被删除.

**Comment by dazuimao1990** [comment]
@barnettZQG  验证通过
