### ISSUE TITLE
多实例应用在线缩容，触发不停进入启动中状态的bug

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#460]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

多实例应用在线缩容之后，应用实例正常缩减为一个，但是应用本身周期性进入启动中状态

![image](https://user-images.githubusercontent.com/33855684/66368390-b3293a80-e9ca-11e9-91ac-042d017bb237.png)

**Comment by GLYASAI** [comment]
duplicated #428
