### ISSUE TITLE
自定义域名 一旦绑定，在网关策略选项中修改其配置时，会被认为 是违法域名，禁止修改

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#461]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

自定义域名，如 gitlab.xxxxyyyy.cn 一旦绑定，在网关策略选项中修改其配置时，会被认为
是违法域名，禁止修改。

![image](https://user-images.githubusercontent.com/33855684/66368499-0e5b2d00-e9cb-11e9-8d77-16a1896a41c4.png)

**Comment by barnettZQG** [comment]
移除与默认分配域名租户冲突的检测。
