### ISSUE TITLE
有关监听0.0.0.0IP后的两个问题

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#462]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

新网关：

- 修改策略从监听0.0.0.0到特定的某个网关地址，没有立即生效，需要更新。

- 更新后，即使只指定了监听一个网关监听的地址，其余网关也都会继续生效，访问对应端口，也可以访问。

**Comment by barnettZQG** [comment]
#417 BUG.

**Comment by fanyangyang** [comment]
发现其他问题有待改进
