### ISSUE TITLE
postgresql修改共享存储权限时提示权限不足

### ISSUE THREAD

**Issue by 1909490139** [goodrain/rainbond#463]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

postgresql修改共享存储/var/lib/postgresql/data的权限时，提示权限不足，报错信息如下
<img width="1280" alt="屏幕快照 2019-10-08 16 31 00" src="https://user-images.githubusercontent.com/55137659/66380090-4a04ef80-e9e9-11e9-8247-96b0a079b5a7.png">

**Comment by barnettZQG** [comment]
不支持直接修改存储挂载目录的权限，建议将需要修改目录权限的目录放到持久化目录的下级目录。
比如： 持久化目录 /var/lib/postgresql/

**Comment by barnettZQG** [comment]
我将关闭这个问题，如有疑问，请重新打开。
