### ISSUE TITLE
应用备份恢复时提示删除原备份，但服务器上查看原备份并没有被删除

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#472]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云
![image](https://user-images.githubusercontent.com/50609288/66556777-689eee00-eb83-11e9-9b8b-fbbcb2f367a2.png)
![image](https://user-images.githubusercontent.com/50609288/66556807-73598300-eb83-11e9-82c2-de78dcf8de55.png)

**Comment by dazuimao1990** [comment]
@barnettZQG 验证通过
