### ISSUE TITLE
【需求】  当前应用备份只支持本地备份，备份较多时消耗磁盘空间较大，希望应用备份支持云端备份至OSS

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#473]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

**Comment by dazuimao1990** [comment]
@barnettZQG  @GLYASAI 对接功能已经实现了，但是云端备份删除后，对象存储中的文件不会被删除，是有意这样设置的么？

**Comment by GLYASAI** [comment]
@dazuimao1990 是的, 不删除云端中的备份, 但是会删除等地备份
