### ISSUE TITLE
第三方服务多个实例没有轮询

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#476]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

我创建了一个第三方服务（平台数据库rbd-db），并在平台上创建了rbd-app-ui组件，并依赖了数据库。运行一段时间后，rbd-db所在的服务器宕机启动不了了，由于我没有为第三方服务设置健康检查，所以虽说它不健康，但是没有下线，然后rbd-app-ui服务就因为访问不了数据库而GG了；

我开始修复这个问题，重新在另一个节点启动了可用的 rbd-db服务，并新增实例到第三方服务里。理论上应该触发轮询，使rbd-app-ui的访问可以时断时续（一个数据库是好的，另一个不可用），但是并没有。直到我手动下线了不可用的数据库实例

**Comment by GLYASAI** [comment]
因为MySQL的连接是长连接, 所以并不会进行轮询. 你可以为这个组件的健康检查打开, 如果某个实例出现问题了, 就会把它下线.
