### ISSUE TITLE
rainbondfile 中端口协议识别不出来

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#477]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

![image](https://user-images.githubusercontent.com/33855684/66692235-ede2e980-ecce-11e9-877e-8b6a075ed26b.png)

![image](https://user-images.githubusercontent.com/33855684/66692241-03f0aa00-eccf-11e9-96a4-1d0f4362b5a8.png)

但是点击更改xie协议的那个按键，貌似默认是识别到了 http 协议，请确定是否是个前端显示问题

![image](https://user-images.githubusercontent.com/33855684/66692255-25ea2c80-eccf-11e9-8fd3-07a1c863a971.png)

**Comment by barnettZQG** [comment]
@dazuimao1990 无法复现这个问题。

**Comment by barnettZQG** [comment]
@dazuimao1990  "procotol" => "protocol"
