### ISSUE TITLE
Load Balancing OpenResty Rules Error

### ISSUE THREAD

**Issue by goodrainzh** [goodrain/rainbond#48]
When app has stoped , the  openresty rule still exist。

**Comment by barnettZQG** [comment]
@goodrainzh  Provides a screenshot of  exec shell "curl 127.0.0.1:10002/server/details"

**Comment by goodrainzh** [comment]
<img width="654" alt="lb-rules" src="https://user-images.githubusercontent.com/33080353/37589228-939536f0-2b9f-11e8-820d-d5182c0fb145.png">
