### ISSUE TITLE
创建应用时使用docker-compose方式对接私有镜像仓库进行构建，出现查询不到镜像

### ISSUE THREAD

**Issue by zeroByzero** [goodrain/rainbond#480]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)
异常信息：
![image](https://user-images.githubusercontent.com/7357057/66725826-d8ed8e00-ee67-11e9-98d1-b0391f72aed5.png)
![image](https://user-images.githubusercontent.com/7357057/66725832-dc811500-ee67-11e9-96fc-50bdd7a29131.png)

- [ ] Rainbond版本(执行grctl version获取)
v5.1.6
- [ ] 操作系统类型和版本
CentOS Linux release 7.5.1804 (Core)
- [ ] 部署环境：公有云、私有云
私有云

**Comment by fanyangyang** [comment]
排查原因是rbd-chaos容器中chaos进程不能正常使用/etc/hosts文件中配置的域名地址，而是使用了一个不知名的IP处理请求，导致manifests接口返回404

临时解决方案：

修改rbd-dns，添加dns解析，重新构建rbd-dns服务

**Comment by fanyangyang** [comment]
暂时关闭该issue
