### ISSUE TITLE
高可用测试宕掉其中一个管理节点，grctl cluster命令查询不到集群信息，node日志如下

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#481]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

![image](https://user-images.githubusercontent.com/50609288/66796019-efafe580-ef38-11e9-8974-d8797c4004f0.png)

**Comment by barnettZQG** [comment]
提供一个一个管理节点宕机后etcd中的数据：
```
ETCDCTL_API=3 etcdctl get /rainbond/nodes
```
另外，多次执行grctl是否出现间接性成功？

**Comment by Aaron-23** [comment]
![image](https://user-images.githubusercontent.com/50609288/66923801-1155bd80-f05c-11e9-9c11-7ad23c532312.png)
多次执行grctl会出现间接性成功

**Comment by barnettZQG** [comment]
5.1.9优化了此问题
