### ISSUE TITLE
nodejs项目构建出现Permission denied问题

### ISSUE THREAD

**Issue by wwater84** [goodrain/rainbond#482]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ v5.1.7-release-f48d522-2019-09-08-07] Rainbond版本(执行grctl version获取)

- [ Centos 7.6.1810] 操作系统类型和版本

- [ 公有云] 部署环境：公有云、私有云

在构建源中切换设置nodejs版本，不管设置那个版本都出现下图错误
![image](https://user-images.githubusercontent.com/46913956/66801173-c0a26f80-ef4a-11e9-93b9-2ea1989b3996.png)

**Comment by barnettZQG** [comment]
由于package.json中未按照规范定义node或npm或yarn版本所致。参考如下用例：
```
"engines": {
    "node": "12.8.1",
    "npm": "6.4.1"
 }
```
