### ISSUE TITLE
nodejs项目，无法切换私有源

### ISSUE THREAD

**Issue by wwater84** [goodrain/rainbond#483]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步Rainbond用户社区

[ v5.1.7-release-f48d522-2019-09-08-07] Rainbond版本(执行grctl version获取)

[ Centos 7.6.1810] 操作系统类型和版本

[ 公有云] 部署环境：公有云、私有云

nodejs项目构建，无法切换其他源，怎么设置最终构建使用源都是默认的淘宝源

**Comment by barnettZQG** [comment]
已在5.2版本中支持。
