### ISSUE TITLE
高可用测试，一台管理节点宕机，在其他管理节点grctl查看，节点状态unknown，但大部分服务仍然在线

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#488]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云
![image](https://user-images.githubusercontent.com/50609288/66880722-b9d13680-eff6-11e9-9675-f45eac781fed.png)

**Comment by barnettZQG** [comment]
参考：
https://www.rainbond.com/docs/troubleshoot/cluster-problem/#%E9%9B%86%E7%BE%A4%E8%8A%82%E7%82%B9%E7%8A%B6%E6%80%81%E4%B8%BAunknow%E6%80%8E%E4%B9%88%E5%8A%9E

**Comment by Aaron-23** [comment]
节点unknown状态下，大部分组件仍然在线
