### ISSUE TITLE
应用无法备份，备份失败，chaos日志如下

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#494]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

![image](https://user-images.githubusercontent.com/50609288/66924566-6940f400-f05d-11e9-9b5d-d7e3250ae52d.png)

![image](https://user-images.githubusercontent.com/50609288/66924629-8970b300-f05d-11e9-9b9b-f65f64cc79c4.png)

**Comment by GLYASAI** [comment]
已在5.1.8中修复.
