### ISSUE TITLE
关于 .netcore 语言源码构建的建议 

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#496]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

目前的 .netcore 源码构建，如果希望能够随意修改监听端口，是需要修改用户源码的，目前的方式：
[如何适应rainbondfile中设置的端口](https://www.rainbond.com/docs/user-manual/app-creation/language-support/netcore/#如何适应rainbondfile中设置的端口)

这样指定端口的问题是：
- 需要用户修改代码
- 如果想要重新修改端口，需要的操作是重新构建，而不是简单的更新

所以，有一个来自用户新的建议是：
既然 .netcore 是借助dockerfile 构建镜像运行而来，那可否动态配置端口映射到容器的默认端口（80），这样就不用改变用户代码，更新的时候只需要动态改变映射端口就可以了。

**Comment by barnettZQG** [comment]
不存在端口映射逻辑。

这里的问题其实与.netcore开发语言无关， Rainbond平台配置的端口实际上就是告知平台组件监听的端口是什么。 为了配置方便，反过来组件通过平台注入的变量来建立监听这种模式是一种推荐模式，但不是必须的模式。如果组件默认监听端口是80，只需要在Rainbond平台配置80即可。
需要注意的是80端口比较特殊，在Rainbond中会用于ServiceMesh网络治理中，不推荐用户自己的服务默认监听80端口。
