### ISSUE TITLE
服务间互相依赖，两个服务都无法启动，日志如下

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#499]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云
![image](https://user-images.githubusercontent.com/50609288/67065442-eb860100-f1a0-11e9-8cd2-12bf6ec79bb9.png)
![image](https://user-images.githubusercontent.com/50609288/67065472-08223900-f1a1-11e9-98ad-135fd04e7cf7.png)
![image](https://user-images.githubusercontent.com/50609288/67065484-13756480-f1a1-11e9-9454-7f62cab6c32d.png)

**Comment by dazuimao1990** [comment]
@barnettZQG 验证通过
