### ISSUE TITLE
修改某个组件的配置文件后（更改镜像），node service update ，查看systemd配置文件，镜像并没有改过来，docker images 查看镜像是存在的

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#503]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

**Comment by fanyangyang** [comment]
如果配置文件不生效可以通过`journalctl -fu node`命令查看node日志，确定是否是生成service文件出错

如果写问题出错会出现*Generate config file...*类似日志

不能复现，暂时关闭
