### ISSUE TITLE
在好雨云访问控制中，给应用绑定某个域名访问链接后，一段时间会被链接到好雨云自带maven仓库控制台

### ISSUE THREAD

**Issue by mayizhenxu** [goodrain/rainbond#506]
<img width="844" alt="微信图片_20191023103326" src="https://user-images.githubusercontent.com/49012273/67351734-cd454a00-f580-11e9-92b4-1b5513abeaf0.png">

**Comment by GLYASAI** [comment]
问题已在5.1.8中解决.
