### ISSUE TITLE
内部市场导入应用成功后应用列表没有刷新

### ISSUE THREAD

**Issue by fanyangyang** [goodrain/rainbond#510]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

内部市场手动导入应用成功之后流程直接结束，页面中的应用列表没有刷新，新的应用不可见，通过刷新页面的方式可以看到新导入的应用

**Comment by GLYASAI** [comment]
测试通过
