### ISSUE TITLE
挂载配置文件后摘除，构建应用启动不了

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#521]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

如题：
- 我为一个mysql应用挂载了配置文件
- 摘除了这个配置文件
- 构建
- 启动不了了

![image](https://user-images.githubusercontent.com/33855684/67846501-4c67ee80-fb3c-11e9-8ded-320b1cd25bf2.png)

**Comment by GLYASAI** [comment]
摘除了这个配置文件后, 是执行了 `更新`, 还是 `重启`?

**Comment by dazuimao1990** [comment]
> 摘除了这个配置文件后, 是执行了 `更新`, 还是 `重启`?

关闭状态下摘除，然后启动这个服务组件

**Comment by dazuimao1990** [comment]
没有办法复现，先关闭了
