### ISSUE TITLE
镜像名称过长在创建应用时无法创建且无法删除

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#522]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

点击构建时系统异常
![image](https://user-images.githubusercontent.com/50609288/67912107-bf687800-fbc3-11e9-9d0a-d6e677887f88.png)

删除不掉
![image](https://user-images.githubusercontent.com/50609288/67912079-af509880-fbc3-11e9-9236-ae1de842ccce.png)

F12
![image](https://user-images.githubusercontent.com/50609288/67912142-e9219f00-fbc3-11e9-9224-54611df83ebf.png)

app-ui日志
![image](https://user-images.githubusercontent.com/50609288/67912148-f2ab0700-fbc3-11e9-8984-889d9518ee9e.png)
![image](https://user-images.githubusercontent.com/50609288/67912155-f8085180-fbc3-11e9-94bb-fa6b07053399.png)

**Comment by fanyangyang** [comment]
看日志能确定是数据中心500错误，但暂无法复现问题，无法定位，如遇到相同问题请提供数据中心日志便于排查

**Comment by fanyangyang** [comment]
暂时关闭该issue
