### ISSUE TITLE
无法删除组件, 提示"请先卸载组件安装的插件"

### ISSUE THREAD

**Issue by GLYASAI** [goodrain/rainbond#524]
- Rainbond版本: v5.1.8-release

![image](https://user-images.githubusercontent.com/21967570/67936942-9ff33e80-fc07-11e9-9fdb-f849b78e7a86.png)

在删除组件的时候, 控制台提示"请先卸载组件安装的插件". 但是我这个组件并没有安装插件.

**Comment by dazuimao1990** [comment]
@barnettZQG 验证通过

**Comment by lxm** [comment]
![image](https://user-images.githubusercontent.com/1918195/70998829-21992000-2113-11ea-9d8b-86cbecf0fa91.png)

此问题在5.1.9中依然存在

**Comment by lxm** [comment]
@GLYASAI

**Comment by Aaron-23** [comment]
v5.1.11版本验证通过
