### ISSUE TITLE
修改yaml配置文件后node service update 但是systemd文件并没有被更新

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#525]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云

**Comment by fanyangyang** [comment]
执行update时可观察node日志，确定是否正常写入文件，如果没有正常写入文件会有相应日志提示
如`Generate config file....`等，请留心观察

**Comment by barnettZQG** [comment]
5.1.9 更新后将重写文件。
