### ISSUE TITLE
5.1.7在证书管理管理界面更新证书后，组件无法自动更新域名所使用的证书

### ISSUE THREAD

**Issue by liaoyizhi** [goodrain/rainbond#527]
- [ Rainbond grctl v5.1.7-release-afa0e36-2019-09-11-00 ] Rainbond版本(执行grctl version获取)

- [ CentOS Linux release 7.6.1810 ] 操作系统类型和版本

- [ 阿里云-单节点 ] 部署环境：公有云、私有云

5.1.7在证书管理管理界面更新证书后，界面显示了证书的最新有效期，单组件无法自动更新域名所使用的证书，还是原来的有效期，更新组件或者重启组件都没有效果，必须删除域名重新添加才能生效。当组件很多的时候，更新证书相当麻烦，是否有更有效的方式，或者增加自动获取免费证书的功能。

**Comment by dazuimao1990** [comment]
@barnettZQG 测试通过

**Comment by laoliao0806** [comment]
分享一下在5.1.7中的处理方法，在“访问控制”中，找到相关域名，点击“编辑”，然后再直接点击“确认”，即可成功更新组件的证书。

**Comment by lxm** [comment]
5.1.10中  证书更新后没有自动生效

![image](https://user-images.githubusercontent.com/1918195/73641950-c663c280-46ab-11ea-94b8-896a4524f739.png)

**Comment by laoliao0806** [comment]
我还没有测试，建议开新的issues，被关闭的大佬看不见
