### ISSUE TITLE
5.1.7内存足够时，启动组件报cannot allocate memory错误

### ISSUE THREAD

**Issue by liaoyizhi** [goodrain/rainbond#528]
- [ Rainbond grctl v5.1.7-release-afa0e36-2019-09-11-00 ] Rainbond版本(执行grctl version获取)

- [ CentOS Linux release 7.6.1810 ] 操作系统类型和版本

- [ 阿里云-单节点 ] 部署环境：公有云、私有云

![image](https://user-images.githubusercontent.com/1860589/68028063-df488a80-fcee-11e9-9df6-57afdab48000.png)

![image](https://user-images.githubusercontent.com/1860589/68028279-7dd4eb80-fcef-11e9-8fcd-8a8e0a27929a.png)

如图所示，服务器为阿里云8核32G内存，单节点部署，内存剩余19G，组件所需内存512M，可以说内存是非常充足的，不知为何会报这个错误，虽然是警告，但是组件确实起不来。

**Comment by barnettZQG** [comment]
https://github.com/moby/moby/issues/18295#issuecomment-308957013
 
建议参考此issues处理当前计算节点。

**Comment by barnettZQG** [comment]
我将关闭这个issue.
