### ISSUE TITLE
节点删除组件时无法删除，节点一直处于unhealth状态

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#529]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云
执行操作如下
# 将rbd-db配置文件移走
mv /opt/rainbond/conf/db.yaml /backup
rm -rf  /etc/systemd/system/rbd-db.service 
# 停止rbd-db服务
systemctl stop rbd-db
# 将rbd-db从组件列表删除
grctl node condition delete <NODE ID> --name rbd-db
# 更新组件
node service update

![image](https://user-images.githubusercontent.com/50609288/68096612-d3c2b280-feec-11e9-8b6b-d51eb5b3d64d.png)

**Comment by dazuimao1990** [comment]
对于多管理节点的情况，可以按照如下操作临时解决：
- 关闭问题节点的node服务 ：systemctl stop node  
- 切换到其他节点执行删除组件的操作 ： grctl node condition delete --name rbd-db <Node Uid>
- 启动问题节点的node服务： systemctl start node
问题就会得到解决。

对于单个管理节点的情况，上述方式并不适用，请等待更新的解决方案。

**Comment by barnettZQG** [comment]
该问题将于5.1.9发行版修复。修复后从配置文件中删除组件或监控项后，node的condition数据将自动清理。
另外，新增condition更新超时状态，每一个condition超过1m不更新将设置为“UnKnow”状态。

**Comment by dazuimao1990** [comment]
@barnettZQG  验证通过
