### ISSUE TITLE
网关https策略修改为http策略不生效

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond#534]
添加了https访问策略，绑定了证书，然后编辑访问策略去除证书绑定，即从https编辑为http.
元数据修改成功，但实际生效的效果是 https依然可以访问, http不能访问。

相关版本信息：
- [x] Rainbond版本(执行grctl version获取): 5.1.8

**Comment by dazuimao1990** [comment]
@barnettZQG 验证通过
