### ISSUE TITLE
新建应用，打开应用一直报错，然后构建一直在进行中

### ISSUE THREAD

**Issue by kkrout** [goodrain/rainbond#544]
报错的返回的json
{"msg":{"url":"https://region.goodrain.me:8443/v2/tenants/psyhzuaq/pods?enterprise_id=7aa21a93072302ab1654be93ef297cca&service_ids=e5735ac902576ce1ffba3cf1f0f3be4e","body":{"raw":"Internal Server Error\n"},"httpcode":500,"method":"GET","apitype":"Not specified"},"code":10401,"msg_show":"服务端异常"}

**Comment by barnettZQG** [comment]
集群状态是否正确？ 执行grctl cluster 获取。
另外可以查看 journalctl -fu rbd-api日志确定API服务的错误。
参考文档：https://www.rainbond.com/docs/troubleshoot/cluster-problem/

**Comment by kkrout** [comment]
貌似服务启动异常了
![image](https://user-images.githubusercontent.com/37602470/68575309-bc646600-04a6-11ea-8d24-a52374720f2f.png)

**Comment by kkrout** [comment]
![image](https://user-images.githubusercontent.com/37602470/68575580-50363200-04a7-11ea-8439-fbbe5687660e.png)

**Comment by kkrout** [comment]
![image](https://user-images.githubusercontent.com/37602470/68575653-752aa500-04a7-11ea-85d5-74dc3897c9f2.png)

**Comment by fanyangyang** [comment]
根据rbd-gateway的日志看到提示是参数不对，可以尝试通过重启node服务让其重新注入参数
