### ISSUE TITLE
机器突然断电，来电后出现某个应用的实例启动了很多，导致资源不足。

### ISSUE THREAD

**Issue by zeroByzero** [goodrain/rainbond#550]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)
v5.1.6

- [ ] 操作系统类型和版本
CentOS Linux release 7.5.1804 (Core)

- [ ] 部署环境：公有云、私有云
私有云

**Comment by barnettZQG** [comment]
此问题升级到V5.1最新版本
