### ISSUE TITLE
应用升级出现长时间未就绪状态

### ISSUE THREAD

**Issue by lxm** [goodrain/rainbond#553]
- [ ] Rainbond版本 v5.1.8-release-bffee0f

**Comment by GLYASAI** [comment]
能提供更详细的信息吗?

在控制台页面上可以点击未就绪的实例, 里面会有详细的日志, 麻烦提供相应的截图.

另外, 还可以在管理节点执行 `journal -fu rbd-worker`查看 `rbd-worker` 相应的日志. 如果有多个管理节点, 则需要在每个管理节点上都执行以上命令. 把相应的错误日志提供一下.

谢谢.

**Comment by barnettZQG** [comment]
没有反馈，此类问题升级到V5.1最新版本
