### ISSUE TITLE
应用网关--> 路由规则未显示VIP（10.63.4.53），无法绑定，后端服务器vip正常

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#555]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云
![image](https://user-images.githubusercontent.com/50609288/68839274-54f32400-06fb-11ea-8c80-0b23800d2eef.png)

**Comment by barnettZQG** [comment]
这个问题需要更多的gateway组件日志反馈
https://github.com/goodrain/rainbond/commit/1a856b3c94d11f6723cdd7e8749a6dac191e130a
代码提交可能修复这个问题。

**Comment by barnettZQG** [comment]
经过测试，该问题已得到解决。
