### ISSUE TITLE
rbd-gateway日志出现大量wrong endpoint

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#556]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云
![image](https://user-images.githubusercontent.com/50609288/68839393-9aafec80-06fb-11ea-9b9b-4de103071a5c.png)

**Comment by barnettZQG** [comment]
同一个问题 #532
