### ISSUE TITLE
更新应用时长期处于等待中状态，一段时间后超时，重启组件后恢复运行中状态

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#563]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云
![image](https://user-images.githubusercontent.com/50609288/69214117-059c7000-0ba1-11ea-8e02-10bbe4c61b75.png)

**Comment by barnettZQG** [comment]
没有反馈，我们将关闭这个问题
