### ISSUE TITLE
创建新服务后，报错请求异常

### ISSUE THREAD

**Issue by lxm** [goodrain/rainbond#565]
![image](https://user-images.githubusercontent.com/1918195/69320789-d1967d00-0c7c-11ea-9124-c27b24ff2559.png)

之后应用变成关闭状态
过段时间手动点击启动应用可以启动

**Comment by GLYASAI** [comment]
我想应该是 `rbd-worker` 异常了, 能提供 `rbd-worker` 组件的状态和相应日志吗?

在管理节点执行以下命令:
```
# 查看状态
grctl cluster
# 查看日志
journalctl -fu rbd-worker
```

**Comment by barnettZQG** [comment]
没有反馈，我们将关闭这个问题
