### ISSUE TITLE
package api design (Golang pattern)

### ISSUE THREAD

**Issue by avelino** [goodrain/rainbond#57]
https://github.com/goodrain/rainbond/blob/master/pkg/worker/appm/pod.go#L28

```go
import (
	"github.com/goodrain/rainbond/pkg/db"
	"github.com/goodrain/rainbond/pkg/db/model"
	"github.com/goodrain/rainbond/pkg/event"
	"github.com/goodrain/rainbond/pkg/util"
...
)
```

Using PKG in the packet API is not recommended, read more[1]

[1] https://rakyll.org/style-packages/#clean-import-paths (pt-BR: http://www.avelino.xxx/guia-de-estilo-para-pacotes-go/)

**Comment by barnettZQG** [comment]
@avelino Thank you for your advice.

**Comment by avelino** [comment]
My recommendation is moved all package of pkg to root folder

Example:
github.com/goodrain/rainbond/db


What do you think? I can help by sending PR this refactoring

**Comment by barnettZQG** [comment]
@avelino  That's great, and we're starting to focus on the code style.

**Comment by avelino** [comment]
Great, I will arrange my time to look at this issue

**Comment by avelino** [comment]
Very very good @barnettZQG

**Comment by barnettZQG** [comment]
@avelino Are you agree to join this project to: `awesome-go`,  That is pleasant.
