### ISSUE TITLE
应用首次导入失败时，重新导入，chaos显示文件不存在，查看确实无此文件，故点击重新导入仍会失败

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#570]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云
![image](https://user-images.githubusercontent.com/50609288/69785997-77edff80-11f4-11ea-994f-639d6d7b8a1a.png)
![image](https://user-images.githubusercontent.com/50609288/69786043-9227dd80-11f4-11ea-8806-9bcd87549e2b.png)

**Comment by barnettZQG** [comment]
此问题转前端修复，离线导入UI展示在5.2版本中重构，将移除重新导入按钮。
