### ISSUE TITLE
查看集群信息显示  NodeInit  Condition not updated in more than 1 minute

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#572]
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，请移步[Rainbond用户社区](https://t.goodrain.com/)

- [ ] Rainbond版本(执行grctl version获取)

- [ ] 操作系统类型和版本

- [ ] 部署环境：公有云、私有云
![image](https://user-images.githubusercontent.com/50609288/70014920-e812d180-15b6-11ea-8ec9-bbe2f35ad200.png)

![image](https://user-images.githubusercontent.com/50609288/70014981-11cbf880-15b7-11ea-8049-5a43b879ea60.png)

**Comment by barnettZQG** [comment]
Nodeinit condition 于5.1.9版本中删除，请用以下命令移除已经存在的condition:
```
grctl node condition delete <NodeID> --name NodeInit
```
