### ISSUE TITLE
同一应用添加两个tcp对外端口，同时只有一个生效

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#583]
【BUG描述】(同一应用添加两个tcp对外端口，同时只有一个生效)

【部署环境】
- Rainbond版本(执行`grctl version`获取): [请填写此处]
- 操作系统类型和版本:[请填写此处]
- 离线部署/网络开放：[请填写此处]
20006和20044同时只有一个可以提供对外访问
![image](https://user-images.githubusercontent.com/50609288/70704026-312bf980-1d0c-11ea-9134-13f9072f632e.png)

gateway日志
![image](https://user-images.githubusercontent.com/50609288/70703637-7996e780-1d0b-11ea-85cd-fdeba6b05819.png)

**Comment by barnettZQG** [comment]
从日志看，不是因为一个组件添加了两个tcp策略而不能访问，是由于20048端口冲突导致的新添加策略无法生效。
所以这里的问题是能否告知20048端口被哪个进程占用了导致冲突 @Aaron-23

**Comment by Aaron-23** [comment]
20048端口即两个tcp策略中的一个，上图是我验证之后的，所以更改了端口

**Comment by fanyangyang** [comment]
自测开启两个对外端口均可正常工作，待进一步测试

**Comment by barnettZQG** [comment]
长期不更新，我将关闭这个问题
