### ISSUE TITLE
5.1.9 UI拓扑图实例数量显示与微服务管理页面实例数量不一致。

### ISSUE THREAD

**Issue by yszansx** [goodrain/rainbond#588]
【BUG描述】
升级到5.1.9 启用自动伸缩功能后发现，拓扑图UI实例**显示**数量与微服务管理页面的实例实际数量不一致。
拓扑图界面中，永远都是一个实例，微服务管理页面里面有可能是1个 、2个或者3个。这个能给优化和修复下嘛。
![image](https://user-images.githubusercontent.com/43443722/70885070-be27c900-2012-11ea-96c4-11b246c31e1c.png)

![image](https://user-images.githubusercontent.com/43443722/70885040-a7817200-2012-11ea-9b30-e23ba3206b40.png)

【部署环境】
- Rainbond版本(执行`grctl version`获取): Rainbond grctl v5.1.9-release-32cc2ba-2019-12-13-05
- 操作系统类型和版本:ubuntu 16.4
- 离线部署/网络开放：私有化高可用集群部署

**Comment by barnettZQG** [comment]
组件初始化设置的实例数量是否为1？
@yszansx

**Comment by barnettZQG** [comment]
参考升级指南 https://www.rainbond.com/docs/upgrade/5.1.9-5.1.10/
