### ISSUE TITLE
第三方服务无规律不可用

### ISSUE THREAD

**Issue by lxm** [goodrain/rainbond#590]
【BUG描述】第三方服务无规律不可用

【部署环境】
- Rainbond版本 v5.1.9-release-32cc2ba-2019-12-13-09
- 操作系统类型和版本: ubuntu
- 离线部署/网络开放：网络开放

间歇性出现第三方服务不可用，但是第三方服务状态为上线
多次出现后变得完全不可用
127.0.0.1:65533/clusters 信息中关于第三方服务的信息出现了8.8.8.8的信息

**Comment by fanyangyang** [comment]
8.8.8.8是为了将第三方组件的域名信息写入到k8s的endpoint资源中，这个会导致第三方服务不可用吗？

**Comment by fanyangyang** [comment]
@lxm

**Comment by lxm** [comment]
目前观察到的现象是这样，手动将第三方服务上下线之后恢复了正常

**Comment by fanyangyang** [comment]
如何复现该问题？方便我进行复现排查问题@lxm

**Comment by lxm** [comment]
目前没有找到复现方法

**Comment by barnettZQG** [comment]
应该与第三方组件健康检测下线后不会自动恢复有关，需要对健康检测控制器进行改进支持实例恢复健康后重新上线。

**Comment by barnettZQG** [comment]
#580

**Comment by barnettZQG** [comment]
参考升级指南 https://www.rainbond.com/docs/upgrade/5.1.9-5.1.10/
