### ISSUE TITLE
【探讨】应用网关是否新增默认参数X-Forwarded-Proto 

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond#591]
【需求描述】
 应用网关是否新增默认参数:
`proxy_set_header X-Forwarded-Proto $scheme;`

 访问协议对于后端应用是有用的，它有助于业务完成正确的重定向或Cookies安全控制。

**Comment by dazuimao1990** [comment]
在被discourse的强制https影响登陆这个问题差点搞疯之后，我强烈建议在网关默认添加该配置。

**Comment by barnettZQG** [comment]
相关参数：
*  X-Request-ID
*  X-Real-IP 
*  X-Forwarded-For   
*  X-Forwarded-Host
*  X-Forwarded-Port
*  X-Forwarded-Proto
*  X-Original-URI
*  X-Scheme

**Comment by barnettZQG** [comment]
已于V5.2.0支持。
