### ISSUE TITLE
有依赖的应用随机无法启动

### ISSUE THREAD

**Issue by lxm** [goodrain/rainbond#593]
【BUG描述】有依赖的应用随机无法启动

【部署环境】
- Rainbond版本 v5.1.9-release-32cc2ba-2019-12-13-09
![image](https://user-images.githubusercontent.com/1918195/71169297-98f5bd80-2293-11ea-98bc-66abc91e2495.png)

time="2019-12-19T19:13:22+08:00" level=info msg="start checking eds; dependent service cluster names: []"
15f8ed6aac2c
66
time="2019-12-19T19:13:22+08:00" level=info msg="depend service (0f09df5f31074a33b62df691b25d4bb9_gra2bac8_gr363055_9000) start complete"
67
time="2019-12-19T19:13:22+08:00" level=info msg="received cluster load assignments; length: 1; names: 0f09df5f31074a33b62df691b25d4bb9_gra2bac8_gr363055_9000"
68
time="2019-12-19T19:13:22+08:00" level=info msg="cluster name: 0f09df5f31074a33b62df691b25d4bb9_gra2bac8_gr363055_9000; ready: true"
69
time="2019-12-19T19:13:22+08:00" level=info msg=" not ready."

**Comment by barnettZQG** [comment]
@GLYASAI  该问题分析原因。

**Comment by lxm** [comment]
![image](https://user-images.githubusercontent.com/1918195/71169921-0c4bff00-2295-11ea-9e8f-add218089160.png)

**Comment by barnettZQG** [comment]
我分析可能是 goodrain.me/rbd-init-probe 镜像未升级到5.1.9版本。

**Comment by GLYASAI** [comment]
的确是 goodrain.me/rbd-init-probe 镜像未升级到5.1.9版本, 可以用一下命令进行升级:

```bash
docker pull rainbond/rbd-init-probe
docker tag rainbond/rbd-init-probe goodrain.me/rbd-init-probe
docker push  goodrain.me/rbd-init-probe
```

升级完成后需要重启应用.

**Comment by lxm** [comment]
> docker run -it goodrain.me/rbd-init-probe /run/rainbond-init-probe --version
结果如下
```
rainbond-init-probe version v5.1.9-release-32cc2ba-2019-12-13-09
```
> docker pull rainbond/rbd-init-probe
结果如下
```
Using default tag: latest
Error response from daemon: manifest for rainbond/rbd-init-probe:latest not found
```

**Comment by barnettZQG** [comment]
@lxm  
镜像名称为`rainbond/rbd-init-probe:v5.1.9-release`

**Comment by lxm** [comment]
已更新

**Comment by lxm** [comment]
升级此镜像后依然复现

**Comment by barnettZQG** [comment]
@lxm 5.1.9版本已就此问题做了补丁修复。
```
//升级mesh plugin 镜像
docker pull rainbond/rbd-init-probe:v5.1.9-release
docker tag rainbond/rbd-init-probe goodrain.me/rbd-init-probe
docker push  goodrain.me/rbd-init-probe

//升级worker组件
grclis upgrade rbd-worker

//升级node组件
docker pull rainbond/cni:rbd_v5.1.9-release
docker run --rm -v /tmp/upgrade:/sysdir rainbond/cni:rbd_v5.1.9-release tar zxf /pkg.tgz -C /sysdir
systemctl stop node && cp -a /tmp/upgrade/bin/node /usr/local/bin/node && systemctl start node
```

**Comment by barnettZQG** [comment]
已修复，如有问题重新打开。

**Comment by lxm** [comment]
node组件修复需要在所有节点执行吗？

**Comment by barnettZQG** [comment]
@lxm 需要。
