### ISSUE TITLE
【需求】支持设置应用CPU

### ISSUE THREAD

**Issue by lxm** [goodrain/rainbond#594]
【需求描述】支持设置应用CPU
 
【BUG描述】(非BUG请删除本行)

-------------------------以下内容请阅读后删除-----------------------------
目前应用仅支持设置内存大小，不支持设置CPU，建议支持CPU设置按照0.5G步进

**Comment by barnettZQG** [comment]
目前默认情况下CPU按照一定算法进行换算，模式如下：
```
base := int64(memory) / 128
if memory < 512 {
		cpuRequest, cpuLimit = base*30, base*80
	} else if memory <= 1024 {
		cpuRequest, cpuLimit = base*30, base*160
	} else {
		cpuRequest, cpuLimit = int64(memory)/128*30, ((int64(memory)-1024)/1024*500 + 1280)
	}
```
该模式基本上与节点推进的内存/CPU比例一致。
目前若某组件需要自行定义CPU，可设置如下环境变量：
ES_CPULIMIT: CPU限制值
ES_CPUREQUEST：CPU请求值
