### ISSUE TITLE
组件的状态判断不准确

### ISSUE THREAD

**Issue by GLYASAI** [goodrain/rainbond#595]
【BUG描述】组件的状态判断不准确

![image](https://user-images.githubusercontent.com/21967570/71228473-2cbf9c00-231d-11ea-9347-ee375348cf34.png)

如图, 组件的状态显示地是 `关闭中`, 但是我并没有关闭该组件, 而是执行了更新操作.

这是一个有状态的组件, 实例数量为 3 . 当我点击更新时, 触发了滚动更新; 滚动更新会先停掉一个旧的实例, 再起一个新的实例.

【部署环境】

- Rainbond版本: Rainbond grctl v5.1.9-release-32cc2ba-2019-12-13-05 (console.goodrain.com)

**Comment by barnettZQG** [comment]
@GLYASAI 
状态 “关闭中” 判断依据是Pod正在正常关闭，更新操作触发的就是先正常关闭Pod然后再启动Pod的过程。因此若要正确判断组件状态为”更新中“需要结合操作过程来判定，然而操作过程数据不是全局状态，不能在多个 worker组件中共享，因此目前不能作为组件状态判断的条件。

这里我们需求明确组件状态的作用，其正确反应当前组件的运行周期状态即可。一次更新动作由组件状态来体现，先关闭中，再启动中，未尝不可。

“升级中”的状态还需要更多的数据来支撑判断，比如statefulset的滚动过程数据来体现。
