### ISSUE TITLE
5.1.9: OAuth2.0无法从gitlab项目创建组件

### ISSUE THREAD

**Issue by laoliao0806** [goodrain/rainbond#597]
【BUG描述】
![image](https://user-images.githubusercontent.com/53854600/71305005-cdd75100-2408-11ea-904f-0dcf8a6c931e.png)

![image](https://user-images.githubusercontent.com/53854600/71305124-0592c880-240a-11ea-986a-2318dc208cf7.png)

![image](https://user-images.githubusercontent.com/53854600/71305019-fc552c00-2408-11ea-82a6-eb634bacaa3e.png)

![image](https://user-images.githubusercontent.com/53854600/71305027-1c84eb00-2409-11ea-9fee-e65651871f9f.png)

![image](https://user-images.githubusercontent.com/53854600/71304953-3b36b200-2408-11ea-8f35-f2a482c69cae.png)

尝试使用OAuth2.0功能，能够正常绑定与登录，但是无法从gitlab项目创建组件，接口返回：该OAuth服务不是代码仓库类型，或Access Token 已过期

不知道哪里配置有问题？

【部署环境】
- Rainbond版本: [v5.1.9-release-32cc2ba-2019-12-13-05]
- 操作系统类型和版本:[CentOS Linux release 7.7.1908]
- 离线部署/网络开放：[网络开放]
- gitlab版本：[11.9.0-ee (2f3536b)]

**Comment by panda-zxs** [comment]
需要后端日志来确定问题

**Comment by panda-zxs** [comment]
控制台日志路径 /opt/rainbond/logs/rbd-app-ui/goodrain.log @laoliao0806

**Comment by laoliao0806** [comment]
@panda-zxs 你好，重新搭建集群后已能正常使用，之前的日志已无法找到

**Comment by barnettZQG** [comment]
我们将关闭这个问题。
