### ISSUE TITLE
5.1.9 添加第三方组件时无法添加多个IP

### ISSUE THREAD

**Issue by laoliao0806** [goodrain/rainbond#598]
【BUG描述】
![image](https://user-images.githubusercontent.com/53854600/71316348-6c1af380-24a9-11ea-89ec-7a82020895c3.png)

![image](https://user-images.githubusercontent.com/53854600/71316455-bd77b280-24aa-11ea-9b2b-3dc63afb4999.png)

![image](https://user-images.githubusercontent.com/53854600/71316513-8950c180-24ab-11ea-9afc-c7db03a662a9.png)

这个5.1.8已经存在的问题仍未解决呢，我添加的是IP，不是域名，应该是可以添加多个才对，现在的情况是，不带端口的IP可以添加多个，只要有一个带端口，就不能再添加IP了 #512

@fanyangyang 

【部署环境】
- Rainbond版本: [v5.1.9-release-32cc2ba-2019-12-13-05]
- 操作系统类型和版本:[CentOS Linux release 7.7.1908]
- 离线部署/网络开放：[网络开放]
- gitlab版本：[11.9.0-ee (2f3536b)]

**Comment by fanyangyang** [comment]
我会对其进行详细的确认并在此给出一个解决的方案
@laoliao0806 很抱歉给您的使用带来了很大的困扰

**Comment by laoliao0806** [comment]
好的，辛苦了！

**Comment by fanyangyang** [comment]
@laoliao0806 目前了解的情况是前端限制，同事@zsl1549 会提供相应修改的镜像支持，并将此次修改做一次pr，合并到开发分支中，避免后续遇到类似的情况

**Comment by laoliao0806** [comment]
@fanyangyang 为你们的态度点赞

**Comment by zsl1549** [comment]
@laoliao0806 问题已修复  请查看 https://github.com/goodrain/rainbond-ui/pull/297

**Comment by fanyangyang** [comment]
@laoliao0806 新的镜像基于v5.1.9-release版本制作已经完成，可以下载安装使用

```
docker pull a985850124/rbd-app-ui:v5.1.9-issue-589
docker tag a985850124/rbd-app-ui:v5.1.9-issue-589 goodrain.me/rbd-app-ui:v5.1.9-release
systemctl restart rbd-app-ui
```

请对修改结果进行反馈，感谢

**Comment by laoliao0806** [comment]
@fanyangyang @zsl1549 经测试已可正常添加多个IP，辛苦了，感谢！

**Comment by fanyangyang** [comment]
嗯嗯，给您造成了不便，再次抱歉

我将关闭该issue
