### ISSUE TITLE
The "rbd-entrance" component depends on the "host_uuid.conf" file address to the "/opt/rainbond/" directory.

### ISSUE THREAD

**Issue by goodrainzh** [goodrain/rainbond#60]
@barnettZQG

**Comment by ysicing** [comment]
fixed here [rainbond-install #43](https://github.com/goodrain/rainbond-install/issues/43)

**Comment by ysicing** [comment]
It is recommended to support dynamic configuration.
```
--nodeid-file=/opt/rainbond/etc/node/node_host_uuid.conf
```

**Comment by barnettZQG** [comment]
@ysicing `rbd-eventlog`, `rbd-node` read hostid from configuration `--nodeid-file` or `/opt/rainbond/etc/node/node_host_uuid.conf`.
