### ISSUE TITLE
频繁的伸缩资源，导致计算资源页面统计出了问题

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#601]
【BUG描述】

频繁的伸缩资源，导致计算资源页面统计出了问题

![image](https://user-images.githubusercontent.com/33855684/71397357-50098480-2658-11ea-8083-db1799033347.png)

【部署环境】
- Rainbond版本(执行`grctl version`获取): 5.1.9

**Comment by GLYASAI** [comment]
频繁伸缩, 是垂直伸缩, 还是水平伸缩, 还是自动伸缩. 另外, 能否具体描述操作的过程.

**Comment by wwater84** [comment]
水平伸缩

**Comment by wwater84** [comment]
水平伸缩，系统的内存资源在buff/cache中没有释放，导致rainbond中统计系统资源误报

**Comment by wwater84** [comment]
![image](https://user-images.githubusercontent.com/46913956/71567472-69984980-2afa-11ea-8431-b99ef0dcf43a.png)

**Comment by wwater84** [comment]
手动释放一下buff/cache缓存，集群中有足够的内存供使用。

**Comment by Aaron-23** [comment]
实际使用内存8G+，统计页面只显示1G

**Comment by Aaron-23** [comment]
这是两个问题
1.频繁的伸缩资源，导致平台资源统计出错，可以确定这是一个bug；
2.系统内存资源都被buffer占用，导致创建应用时平台显示集群资源不足，无法创建，平台在统计计算资源时可使用的资源不足，这是一个系统层面问题，需从系统层面入手查看buffer大量占用内存的原因。

**Comment by dazuimao1990** [comment]
@GLYASAI 请关注下这个问题
