### ISSUE TITLE
Rainbond被检测出了漏洞，需要考虑修复

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#603]
【需求描述】
Rainbond被检测出了如下漏洞，需要考虑修复。
![image](https://user-images.githubusercontent.com/33855684/71402695-82bb7900-2668-11ea-97a0-1aa97fdd2337.png)

【部署环境】
- Rainbond版本(执行`grctl version`获取): 5.1.9

**Comment by GLYASAI** [comment]
Rainbond 5.2 will improve this issue

**Comment by dazuimao1990** [comment]
Is there a temporary solution @GLYASAI

**Comment by GLYASAI** [comment]
To solve this problem, you need to put the certificate of `goodrain.me` in the corresponding directory of Docker (eg. `/etc/docker/certs.d/goodrain.me/`). But the certificate of goodrain.me is generated by `rbd-gateway`, and Does not persist, new certificates are generated with each restart. So it cannot be temporarily resolved

**Comment by GLYASAI** [comment]
5.2 已支持通过证书访问 goodrain.me
