### ISSUE TITLE
【需求】应用标签支持增删访问策略

### ISSUE THREAD

**Issue by lxm** [goodrain/rainbond#604]
【需求描述】应用标签支持增删访问策略
 
![image](https://user-images.githubusercontent.com/1918195/71413204-1ce0e880-268c-11ea-8e05-91904f2e07b7.png)

考虑可以在应用内增加访问策略标签，便于管理域名等配置，网关模块访问策略较多，不容易查找

**Comment by barnettZQG** [comment]
此需求已经列入V5.2规划。应用管理视图中将增加访问策略管理。

**Comment by barnettZQG** [comment]
已于5.2.0-bete2版本支持
