### ISSUE TITLE
服务正常，但不停起新的并且老的不关闭

### ISSUE THREAD

**Issue by caijiaolong** [goodrain/rainbond#607]
【BUG描述】(非BUG请删除本行)
不停的失败老的构建，不停的新产生pod，但是老的pod并没有删除
--健康检查是关闭的
如图，这个就是个很简单的rocketmq的console，还是官方的。一直这样

![image](https://user-images.githubusercontent.com/29752476/71463258-bd501d80-27f0-11ea-9450-59f8eccd7f16.png)

【部署环境】
- Rainbond版本(执行`grctl version`获取): [请填写此处]
5.1.9 单机8核16g
- 操作系统类型和版本 :[请填写此处]
centos7.5

- 离线部署/网络开放：[请填写此处]
磁盘信息如图
![image](https://user-images.githubusercontent.com/29752476/71463343-0b652100-27f1-11ea-95cb-9212c97490ab.png)

**Comment by barnettZQG** [comment]
@caijiaolong 
麻烦提供一下 执行 grctl service get 命令 的结果截图（实例页面有此命令）

**Comment by caijiaolong** [comment]
Error: tenant alias can not be empty

**Comment by barnettZQG** [comment]
@caijiaolong 
![image](https://user-images.githubusercontent.com/18493394/71496553-d5767a00-288e-11ea-91ad-99cd91add892.png)

**Comment by barnettZQG** [comment]
@caijiaolong 需要提供更多的信息协助分析原因。

**Comment by barnettZQG** [comment]
请升级V5.1最新版本
