### ISSUE TITLE
建议：隐藏openresty版本号

### ISSUE THREAD

**Issue by laoliao0806** [goodrain/rainbond#612]
【需求描述】
 
![image](https://user-images.githubusercontent.com/53854600/71660361-be032980-2d85-11ea-9063-e511b7fe5876.png)

如题，建议始终隐藏网关节点openresty的版本号，无论是报错时还是正常请求时的响应头中，甚至openresty都不需要显示，避免被有心人针对

**Comment by barnettZQG** [comment]
这个问题可以优化

**Comment by barnettZQG** [comment]
1.  隐藏openresty 版本号。
2. 增加应用未启动时访问的默认页面返回。

**Comment by barnettZQG** [comment]
参考升级指南 https://www.rainbond.com/docs/upgrade/5.1.9-5.1.10/
