### ISSUE TITLE
跪求更新go module源码部署

### ISSUE THREAD

**Issue by cn-ygf** [goodrain/rainbond#613]
【需求描述】(非需求请删除本行)
 满地打滚求更新go语言 go module源码部署
现在很多代码都有go mod了，顺便加上go proxy 么么哒
【部署环境】
- Rainbond版本(执行`grctl version`获取): Rainbond grctl v5.1.9-release-ac6e5fc-2019-12-27-01
- 操作系统类型和版本:CentOS7
- 离线部署/网络开放：网络开放

**Comment by barnettZQG** [comment]
package  manage util support gomodules、dep、govendor、glide、gb。

**Comment by barnettZQG** [comment]
@cn-ygf  最新的测试版本已经支持go mod ，相关说明如下：

* 支持的go 版本增加了 1.12（1.12.14）、1.13（1.13）
* go mod 模式下默认设置GOPROXY，用户也可以自定义环境变量BUILD_GOPROXY设置。
* 支持组件级缓存，依赖包无需每次构建都重新下载。

demo 代码参考：
http://git.goodrain.com/apps/gomod-demo.git

现有版本使用方式：
管理节点更新builder镜像：
```
docker pull rainbond/builder:5.2.0 && docker tag rainbond/builder:5.2.0 goodrain.me/builder && docker push goodrain.me/builder
```

**Comment by barnettZQG** [comment]
我将关闭这个问题，如有疑问，请重新打开
