### ISSUE TITLE
自定义插件不支持修改更新说明

### ISSUE THREAD

**Issue by yszansx** [goodrain/rainbond#614]
【BUG描述】(非BUG请删除本行)
rainbond v5.1.9自定义了一个插件，调试完成后需要修改插件的说明项。但是找不到具体修改的地方。

详细信息在帖子里面。
https://t.goodrain.com/t/topic/1310

**Comment by panda-zxs** [comment]
现在的接口不支持修改插件的说明项，只能添加更新信息

**Comment by barnettZQG** [comment]
已于5.1.10版本中修复。更新说明即修改插件说明
