### ISSUE TITLE
OAM模型支持-Roadmap

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond#616]
### OAM说明
[OAM](https://github.com/oam-dev/spec)(Open Application Model) 是一个专注于描述应用的标准规范，由微软和阿里巴巴共同推出。有了这个规范，应用描述就可以彻底与基础设施部署和管理应用的细节分开。这种关注点分离（Seperation of Conerns）的设计好处是非常明显的。 举个例子，在实际生产环境中，无论是 Ingress、CNI 还是 Service Mesh，这些表面看起来一致的运维概念，在不同的 Kubernetes 集群中可谓千差万别。 通过将应用定义与集群的运维能力分离，我们就可以让应用开发者更专注应用本身的价值点，而不是”应用部署在哪“这样的运维细节。

### OAM与Rainbond的关系
Rainbond 目前的应用模型命名为（Rainbond Application Model），设计思想与OAM基本一致，致力于定义一种应用描述规范。OAM模型致力于更加规范和开放的模型定义，Rainbond愿意与之合作打造一个云原生应用描述模型及生态产品支持，Rainbond主要提供应用模型组装、架构支持、组件开发、交付、运维管理等应用全生命周期流程的应用管理平台。

### Rainbond与OAM模型结合计划

* Rainbond 开放应用市场支持OAM应用规范的应用存储和交付，与OAM社区一道完成OAM仓库规范的定义和实现。
* Rainbond PaaS平台支持发布OAM应用。
* Rainbond PaaS平台组件类型支持全量OAM Core workload。
* Rainbond PaaS平台组件类型逐步支持OAM Extended workload types。

**Comment by barnettZQG** [comment]
受疫情和OAM规范调整的影响，对OAM的支持进度有稍微延迟，我们预计在2020年4月左右发布的版本中逐步引入OAM应用规范。

**Comment by barnettZQG** [comment]
Rainstore产品将率先实现OAM原生应用仓库功能。

**Comment by barnettZQG** [comment]
Trait Demand:

* ExternalDNS

Workload Demand:

* RDS

**Comment by zzxwill** [comment]
> Rainstore产品将率先实现OAM原生应用仓库功能。

请问，已经实现了吗？
