### ISSUE TITLE
支持在已有k8s集群上部署rb

### ISSUE THREAD

**Issue by F-liuhui** [goodrain/rainbond#617]
【需求描述】(非需求请删除本行)
 支持在已有k8s集群上部署rb
【BUG描述】(非BUG请删除本行)

【部署环境】
- Rainbond版本(执行`grctl version`获取): [请填写此处]
- 操作系统类型和版本:[请填写此处]
- 离线部署/网络开放：[请填写此处]
  rb目前不支持在已有集群上部署，希望能有这方面的支持。例如我们现在已经有一套k8s集群，想在已有集群上部署rb来了解这款产品，但是rb目前不支持。重新提供资源来部署rb领导又不同意，我相信像我们这样情况的人不在少数。不利于rb的推广。

**Comment by barnettZQG** [comment]
@F-liuhui 请关注5.2-beta1版本的发布，即可支持在已有kubernetes集群中部署Rainbond。
预计时间 1月15日之前。

**Comment by barnettZQG** [comment]
参考：#586

**Comment by barnettZQG** [comment]
参考 https://github.com/goodrain/rainbond/releases/tag/v5.2.0-beta1
