### ISSUE TITLE
5.1.9 当计算节点运行一段时间后，经常无法启动或关闭容器

### ISSUE THREAD

**Issue by laoliao0806** [goodrain/rainbond#618]
【BUG描述】
![image](https://user-images.githubusercontent.com/53854600/71790673-a28d6c80-306c-11ea-84ff-56bac72585be.png)

上图是构建的时候，新的实例已经起来了，旧的实例一直没法关闭，超过10分钟了，也不知道要看哪个平台组件的日志，最后尝试强制手动关闭，然后再启动才行。这个问题5.1.7时已存在，经常需要重启计算节点才行。

【部署环境】
- Rainbond版本: [Rainbond grctl v5.1.9-release-32cc2ba-2019-12-13-09]
- 操作系统类型和版本:[CentOS Linux release 7.6.1810 (Core)]
- 离线部署/网络开放：[离线部署]

**Comment by barnettZQG** [comment]
@laoliao0806  看运行实例节点docker的日志和kubelet日志

**Comment by laoliao0806** [comment]
[docker.log](https://github.com/goodrain/rainbond/files/4024530/docker.log)
[kubelet.log](https://github.com/goodrain/rainbond/files/4024531/kubelet.log)

@barnettZQG 以上是实例节点的docker日志和kubelet日志，不知大佬是否有时间帮忙分析一下，这个问题困扰了挺久的，以为升级了好了，结果还是存在

**Comment by barnettZQG** [comment]
请升级V5.1最新版本。
