### ISSUE TITLE
install manage node err

### ISSUE THREAD

**Issue by haoren1ge** [goodrain/rainbond#62]
--- will install manage node. --- 
Start install init ...
manage01:
----------
          ID: key_build
    Function: cmd.run
        Name: ssh-keygen -t rsa -f ~/.ssh/id_rsa -P ""
      Result: False
     Comment: Command "ssh-keygen -t rsa -f ~/.ssh/id_rsa -P """ run
     Started: 10:54:43.283765
    Duration: 380.987 ms
     Changes:   
              ----------
              pid:
                  7112
              retcode:
                  1
              stderr:
                  Saving key "~/.ssh/id_rsa" failed: No such file or directory
              stdout:
                  Generating public/private rsa key pair.

Summary for manage01
------------
Succeeded: 0 (changed=1)
Failed:    1

**Comment by ysicing** [comment]
Please do it again. @haoren1ge
