### ISSUE TITLE
5.1.9 水平伸缩记录时间显示错乱

### ISSUE THREAD

**Issue by laoliao0806** [goodrain/rainbond#625]
【BUG描述】(非BUG请删除本行)
![image](https://user-images.githubusercontent.com/53854600/71872128-71896680-3156-11ea-9b23-99b0ea84d173.png)

如图，一会是6号一会是2号的，最上面几条应该是最新的，伸缩详情是能对上，但是时间不对，感觉就像是把之前相同内容的记录改了个状态显示到了最前面，但是时间没有更新，看着有些摸不着头脑

【部署环境】
- Rainbond版本(执行`grctl version`获取): [Rainbond grctl v5.1.9-release-32cc2ba-2019-12-13-09]
- 操作系统类型和版本:[CentOS Linux release 7.6.1810 (Core)]
- 离线部署/网络开放：[离线部署]

**Comment by barnettZQG** [comment]
@laoliao0806 按照更新时间倒序排列。

**Comment by laoliao0806** [comment]
@barnettZQG 截图中前3条应该是1月6日的，为何显示1月2日？

**Comment by barnettZQG** [comment]
应该是前端展示的是记录创建时间，而非更新时间，这个问题应该修复。

**Comment by laoliao0806** [comment]
👍🏻效率高

**Comment by barnettZQG** [comment]
参考升级指南 https://www.rainbond.com/docs/upgrade/5.1.9-5.1.10/
