### ISSUE TITLE
第三方服务下线后平台仍然会发送连接请求

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#627]
【BUG描述】第三方服务下线后平台仍然会发送连接请求

【部署环境】
- Rainbond版本(执行`grctl version`获取): 5.1.8
- 操作系统类型和版本:ubuntu16.04
- 离线部署/网络开放：online

添加第三方服务打开对内端口后下线该服务，平台仍会发送连接请求
rbd-worker日志
1111  23333 9092均为添加的第三方服务端口，在下线该服务乃至删除后平台仍尝试连接
![image](https://user-images.githubusercontent.com/50609288/71954992-00af8080-3222-11ea-95fe-c2694fc69f61.png)

**Comment by barnettZQG** [comment]
5.1.10版本对第三方组件健康检测和上下线机制进行调整，移除手动上/下线操作。需要手动下线需删除endpoint。

只要endpoint 存在 健康检测会一直工作。
