### ISSUE TITLE
5.1.9 实例deployment运行内存和实际docker使用内存对不上,不能自动伸缩

### ISSUE THREAD

**Issue by yszansx** [goodrain/rainbond#628]
【BUG描述】(非需求请删除本行)
 
管理后台显示实例deployment运行内存83.88% 实际查看docker使用内存才33%，然后我把同个deployment下的三个Containers 实际使用内存大小 和百分比统计了一下 。内存达不到1.6G。但是三个内存使用率直接累加是到83.88%
![image](https://user-images.githubusercontent.com/43443722/71957249-38212b80-3228-11ea-846f-3dcfadfe9325.png)

![image](https://user-images.githubusercontent.com/43443722/71957627-415ec800-3229-11ea-942e-54470bcccd2b.png)

![image](https://user-images.githubusercontent.com/43443722/71957392-9e0db300-3228-11ea-8303-cc570ea5d754.png)
![image](https://user-images.githubusercontent.com/43443722/71957556-052b6780-3229-11ea-8834-ddd4bf5a32c8.png)
![image](https://user-images.githubusercontent.com/43443722/71957602-25f3bd00-3229-11ea-89f5-c11840374c18.png)

【部署环境】
- Rainbond版本(执行`grctl version`获取): v5.1.9-release-32cc2ba-2019-12-13-09
- 操作系统类型和版本:ubuntu16.04
- 离线部署/网络开放：私有化高可用部署

**Comment by yszansx** [comment]
导致后台设置自动伸缩的时候提示内存使用率不到80% 平台却显示已经用了88%甚至是99%

**Comment by yszansx** [comment]
还有一个问题，开启自动伸缩后 修改不了已经设置的规则。比如设置内存使用率80%  ，既不能删除这条规则，也不能修改这条规则为cpu使用率80%

**Comment by barnettZQG** [comment]
![image](https://user-images.githubusercontent.com/18493394/71977511-ee4e3a80-3253-11ea-8908-33fbd45c00e9.png)
截图所示红框分别表示删除、修改、新增 @yszansx

**Comment by yszansx** [comment]
@barnettZQG 控制台使用率显示不正确的怎么处理呀？

**Comment by panda-zxs** [comment]
关于内存使用率问题，为获取容器使用内存量时使用的监控指标有问题导致，现在修改为container_memory_rss统计使用量，详见pr #637

**Comment by panda-zxs** [comment]
container_memory_usage_bytes 与container_memory_rss关系：
`container_memory_usage_bytes == container_memory_rss + container_memory_cache + container_memory_swap + kernel memory`

container_memory_rss	RSS内存，即常驻内存集（Resident Set Size），是分配给进程使用实际物理内存，而不是磁盘上缓存的虚拟内存。RSS内存包括所有分配的栈内存和堆内存，以及加载到物理内存中的共享库占用的内存空间，但不包括进入交换分区的内存。

container_memory_usage_bytes 当前使用的内存量，包括所有使用的内存，不管有没有被访问。
container_memory_cache	高速缓存（cache）的使用量。cache是位于CPU与主内存间的一种容量较小但速度很高的存储器，是为了提高cpu和内存之间的数据交换速度而设计的。
container_memory_swap	虚拟内存使用量。虚拟内存（swap）指的是用磁盘来模拟内存使用。当物理内存快要使用完或者达到一定比例，就可以把部分不用的内存数据交换到硬盘保存，需要使用时再调入物理内存
