### ISSUE TITLE
maven多模块构建报错

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#629]
【需求描述】(非需求请删除本行)
 
【BUG描述】(非BUG请删除本行)

【部署环境】
- Rainbond版本(执行`grctl version`获取): 5.1.8
- 操作系统类型和版本:ubuntu16.04
- 离线部署/网络开放：online

检测源通过后点击构建会出现如下报错
![image](https://user-images.githubusercontent.com/50609288/71966491-aa037000-323c-11ea-9fd7-7051a598a78b.png)

![image](https://user-images.githubusercontent.com/50609288/71966508-b687c880-323c-11ea-858a-401c907c2097.png)

![image](https://user-images.githubusercontent.com/50609288/71966279-424d2500-323c-11ea-92c8-711514a62f4d.png)

出现报错后在应用中会出现一个相同的服务，点进去每点击构建一次即出现一个相同应用，无法构建

![image](https://user-images.githubusercontent.com/50609288/71966459-99eb9080-323c-11ea-9711-e4e16ff3a436.png)

日志如下
app-ui日志
![image](https://user-images.githubusercontent.com/50609288/71966672-fbabfa80-323c-11ea-9afc-53c688b4b876.png)
rbd-api日志
![image](https://user-images.githubusercontent.com/50609288/71966706-0bc3da00-323d-11ea-81c3-eafc993c5de9.png)

![image](https://user-images.githubusercontent.com/50609288/71966753-239b5e00-323d-11ea-95ea-7ca4e29efbc8.png)

**Comment by dazuimao1990** [comment]
这个问题得以手动解决，问题的根本原因在于用户的代码里，规定有 Procfile 文件，这和rbd-api日志中添加环境变量 
```
add env BUILD_PROCFILE
```
有冲突，手动的解决方式是给这 Procfile 改名。但是这是产品需要改进的点，一旦发现多模块构建项目的代码中有 Procfile ，就需要忽略之，使用系统自动生成的 BUILD_PROCFILE
