### ISSUE TITLE
升级到 5.1.10 版本后，第三方服务出现异常影响到了 rbd-worker

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#633]
【BUG描述】(非BUG请删除本行)

【部署环境】
- Rainbond版本(执行`grctl version`获取): [ v5.1.10 ]
- 操作系统类型和版本:[请填写此处]
- 离线部署/网络开放：[请填写此处]

5.1.9升级到5.1.10后报错，查看rbd-worker 后发现提示原来平台已经创建的第三方服务端口异常。

具体报错信息请关注 https://t.goodrain.com/t/topic/1325

**Comment by barnettZQG** [comment]
这是版本正式发布前升级的导致。
执行下述命令再次升级worker组件：
```
grclis upgrade rbd-worker
```
