### ISSUE TITLE
5.1.9 希望能增加批量绑定域名功能

### ISSUE THREAD

**Issue by laoliao0806** [goodrain/rainbond#634]
【需求描述】
我们的业务经常需要绑定上百个域名，一个一个来实在太没效率，是否有可能增加批量绑定的功能？

【部署环境】
- Rainbond版本: [Rainbond grctl v5.1.9-release-32cc2ba-2019-12-13-09]
- 操作系统类型和版本:[CentOS Linux release 7.6.1810 (Core)]
- 离线部署/网络开放：[离线部署]

**Comment by barnettZQG** [comment]
@laoliao0806 建议使用泛域名。如果是多个同类域名绑定到同一个应用上。

**Comment by laoliao0806** [comment]
@barnettZQG 
我说的并不是绑定子域名，而是顶级域名，所以泛域名并不适用。如aaa.com,bbb.com,ccc.com这样的，成百上千个。

另外发现在组件的端口页面是无法添加泛域名的，只能在访问控制页面中添加，而且添加泛域名后，点击访问的时候跳转的直接是*.xxx.com这样的地址，不太合理，这样的地址肯定是不能访问的，跳到xxx.com都好些

**Comment by barnettZQG** [comment]
@laoliao0806 
关于域名跳转问题对于泛域名确实没有做兼容，因为泛域名没有对应一个实际的域名。这个交给用户去决策即可。因为直接访问 xxx.com也不合理。

你们添加了500个域名会遇到域名不生效问题这个我们可以做个专项测试。

**Comment by laoliao0806** [comment]
@barnettZQG 好的，感谢！关于大量域名的问题，我有更新新的测试结果 #635

**Comment by barnettZQG** [comment]
批量添加域名应该不是一个通用的需求，如果你有此场景建议通过api与rainbond对接实现域名添加的批量化。我先关闭这个issues。

**Comment by laoliao0806** [comment]
@barnettZQG 
rainbond有开放api了？是否有相关文档呢？
还是说这是企业版的功能？
