### ISSUE TITLE
5.1.9 添加数百个域名后gateway崩溃

### ISSUE THREAD

**Issue by laoliao0806** [goodrain/rainbond#635]
【BUG描述】
![image](https://user-images.githubusercontent.com/53854600/72141073-144b1a80-33cd-11ea-8594-f4f2edec2dcc.png)

执行`journalctl -fu rbd-gateway`后，日志如上图所示，重启rbd-gateway服务无效，重启gateway节点服务器无效，将添加的域名删除后依然无效，访问绑定的所有域名均返回502错误。

进入rbd-gateway容器查看default_servers.conf文件，发现文件大小一直在变化，忽大忽小，里面的内容也一直在变化

请问这个情况应该如何处理才能恢复😭？

【部署环境】
- Rainbond版本: [Rainbond grctl v5.1.9-release-32cc2ba-2019-12-13-09]
- 操作系统类型和版本:[CentOS Linux release 7.6.1810 (Core)]
- 离线部署/网络开放：[离线部署]

**Comment by GLYASAI** [comment]
我想确认一下, 所有域名都用不了了吗?  还有一部分用不了了.

**Comment by laoliao0806** [comment]
@GLYASAI 你好，是所有域名都用不了，5台gateway服务器的日志都一样。容器内执行`nginx -t`是正常的返回。添加的域名大概在300个左右。

**Comment by GLYASAI** [comment]
麻烦使用命令 `curl http://127.0.0.1:18080/config/backends` 提供下 endpoints 信息

**Comment by laoliao0806** [comment]
@GLYASAI 
你好，返回信息如下：
```bash
/run/nginx/conf/http/default # curl http://127.0.0.1:18080/config/backends
[{"name":"lang","endpoints":[{"address":"172.31.23.127","port":"8081","weight":1},{"address":"172.31.34.184","port":"8081","weight":1},{"address":"172.31.8.116","port":"8081","weight":1}],"sessionAffinityConfig":{"name":"","cookieSessionAffinity":{"name":"","hash":""}},"load-balance":"round_robin"},{"name":"maven","endpoints":[{"address":"172.31.23.127","port":"8081","weight":1},{"address":"172.31.34.184","port":"8081","weight":1},{"address":"172.31.8.116","port":"8081","weight":1}],"sessionAffinityConfig":{"name":"","cookieSessionAffinity":{"name":"","hash":""}},"load-balance":"round_robin"},{"name":"registry","endpoints":[{"address":"172.31.23.127","port":"5000","weight":1},{"address":"172.31.34.184","port":"5000","weight":1},{"address":"172.31.8.116","port":"5000","weight":1}],"sessionAffinityConfig":{"name":"","cookieSessionAffinity":{"name":"","hash":""}},"upstream-hash-by":"$remote_addr","load-balance":"round_robin"}]
```

**Comment by GLYASAI** [comment]
这里一个endpoints都没有了, 是不是所有的组件都停止了?

**Comment by GLYASAI** [comment]
这个问题比较复杂, 建议加我们的微信群, 方便沟通. 

加入方式:
在社区 `https://t.goodrain.com/` 的底部, 右方. 有我们工作人员的联系方式, 他会负责加你进群.

**Comment by laoliao0806** [comment]
@GLYASAI 我人不在国内，不太方便上微信，如果没有较简单的解决办法，我只能拆了集群重新搭一个了😂

**Comment by laoliao0806** [comment]
目前gateway已自行恢复访问，配置文件大小也没有再变化，但是rbd-gateway日志还是和上面截图一样一直输出，是否etcd中还存在已删除的内容，我重启什么组件或者重启哪个节点服务器能够解决么？

**Comment by GLYASAI** [comment]
截图中的警告是不影响正常使用的。这个日志是不应该打印的，是多余的。

**Comment by laoliao0806** [comment]
@GLYASAI 
我刚才新开了台机器重新装了个5.1.10版本的来测试，只跑了一个nginx组件，只添加了1个域名，也会一直打印这个日志。
你的意思是说，我的gateway现在处于正常状态，只是日志输出了多余的内容，可能会在未来的版本中把这个输出给干掉？

**Comment by GLYASAI** [comment]
嗯嗯, 是这个意思

**Comment by laoliao0806** [comment]
好的，那我就不用重新建集群了，继续使用，不过添加大量域名导致崩溃这个问题还得辛苦大佬们看看了，感谢！

**Comment by laoliao0806** [comment]
@GLYASAI 还是不行，现在生产环境已经升级到5.1.10，据测试，添加230多个域名的时候，网关能够正常访问，只是有较长时间的延迟才能访问到后面添加的域名，延迟时间以小时为单位；当添加的域名达到400-500个的时候，网关开始全部返回502，日志依然是之前截图那个输出，进入容器执行`curl http://127.0.0.1:18080/config/backends`没有endpoints返回，必须删除之前添加的域名，或者关闭这个组件的对外访问，然后等待几分钟，才能恢复访问。

这个问题比较严重，我们每个组件都可能需要绑定上千个域名（顶级域名，非子域名），而组件会根据需求不断增加，最后绑定的域名可能会在万级以上，现在生产环境都跑在rainbond上，希望能引起各位大佬重视。

目前来说，rainbond各方面功能都能较好的满足我们的，唯独域名和证书（指的是自动更新）这块比较尴尬，现在能想到的办法就是再开一台服务器，用来绑定域名并反代到rainbond中绑定的域名，不过这样就和当初选用rainbond时的初衷想违背了。

下图是达到500个域名时，访问报502错误时的日志：
![image](https://user-images.githubusercontent.com/53854600/72228868-6797b580-35e5-11ea-9e50-54ce5f9be338.png)

**Comment by barnettZQG** [comment]
@laoliao0806 这个问题我们会重点关注

**Comment by laoliao0806** [comment]
@barnettZQG 好的，感谢！

**Comment by barnettZQG** [comment]
@laoliao0806 关于这个问题做如下修改：
1. 增加nginx lua共享内存到128MB 并支持配置参数，解决由于内存限制导致endpoints更新失败的问题。
2. 移除过去的循环校验nginx配置文件，改为前置对配置内容进行规则校验。解决域名量大以后生效缓慢问题。
3. 增加更新频率限制，防止nginx频繁reload配置。

下面给出最新版本镜像，可以尝试更新组件并测试是否解决问题，然后给我们反馈：
```
docker pull rainbond/rbd-gateway:V5.1-dev
docker tag rainbond/rbd-gateway:V5.1-dev goodrain.me/rbd-gateway:v5.1.10-release
docker push goodrain.me/rbd-gateway:v5.1.10-release
# 所有网关节点
systemctl restart rbd-gateway
```

**Comment by laoliao0806** [comment]
@barnettZQG 好的，今天将进行测试，然后反馈

**Comment by laoliao0806** [comment]
@barnettZQG 以下是今天的测试反馈：

测试方式：新开干净的服务器，全新单节点安装5.1.10版本，各组件正常启动后，按上述方法拉取最新gateway镜像并重启网关组件，进入rainbond控制台从Docker镜像创建组件(nginx:alpine)，默认域名访问正常，开始添加域名。

**第一批**域名共226个，每3秒左右添加1个，大概12分钟添加完成，完全生效耗时2小时左右（以最后一个域名可访问为准），全部生效后网关无异常。

**第二批**域名共214个，每3秒左右添加1个，大概11分钟添加完成，完全生效耗时5小时，全部生效后网关无异常。**第二批域名开始后，曾出现长时间不更新的情况**，见下图（_中间有一些域名未生效时访问异常的日志省略掉了_）：
![image](https://user-images.githubusercontent.com/53854600/72421023-b2b6f180-37ba-11ea-8cf9-c9e0d1375de9.png)
![image](https://user-images.githubusercontent.com/53854600/72421098-d8dc9180-37ba-11ea-8c64-9bf10f4cd06f.png)
![image](https://user-images.githubusercontent.com/53854600/72420902-76839100-37ba-11ea-94b1-a97f8b3563dd.png)


结论：
1. 增加了内存配置后，不再出现endpoints为空的问题；

2. 生效缓慢问题仍未解决，生效时间以小时为单位计算；

3. 增加了更新频率限制后，生效时间似乎更慢，大概3分钟更新一次，而每次只生效了一个域名。

建议：
是否可能改为：当添加域名很多时（以前后两条添加时间做判断），域名进入待绑定缓存，当到时间更新的时候，从缓存中取出并批量更新域名，reload，等待下一次更新。

**Comment by barnettZQG** [comment]
@laoliao0806 
提供一下你的测试用例。
我们的基础测试用例是在一个组件上绑定了500个域名，秒级生效，后续添加域名也是秒级生效。

**Comment by laoliao0806** [comment]
@laoliao0806 
抱歉昨天比较忙没有回复，我们的测试方式是写了个脚本，模拟手动添加，每隔3秒添加一个，一轮跑200个左右，都是绑定到同一个组件，如果需要的话可以把脚本发到这里。

附件中是我们用于测试的域名，非真实域名，需要本机修改hosts解析到rainbond上验证是否可用。
[domains.txt](https://github.com/goodrain/rainbond/files/4075274/domains.txt)

**Comment by barnettZQG** [comment]
@laoliao0806 
我们会基于这种频繁添加大量域名的场景进行针对性测试和优化。

**Comment by barnettZQG** [comment]
@laoliao0806
经我们测试确实发现在连续逐次为一个组件添加大量域名造成后续添加的域名生效时间很长，这里的主要原因不在网关组件，而在于策略的生效流程的资源控制。我们对所有网关策略生效（增、删、改）的控制链路进行了优化，并基于下面的用例进行测试，结果如下：
测试用例代码：https://github.com/goodrain/rainbond/blob/V5.1/api/handler/gateway_action_test.go#L63
逻辑说明：每隔2秒中为一个组件添加一个http访问策略，并获取从添加到能够访问的间隔时间。
测试环境：2Core 4GB
测试结果：
* 1-200 个域名平均生效时间为 1s
* 200-500个域名平均生效时间为 4s

你可以通过以下方式进行相关组件升级后使用你的测试用例进行测试。
```
docker pull rainbond/rbd-gateway:V5.1-dev
docker tag rainbond/rbd-gateway:V5.1-dev goodrain.me/rbd-gateway:v5.1.10-release
docker push goodrain.me/rbd-gateway:v5.1.10-release

docker pull rainbond/rbd-worker:V5.1-dev
docker tag rainbond/rbd-worker:V5.1-dev goodrain.me/rbd-worker:v5.1.10-release
docker push goodrain.me/rbd-worker:v5.1.10-release

docker pull rainbond/rbd-api:V5.1-dev
docker tag rainbond/rbd-api:V5.1-dev goodrain.me/rbd-api:v5.1.10-release
docker push goodrain.me/rbd-api:v5.1.10-release

# 所有网关节点
docker pull goodrain.me/rbd-gateway:v5.1.10-release
systemctl restart rbd-gateway

# 所有管理节点
docker pull goodrain.me/rbd-api:v5.1.10-release
systemctl restart rbd-api
docker pull goodrain.me/rbd-worker:v5.1.10-release
systemctl restart rbd-worker
```

**Comment by laoliao0806** [comment]
@barnettZQG 
好的，我们测试一下，辛苦了！

**Comment by barnettZQG** [comment]
@laoliao0806 最新的版本是否解决了你的问题？

**Comment by laoliao0806** [comment]
@barnettZQG 经生产环境测试，该问题已解决！

**Comment by barnettZQG** [comment]
@laoliao0806 感谢提供问题，我将关闭这个Issues。
