### ISSUE TITLE
应用正常运行，但无法获取日志

### ISSUE THREAD

**Issue by 1909490139** [goodrain/rainbond#636]
【BUG描述】
应用正常运行，但在日志界面不显示日志

【部署环境】
- Rainbond版本: [5.1.9]
- 操作系统类型和版本:[centos7.4]
- 离线部署/网络开放：[离线部署]

![401579163165_ pic_hd](https://user-images.githubusercontent.com/55137659/72510556-9d0dfe80-3884-11ea-8c42-4a97fbfcbb1a.jpg)
![541579165016_ pic_hd](https://user-images.githubusercontent.com/55137659/72510624-bca52700-3884-11ea-87dc-265d6d0d33b3.jpg)
![451579163385_ pic_hd](https://user-images.githubusercontent.com/55137659/72510646-c62e8f00-3884-11ea-8f5f-385ae8b3a8a8.jpg)
![481579164068_ pic_hd](https://user-images.githubusercontent.com/55137659/72510664-cc247000-3884-11ea-9f88-6803ae5cd3e6.jpg)
![501579164224_ pic_hd](https://user-images.githubusercontent.com/55137659/72510673-d21a5100-3884-11ea-8eac-24ec36cddd63.jpg)

**Comment by barnettZQG** [comment]
@1909490139 该问题是否能够复现？
