### ISSUE TITLE
Web page show "your application is preparing", after app was created and run normally for about 1 minutes

### ISSUE THREAD

**Issue by mchtech** [goodrain/rainbond#64]
>
> bug
> 

**Description**
When app was just created and run, it was normal. But after about 1 minute, page show "your application is preparing".

**How to reproduce it (as minimally and precisely as possible)**:
Create an example app(2048) and keep refreshing the main page of the app.

**Environment**:
- rainbond version:3.5
- Cloud provider or hardware configuration:qemu-kvm
- OS (e.g. from /etc/os-release):centos 7.4
- Kernel (e.g. `uname -a`):3.10.0-693.21.1.el7.x86_64
- docker image version:1.12.6
- grctl version:0.0.0
- Others:

**Comment by ysicing** [comment]
What is the application state? running？
