### ISSUE TITLE
网关节点删除后，在添加tcp访问策略时仍有该节点信息

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#641]
【BUG描述】网关节点已删除，在添加tcp访问策略时，节点信息仍存在于列表中

【部署环境】
- Rainbond版本(执行`grctl version`获取): 5.1.10
- 操作系统类型和版本：ubuntu16.04
- 离线部署/网络开放：online

**Comment by fanyangyang** [comment]
网关节点删除需要保证已删除节点上的rbd-gateway网关组件停止运行，
网关IP的的注册会在网关组件停止10s内自动回收，添加TCP策略时不会再出现该网关IP

单纯的通过停掉网关节点的node服务并删除网关节点是不会影响网关节点IP的keepalive的

问题未复现，我将关闭该issue

**Comment by Aaron-23** [comment]
网管节点在删除之前必须手动停掉rbd-gateway组件？ 在此网管节点上没有keepalived服务

**Comment by fanyangyang** [comment]
删除节点意味着该节点不可用，不止是node组件不能用，所有的组件都不能用

**Comment by Aaron-23** [comment]
解决方案：删除节点，需要将该节点上的网关服务停掉
网关组件自己维护自己节点的注册和发现，只要该组件一直运行着，此数据就一直存在。
