### ISSUE TITLE
"系统异常" after server was restarted

### ISSUE THREAD

**Issue by mchtech** [goodrain/rainbond#65]
>
> bug
> 

**Description**
After server was restarted:
1. "系统异常"
2. "团队成员" is 0 
3. application status are unknown

**What happened**:
1. rbd-repo:3.5 kept restarting
2. run "docker-compose down && docker-compose up -d"  cannot resolve the problem

**How to reproduce it (as minimally and precisely as possible)**:
restart server

**Environment**:
- rainbond version:3.5
- Cloud provider or hardware configuration:qemu-kvm
- OS (e.g. from /etc/os-release):centos 7.4
- Kernel (e.g. `uname -a`):3.10.0-693.21.1.el7.x86_64
- docker image version:1.12.6
- grctl version:0.0.0
- Others:

**Comment by ysicing** [comment]
rbd-repo restarting, just run
```
dc-compose stop rbd-repo
cclear
dc-compose up -d
```
Check your system DNS to ensure that DNS(`/etc/resolv.conf`) is your management node IP.

**Comment by ysicing** [comment]
Thanks @mchtech .  
I have planned to rebuild this plugin.This issue will be resolved in 3.5.1

**Comment by ysicing** [comment]
@mchtech  This issue has resolved.
