### ISSUE TITLE
关于ctop命令

### ISSUE THREAD

**Issue by laoliao0806** [goodrain/rainbond#651]
![image](https://user-images.githubusercontent.com/53854600/73724361-1c953c00-4766-11ea-8142-86aaf3b7edf2.png)

请教一下，图中的CPU使用率，100%是指使用了1个内核还是指CPU总数的百分比？

**Comment by barnettZQG** [comment]
一般指占用的1核CPU 100%的计算周期。

**Comment by laoliao0806** [comment]
@barnettZQG 
谢谢解答。

那比如当前我每个实例分配了2个CPU，这里显示的166%该怎么理解？占用了2个内核的166%的计算周期？或者是每个内核占用了80%的计算周期？

当分配了1个CPU的时候，166%又该怎么理解呢？

**Comment by barnettZQG** [comment]
最大占用量与当前宿主机的总共CPU核数有关，CPU目前不是做的强限制，做的是共享比例。比如宿主机4Core，某组件实例分配2Core，理论上最大占用200%如果其他200%被其他实例占用了。如果没有，它可以占用到400%。

**Comment by laoliao0806** [comment]
@barnettZQG 了解了，感谢！
