### ISSUE TITLE
服务实时性能分析插件URL排行没有数据

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#656]
【BUG描述】

对Rainbond平台上的业务进行集中压测一段时间后，发现业务绑定的服务实时性能分析插件中，5分钟URL排行没有数据了。
![image](https://user-images.githubusercontent.com/33855684/73905574-b7168c00-48da-11ea-9e68-fc7d1ea0961f.png)
经过排查，发现管理节点上的 rbd-eventlog 组件发生过自动重启。
手动重启该服务后，插件数据恢复正常。

推断是集中压测时，插件产生的数据太多，导致eventlog组件发生了崩溃。

【部署环境】
- Rainbond版本(执行`grctl version`获取): v5.1.10-release
- 操作系统类型和版本:Ubuntu1604
- 离线部署/网络开放：离线部署

-------------------------以下内容请阅读后删除-----------------------------
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，还可以参阅[Rainbond用户社区](https://t.goodrain.com/)，[Rainbond用户文档](https://www.rainbond.com/docs/)或添加微信群与我们实时沟通；

**Comment by barnettZQG** [comment]
该问题已在5.1.10最新版本中修复。
