### ISSUE TITLE
应用发布到应用市场后（发布范围为公司），在内部市场执行删除操作，无法删除

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#661]
【BUG描述】应用发布到应用市场后（发布范围为公司），在内部市场执行删除操作，无法删除

【部署环境】
- Rainbond版本(执行`grctl version`获取):   console线上环境

删除时提示
![image](https://user-images.githubusercontent.com/50609288/74132439-88bde700-4c21-11ea-8cbc-9753900a395a.png)

但此用户已是企业管理员
![image](https://user-images.githubusercontent.com/50609288/74132511-b0ad4a80-4c21-11ea-9abb-5b193c48eee1.png)

**Comment by panda-zxs** [comment]
该bug是由于一个企业有多个id导致的

**Comment by barnettZQG** [comment]
我将关闭这个问题，多企业故障将在5.2版本中优化。开源版本无此问题
