### ISSUE TITLE
插件更新内存后，会影响其它服务组件的组件内存

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#662]
【BUG描述】

当我更新了某个服务组件A上安装的插件的内存之后，发现新建的其它组件的内存不会使用默认值，而是会使用服务组件A插件的内存。同样的，对于其它已安装的插件内存也会有影响。

【部署环境】
- Rainbond版本(执行`grctl version`获取): v5.1.10-release
- 操作系统类型和版本:Ubuntu1604
- 离线部署/网络开放：Open

**Comment by fanyangyang** [comment]
这个其他组件不会使用默认值的表现特征是：控制台插件管理中，插件的内存显示的不是默认值
还是实际插件容器的内存不是默认值？
@dazuimao1990

**Comment by dazuimao1990** [comment]
实际使用，和显示的值，都不再是默认值
