### ISSUE TITLE
在控制台删除某个组件的一个访问域名后，影响了其他的访问策略

### ISSUE THREAD

**Issue by lxm** [goodrain/rainbond#664]
【BUG描述】在控制台删除了某一个应用的https域名访问策略后，此组件的其他https域名也无法访问

组件A有4条访问策略
分别为 
http://a.abc.com 
http://b.abc.com
https://a.abc.com
https://b.abc.com

删掉其中任何一条https策略会导致另一条https策略失效

【部署环境】
- Rainbond版本(执行`grctl version`获取): [v5.1.10-release-6ab0b92-2020-01-09-07]
- 操作系统类型和版本:[CentOS 7]
- 离线部署/网络开放：[网络开放]

**Comment by Aaron-23** [comment]
5.1.11版本已修复
