### ISSUE TITLE
从源码创建应用时，如果填写了子目录，将会构建失败

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#683]
【BUG描述】源码构建时，如果填写了子目录，将会构建失败

【部署环境】
- Rainbond版本(执行`grctl version`获取):  V5.2版本
- 操作系统类型和版本: ubuntu16.04
- 离线部署/网络开放：开放

代码地址：https://github.com/goodrain-apps/percona-mysql.git     

![image](https://user-images.githubusercontent.com/50609288/74905993-a42bad80-53ea-11ea-8b89-84d62bf599e9.png)

![image](https://user-images.githubusercontent.com/50609288/74906126-02f12700-53eb-11ea-8f80-6af712c9d363.png)

**Comment by fanyangyang** [comment]
已修复，我将关闭该issue
