### ISSUE TITLE
rainbond-node组件持续占用CPU

### ISSUE THREAD

**Issue by fanyangyang** [goodrain/rainbond#687]
【BUG描述】

rainbond-node组件CPU占用率高达100%，且持续占用

![image](https://user-images.githubusercontent.com/14025359/75157829-e6891d80-574f-11ea-9be6-de7cda94ea98.png)

【部署环境】
- Rainbond版本(执行`grctl version`获取): v5.2.0-dev
- 操作系统类型和版本:阿里云 centos7
- 离线部署/网络开放：[请填写此处]

**Comment by barnettZQG** [comment]
已于5.2.0-beta2修复。
