### ISSUE TITLE
构建源不显示识别出的语言

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#688]
【BUG描述】
![image](https://user-images.githubusercontent.com/33855684/75208447-a741e780-57b6-11ea-8a9f-969eb55e2a6e.png)

如图，构建语音不显示；
基于镜像构建的应用，根据开源用户反馈，可能会有命令不显示的BUG。

【部署环境】
- Rainbond版本(执行`grctl version`获取): v5.1.10
- 操作系统类型和版本:ubuntu1604
- 离线部署/网络开放：公有云

**Comment by zsl1549** [comment]
@dazuimao1990  已修复 https://github.com/goodrain/rainbond-ui/pull/365
