### ISSUE TITLE
5.2版本安装数据库连接错误

### ISSUE THREAD

**Issue by shenfh** [goodrain/rainbond#689]
【部署环境】

kubectl logs rbd-worker-kw2cv -n rbd-system
error: Error 1045: Access denied for user 'write'@'172.20.0.1' (using password: YES)

kubectl logs rbd-chaos-wvdmb -n rbd-system
error: Error 1045: Access denied for user 'write'@'172.20.0.1' (using password: YES)

 kubectl logs rbd-app-ui-7cfb548cf4-x49hf -n rbd-system
ERROR 1045 (28000): Access denied for user 'write'@'172.20.0.1' (using password: YES)
Database not ready

**Comment by fanyangyang** [comment]
关联issue ：https://github.com/goodrain/rainbond-operator/issues/41

**Comment by GLYASAI** [comment]
请问有没有进行卸载重装呢? 可能是没卸载干净, 导致新创建的数据库的账号密码不对.

**Comment by fanyangyang** [comment]
@shenfh 临时解决方案
删除数据库组件，让数据库重新启动
```
kubectl del statefulset rbd-db -n rbd-system 
```
删除旧的数据库数据
```
rm -rf /opt/rainbond/data/db
```

待数据库成功启动后再删除其他依赖数据库的组件，让其重新启动就可以绑定新的数据库密码
```
kubectl delete ds rbd-worker rbd-chaos rbd-api  -n rbd-system
kubectl delete deployment rbd-app-ui -n rbd-system
```

数据库启动成功的标识是对应的

```
NAME                          READY   STATUS    RESTARTS   AGE
rbd-db-0                      2/2     Running   0          5d
```
需注意：READY=2

**Comment by shenfh** [comment]
可以了
