### ISSUE TITLE
5.1.10 经常无法从ui界面进入容器

### ISSUE THREAD

**Issue by laoliao0806** [goodrain/rainbond#698]
【BUG描述】
![image](https://user-images.githubusercontent.com/53854600/75875900-91d05b80-5e4f-11ea-8584-972ed0f58dec.png)

如题，不知是哪个组件的问题？

【部署环境】
- Rainbond版本(执行`grctl version`获取): [Rainbond grctl v5.1.10-release-f4c675d-2020-01-09-13]
- 操作系统类型和版本:[CentOS Linux release 7.6.1810 (Core)]
- 离线部署/网络开放：[离线部署]

**Comment by barnettZQG** [comment]
节点ID不能解析导致，正常情况下节点ID是写入管理节点hosts文件，rbd-dns也支持解析。
如果有异常需要确认管理节点宿主机hosts文件，kube-apiserver容器内hosts文件是否都正常能够解析。如kube-apiserver容器与宿主机不一致，可以重启kube-apiserver容器。

**Comment by laoliao0806** [comment]
目前的情况是：
宿主机和kube-apiserver容器内都没有截图中节点ID，但是宿主机可以解析节点，kube-apiserver容器内无法解析节点，重启kube-apiserver并无效果。

意思是我要把所有节点都手动写到宿主机的hosts中？这样每增加一个计算节点，都需要修改一下管理节点的hosts文件？

@barnettZQG

**Comment by barnettZQG** [comment]
@laoliao0806 不需要。正常情况下安装时hosts文件会自动写入，但是hosts文件只是作为备选。节点id的解析主要是rbd-dns的职责，你说的宿主机可以解析节点就是因为宿主机dns的配置使用的是rbd-dns。是否kube-apiserver容器内的dns设置不正确？

**Comment by laoliao0806** [comment]
@barnettZQG 
![image](https://user-images.githubusercontent.com/53854600/76154931-b5312a00-611f-11ea-9a7d-b118438383c2.png)

从上图可以看出，红框中的是在kube-apiserver容器内的情况，红框外的是宿主机的情况，2者DNS设置是相同的，但是容器中却无法解析节点ID。
