### ISSUE TITLE
CentOS7.3安装成功之后，无法部署官方示例

### ISSUE THREAD

**Issue by aidisheng** [goodrain/rainbond#7]
虚拟机，单节点，安装过程没有提示异常，可以访问7070端口，可以正常注册管理账号。但新增官方示例应用无法部署（从镜像、从源码两种途径都无法部署），提示“网络异常，请稍后再试”。
tail -f error.log:
2017-12-17 16:57:53 [ERROR] localhost.localdomain [get] /app/ui/www/views/ajax/service_actions.py:779 

 Unable to find the server at region.goodrain.me 

Traceback (most recent call last):
  File "/app/ui/www/views/ajax/service_actions.py 

", line 759, in get
    "enterprise_id": self.tenant.enterprise_id})
  File "/app/ui/www/apiclient/regionapi.py 

", line 614, in service_status
    res, body = self._post(url, self.default_headers, region=region, body=json.dumps(body))
  File "/app/ui/www/apiclient/baseclient.py 

", line 104, in _post
    response, content = self._request(url, 'POST', headers=headers, body=body, *args, **kwargs)
  File "/app/ui/goodrain_web/decorator.py 

", line 15, in wrapper
    ret = func(self, *args, **kwargs)
  File "/app/ui/www/apiclient/baseclient.py 

", line 67, in _request
    response, content = client.request(url, method, headers=headers, body=body)
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1278, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
ServerNotFoundError: Unable to find the server at region.goodrain.me 

**Environment**:
- rainbond version:
$ grctl -v
grctl version release-3.4-14.g622dc14
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 
$ cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core) 

- Kernel (e.g. `uname -a`):
Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

rsion:
[error.log](https://github.com/goodrain/rainbond/files/1565477/error.log)

![Uploading error2.png…]()
![Uploading rainbond.jpg…]()

**Comment by barnettZQG** [comment]
@aidisheng 
请提供一下主机DNS配置情况：
```
cat /etc/resolv.conf
ps -ef |grep dns
```

**Comment by ysicing** [comment]
此类无法找到`Unable to find the server at region.goodrain.me`解决方法
```
1.确定rbd-dns 状态是否是up
 dc-compose ps | grep rbd-dns
如果rbd-dns 一直重启中，检查53端口是否被其他程序占用
netstat -pantu | grep 53
关闭占用53端口的服务
2.排查系统dns配置文件
cat /etc/resolv.conf
dns配置是否为当前机器的ip
3.重启服务
dc-compose stop
cclear
dc-compose up -d
```
