### ISSUE TITLE
基于gitlib的源码持续构建未生效

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#716]
【BUG描述】基于gitlib的源码持续构建配置webhook后未生效

【部署环境】
- Rainbond版本(执行`grctl version`获取): 5.1.10
- 操作系统类型和版本: ubuntu 16.04
- 离线部署/网络开放：网络开放

基于[文档](https://www.rainbond.com/docs/user-manual/app-service-manage/auto-deploy/#%E9%95%9C%E5%83%8F%E4%BB%93%E5%BA%93%E8%87%AA%E5%8A%A8%E5%8C%96%E6%9E%84%E5%BB%BA%E8%AF%B4%E6%98%8E)在gitlib创建webhook后，提交代码未生效

![image](https://user-images.githubusercontent.com/50609288/77142503-42c72f00-6abb-11ea-8260-9f9b305fbc6a.png)
![image](https://user-images.githubusercontent.com/50609288/77142525-52df0e80-6abb-11ea-9370-0b68cfcabad5.png)
![image](https://user-images.githubusercontent.com/50609288/77142535-5d99a380-6abb-11ea-8285-22877492cc6a.png)
![image](https://user-images.githubusercontent.com/50609288/77142547-6be7bf80-6abb-11ea-892b-eba809ace3cb.png)

**Comment by barnettZQG** [comment]
@Aaron-23 http://console.goodrain.com 会被强转到https://console.goodrain.com，配置webhook时需要使用https://console.goodrain.com

**Comment by Aaron-23** [comment]
已知悉
