### ISSUE TITLE
有状态服务使用本地存储时无法通过ES_SELECTNODE变量指定运行在哪个节点

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#730]
【BUG描述】有状态服务使用本地存储时无法通过ES_SELECTNODE变量指定运行在哪个节点

【部署环境】
- Rainbond版本(执行`grctl version`获取): 5.1
- 操作系统类型和版本:ubuntu16.04
- 离线部署/网络开放：开放

-------------------------以下内容请阅读后删除-----------------------------
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，还可以参阅[Rainbond用户社区](https://t.goodrain.com/)，[Rainbond用户文档](https://www.rainbond.com/docs/)或添加微信群与我们实时沟通；

**Comment by barnettZQG** [comment]
设置的ES_SELECTNODE必须为 kubectl get node 所看到的节点NAME
