### ISSUE TITLE
关于组件伸缩Bug

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#733]
【BUG描述】 组件内存伸缩至8GB，使用kubectl describe pod命令查看Limits memry值为512M，操作界面也并未显示伸缩失败，手动重启后伸缩生效

【部署环境】
- Rainbond版本(执行`grctl version`获取):5.1.10
- 操作系统类型和版本:ubuntu16.04
- 离线部署/网络开放：开放

![image](https://user-images.githubusercontent.com/50609288/79111466-2a42ef80-7daf-11ea-97ab-47a85fd2e969.png)

**Comment by barnettZQG** [comment]
既然重启后生效，考虑是伸缩操作时由于某种运行环境原因导致扩容异步任务未执行。但8g是可以正常设置
