### ISSUE TITLE
支持configmap

### ISSUE THREAD

**Issue by lxm** [goodrain/rainbond#735]
【需求描述】
 应用中存在较多公用一组环境变量和配置的场景，目前使用第三方服务的形式来共享环境变量，必须添加一个对内服务端口才能使用，会引入不必要的问题

建议添加configmap类型，在应用内进行共享，使用类似依赖的形式进行加载

**Comment by barnettZQG** [comment]
计划支持变量组。
变量组资源将属于应用，应用下所有组件都可以共享此变量组的变量。应用也可以共享其他应用的变量组，但不能跨团队进行依赖。

变量组中的变量将采用yaml的方式实现批量的添加和管理。

> 变量组的变量优先级低于组件本身的环境变量或连接信息变量。因此在组件中可实现部分变量的自定义。

**Comment by barnettZQG** [comment]
Release in 5.3.0
