### ISSUE TITLE
5.2 版安装失败：rbd-gateway 容器无法启动

### ISSUE THREAD

**Issue by yaozijian** [goodrain/rainbond#751]
【BUG描述】
5.2 版安装失败，rbd-gateway 容器无法启动。已经反复尝试过多次，都是相同的问题。rbd-gateway 容器中的错误日志为：
init openresty config failure nginx config check error
Fail to start GWController nginx config check error

尝试过
1 修改 gateway 镜像中 /run/nginxtmp/nginx.tmpl 之后，docker build 为新镜像
2 用 kubectl set image daemonset rbd-gateway 设置为使用新镜像

结果还是失败，即使把配置文件改得只剩两三行，最后还是出相同的错误。
（错误日志给出的nginx配置文件主体就是修改过的、替换后的nginx.tmpl，说明修改生效了）。所以可能不是配置文件错误，可能是其他的问题，如lua配置不正确？

【部署环境】
- Rainbond版本(执行`grctl version`获取): 5.2 版，不是用 5.1 版的安装方法安装的，是用Web界面启动安装的，总是在第2步，等待5个容器启动时，只有 4 个启动完成，而rbd-gateway 容器很长时间不能启动完成。
- 操作系统类型和版本: 64 位 CentOS 7.7 版
- 离线部署/网络开放：5.2 版，在线部署。

**Comment by dazuimao1990** [comment]
@GLYASAI  看下这个问题

**Comment by GLYASAI** [comment]
麻烦提供以下几个文件的内容:

- /run/nginx/conf/nginx.conf
- /run/nginx/conf/http/default/default_servers.conf
- /run/nginx/conf/stream/default/default_servers.conf

**Comment by yaozijian** [comment]
rbd_gateway 容器中没有后面两个文件！


直接用 docker run --rm -it registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-gateway:v5.2.0-release  bash 执行后，容器中也没有这两个文件。


是提供的容器镜像中少了这两个文件，还是这两个文件是运行时动态生成的？


kubernetes 的 cni_flannel 容器总是退出状态，也许跟这个问题有一定关系？




此外，我用的是 64 位 CentOS 7.7 系统，KDE 桌面，Firefox 浏览器。


版本号已经是 5.2 ，安装起始页面这里还没有改过来









在 2020-04-18 12:14:06，"黄润豪" <notifications@github.com> 写道：

麻烦提供以下几个文件的内容:

/run/nginx/conf/nginx.conf
/run/nginx/conf/http/default/default_servers.conf
/run/nginx/conf/stream/default/default_servers.conf

**Comment by yaozijian** [comment]
进一步说明：


1  64 位 CentOS 7.7 系统，KDE 桌面，内核已经升级为 5.6.4 版


Linux newstar 5.6.4-1.el7.elrepo.x86_64 #1 SMP Sun Apr 12 16:56:32 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux



2  从安装文档提供的你们的网站地址，下载的 easzup  是 2.1.0 版的，用这个安装 kubernetes 之后，kubectl get componentstatus 显示的组件状态都是 Unknow


从 github 上下载最新的 easzup 2.2 版之后，安装后 kubectl get componentstatus 显示组件状态正常。


但是有一个  cni_flannel 容器总是不正常，总是退出状态。


3  前两天安装 rainbond 时，总是在 第 2 步，等待 5 个组件就绪的时候，rbd-gateway 组件不正常，反复多次，都是同样的问题。


重试的时候，都是用 easzup 清理掉所有容器，所有镜像，删除 docker，重启系统后再试的。

















在 2020-04-18 12:14:06，"黄润豪" <notifications@github.com> 写道：

麻烦提供以下几个文件的内容:

/run/nginx/conf/nginx.conf
/run/nginx/conf/http/default/default_servers.conf
/run/nginx/conf/stream/default/default_servers.conf

**Comment by barnettZQG** [comment]
时间过去较远，该问题未有响应。将关闭这个问题
