### ISSUE TITLE
官网论坛无法登录

### ISSUE THREAD

**Issue by yaozijian** [goodrain/rainbond#752]
【BUG描述】
官网注册后，可以登录到后台管理系统，但打开社区时还是显示为没有登录。
点击社区页面上的注册后，进入到的注册页面与先前的注册页面相同。
登录页面经常出现不能登录，提示密码错误的问题；重设密码（其实设置的是与先前一样的密码）后又能正常登录。

**Comment by dazuimao1990** [comment]
请问你是指 t.goodrain.com 无法登陆么

**Comment by yaozijian** [comment]
登录之后，进到了 企业版的 控制台界面。但是，我只是想在 社区里面发帖，问问 5.2 版安装问题的。

然而，打开社区页面时，还是未登录界面，没法发帖。

我遇到的问题是：

在 64 位 CentOS 7.7 系统中，安装 5.2 版(all-in-one安装）失败，多次尝试都是相同的错误：rbd-gateway 容器无法启动，总是退出。容器日志显示，是 nginx check config error

( 在 github 上提的 issue 也是描述这个问题的）。



姚子建
 
发件人： Guox
发送时间： 2020-04-18 11:34
收件人： goodrain/rainbond
抄送： 姚子建; Author
主题： Re: [goodrain/rainbond] 官网论坛无法登录 (#752)
请问你是指 t.goodrain.com 无法登陆么

**Comment by dazuimao1990** [comment]
已经指定了开发人员去看 rbd-gateway 的具体问题了；
有关社区登陆失败这个问题，可否有些具体的截图？企业版控制台 这个描述，我不是很清楚到底是哪里

**Comment by yaozijian** [comment]
登录后有以下界面




但是这个界面还是显示没有登录，无法发帖






点击右上角的【登录】按钮，进入到的登录页面与先前的页面是相同的，但是用相同的用户名和密码登录会出错






在 2020-04-18 12:08:55，"Guox" <notifications@github.com> 写道：

已经指定了开发人员去看 rbd-gateway 的具体问题了；
有关社区登陆失败这个问题，可否有些具体的截图？企业版控制台 这个描述，我不是很清楚到底是哪里
