### ISSUE TITLE
5.2.0是否支持在已有k8s集群上离线安装 

### ISSUE THREAD

**Issue by F-liuhui** [goodrain/rainbond#756]
【需求描述】(非需求请删除本行)
 5.2.0在已有k8s集群上离线安装 
【BUG描述】(非BUG请删除本行)

【部署环境】
- Rainbond版本(执行`grctl version`获取): [请填写此处]
- 操作系统类型和版本:[请填写此处]
- 离线部署/网络开放：[请填写此处]
5.2.0是否支持在已有k8s集群上离线安装，公司不允许访问外网

[Rainbond用户文档](https://www.rainbond.com/docs/)或添加微信群与我们实时沟通；

**Comment by GLYASAI** [comment]
你好, 5.2.0 目前还不支持离线安装.
