### ISSUE TITLE
Release5.2版本通过easzup安装的子节点网络有问题

### ISSUE THREAD

**Issue by wmabcde** [goodrain/rainbond#765]
【BUG描述】(非BUG请删除本行)
Release5.2版本，
1，通过all-in-one方式安装单机版（172.20.32.234）
2，运用kubeasz的 easzctl add-node 172.20.32.196安装子节点
【部署环境】
- Rainbond版本(执行`grctl version`获取): Release5.2
- 操作系统类型和版本:CentOS Linux release 7.6.1810 (Core)     4.4.220-1.el7.elrepo.x86_64
- 离线部署/网络开放：网络开放

安装的子节点172.20.32.196网络存在问题
1，访问7070的页面报错，http://172.20.32.234:7070/console/teams/cbcb395a8a9411eaa2540242ac110005/overview
返回：{"msg":{"url":"https://rbd-api-api:8443/v2/resources/tenants","body":{"msg":"get resources error, error getting allocatalbe cpu and memory: error getting cluster resources: Get http://172.20.32.196:6100/v2/nodes/rule/compute: dial tcp 172.20.32.196:6100: i/o timeout"},"httpcode":500,"method":"POST","apitype":"Not specified"},"code":10401,"msg_show":"服务端异常"}
2.1，kubectl top node命令无法查看子节点数据
[root@goodrain ~]# kubectl top node
NAME            CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
172.20.32.234   1026m        6%     23960Mi         60%
172.20.32.196   unknown     unknown      unknown     unknown
2.2，metrics-server日志如下：
E0506 10:01:05.801199       1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:172.20.32.196: unable to fetch metrics from Kubelet 172.20.32.196 (172.20.32.196): Get https://172.20.32.196:10250/stats/summary?only_cpu_and_memory=true: context deadline exceeded
E0506 10:01:35.814806       1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:172.20.32.196: unable to fetch metrics from Kubelet 172.20.32.196 (172.20.32.196): Get https://172.20.32.196:10250/stats/summary?only_cpu_and_memory=true: context deadline exceeded
E0506 10:02:05.801373       1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:172.20.32.196: unable to fetch metrics from Kubelet 172.20.32.196 (172.20.32.196): Get https://172.20.32.196:10250/stats/summary?only_cpu_and_memory=true: context deadline exceeded
E0506 10:02:35.801090       1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:172.20.32.196: unable to fetch metrics from Kubelet 172.20.32.196 (172.20.32.196): Get https://172.20.32.196:10250/stats/summary?only_cpu_and_memory=true: context deadline exceeded
E0506 10:03:05.846686       1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:172.20.32.196: unable to fetch metrics from Kubelet 172.20.32.196 (172.20.32.196): Get https://172.20.32.196:10250/stats/summary?only_cpu_and_memory=true: context deadline exceeded
E0506 10:03:35.801106       1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:172.20.32.196: unable to fetch metrics from Kubelet 172.20.32.196 (172.20.32.196): Get https://172.20.32.196:10250/stats/summary?only_cpu_and_memory=true: context deadline exceeded
E0506 10:04:02.437850       1 reststorage.go:135] unable to fetch node metrics for node "172.20.32.196": no metrics known for node
E0506 10:04:03.493452       1 reststorage.go:135] unable to fetch node metrics for node "172.20.32.196": no metrics known for node

**Comment by barnettZQG** [comment]
该问题在 5.2.1  版本中优化修复。
