### ISSUE TITLE
5.1的版本无法升级到5.2

### ISSUE THREAD

**Issue by aioloswong** [goodrain/rainbond#767]
【BUG描述】
已安装运行的Rainbond5.1的版本现在无法升级到5.2。

**Comment by barnettZQG** [comment]
从5.1到5.2版本的底层部署结构变化是巨大的，因此暂不提供自动化升级脚本。可参考以下方式进行迁移：
1. 安装全新版本的5.2 Rainbond 集群。
2. 对5.1平台应用进行备份，迁移到5.2平台， 此过程可联系我们进行远程协助。

**Comment by aioloswong** [comment]
对于开源版的用户没法通过对应用进行备份，然后再进行迁移。因为全新安装的5.2版本的集群，它的集群的Id变了。开源版本只能进行本地备份，没法跨数据中心（跨集群）迁移。所以我的理解就是对于已经上线的5.1开源版本Rainbond，就永远没办法升级了，是吧？
