### ISSUE TITLE
5.2.0 海外服务器安装问题

### ISSUE THREAD

**Issue by laoliao0806** [goodrain/rainbond#770]
【BUG描述】
![image](https://user-images.githubusercontent.com/53854600/81494799-1fac4500-92de-11ea-9053-ed6ad846a5d4.png)

安装到第三步卡住了，服务器在亚马逊，估计是网络原因一直无法下载安装包，提示框给出的下载地址是个内网地址（如上图）。

建议照顾一下海外用户的网络，弄点cdn啥的，包括镜像和安装包都是针对国内网络优化，海外想安装相当费劲。。。

@fanyangyang @barnettZQG 

【部署环境】
- Rainbond版本(执行`grctl version`获取): [5.2.0]
- 操作系统类型和版本:[CentOS 7.6.1810]
- 离线部署/网络开放：[网络开放]

**Comment by barnettZQG** [comment]
尝试使用非安装包模式进行安装，安装方式如下：
1. helm 先卸载现在的operator
2. helm使用下述命令安装operator

```
helm install  rainbond-operator ./chart --set openapi.installMode=WithoutPackage --set openapi.imageRepository=rainbond --namespace=rbd-system
``` 
@laoliao0806

**Comment by barnettZQG** [comment]
@zsl1549  UI上的下载连接错误请尽快修复。

**Comment by barnettZQG** [comment]
目前的最新安装包下载地址应该是：
https://rainbond-pkg.oss-cn-shanghai.aliyuncs.com/offline/5.2/rainbond.images.2020-05-08-v5.2.0-release.tgz

**Comment by laoliao0806** [comment]
目前已安装成功，但无法构建组件：#782
