### ISSUE TITLE
5.2.0 初次安装完毕，构建nginx失败

### ISSUE THREAD

**Issue by laoliao0806** [goodrain/rainbond#782]
【BUG描述】
![image](https://user-images.githubusercontent.com/53854600/83634469-2d9b7000-a5d5-11ea-9ecc-3fbcc80a5fd6.png)

![image](https://user-images.githubusercontent.com/53854600/83634491-3a1fc880-a5d5-11ea-8a08-1c1fac3009bc.png)

![image](https://user-images.githubusercontent.com/53854600/83634585-60456880-a5d5-11ea-937b-ed7cd2596127.png)

如图，通过镜像构建，镜像名nginx:alpine

查看rbd-chaos容器一直报错：
```
time="2020-06-03T18:46:37+08:00" level=error msg="build from image error: Error response from daemon: Get https://registry-1.docker.io/v2/library/nginx/manifests/alpine: unauthorized: incorrect username or password"
```
看错误信息好像是验证失败，但是nginx官方镜像需要登录么？？

@fanyangyang @barnettZQG 

【部署环境】
- Rainbond版本(执行`grctl version`获取): [5.2.0]
- 操作系统类型和版本:[CentOS 7.6.1810]
- 离线部署/网络开放：[网络开放]

**Comment by GLYASAI** [comment]
这个 bug 已经修复，请用一下命令更新 rbd-chaos：

```
kubectl set image ds -n rbd-system rbd-chaos rbd-chaos=registry.cn-hangzhou.aliyuncs.com/abewang/rbd-chaos:V5.2-dev --record
```
