### ISSUE TITLE
测试最小化安装后，卸载后存在僵尸进程

### ISSUE THREAD

**Issue by szsuyuji** [goodrain/rainbond#785]
【BUG描述】(非BUG请删除本行)

卸载会产生僵尸进程：
 Zsl  14090 14108 [rainbond-api] <defunct>
 Zl   13579 14343 [java] <defunct>
Zsl  23499 23517 [mysqld] <defunct>

服务器load很高：
top - 11:16:06 up  1:38,  1 user,  load average: 10.01, 9.09, 5.39

r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  4      0 4096112 235808 2160236    0    0    81    41 1659 1044  3  2 86  9  0
 0  4      0 4095856 235812 2160240    0    0     0    60 4466 8137  1  1 24 73  0
 0  4      0 4095436 235812 2160260    0    0     0    40 6860 12018  3  3 24 71  0
 0  4      0 4092592 235812 2160256    0    0     0    68 4693 8582  1  1 24 73  0

测试安装几次，确实存在这个问题

【部署环境】
- Rainbond版本(执行`grctl version`获取): [请填写此处]
5.2.0.RELEASE

- 操作系统类型和版本:[请填写此处]
- 离线部署/网络开放：[请填写此处]

-------------------------以下内容请阅读后删除-----------------------------
如果你想提交一个BUG，请优先查看已经存在的BUG提交是否与你的问题一致。
如果你想提交一个需求建议，请详细描述你的场景。
如果你想咨询Rainbond的使用场景，还可以参阅[Rainbond用户社区](https://t.goodrain.com/)，[Rainbond用户文档](https://www.rainbond.com/docs/)或添加微信群与我们实时沟通；

**Comment by GLYASAI** [comment]
检查下是否已经卸载干净：

```
kubectl get ns
kubectl get all -n rbd-system
```

**Comment by szsuyuji** [comment]
> 检查下是否已经卸载干净：
> 
> ```
> kubectl get ns
> kubectl get all -n rbd-system
> ```
NAME                      READY   STATUS    RESTARTS   AGE
pod/rainbond-operator-0   2/2     Running   4          21h

NAME                        TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/rainbond-operator   NodePort   10.43.110.220   <none>        8080:30008/TCP   21h

NAME                                 READY   AGE
statefulset.apps/rainbond-operator   1/1     21h


只剩下了安装器

**Comment by barnettZQG** [comment]
@szsuyuji 出现僵尸出现较大的原因是异常的关闭docker daemon导致， 重启机器恢复。
