### ISSUE TITLE
5.2.0 开源版本使用发现的bug

### ISSUE THREAD

**Issue by yszansx** [goodrain/rainbond#790]
【BUG描述】
1.云帮系统内部服务调用不支持https通讯，只能将https协议通过X-Forwarded-Proto 转换成http实现。
2.云帮性能监控插件不能跟filebeat并存，二选一。只能同时开启一个。

**Comment by barnettZQG** [comment]
@yszansx 
问题1是什么意思，能否详细说明。组件间调用默认是TCP协议治理，不涉及https层面。 目前HTTP层治理插件确实不支持HTTPS。
若组件提供HTTPS服务，通过网关访问时不能直接转发HTTPS，建议服务工作在HTTP层面，然后由网关对外提供HTTPS服务。

问题2: 正常情况下可以并存，目前有什么实际报错吗？

**Comment by yszansx** [comment]
![image](https://user-images.githubusercontent.com/43443722/87238796-db523800-c439-11ea-86fe-486a94059213.png)

**Comment by yszansx** [comment]
![image](https://user-images.githubusercontent.com/43443722/87239020-adbabe00-c43c-11ea-9499-fe1d6776efaf.png)

**Comment by barnettZQG** [comment]
@yszansx 
问题1：我刚才已经提到，通过网关到组件端口这一段目前不支持进行HTTPS负载。正确的配置应该这样：

浏览器->https->网关->http->组件端口。因此组件本身目前不建议直接进行HTTPS监听。如果确认需要的话。网关这层需采用TCP策略对外暴露。

问题2:  你是自己创建的插件还是使用的是默认插件？看起来是插件镜像配置有问题导致。

**Comment by barnettZQG** [comment]
问题2将在5.2.1版本中修复
