### ISSUE TITLE
源码构建的应用端口号修改时报错

### ISSUE THREAD

**Issue by zhouyq** [goodrain/rainbond#8]
创建了一个nodejs的程序，监听端口是9000，平台默认是5000端口，当尝试修改端口为9000时，提示修改错误

![image](https://user-images.githubusercontent.com/1088647/34087843-ad40acf8-e3e0-11e7-8701-ab84a8f22ae9.png)

**Environment**:
- rainbond version: 3.4 
rbd-api: release-3.4-0.4b2ca65
rbd-app-ui: master-3.4-2.gfb5b047
- Cloud provider or hardware configuration: 
32G Memory
8CPU

- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- docker image version:
- grctl version:
- Others:

**Comment by barnettZQG** [comment]
端口将不支持修改，只能添加和删除
