### ISSUE TITLE
集群管理支持web形式的kubectl

### ISSUE THREAD

**Issue by lxm** [goodrain/rainbond#810]
创建带serviceaccount的容器，并提供web console，容器中内置kubectl命令，用来维护集群

**Comment by lxm** [comment]
可以参考这个项目 https://github.com/KubeOperator/webkubectl

**Comment by barnettZQG** [comment]
@lxm 或许可以先由用户在dashboard自行部署一个服务，然后通过dashboard中的容器终端控制入口进行操作。
![image](https://user-images.githubusercontent.com/18493394/89264106-f133d100-d664-11ea-9fe7-aae2d550b916.png)

![image](https://user-images.githubusercontent.com/18493394/89264059-e24d1e80-d664-11ea-8e9c-ae937706282e.png)
