### ISSUE TITLE
期望增加volume的文件在线上传/下载/修改功能

### ISSUE THREAD

**Issue by cxgreat2014** [goodrain/rainbond#813]
daocloud的用户体验中，volume的文件在线上传/下载/修改给各个网站运维管理带来了很多便利，技术实现方式是将kodexplorer进行了一些定制，然后在用户选择编辑volume文件功能时将其挂载到kodexplorer的镜像下再打开外网访问，对于项目在线调试部署来说是重大利好，期望增加，哈哈哈哈

**Comment by barnettZQG** [comment]
@cxgreat2014 对于用户业务的数据操作，目前还是建议用户自行创建部署类似kodexplorer或者sftp类的业务服务，通过Rainbond提供的共享挂载其他组件volume的功能来实现对volume中文件的上传/下载/修改。
