### ISSUE TITLE
优化rainbond升级过程中的镜像操作流程

### ISSUE THREAD

**Issue by lxm** [goodrain/rainbond#817]
目前的升级操作，有时候需要手动进入服务器进行镜像的pull && tag && push 操作

建议可以使用如`Kaniko` 的方案，将镜像拉取操作封装成job类型，直接apply到集群即可完成镜像操作

**Comment by barnettZQG** [comment]
@lxm 你描述过程由rainbond-operator完成。随着cloud场景的升级逐步规范化和常态化。集群升级将统一由operator完成
