### ISSUE TITLE
构建队列的功能增加

### ISSUE THREAD

**Issue by lev-gc** [goodrain/rainbond#820]
### 目前状况
目前应用的构建功能为单一应用的构建按钮仅能点击一次，重复点击会提示请勿频繁操作。

### 问题描述
当应用构建时间较长（比如半个小时以上甚至几个小时），点击开始构建后，发现源码仓库目标分支的版本还没有更新，或者在构建的过程中又做了代码版本更新，这时候就需要等待到上一次构建完成后才能进行下一次点击触发构建，整个过程需要人经常监控着是否已经完成上一次构建，会造成比较大的不便（尤其在一些比较尴尬的时间点特别不便）。

### 期望功能
- 参考Jenkins的实现，是否可以增加一个构建取消的功能？
- 如果无法取消构建，是否可以开放构建队列的功能，可以把下一次构建添加到队列中，等待上一次构建完成后自动开始下一次构建，而无需人工监控。对于可能造成重复点击的问题，可以对在构建时再加入队列的另一个构建任务进行二次确认。

**Comment by barnettZQG** [comment]
@lev-gc 此建议加到新版本计划中
