### ISSUE TITLE
5.2.1 install issue

### ISSUE THREAD

**Issue by airclear** [goodrain/rainbond#822]
**Describe the bug**

使用最小化安装，在安装界面点击开始安装，出现错误：

查看网络请求/cluster/init 返回错误信息

```json
{"code":200,"msg":"ok","data":{"ErrStatus":{"metadata":{},"status":"Failure","message":"RainbondCluster.rainbond.io \"rainbondcluster\" is invalid: spec.enableHA: Required value","reason":"Invalid","details":{"name":"rainbondcluster","group":"rainbond.io","kind":"RainbondCluster","causes":[{"reason":"FieldValueRequired","message":"Required value","field":"spec.enableHA"}]},"code":422}}}

```

**To Reproduce**
1. 安装好operator
2. 访问安装页面
3. 点击开始安装，无法进入下一步

**Screenshots**

**The relevant information:**
 - Rainbond Version 5.2.1
 - Browser chrome
 - Kubernetes version v1.16.9-aliyun.1 托管集群

**Comment by GLYASAI** [comment]
这个机器之前是否安装过 5.2.0? 然后卸载了? 可能是 5.2.0 残留的 crd 导致的, 5.2.1 更新了 crd, enableHA 字段已经不是必须的了.
