### ISSUE TITLE
开发前端项目rainbond-ui 是否必须要链接一个后端rainbond的服务

### ISSUE THREAD

**Issue by PmcFizz** [goodrain/rainbond#823]
开发前端项目rainbond-ui 是否必须要链接一个后端rainbond的服务
如标题， 我想在本地运行rainbond-ui 预览一下项目，是不是必须要安装一个rainbond服务 或者使用一个线上的服务？

并且我在本地运行起来 rainbond-ui 自动打开 8000端口，没有显示具体页面，一直跳转

http://localhost:8000/enterprise-server/oauth/authorize?client_id=dd8e57b70f055bf6f123&redirect_uri=http://localhost:8000/console/oauth/redirect?service_id=2&response_type=code

http://localhost:8000/enterprise-server/oauth/authorize?client_id=dd8e57b70f055bf6f123&redirect_uri=http://localhost:8000/console/oauth/redirect?service_id=2&response_type=code#/enterprise/auto

谢谢.

**Comment by barnettZQG** [comment]
@PmcFizz 是的，你需要一个后端API服务。定制开发问题不再支持范围内，我将关闭这个Issues。

**Comment by PmcFizz** [comment]
> @PmcFizz 是的，你需要一个后端API服务。定制开发问题不再支持范围内，我将关闭这个Issues。

嗯 明白了，不过我觉得你们在项目开启后，给个引导页，让开发用户去安装你们的产品，指导他们。这样对你们的产品推广会有很好的效果。你说那。
