### ISSUE TITLE
增加用户可以设置的标识并写入pod、svc、endpoint等相关资源的label中

### ISSUE THREAD

**Issue by lxm** [goodrain/rainbond#824]
目前用户可以设置的组件名称，规则比较宽松，可以也可以设置中文等名称
建议增加一个组件标识字段，只允许英文及符号，允许用户配置，用来解决service_alias不可读的问题
组件标识可用于监控等场景的应用识别，且应该在集群维度唯一

**Comment by barnettZQG** [comment]
Release in 5.3.0.
1. support user set component port service name.
2. support user set ServiceMonitor.
