### ISSUE TITLE
chaos所在节点会遗留大量无用镜像，导致磁盘空间、inode耗尽

### ISSUE THREAD

**Issue by lxm** [goodrain/rainbond#827]
RT

![image](https://user-images.githubusercontent.com/1918195/90632398-ed07d600-e256-11ea-9ed9-f37cade08c43.png)

**Comment by GLYASAI** [comment]
可以在 chaos 加一个自动执行 `docker image prune` 的功能， 将无用的镜像给清了

**Comment by lxm** [comment]
![image](https://user-images.githubusercontent.com/1918195/94128934-52219d80-fe8d-11ea-8dee-b14a8c1f8ee5.png)
看起来没有什么作用

**Comment by GLYASAI** [comment]
嗯嗯，这就需要另外的策略是清理镜像了. 最终的效果清理 rbd-chaos 产生的镜像. 

比如：当rbd-chaos产生的镜像到达某个阈值了（磁盘占用率，或 inodes 使用率）， 就开始清理。

**Comment by dazuimao1990** [comment]
> 嗯嗯，这就需要另外的策略是清理镜像了. 最终的效果清理 rbd-chaos 产生的镜像.
> 
> 比如：当rbd-chaos产生的镜像到达某个阈值了（磁盘占用率，或 inodes 使用率）， 就开始清理。

现在这个问题影响比较严重，inode使用率过高会对服务器产生严重影响。可否在开发具体功能之前，提供临时解决方案来释放资源。

**Comment by dazuimao1990** [comment]
经过测试，如下命令可以手动清理过多的镜像：
```bash
docker rmi $(docker images | grep none | awk '{print $3}') -f
```

**Comment by barnettZQG** [comment]
进行大量的基于镜像的组件构建会遗留下源镜像，如果源镜像TAG未变化，则会遗留大量的TAG为none的镜像。

1. 为什么不在组件版本构建完成后删除源镜像？

> 继续镜像的构建过程是从源仓库获取回镜像后修改TAG存入集群本地镜像版本库。源镜像暴露的主要作用是缓存，防止每次基于同一个镜像构建时全量从源仓库获取而导致时间过长。可以认为构建节点的所有镜像都是可以清理的。

2. Rainbond如何管理构建节点缓存的镜像？

> 缓存的清理一方面可以由运维人员手工完成，比如楼上的bash命令，这在任何时候都有效。另外出于系统健康自治的角度，可以在构建服务中添加缓存镜像的回收任务，两个策略：
* Tag为 none 的镜像进行回收。
* 长时间未使用的镜像进行回收。基于基础的LRU算法进行标记清除。

**Comment by barnettZQG** [comment]
https://github.com/goodrain/rainbond/commit/8e6fb9393eaa6e982e0dbedb862536066b5de952

Remove local image after build.

**Comment by barnettZQG** [comment]
Release in 5.3.0
