### ISSUE TITLE
configuration file mounting supports permission management

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond#828]
![image](https://user-images.githubusercontent.com/33855684/90639791-c733fe80-e261-11ea-8e02-df0220a7ca9f.png)

Some profiles have permission requirements, such as my.cnf ,  777 is too open ,so mysqld will ignore it.

how about add permission contorl feature for configuration file.

**Comment by barnettZQG** [comment]
The default mode is 0777. support for this parameter setting is required.
