### ISSUE TITLE
rbd-gateway组件由于proxy_buffer配置过小，导致oidc无法登录的问题

### ISSUE THREAD

**Issue by aioloswong** [goodrain/rainbond#858]
**Describe the bug**
我的应用使用IdentityServer4来实现oidc单点登录，当输入用户名密码登录后，卡在oidc登录跳转的signin-oidc界面，如下图所示：
![image](https://user-images.githubusercontent.com/10336303/95647779-9efbaa00-0b04-11eb-89be-36ad7a049c30.png)
我把应用放到本地运行，然后使用nginx代理，配置如下：
![image](https://user-images.githubusercontent.com/10336303/95647806-e5e99f80-0b04-11eb-8a5c-fd5fda98f502.png)
是能正常代理登录的，不会卡在signin-oidc界面。
如果把里面的buffer的大小配置成和你们的rbd-gateway的默认的buffer的大小一样，也会卡在signin-oidc界面。
这个问题在5.1的版本就存在，当时在沟通群里面反馈过。然后贵公司的【润豪】打包了一个定制的设置较大的buffer的rbd-gateway组件给我，临时解决了这个问题。

目前我的另外一个环境安装了新的5.2.1的版本Rainbond，这个问题又再次出现了。

**Screenshots**
5.2.1中默认的rbd-gateway组件的代理配置
![image](https://user-images.githubusercontent.com/10336303/95647267-a751e600-0b00-11eb-8b42-84c21be969b5.png)

5.1.11版本中，由贵公司【润豪】修改后的rbd-gateway组件的可以正常登录的配置：
![image](https://user-images.githubusercontent.com/10336303/95647718-3f050380-0b04-11eb-82d3-1b3cc8324b50.png)

备注：由于新的chrome 80（包含80）以后的版本针对cookie的策略做了调整，无法通过http发送SameSite为none的cookie到后台。所以要验证复现上述问题，要么使用https部署的oidc登录，或者使用360浏览器/极速浏览器、微软edge（内部版本为86以下的版本）。

**The relevant information:**
 - Rainbond Version [5.2.1]
 - Browser [360极速浏览器12.0.1550.0] 
 - Kubernetes version [e.g 1.18.2]

**Comment by barnettZQG** [comment]
@aioloswong 

You can customize parameters such as `proxy_buffer` in the following way:

step1:
```
# find ingress by domain
kubectl get ingress --all-namespaces | grep "<YOUR DOMAIN>"
```
step2:
```
kubectl edit ingress <INGRESS NAME> -n <NAMESPACE>
```
![image](https://user-images.githubusercontent.com/18493394/95650185-8c896c80-0b14-11eb-80ad-e3db96fd6ae1.png)

**Comment by barnettZQG** [comment]
It should be noted that Rainbond will recreate ingress after component restarting.

**Comment by aioloswong** [comment]
@barnettZQG 
参照你的方法，修改ingress的配置后可以正常登录了，但正如你所说的组件重启后就会失效，需要重新进行配置，所以这只是一个临时解决方案。

**Comment by barnettZQG** [comment]
@aioloswong 计划在5.2的BUG更新版本中增加UI设置以上两个参数。目前可以尽可能使用更新来操作组件的升级；构建、更新操作是不会重建ingress资源的。

**Comment by barnettZQG** [comment]
@aioloswong 已经在5.2.2-release版本中增加这两个参数的设置。
![image](https://user-images.githubusercontent.com/18493394/97276985-de4f2800-1872-11eb-93ce-f920ecd75380.png)
