### ISSUE TITLE
通过HTTPS部署的oidc服务无法跳转到登录页面

### ISSUE THREAD

**Issue by aioloswong** [goodrain/rainbond#861]
**Describe the bug**
Rainbond应用网关配置oidc认证服务为https访问。结果oidc服务的发现接口返回的数据如下图：
![image](https://user-images.githubusercontent.com/10336303/95955716-dd100b00-0e2f-11eb-841a-b97817a5d339.png)

导致oidc跳转登录的时候，第一步需要获取jkws秘钥(如果未获取过秘钥)，访问的是http的接口地址。然后就报了“The plain HTTP request was sent to HTTPS port“的错误。

而我本地的nginx代理，oidc服务发现接口返回的数据如下图：
![image](https://user-images.githubusercontent.com/10336303/95956140-75a68b00-0e30-11eb-95e2-489d01c229fa.png)
可以看到，返回的接口都是https开头的接口。

为了验证这个问题，我编写了一个测试接口，接口很简单，就是直接返回访问的scheme，代码如下图：
![image](https://user-images.githubusercontent.com/10336303/95956345-bacabd00-0e30-11eb-9970-d88dfeb588ad.png)

然后访问这个接口，Rainbond网关返回的结果是http，如下图：
![image](https://user-images.githubusercontent.com/10336303/95956436-dcc43f80-0e30-11eb-8d69-946b057b14fa.png)

而我本地nginx代理返回的结果是https，如下图：
![image](https://user-images.githubusercontent.com/10336303/95956734-4ba19880-0e31-11eb-819d-37173e86fc33.png)

**The relevant information:**
 - Rainbond Version [5.2.1]
 - Kubernetes version [1.18.2]

**Comment by barnettZQG** [comment]
@aioloswong 
The flow path is as follows:

client --https--> Rainbond-Gateway --http--> Application

The application can get really scheme by request-header `X-Forwarded-Proto` or `X-Scheme`

**Comment by aioloswong** [comment]
@barnettZQG 
我知道你说的这种访问路径，我本地的访问也是client --https--> nginx --http--> Application。
也就是说同样的代码，同样的访问路径，在Rainbond-Gateway代理下访问，和我本地nginx代理访问，一个返回的结果是http，一个返回是https。直接获取request-header X-Forwarded-Proto or X-Scheme，当然是可以的。但这样我就得修改IdentityServer4的源码，并维护一个定制版本的IdentityServer4。

**Comment by barnettZQG** [comment]
@aioloswong 
可以贴一下你的nginx配置吗？

**Comment by aioloswong** [comment]
我刚开始也以为是由于Rainbond的gateway的配置和我本地的配置不同导致的，但是我把Rainbond配置拷贝到本地后（未包含lua的那一部分，因为我本地没有openresty），我本地的nginx的接口返回的还是https，所以不知道是否是lua脚本那一部分影响了结果。
下图是我本地nginx的配置：
![image](https://user-images.githubusercontent.com/10336303/95964269-37fb2f80-0e3b-11eb-9b70-1b458e515ecd.png)
![image](https://user-images.githubusercontent.com/10336303/95964064-fff3ec80-0e3a-11eb-9e15-2b99d8af0a3f.png)

Rainbond-Gateway的配置：
![image](https://user-images.githubusercontent.com/10336303/95964527-78f34400-0e3b-11eb-971d-52cc5f0ece19.png)
![image](https://user-images.githubusercontent.com/10336303/95964613-96c0a900-0e3b-11eb-8413-fbe6077eb775.png)

**Comment by barnettZQG** [comment]
根据nginx配置，https在网关这层已经终止，因此应用程序必须依赖header头来获取真实协议。你的测试用例是否足够严谨呢？
下面这个可以做个参考，考虑在你的demo代码中打印一下 X-Forwarded-Proto 和 X-Scheme：
https://stackoverflow.com/questions/30196569/request-url-scheme-gives-http-instead-of-https-on-load-balanced-site

**Comment by aioloswong** [comment]
@barnettZQG 
这个issue可以关闭了，问题原因我通过调试asp.net core ForwardedHeadersMiddleware的源码找到了。具体原因是因为ForwardedHeadersMiddleware为了防止 IP 欺骗攻击，默认启用了ForwardedHeadersMiddleware的代理IP白名单（KnownNetworks，KnownProxies），且在默认情况下分别放入了IPAddress.Loopback，IPAddress.IPv6Loopback。我本地的代理的upstream配置的server使用的是localhost，所以访问的时候取得的代理IP就是Loopback，而Rainbond上面访问的时候取得的代理地址不是Loopback，就导致ForwardedHeadersMiddleware报“Unknown Proxy"（日志级别设置为Debug可以看到）。
![image](https://user-images.githubusercontent.com/10336303/96088225-b1f0ee80-0ef7-11eb-83c1-029bfa495788.png)
这样就导致在设置currentValues.Scheme前break，所以scheme就不会变成https。[具体代码在ForwardedHeadersMiddleware的250行。](https://source.dot.net/#Microsoft.AspNetCore.HttpOverrides/ForwardedHeadersMiddleware.cs,250)

解决的办法是把Rainbond Gateway的IP地址全部添加到KnownProxies或者KnowNetworks之中，但是由于pod重启后IP可能会变，所以在K8s的环境下可以把这2个白名单列表清空，这样百分单就不会生效了。具体代码如下，红框部分为发现问题后新加入的代码：
![image](https://user-images.githubusercontent.com/10336303/96087636-c1236c80-0ef6-11eb-9bd6-2f519ffdbaac.png)
