### ISSUE TITLE
goodrain.me, region.goodrain.me maps to a specific Node's IP, not VIP.

### ISSUE THREAD

**Issue by aioloswong** [goodrain/rainbond#866]
**Describe the bug**
I have a k8s cluster that has 3 nodes with the following information:
![image](https://user-images.githubusercontent.com/10336303/97269597-ba86e480-1868-11eb-8a26-f54be266fdb4.png)
All 3 nodes are configured to be scheduleable. 

There is a VIP 192.168.3.200 pointing to these 3 nodes.
![image](https://user-images.githubusercontent.com/10336303/97270504-3f263280-186a-11eb-8583-f66dbd49d237.png)

I configured the IP of the gateway node to be this VIP when I installed Rainbond. After installation, the hosts configuration information of these nodes are as follows.
![image](https://user-images.githubusercontent.com/10336303/97270991-f4f18100-186a-11eb-8f5f-add652b83ec4.png)
![image](https://user-images.githubusercontent.com/10336303/97272734-4bf85580-186d-11eb-9379-dc5eebfc1b4f.png)
![image](https://user-images.githubusercontent.com/10336303/97272876-7a763080-186d-11eb-8263-4a2f9676b6a4.png)

When I shut down the node k8s-master2 whose IP is 192.168.3.205, all the applications with image name like goodrain.me/xxxx installed on the Rainbond failed to be scheduled as they couldn't pull the images. I solved this problem by modifying the goodrain.me and region.goodrain.me mapping to the VIP for all node hosts.

**The relevant information:**
 - Rainbond Version [5.2.1]
 - Kubernetes version [1.18.10]

**Comment by barnettZQG** [comment]
@aioloswong On which node does the gateway run? 
By default, the Node component writes the first gateway node to the /etc/hosts file. Of course, this process is dynamic, if the first gateway node is closed, use the remaining first.

The Node component has a parameter `--gateway-vip`, Specify VIP directly rather than using dynamic service discovery.

**Comment by aioloswong** [comment]
@barnettZQG 
The current status of my Rainbond cluster show as follows:
![image](https://user-images.githubusercontent.com/10336303/97278885-3e46ce00-1875-11eb-85b7-ae9a8f6c98ef.png)
![image](https://user-images.githubusercontent.com/10336303/97279182-9ed60b00-1875-11eb-87b0-2473d7182542.png)
![image](https://user-images.githubusercontent.com/10336303/97279329-d6dd4e00-1875-11eb-8f29-bf7b5da69793.png)

**Comment by GLYASAI** [comment]
可以执行 `kubectl edit rbdcomponent rbd-node -n rbd-system` 命令, 给 rbd-node 加上以下参数:

![image](https://user-images.githubusercontent.com/21967570/97282478-abf4f900-1879-11eb-92f3-44dc97002086.png)

```
spec:
  args:
  - --gateway-vip=${your vip}
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-node:v5.2.2-release
  imagePullPolicy: IfNotPresent
  priorityComponent: false
  replicas: 1
  resources: {}
```

根据实际情况, 将 ${your vip} 替换为你的 VIP

**Comment by barnettZQG** [comment]
I'm closing this issue without any other feedback.
