### ISSUE TITLE
Rendering SLS 'rainbond' failed. Please see master log for details.

### ISSUE THREAD

**Issue by iver3on** [goodrain/rainbond#88]
--- Getting Hardware information ... ---
 OK

 --- Getting Network information ... ---
 OK

 --- will install manage node.It will take 15-30 minutes to install ---
 --- Start install init ... ---
manage01:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Rendering SLS 'rainbond' failed. Please see master log for details.
ERROR: Minions returned with non-zero exit code

**Comment by zhouyq** [comment]
机器配置和操作系统信息发一下

**Comment by barnettZQG** [comment]
Too long without feedback
