### ISSUE TITLE
suport .net core 

### ISSUE THREAD

**Issue by geffzhang** [goodrain/rainbond#89]
The. NET Core is cross-platform and works perfectly in a Linux environment, using C # as the primary development language, supporting many languages, such as vb,f# and so on, and expecting platform support for C #。https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.0-download.md

**Comment by barnettZQG** [comment]
@geffzhang 
1. The current version can support .NET core based on Dockerfile.
2. If.net Core has more users, we'll build the buildingpack

**Comment by geffzhang** [comment]
我才发现你们是一家中国公司，我有个.netcore相关公众号，有粉丝4万人，我在公众号做过调查，目前.netcore的采用率在上升，在我的公众号所做的调查中，采用.netcore技术已经超过50%，还有更多人在考虑迁移

**Comment by leegkon** [comment]
希望尽早支持.net core,.net core更适合容器化部署

**Comment by barnettZQG** [comment]
@geffzhang 
5.0 主要支持 .net，对于可以在linux下部署的.net core 可以提前版本支持。另外如果你能提供一些关于.net core的编译和运行最佳实践那就最好了

**Comment by geffzhang** [comment]
@barnettZQG 可以加我微信 geffzhang 具体聊

**Comment by ElderJames** [comment]
赞同，希望尽早支持.Net Core。

**Comment by ysicing** [comment]
@ElderJames 我们也在推进中,将在3.7版本支持.Net Core,可以参见 [版本功能计划](https://www.rainbond.com/docs/stable/architecture/roadmap.html#v3-7)

**Comment by barnettZQG** [comment]
support in v3.7. demo code :
https://github.com/goodrain-apps/dotnet-demo
if code home have `*.sln` or `*.csproj` file. The current code recognizes `.netcore` lang.
rainbond will default use the following command builds:
```
RUN dotnet restore
RUN dotnet publish -c Release -o /out
```
so, you must define start cmd in rainbondfile, like:
```
cmd: dotnet aspnetapp.dll
```
