### ISSUE TITLE
请问，开通数据中心是怎么开通的啊？

### ISSUE THREAD

**Issue by cnhans** [goodrain/rainbond#91]
您好 ，请问开通数据中心是怎么个开通法呢？目前无法添加数据中心

**Comment by ysicing** [comment]
开源版只能手动添加。
1. 首先安装一个完整的数据中心
2.  将数据中心的信息手动添加到控制台数据库中
@cnhans

**Comment by cnhans** [comment]
@ysicing 好吧，谢谢，如果能在控制台添加会比较方便和完善。

**Comment by barnettZQG** [comment]
@cnhans UI安装和添加在商业版中支持。

**Comment by cnhans** [comment]
企业版没看到收费情况，我们有这方面的需求

**Comment by barnettZQG** [comment]
@cnhans 加我微信沟通吧。 18501030060
