### ISSUE TITLE
成员角色设置后显示有误

### ISSUE THREAD

**Issue by lev-gc** [goodrain/rainbond#920]
**Describe the bug**
团队管理内成员角色显示有误，显示为数字。

**To Reproduce**
- 进入：团队管理-成员
- 成员修改角色时显示的角色列表为角色名称，显示没有问题；
- 设置成功后重新打开修改角色的窗口，发现刚才设置的角色名称显示成了数字，疑似为角色的ID；

**Screenshots**
设置时：
![set](https://user-images.githubusercontent.com/18007701/109469815-82f3a780-7aa9-11eb-8390-05b32ecb5da9.png)
设置后重新打开时显示：
![show](https://user-images.githubusercontent.com/18007701/109469827-89821f00-7aa9-11eb-8b27-5ee83f5a8621.png)

**The relevant information:**
 - Rainbond Version: v5.2.2
 - Browser:  Chrome
 - Kubernetes:  v1.19.6

**Comment by barnettZQG** [comment]
@lev-gc 该问题已在5.3.0 版本中修复。

**Comment by lev-gc** [comment]
明白👌
