### ISSUE TITLE
使用本地组件库的模板创建的组件没办法修改构建源么？ 只能一直使用模板源？是否可以提供修改构建源

### ISSUE THREAD

**Issue by cnwangzhanfei** [goodrain/rainbond#928]
【需求描述】
场景是这样的：
 使用本地组件库的模板快速创建组件，在组件创建后组件的更新需要由自己觉得，不在依赖模板的更新，是否可以执行修改构建源

**Comment by barnettZQG** [comment]
@cnwangzhanfei 按照你的场景，目前来说处理方式为直接以新的构建源创建一个组件，然后替换掉从模版创建来的组件。

按照Rainbond 的最佳实践，应用中每一个组件都应该设计成容易替换。与外部依赖注入信息设计成标准的变量列表。

**Comment by yangkaa** [comment]
5.8.0 版本已支持
