### ISSUE TITLE
请问怎么扩容管理节点

### ISSUE THREAD

**Issue by yeyongyong** [goodrain/rainbond#93]
请问怎么扩容管理节点，管理节点的扩容官方文档没有

**Comment by ysicing** [comment]
@yeyongyong  目前3.6版本扩容管理节点不是很完善，无法完全自动化实现扩容，故暂未提供相关管理文档。

**Comment by barnettZQG** [comment]
3.7版本已支持管理节点扩容，文档如下：
https://www.rainbond.com/docs/stable/operation-manual/cluster-management/add-manage-node.html
