### ISSUE TITLE
Optimize the naming of k8s resources for components

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond#930]
The k8s resources for components are currently named mainly by component_id. This is a UUID string. It is difficult when users want to find related resources. 

Same with #929, The naming convention should be changed

**Comment by yangkaa** [comment]
团队命名空间支持创建时设置，不支持修改。集群内资源名称生成规则为：应用英文名-组件英文名。关闭应用后，支持修改对应名称。
