### ISSUE TITLE
Supports automatic cleaning of images in image registry (rbd-hub)

### ISSUE THREAD

**Issue by Aaron-23** [goodrain/rainbond#937]
The long-term use of the platform will produce a large number of images. The default installation of the image warehouse RBD hub will occupy more and more disks. The images corresponding to premature or deleted components should be deleted.

**Comment by barnettZQG** [comment]
```
grctl registry cleanup
```
支持清理集群中镜像仓库中的无用镜像，包括：已删除的组件所有版本镜像，已删除的版本镜像等。

* 已知缺陷

如果平台组件库未配置独立的镜像仓库，该清理动作会会将发布到组件库的镜像清理。
