### ISSUE TITLE
rbd-gateway内存泄漏问题

### ISSUE THREAD

**Issue by marcosweng** [goodrain/rainbond#939]
**现象：** rbd-gateway在运行一段时间后，nginx部分进程开始出现dead，但是进程无法正常关闭，导致使用内存不断往上递增，在内存使用超过服务器临界值后，网关开始无法提供服务。

**出现版本**： 5.1.4、5.2.1

**解决方案：** 系统上配置定时任务，定时检测nginx dead描述进程以及内存使用超过1G的nginx进程，并对此类进程进行关闭处理，由nginx自身的进程守护机制完成关闭进程的重启

**Comment by barnettZQG** [comment]
@marcosweng 在5.3.1发行版中修复。
