### ISSUE TITLE
rainbond-operator挂载问题

### ISSUE THREAD

**Issue by marcosweng** [goodrain/rainbond#940]
**现象：** 

​	1、在rancher上使用rainbon-operator安装rainbond时，由于很多配置没有开放出来，导致rainbond部署所需的pvc都以默认的1GB大小进行申请，在空间使用超过一定大小时，很多功能如：日志就无法使用了

​	2、rancher-operator安装时，选择存储卷时，第二个类型的存储卷无法正常选择，可能存在bug

​	3、rancher-operator会不断的去检测更新rainbond的组件，导致在rancher上部署的rainbond组件无法进行更改，一更改就会被还原获取，如：想修改rbd-app-ui里的数据库连接

​	4、rancher-operator默认创建rbd_node用于读取日志的的挂载卷是/var/lib/docker，但很多情况下服务器会有单独的目录用于/var/lib/docker目录的存储，如我们的是：/data/docker/lib/docker，此时会导致rainbond日志无法正常读取，但没有任何提示

**出现版本：**5.2.1

**解决方案**：

​	1、pvc空间大小通过先暂停rancher-operator，rainbond组件，再删除原有pvc，新建新的pvc并分配合适的空间大小后，再开启rainbond组件和rancher-operator组件可解决

​	2、暂未解决

​	3、通过下载rainbond-operator源码，调整部分配置重新构建解决，部分配置可进入到k8s的operator管理界面中，进行调整

​	4、通过下载rainbond-operaor源码，调整部分配置重新构建解决

**建议：**

​	1、将用户可自定义的的参数，在rainbond-operator开放出来配置，否则这块参数调整会相对比较困难

**Comment by barnettZQG** [comment]
@marcosweng 5.2.1 版本使用的rainbond-operator 模式已在 5.3.0版本中完全重构，存储问题应该不在存在。

rainbond-operator会维护rainbond组件生成的k8s资源，所以需要修改rainbond组件相关参数应该修改 rbdcomponent 资源。
