### ISSUE TITLE
rainbond-operator部署管理台高可用问题

### ISSUE THREAD

**Issue by marcosweng** [goodrain/rainbond#941]
**现象**：

​	1、使用rainbond-operator部署，默认管理台节点就只有一个，在k8s主节点发生宕机后，就无法正常使用了

**出现版本**：5.2.1

**解决方案**：

​	1、暂未尝试，目前猜测可通过调整rainbond-operator配置解决

**建议**：

​	1、将高可用配置放入rainbond-operator管理台中

**Comment by barnettZQG** [comment]
从5.3.0版本开始，集群部署模式已变更，请根据新版本进行评估
