### ISSUE TITLE
容器集群环境服务器初始化问题

### ISSUE THREAD

**Issue by marcosweng** [goodrain/rainbond#942]
**现象**：

​	1、跟rainbond关联并不大，属于k8s运维问题，k8s服务器初始化时需要做的一些准备工作：如打开文件数配置、内存配置等，否则会在这上面浪费了较长时间。

**解决方案：**

1、升级系统内核至：4或者5，3内核版本有兼容性bug

2、防火墙关闭

3、swap内存关闭

4、最大文件打开数设置等

**建议**：

1、提供服务器配置的检测脚本，对于服务器中的配置给出一定的建议，或通过引导式的方式，调整安装上面所需内容

**Comment by barnettZQG** [comment]
@marcosweng 5.3 版本的节点初始化脚本已做出如上提醒。详情参考：
http://sh.rainbond.com/init_node
