### ISSUE TITLE
CPU使用设置问题

### ISSUE THREAD

**Issue by marcosweng** [goodrain/rainbond#943]
**现象**：

​	1、rainbond目前默认的CPU与内存配比为：15:64，这种固定方式在生产环境中比较适合，但我们主要用于开发环境，CPU与内存匹配会相差较多

​	2、rainbond也提供配置环境变量：`ES_CPULIMIT`、`ES_CPUREQUEST`的方式，对某个组件的CPU使用进行个性化调整，但这块使用有些bug，有的时候配置无法生效，通过排查发现环境变量配置存储于两个数据库中：`console`、`region`中，但console和region这块配置往往无法很好的同步

**出现版本**：5.1.4、5.2.1

**解决方案：**

1、编写定时任务，定时按照设置的CPU和内存配置，同时更新两个数据库中的环境配置，并进行重启

**建议**：

1、各行各业对于CPU与内存的配比要求不一定相同，且不同应用对于计算能力与内存的要求也不同，建议全局通过开关加入配比，若开关打开，则设置一个配比值自动计算，若不打开，则默认不限制CPU

2、组件个性化CPU设置的部分，建议也将配置在页面中开放出来，上面环境变量的配置虽然也可以，但我们在社区找了很久才找到这个解决方案。

**Comment by barnettZQG** [comment]
与 #594 需求一致，CPU支持自定义设置已加入Roadmap
