### ISSUE TITLE
rainbond日志功能使用问题

### ISSUE THREAD

**Issue by marcosweng** [goodrain/rainbond#944]
**现象**：

​	1、目前日志主要通过rbd-node在各个节点的docker运行目录中进行日志收集归并后放入rainbond的/grdata挂载目录下，空间占用会变大，且grdata空间使用满后，日志就无法正常收集查看了

​	2、日志查询较为麻烦，一是目前标准输出中只能输出当前很少部分的日志，对于之前的日志需要使用：`最近1000条日志`才能查看，查看日志十分麻烦，且由于是归并日志，虽然日志查看右侧有tag可以高亮显示查看的实例日志，但意义不大，多个实例日志仍然混合在一起，只是高亮区分开，整体使用较为繁琐。

**出现版本**：5.1.4、5.2.1

**解决方案：**

暂无

**建议：**

1、实时日志部分内容：可参考rancher或原生k8s的方式，在总览的运行实例中点击即可显示指定实例日志的滚动终端

2、历史日志部分内容：若打开日志收集插件，则使用elk或其他日志系统中收集日志，并提供历史日志查看的功能，一般情况下开发、测试环境对历史日志查看的需求较少，只需要实时日志即可，生产环境对历史日志的需求较为迫切，需要更为完善的日志功能。

**Comment by barnettZQG** [comment]
支持通过kubeapi 查询实例日志。解决某些情况下无法查看到日志的问题。
