### ISSUE TITLE
管理台存储添加问题

### ISSUE THREAD

**Issue by marcosweng** [goodrain/rainbond#946]
**现象**：

添加存储时，有些时刻可以显示k8s集群中的PVC，但大部分时候无法显示，只能显示：共享存储与临时存储。调试发现PVC是由后台返回的，但是大部分时候都返回为空，少部分时候可正常返回。

![image-20210305153727430](http://images.gillion.com.cn/docs/images/uploads/5948a60401c6c64134f92a42fe624a21/image-20210305153727430.png)

**出现版本**：5.2.1

**解决方案**：暂无

**Comment by barnettZQG** [comment]
@marcosweng  自定义存储类型目前仅支持有状态组件使用。
