### ISSUE TITLE
rainbond应用选择困难问题

### ISSUE THREAD

**Issue by marcosweng** [goodrain/rainbond#948]
**现象**：

一般项目人员所运维项目都较唯一，所以比较希望进入rainbond时，马上就能够显示所关注的应用，但目前进入rainbond时，都需要经过：

​	1、选择团队

​	2、选择应用，打开拓扑图，找到列表标签

​	3、找到组件

才能进入所想操作的组件页面，但由于rainbond上面这几个页面本身需要加载一些监控数据，所以部分页面加载又比较缓慢，使得操作感知上有比较强的阻塞感。

**出现版本**：5.2.1

**解决方案：**无

**建议**：

能够理解rainbond团队这种设计所想，让公司组织机构能够跟具体项目关联起来，但对于大部分人员来说，在同一个时间段内运维的项目并不会发生比较大的调整，所以会比较希望进入页面时就一步到位，找到自己的应用。建议

1、前端加个缓存，在进入页面时做个判断，优先进入缓存操作的页面，需要切换时，再做上面的操作

2、主页除了常用团队外，加入常用应用和常用组件

3、组件右上角加入搜索框，快捷进入所需操作的组件页面，或提供快捷键打开网页搜索框弹窗

**Comment by barnettZQG** [comment]
@marcosweng 控制台左下角有收藏页面功能，收藏特定页面后可直接通过左侧划出栏或企业首页中直接跳转。
