### ISSUE TITLE
网关域名绑定多个第二个无效

### ISSUE THREAD

**Issue by marcosweng** [goodrain/rainbond#949]
**现象**：

同个组件，域名绑定两个时，域名无法正常访问，需要删掉，重新添加端口，再开放域名才能访问

**出现版本：**5.2.1

**解决方案**：无

**建议**：

1、修复问题

2、增加检测功能，对对外开放的端口，无法访问的给出告警提示，并进行自动修复

**Comment by barnettZQG** [comment]
@marcosweng 该问题无法复现，提供复现方式。
