### ISSUE TITLE
镜像、deployment名称

### ISSUE THREAD

**Issue by marcosweng** [goodrain/rainbond#950]
**现象**：

目前镜像、部署的deployment都完全使用数据库的组件ID作为标识，想去排查部分问题时较为困难。5.1.4的镜像仍然是显示组件名字的标识，5.2.1开始镜像名称也变成了ID

**出现版本**：5.1.4、5.2.1

**解决方案**：无

**建议**：

1、新增团队时，增加团队编码

2、新增应用时，增加应用编码

3、新增组件时，按组件名称标记部署的deployment和构建的镜像名称

整体命名规则变为：

deployment名称=团队编码\_应用编码\_组件名称

镜像名称=仓库前缀/goodrain/团队编码/应用编码/组件名称

比较便于日常维护。

**Comment by barnettZQG** [comment]
与 #930 一致，我将关闭这个issues.
