### ISSUE TITLE
组件启动超时提示

### ISSUE THREAD

**Issue by marcosweng** [goodrain/rainbond#951]
**现象**：组件超时时间默认为40s，且无法更改，由于很多spring应用基本都是重业务类型应用，所以大部分应用在容器上启动时间都会超过40s，此时每次启动的状态都会变为构建、或启动超时，比较容易让人紧张

**出现版本**：5.1.4、5.2.1

**解决方案**：无

**建议**：

​	启动超时可全局默认为40s，但每个组件可开放配置出来自行定义

**Comment by barnettZQG** [comment]
@marcosweng 组件健康检查设置初始化等候时间即可延长启动控制器超时时间。
![image](https://user-images.githubusercontent.com/18493394/116189864-2d134700-a75c-11eb-8330-cec289423b26.png)
