### ISSUE TITLE
本地应用市场发布未正常更新

### ISSUE THREAD

**Issue by marcosweng** [goodrain/rainbond#952]
**现象：** 构建完一个应用到应用市场后，想升级版本，此时将新应用版本发布至本地市场中，其他使用到本应用的项目点击构建，发现虽然日志显示正常更新了，但应用并未更新到指定的版本

**Comment by barnettZQG** [comment]
@marcosweng 操作方式是否错了？ 应用的升级在应用视图页的升级栏目下。

**Comment by barnettZQG** [comment]
5.3.1 版本中对应用升级进行了重构，可以尝试使用新版本。
