### ISSUE TITLE
第三方组件自身依赖，无法删除

### ISSUE THREAD

**Issue by briannadev** [goodrain/rainbond#953]
【BUG描述】(非BUG请删除本行)
![image](https://user-images.githubusercontent.com/8251627/114036185-70436e00-98b2-11eb-876d-8a6e3c3f0181.png)

![image](https://user-images.githubusercontent.com/8251627/114036209-75082200-98b2-11eb-87e9-4e1838a2b31a.png)

【部署环境】
- Rainbond版本(执行`grctl version`获取): [5.3]
- 操作系统类型和版本:[Centos7.9 64位 K5.11]
- 离线部署/网络开放：[网络开放]

在编辑模式下，第三方组件自身依赖（误操作）之后，无法删除，在编辑模式下无法选中线。

**Comment by barnettZQG** [comment]
限制第三方组件的添加依赖操作。

**Comment by barnettZQG** [comment]
已于 5.3.1 版本修复。
