### ISSUE TITLE
安装长时间卡在“系统所需的非组件镜像本地化处理”

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond#956]
1. 查看rbd-system namespace 下的服务启动情况
```
kubectl get pod -n rbd-system
```
发现rbd-hub、etcd、gateway、rbd-node 服务都正常启动（注意：这四个服务是处理镜像步骤的前提）

2. 查看operator 日志发现一直阻塞在`waiting local image hub ready`

3. 从rainbondcluster 资源中获取rbd-hub的账号密码并尝试登录。
```
kubectl get rainbondcluster rainbondcluster -n rbd-system -o yaml

docker login goodrain.me
```
![image](https://user-images.githubusercontent.com/18493394/114398352-4780e880-9bd2-11eb-9899-6f0f71ff1c76.png)

镜像仓库已经启动但无法进行登录，401错误。

**Comment by barnettZQG** [comment]
基于401错误的报错可知账号密码错误，可能是由于安装过程中进行了重新安装，导致rainbondcluster记录的账号密码与 secret 资源 hub-image-repository 中记录的不一致导致。临时处理方式如下：

1. 删除 hub-image-repository，rbd-hub 等资源
```
kubectl delete secret hub-image-repository -n rbd-system
kubectl delete deployment rbd-hub -n rbd-system
```
2. 重启 rainbond-operator
```
kubectl delete pod  -l release=rainbond-operator -n rbd-system
```

**Comment by 1909490139** [comment]
3. 删除本地证书文件
`rm -rf /etc/docker/certs/goodrain.me/*`
4. 重启rbd-gateway
`kubectl delete pod  -l name=rbd-gateway -n rbd-system`
5. 重启rbd-node
`kubectl delete pod  -l name=rbd-node -n rbd-system`

**Comment by dazuimao1990** [comment]
> 基于401错误的报错可知账号密码错误，可能是由于安装过程中进行了重新安装，导致rainbondcluster记录的账号密码与 secret 资源 hub-image-repository 中记录的不一致导致。临时处理方式如下：
> 
> 1. 删除 hub-image-repository，rbd-hub 等资源
> 
> ```
> kubectl delete secret hub-image-repository -n rbd-system
> kubectl delete deployment rbd-hub -n rbd-system
> ```
> 
> 1. 重启 rainbond-operator
> 
> ```
> kubectl delete pod  -l release=rainbond-operator -n rbd-system
> ```
> 
> 1. 删除本地证书文件
> 
> ```
> rm -rf /etc/docker/certs.d/goodrain.me/*
> ```
> 
> 1. 重启rbd-gateway
> 
> ```
> kubectl delete pod  -l name=rbd-gateway -n rbd-system
> ```
> 
> 1. 重启rbd-node
> 
> ```
> kubectl delete pod  -l name=rbd-node -n rbd-system
> ```
> 
> 完成后等待hub-image-repository 、本地/etc/docker/certs/goodrain.me/目录下证书重新生成后，再次执行 `docker login goodrain.me` 能够成功即可。

步骤 4 和 步骤 5 应调换下位置，先重启 rbd-node 再重启 rbd-gateway
