### ISSUE TITLE
应用备份失败-不支持insecure-registry

### ISSUE THREAD

**Issue by dargoner** [goodrain/rainbond#961]
**Describe the bug**
应用备份失败

**To Reproduce**
备份失败
**Screenshots**
![image](https://user-images.githubusercontent.com/1793850/116027654-0552af00-a688-11eb-98c0-6bc0a638ef9d.png)

**The relevant information:**
 - Rainbond Version 5.3.0
 - Browser chrome 80
 - Kubernetes version 1.19.9

**Comment by barnettZQG** [comment]
@dargoner 提交备份任务后观察一下rbd-chaos组件的日志，并提供给我们。
查看方式：
```
kubectl logs -f -l name=rbd-chaos -n rbd-system
```

**Comment by dargoner** [comment]
![image](https://user-images.githubusercontent.com/1793850/116068033-554b6900-a6bc-11eb-8543-4cc6bb51b3ee.png)

registry.rdc.finstone.com.cn 这个地址，没有开放 https 访问方式，并且在 docker 里面配置了 "insecure-registries": ["registry.rdc.finstone.com.cn"]

**Comment by barnettZQG** [comment]
@dargoner 备份失败的原因是当前应用中有未构建的组件。`Backup build version failure` 这个日志显示 `gr650e59` 这个组件没有可用版本。

**Comment by dargoner** [comment]
![image](https://user-images.githubusercontent.com/1793850/116170536-93d33900-a739-11eb-8e15-ea6d0fdf680e.png)
是商场上拉的应用，我改了数据库。想备份下

**Comment by dargoner** [comment]
![Uploading image.png…]()

**Comment by dargoner** [comment]
![image](https://user-images.githubusercontent.com/1793850/116170622-bfeeba00-a739-11eb-9db4-133908853e5f.png)

**Comment by barnettZQG** [comment]
@dargoner 你把这个第三方组件的组件页面地址发一下，我看看它的id。

**Comment by dargoner** [comment]
![image](https://user-images.githubusercontent.com/1793850/116171157-d21d2800-a73a-11eb-8618-3b51e21317f5.png)
指的这个？

**Comment by barnettZQG** [comment]
进入 Mysql8 这个组件页面，浏览器地址copy发出来。

**Comment by dargoner** [comment]
/team/pvuayblw/region/k8s-rdc/components/grf997f6/overview

**Comment by dargoner** [comment]
![image](https://user-images.githubusercontent.com/1793850/116171558-95056580-a73b-11eb-8999-1d2464f33624.png)
感觉是拉镜像报的错，找不到镜像，服务器都连不上

**Comment by dargoner** [comment]
换了一个应用备份，也是同样的错误

**Comment by barnettZQG** [comment]
@dargoner 确实是，备份时会请求镜像仓库验证镜像是否存在。在这个阶段目前确实不支持非https的镜像仓库。

**Comment by barnettZQG** [comment]
@dargoner 下个版本修复该问题。
