### ISSUE TITLE
初始化类型插件，支持和主应用共享存储

### ISSUE THREAD

**Issue by dargoner** [goodrain/rainbond#963]
**Is your feature request related to a problem? Please describe.**
想安装 Skywalking APM的监控服务，Agent 有三种集成方式：
1、Agent相关的包在常规模式下需要手工复制到每个需要监控的POD里面，
2、或通过应用存储共享的模式，共享存储，
3、或构建的时候打包进去（跟目前pinpoint集成类似）

**Describe the solution you'd like**
以上三种扩展性都有缺陷，提出第四种方案，

想通过新建插件 sidecar 共享目录的方式，将 agent 支持包共享到主应用里。目前的插件体系不支持分享存储给主应用。

**Describe alternatives you've considered**
希望能支持共享目录，agent部署参考：https://segmentfault.com/a/1190000020237280?utm_source=tag-newest
好处：插件版本能独立升级和启停，通过自动设置环境变量和目录共享，能自动进行配置，不影响主配置。

**Additional context**

**Comment by barnettZQG** [comment]
@dargoner 插件与插件主容器共享持久化目录。你在组件上添加一个临时存储（同k8s emptyDir），创建一个初始化插件来进行实现sidecar

**Comment by dargoner** [comment]
![image](https://user-images.githubusercontent.com/1793850/116176220-5c1dbe80-a744-11eb-9600-2b5f15607f27.png)
目前不支持自定义启动命令参数，如果要实现这个功能，要么就是镜像中写死复制命令和路径才能实现。

**Comment by barnettZQG** [comment]
@dargoner 插件支持定义配置信息，比如环境变量。将路径做成可配置项。

参考文档：https://www.rainbond.com/docs/user-manual/plugin-manage/new-plugin/#%e6%8f%92%e4%bb%b6%e9%85%8d%e7%bd%ae

**Comment by dargoner** [comment]
好的，我参考下阿里日志收集插件是怎么处理的，应该差不多一样的原理

**Comment by dargoner** [comment]
建议加个自定义命令的输入框，方便再不改变镜像的前提下，定制功能

**Comment by barnettZQG** [comment]
@dargoner 新的需求建议新开issues，我将关闭该问题。
