### ISSUE TITLE
插件配置组管理删除不了配置项

### ISSUE THREAD

**Issue by dargoner** [goodrain/rainbond#964]
**Describe the bug**

插件配置组管理删除不了配置项

![image](https://user-images.githubusercontent.com/1793850/116340444-bfc1ed80-a811-11eb-9b50-11ae7074ec4c.png)

![image](https://user-images.githubusercontent.com/1793850/116340477-cd777300-a811-11eb-8d93-5ed413da90c1.png)

点删除后，确定，重新打开后还存在

**The relevant information:**
 - Rainbond Version [5.3.0]
 - Kubernetes version [1.19.9]

**Comment by zsl1549** [comment]
It has been fixed, please watch for the release of a new version
