### ISSUE TITLE
自动构建设置 Webhook 地址怎么配置

### ISSUE THREAD

**Issue by dargoner** [goodrain/rainbond#968]
**Describe the bug**

自动构建设置 Webhook 公开地址怎么配置,默认 127.0.0.1 

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/1793850/116663147-4967eb80-a9c9-11eb-88fd-7d205b6ba461.png)

**The relevant information:**
 - Rainbond Version [e.g. 5.3.0]
 - Browser [e.g. chrome, safari] (if it is the front-end bugs, please provide)
 - Kubernetes version [e.g 1.16.3]

**Comment by barnettZQG** [comment]
@dargoner 使用环境变量 DEFAULT_DOMAIN 设置正确的平台外网访问地址。

**Comment by dargoner** [comment]
是说组件里设置，还是说有个全局地方设置？

![image](https://user-images.githubusercontent.com/1793850/116667070-5509e100-a9ce-11eb-9652-e04ff544410b.png)

**Comment by barnettZQG** [comment]
设置控制台的环境变量，如果采用allinone容器部署，则设置该容器变量。如果从应用商店安装部署，则在Console组件上添加该环境变量

**Comment by dargoner** [comment]
可行
