### ISSUE TITLE
Evicted Pod 自动清理

### ISSUE THREAD

**Issue by barnettZQG** [goodrain/rainbond#977]
集群由于磁盘紧张等原因会产生大量的Evicted Pod，导致资源统计等功能异常。应该做如下事项：
1.  集群健康控制器自动清理 Evicted Pod；
2.  资源统计包括：集群资源使用量，租户资源使用量，应用资源使用量等维度统计时排除 Evicted Pod；

**Comment by GLYASAI** [comment]
这种情况建议手动进行处理
