### ISSUE TITLE
前端项目源码构建，web.conf  支持编译环境变量传递

### ISSUE THREAD

**Issue by dargoner** [goodrain/rainbond#978]
前端项目源码编译构建时，能支持环境变量传递到nginx配置中。目前的web.conf 只支持修改端口，其他的配置不支持编译环境变量配置。
如这段配置：
location / {
       try_files $uri $uri/ /index.html;
    }
建议使用 envsubst支持
location /${AppPath} {
       try_files $uri $uri/ ${AppPath}/index.html;
}

**Comment by barnettZQG** [comment]
是一个好建议。使用这样的二进制工具进行处理：https://github.com/barnettZQG/env2file
