### ISSUE TITLE
JAVA编码构建，自动添加PINPOINT_AGETN，无法指定版本

### ISSUE THREAD

**Issue by dargoner** [goodrain/rainbond#984]
1、JAVA编码构建，自动添加PINPOINT_AGETN，但是无法指定版本，建议在构建的地方，添加是否添加Agent 选项，如果添加，则下拉选择构建的版本，目前内置的是2.0.3，最新版本是2.2.0 。

2、APM 自己选择集成 pinpoint  agent 或者 skywalking agent

**Comment by barnettZQG** [comment]
@dargoner 
PINPOINT_AGETN 可以设置版本，但是目前只提供了2.0.3版本的下载源，如有其他需求可以提交需求我们进行补充下载源文件。

另外用户可以通过自定义 `bin/java-post-compile` 脚本在构建后自行下载指定版本的PINPOINT_AGETN到指定目录下，然后设置启动JAVA_OPTS参数即可。

如还有问题请重新打开该Issus.
