### ISSUE TITLE
本地应用市场发布，描述显示不正确

### ISSUE THREAD

**Issue by dargoner** [goodrain/rainbond#985]
![image](https://user-images.githubusercontent.com/1793850/118238559-3d9d1e80-b4cb-11eb-8520-4465dee83d46.png)

![image](https://user-images.githubusercontent.com/1793850/118238627-54dc0c00-b4cb-11eb-8ad9-89e6d43877b5.png)

**Comment by GLYASAI** [comment]
第一个截图里的描述和第二个截图的描述不是一个东西哦. 第一个截图的描述需要在应用详情里编辑, 如图:
![image](https://user-images.githubusercontent.com/21967570/123575103-a504f880-d803-11eb-9c8f-d7b93528fa47.png)

第二个截图里的描述换成"简介"可能更合适.
