### ISSUE TITLE
Delete Application Error

### ISSUE THREAD

**Issue by RainNiu** [goodrain/rainbond#99]
报错信息：删除失败(删除应用失败 {'url': u'http://region.goodrain.me:8888/v2/tenants/zq0rh24k/services/grd72947?enterprise_id=98d58c23feee6e4d767bde42706bec96', 'body': {u'msg': u'delete service error, service name)@admin

后端报错信息如下：docker logs -f rbd-chaos
![image](https://user-images.githubusercontent.com/23009238/43685792-2f63748e-98ec-11e8-865f-f0e1a65a6896.png)

**Comment by barnettZQG** [comment]
删除应用与chaos组件无关
