### ISSUE TITLE
对接完成之后，resource-proxy一直crash

### ISSUE THREAD

**Issue by briannadev** [goodrain/rainbond#996]
已经和Rainbond兄弟沟通过，提个issue跟踪下。

![image](https://user-images.githubusercontent.com/8251627/119309103-6c23b200-bca0-11eb-8910-e5309870207c.png)

日志：
![image](https://user-images.githubusercontent.com/8251627/119309143-7e055500-bca0-11eb-8dcc-dec147a7a7d9.png)

**Comment by barnettZQG** [comment]
已经在PR #938 中修复，下个发行版生效。
